### PR TITLE
fix: Use outputs of last child instead of retry node itslef

### LINKED ISSUE #2560: IP variables unavailable in workflow
Checklist:

 * [X] I've included the version.
 * [X] I've included reproduction steps.
 * [X] I've included the workflow YAML.
 * [X] I've included the logs.
 
**What happened**:
I tried to run a daemon workflow from examples and variable {{steps.influx.ip}} has not been replaced to an actual influx address.

**What you expected to happen**:
Variable replaced by IP

**How to reproduce it (as minimally and precisely as possible)**:
Just run a workflow.

**Anything else we need to know?**:
Nope, but ask if you need something

**Workflow**

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: daemon-step-
spec:
  entrypoint: daemon-example
  templates:
  - name: daemon-example
    steps:
    - - name: influx
        template: influxdb              # start an influxdb as a daemon (see the influxdb template spec below)

    - - name: init-database             # initialize influxdb
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: echo http://{{steps.influx.ip}}:8086; curl -XPOST 'http://{{steps.influx.ip}}:8086/query' --data-urlencode "q=CREATE DATABASE mydb"

    - - name: producer-1                # add entries to influxdb
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: for i in $(seq 1 20); do echo http://{{steps.influx.ip}}:8086; curl -XPOST 'http://{{steps.influx.ip}}:8086/write?db=mydb' -d "cpu,host=server01,region=uswest load=$i" ; sleep .5 ; done
      - name: producer-2                # add entries to influxdb
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: for i in $(seq 1 20); do curl -XPOST 'http://{{steps.influx.ip}}:8086/write?db=mydb' -d "cpu,host=server02,region=uswest load=$((RANDOM % 100))" ; sleep .5 ; done
      - name: producer-3                # add entries to influxdb
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: curl -XPOST 'http://{{steps.influx.ip}}:8086/write?db=mydb' -d 'cpu,host=server03,region=useast load=15.4'

    - - name: consumer                  # consume intries from influxdb
        template: influxdb-client
        arguments:
          parameters:
          - name: cmd
            value: curl --silent -G http://{{steps.influx.ip}}:8086/query?pretty=true --data-urlencode "db=mydb" --data-urlencode "q=SELECT * FROM cpu"

  - name: influxdb
    daemon: true                        # start influxdb as a daemon
    retryStrategy:
      limit: 10                         # retry container if it fails
    container:
      image: influxdb:1.2
      readinessProbe:                   # wait for readinessProbe to succeed
        httpGet:
          path: /ping
          port: 8086

  - name: influxdb-client
    inputs:
      parameters:
      - name: cmd
    container:
      image: appropriate/curl:latest
      command: ["/bin/sh", "-c"]
      args: ["{{inputs.parameters.cmd}}"]
      resources:
        requests:
          memory: 32Mi
          cpu: 100m

```

**Environment**:
- Argo version: 2.7.0 (same problem with 2.6.1)
```
$ argo version
argo: v2.7.0
  BuildDate: 2020-03-31T23:35:04Z
  GitCommit: 4d1175eb68f6578ed5d599f877be9b4855d33ce9
  GitTreeState: clean
  GitTag: v2.7.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :

```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-12-07T21:20:10Z"
  compiler: gc
  gitCommit: 70132b0f130acc0bed193d9ba59dd186f0e634cf
  gitTreeState: clean
  gitVersion: v1.17.0
  goVersion: go1.13.4
  major: "1"
  minor: "17"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-11-13T11:11:50Z"
  compiler: gc
  gitCommit: 7015f71e75f670eb9e7ebd4b5749639d42e20079
  gitTreeState: clean
  gitVersion: v1.15.6
  goVersion: go1.12.12
  major: "1"
  minor: "15"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                daemon-step-cbdf2
Namespace:           argo
ServiceAccount:      argo
Status:              Failed
Message:             child 'daemon-step-cbdf2-2564473569' failed
Created:             Wed Apr 01 22:59:40 +0200 (23 seconds ago)
Started:             Wed Apr 01 22:59:40 +0200 (23 seconds ago)
Finished:            Wed Apr 01 23:00:04 +0200 (now)
Duration:            24 seconds

STEP                  TEMPLATE         PODNAME                       DURATION  MESSAGE
 ✖ daemon-step-cbdf2  daemon-example                                           child 'daemon-step-cbdf2-2564473569' failed
 ├---✔ influx(0)      influxdb         daemon-step-cbdf2-3257897963  13s       
 └---✖ init-database  influxdb-client  daemon-step-cbdf2-2564473569  6s        failed with exit code 3
```
- executor logs:
```
kubectl -n argo logs daemon-step-cbdf2-2564473569 -c wait
time="2020-04-01T20:59:55Z" level=info msg="Starting Workflow Executor" version=vv2.7.0+4d1175e.dirty
time="2020-04-01T20:59:55Z" level=info msg="Creating a K8sAPI executor"
time="2020-04-01T20:59:55Z" level=info msg="Executor (version: vv2.7.0+4d1175e.dirty, build_date: 2020-04-01T00:13:15Z) initialized (pod: argo/daemon-step-cbdf2-2564473569) with template:\n{\"name\":\"influxdb-client\",\"arguments\":{},\"inputs\":{\"parameters\":[{\"name\":\"cmd\",\"value\":\"echo http://{{steps.influx.ip}}:8086; curl -XPOST 'http://{{steps.influx.ip}}:8086/query' --data-urlencode \\\"q=CREATE DATABASE mydb\\\"\"}]},\"outputs\":{},\"metadata\":{},\"container\":{\"name\":\"\",\"image\":\"appropriate/curl:latest\",\"command\":[\"/bin/sh\",\"-c\"],\"args\":[\"echo http://{{steps.influx.ip}}:8086; curl -XPOST 'http://{{steps.influx.ip}}:8086/query' --data-urlencode \\\"q=CREATE DATABASE mydb\\\"\"],\"resources\":{\"requests\":{\"cpu\":\"100m\",\"memory\":\"32Mi\"}}}}"
time="2020-04-01T20:59:55Z" level=info msg="Waiting on main container"
time="2020-04-01T20:59:58Z" level=info msg="main container started with container ID: ed36bf5dbe3be437c526816a507f9c6246a9645ebaf9bd72fcf6b7523ce89e6e"
time="2020-04-01T20:59:58Z" level=info msg="Starting annotations monitor"
time="2020-04-01T20:59:58Z" level=info msg="Waiting for container ed36bf5dbe3be437c526816a507f9c6246a9645ebaf9bd72fcf6b7523ce89e6e to complete"
time="2020-04-01T20:59:58Z" level=info msg="Starting to wait completion of containerID ed36bf5dbe3be437c526816a507f9c6246a9645ebaf9bd72fcf6b7523ce89e6e ..."
time="2020-04-01T20:59:58Z" level=info msg="Starting deadline monitor"
time="2020-04-01T20:59:59Z" level=info msg="ContainerID \"ed36bf5dbe3be437c526816a507f9c6246a9645ebaf9bd72fcf6b7523ce89e6e\" is terminated: &ContainerStatus{Name:main,State:ContainerState{Waiting:nil,Running:nil,Terminated:&ContainerStateTerminated{ExitCode:3,Signal:0,Reason:Error,Message:,StartedAt:2020-04-01 20:59:57 +0000 UTC,FinishedAt:2020-04-01 20:59:57 +0000 UTC,ContainerID:docker://ed36bf5dbe3be437c526816a507f9c6246a9645ebaf9bd72fcf6b7523ce89e6e,},},LastTerminationState:ContainerState{Waiting:nil,Running:nil,Terminated:nil,},Ready:false,RestartCount:0,Image:appropriate/curl:latest,ImageID:docker-pullable://appropriate/curl@sha256:c8bf5bbec6397465a247c2bb3e589bb77e4f62ff88a027175ecb2d9e4f12c9d7,ContainerID:docker://ed36bf5dbe3be437c526816a507f9c6246a9645ebaf9bd72fcf6b7523ce89e6e,Started:nil,}"
time="2020-04-01T20:59:59Z" level=info msg="Main container completed"
time="2020-04-01T20:59:59Z" level=info msg="No output parameters"
time="2020-04-01T20:59:59Z" level=info msg="No output artifacts"
time="2020-04-01T20:59:59Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2020-04-01T20:59:59Z" level=info msg="Killing sidecars"
time="2020-04-01T20:59:59Z" level=info msg="Annotations monitor stopped"
time="2020-04-01T20:59:59Z" level=info msg="Alloc=4171 TotalAlloc=10632 Sys=70592 NumGC=4 Goroutines=9"

```
- workflow-controller logs:
```
time="2020-04-01T20:59:28Z" level=info msg="config map" name=workflow-controller-configmap
time="2020-04-01T20:59:29Z" level=info msg="Configuration:\nartifactRepository: {}\ncontainerRuntimeExecutor: k8sapi\nfeatureFlags: {}\nmetricsConfig:\n  disableLegacy: false\npodSpecLogStrategy: {}\ntelemetryConfig:\n  disableLegacy: false\n"
time="2020-04-01T20:59:29Z" level=info msg="Persistence configuration disabled"
time="2020-04-01T20:59:29Z" level=info msg="Starting CronWorkflow controller"
time="2020-04-01T20:59:29Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2020-04-01T20:59:29Z" level=info msg="Starting Workflow Controller" version=vv2.7.0+4d1175e.dirty
time="2020-04-01T20:59:29Z" level=info msg="Workers: workflow: 8, pod: 8"
time="2020-04-01T20:59:29Z" level=info msg="Performing periodic GC every 5m0s"
time="2020-04-01T20:59:29Z" level=info msg="Started workflow TTL worker"
time="2020-04-01T20:59:40Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:40Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:40Z" level=info msg="Steps node {daemon-step-cbdf2 daemon-step-cbdf2 daemon-step-cbdf2 Steps daemon-example nil    Running   2020-04-01 20:59:40.795529635 +0000 UTC 0001-01-01 00:00:00 +0000 UTC   <nil> nil nil [] []} initialized Running" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:40Z" level=info msg="StepGroup node {daemon-step-cbdf2-2624926814 daemon-step-cbdf2[0] [0] StepGroup daemon-example nil    Running daemon-step-cbdf2  2020-04-01 20:59:40.795590362 +0000 UTC 0001-01-01 00:00:00 +0000 UTC   <nil> nil nil [] []} initialized Running" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:40Z" level=info msg="Retry node {daemon-step-cbdf2-3740773016 daemon-step-cbdf2[0].influx influx Retry influxdb nil    Running daemon-step-cbdf2  2020-04-01 20:59:40.795798539 +0000 UTC 0001-01-01 00:00:00 +0000 UTC   <nil> nil nil [] []} initialized Running" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:40Z" level=info msg="Pod node {daemon-step-cbdf2-3257897963 daemon-step-cbdf2[0].influx(0) influx(0) Pod influxdb nil    Pending daemon-step-cbdf2  2020-04-01 20:59:40.795878782 +0000 UTC 0001-01-01 00:00:00 +0000 UTC   <nil> nil nil [] []} initialized Pending" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:40Z" level=info msg="Created pod: daemon-step-cbdf2[0].influx(0) (daemon-step-cbdf2-3257897963)" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:40Z" level=info msg="Workflow step group node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40.795590362 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} not yet completed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:41Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=252287013 workflow=daemon-step-cbdf2
time="2020-04-01T20:59:42Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:42Z" level=info msg="Updating node &NodeStatus{ID:daemon-step-cbdf2-3257897963,Name:daemon-step-cbdf2[0].influx(0),DisplayName:influx(0),Type:Pod,TemplateName:influxdb,TemplateRef:nil,Phase:Pending,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} message: ContainerCreating"
time="2020-04-01T20:59:42Z" level=info msg="Workflow step group node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} not yet completed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:42Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=252287026 workflow=daemon-step-cbdf2
time="2020-04-01T20:59:43Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:43Z" level=info msg="Workflow step group node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} not yet completed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:44Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:44Z" level=info msg="Workflow step group node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} not yet completed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="Processing ready daemon pod: /api/v1/namespaces/argo/pods/daemon-step-cbdf2-3257897963"
time="2020-04-01T20:59:53Z" level=info msg="Setting node &NodeStatus{ID:daemon-step-cbdf2-3257897963,Name:daemon-step-cbdf2[0].influx(0),DisplayName:influx(0),Type:Pod,TemplateName:influxdb,TemplateRef:nil,Phase:Pending,BoundaryID:daemon-step-cbdf2,Message:ContainerCreating,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} daemoned: <nil> -> 0xc00063e05a"
time="2020-04-01T20:59:53Z" level=info msg="Updating daemon node &NodeStatus{ID:daemon-step-cbdf2-3257897963,Name:daemon-step-cbdf2[0].influx(0),DisplayName:influx(0),Type:Pod,TemplateName:influxdb,TemplateRef:nil,Phase:Pending,BoundaryID:daemon-step-cbdf2,Message:ContainerCreating,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:*true,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} IP  -> 172.16.25.72"
time="2020-04-01T20:59:53Z" level=info msg="Updating node &NodeStatus{ID:daemon-step-cbdf2-3257897963,Name:daemon-step-cbdf2[0].influx(0),DisplayName:influx(0),Type:Pod,TemplateName:influxdb,TemplateRef:nil,Phase:Pending,BoundaryID:daemon-step-cbdf2,Message:ContainerCreating,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:172.16.25.72,Daemoned:*true,Inputs:nil,Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} status Pending -> Running"
time="2020-04-01T20:59:53Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-3740773016,Name:daemon-step-cbdf2[0].influx,DisplayName:influx,Type:Retry,TemplateName:influxdb,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3257897963],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Running -> Succeeded" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-3740773016,Name:daemon-step-cbdf2[0].influx,DisplayName:influx,Type:Retry,TemplateName:influxdb,TemplateRef:nil,Phase:Succeeded,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53.339215484 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3257897963],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} finished: 2020-04-01 20:59:53.339215484 +0000 UTC" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="Step group node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} successful" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Running -> Succeeded" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Succeeded,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53.33926534 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} finished: 2020-04-01 20:59:53.33926534 +0000 UTC" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="StepGroup node {daemon-step-cbdf2-2557669243 daemon-step-cbdf2[1] [1] StepGroup daemon-example nil    Running daemon-step-cbdf2  2020-04-01 20:59:53.339283155 +0000 UTC 0001-01-01 00:00:00 +0000 UTC   <nil> nil nil [] []} initialized Running" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="SG Outbound nodes of daemon-step-cbdf2-3740773016 are [daemon-step-cbdf2-3257897963]" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="Pod node {daemon-step-cbdf2-2564473569 daemon-step-cbdf2[1].init-database init-database Pod influxdb-client nil    Pending daemon-step-cbdf2  2020-04-01 20:59:53.339401381 +0000 UTC 0001-01-01 00:00:00 +0000 UTC   <nil> nil nil [] []} initialized Pending" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="Created pod: daemon-step-cbdf2[1].init-database (daemon-step-cbdf2-2564473569)" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="Workflow step group node &NodeStatus{ID:daemon-step-cbdf2-2557669243,Name:daemon-step-cbdf2[1],DisplayName:[1],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53.339283155 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2564473569],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} not yet completed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:53Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=252287134 workflow=daemon-step-cbdf2
time="2020-04-01T20:59:54Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:54Z" level=info msg="Processing ready daemon pod: /api/v1/namespaces/argo/pods/daemon-step-cbdf2-3257897963"
time="2020-04-01T20:59:54Z" level=info msg="Updating node &NodeStatus{ID:daemon-step-cbdf2-2564473569,Name:daemon-step-cbdf2[1].init-database,DisplayName:init-database,Type:Pod,TemplateName:influxdb-client,TemplateRef:nil,Phase:Pending,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:&Inputs{Parameters:[]Parameter{Parameter{Name:cmd,Default:nil,Value:*echo http://{{steps.influx.ip}}:8086; curl -XPOST 'http://{{steps.influx.ip}}:8086/query' --data-urlencode \"q=CREATE DATABASE mydb\",ValueFrom:nil,GlobalName:,},},Artifacts:[]Artifact{},},Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} message: ContainerCreating"
time="2020-04-01T20:59:54Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Succeeded,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Succeeded -> Running" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:54Z" level=info msg="Step group node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} successful" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:54Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Running -> Succeeded" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:54Z" level=info msg="SG Outbound nodes of daemon-step-cbdf2-3740773016 are [daemon-step-cbdf2-3257897963]" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:54Z" level=info msg="Workflow step group node &NodeStatus{ID:daemon-step-cbdf2-2557669243,Name:daemon-step-cbdf2[1],DisplayName:[1],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2564473569],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} not yet completed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:54Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=252287148 workflow=daemon-step-cbdf2
time="2020-04-01T20:59:55Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:55Z" level=info msg="Processing ready daemon pod: /api/v1/namespaces/argo/pods/daemon-step-cbdf2-3257897963"
time="2020-04-01T20:59:55Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Succeeded,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Succeeded -> Running" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:55Z" level=info msg="Step group node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} successful" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:55Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Running -> Succeeded" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:55Z" level=info msg="SG Outbound nodes of daemon-step-cbdf2-3740773016 are [daemon-step-cbdf2-3257897963]" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:55Z" level=info msg="Workflow step group node &NodeStatus{ID:daemon-step-cbdf2-2557669243,Name:daemon-step-cbdf2[1],DisplayName:[1],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2564473569],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} not yet completed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:55Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=252287148 workflow=daemon-step-cbdf2
time="2020-04-01T20:59:58Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:58Z" level=info msg="Processing ready daemon pod: /api/v1/namespaces/argo/pods/daemon-step-cbdf2-3257897963"
time="2020-04-01T20:59:58Z" level=info msg="Updating node &NodeStatus{ID:daemon-step-cbdf2-2564473569,Name:daemon-step-cbdf2[1].init-database,DisplayName:init-database,Type:Pod,TemplateName:influxdb-client,TemplateRef:nil,Phase:Pending,BoundaryID:daemon-step-cbdf2,Message:ContainerCreating,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:&Inputs{Parameters:[]Parameter{Parameter{Name:cmd,Default:nil,Value:*echo http://{{steps.influx.ip}}:8086; curl -XPOST 'http://{{steps.influx.ip}}:8086/query' --data-urlencode \"q=CREATE DATABASE mydb\",ValueFrom:nil,GlobalName:,},},Artifacts:[]Artifact{},},Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} status Pending -> Running"
time="2020-04-01T20:59:58Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Succeeded,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Succeeded -> Running" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:58Z" level=info msg="Step group node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} successful" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:58Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Running -> Succeeded" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:58Z" level=info msg="SG Outbound nodes of daemon-step-cbdf2-3740773016 are [daemon-step-cbdf2-3257897963]" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:58Z" level=info msg="Workflow step group node &NodeStatus{ID:daemon-step-cbdf2-2557669243,Name:daemon-step-cbdf2[1],DisplayName:[1],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2564473569],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} not yet completed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:58Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=252287200 workflow=daemon-step-cbdf2
time="2020-04-01T20:59:59Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:59Z" level=info msg="Processing ready daemon pod: /api/v1/namespaces/argo/pods/daemon-step-cbdf2-3257897963"
time="2020-04-01T20:59:59Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Succeeded,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Succeeded -> Running" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:59Z" level=info msg="Step group node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} successful" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:59Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Running -> Succeeded" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:59Z" level=info msg="SG Outbound nodes of daemon-step-cbdf2-3740773016 are [daemon-step-cbdf2-3257897963]" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:59Z" level=info msg="Workflow step group node &NodeStatus{ID:daemon-step-cbdf2-2557669243,Name:daemon-step-cbdf2[1],DisplayName:[1],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2564473569],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} not yet completed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T20:59:59Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=252287200 workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Processing ready daemon pod: /api/v1/namespaces/argo/pods/daemon-step-cbdf2-3257897963"
time="2020-04-01T21:00:00Z" level=info msg="Updating node &NodeStatus{ID:daemon-step-cbdf2-2564473569,Name:daemon-step-cbdf2[1].init-database,DisplayName:init-database,Type:Pod,TemplateName:influxdb-client,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:&Inputs{Parameters:[]Parameter{Parameter{Name:cmd,Default:nil,Value:*echo http://{{steps.influx.ip}}:8086; curl -XPOST 'http://{{steps.influx.ip}}:8086/query' --data-urlencode \"q=CREATE DATABASE mydb\",ValueFrom:nil,GlobalName:,},},Artifacts:[]Artifact{},},Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} status Running -> Failed"
time="2020-04-01T21:00:00Z" level=info msg="Updating node &NodeStatus{ID:daemon-step-cbdf2-2564473569,Name:daemon-step-cbdf2[1].init-database,DisplayName:init-database,Type:Pod,TemplateName:influxdb-client,TemplateRef:nil,Phase:Failed,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:&Inputs{Parameters:[]Parameter{Parameter{Name:cmd,Default:nil,Value:*echo http://{{steps.influx.ip}}:8086; curl -XPOST 'http://{{steps.influx.ip}}:8086/query' --data-urlencode \"q=CREATE DATABASE mydb\",ValueFrom:nil,GlobalName:,},},Artifacts:[]Artifact{},},Outputs:nil,Children:[],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} message: failed with exit code 3"
time="2020-04-01T21:00:00Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Succeeded,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Succeeded -> Running" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Step group node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} successful" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2624926814,Name:daemon-step-cbdf2[0],DisplayName:[0],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-3740773016],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Running -> Succeeded" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="SG Outbound nodes of daemon-step-cbdf2-3740773016 are [daemon-step-cbdf2-3257897963]" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Step group node &NodeStatus{ID:daemon-step-cbdf2-2557669243,Name:daemon-step-cbdf2[1],DisplayName:[1],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2564473569],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} deemed failed: child 'daemon-step-cbdf2-2564473569' failed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2557669243,Name:daemon-step-cbdf2[1],DisplayName:[1],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2564473569],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Running -> Failed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2557669243,Name:daemon-step-cbdf2[1],DisplayName:[1],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Failed,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2564473569],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} message: child 'daemon-step-cbdf2-2564473569' failed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2-2557669243,Name:daemon-step-cbdf2[1],DisplayName:[1],Type:StepGroup,TemplateName:daemon-example,TemplateRef:nil,Phase:Failed,BoundaryID:daemon-step-cbdf2,Message:child 'daemon-step-cbdf2-2564473569' failed,StartedAt:2020-04-01 20:59:53 +0000 UTC,FinishedAt:2020-04-01 21:00:00.345897013 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2564473569],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} finished: 2020-04-01 21:00:00.345897013 +0000 UTC" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="step group daemon-step-cbdf2-2557669243 was unsuccessful: child 'daemon-step-cbdf2-2564473569' failed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Outbound nodes of daemon-step-cbdf2-2564473569 is [daemon-step-cbdf2-2564473569]" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Outbound nodes of daemon-step-cbdf2 is [daemon-step-cbdf2-2564473569]" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2,Name:daemon-step-cbdf2,DisplayName:daemon-step-cbdf2,Type:Steps,TemplateName:daemon-example,TemplateRef:nil,Phase:Running,BoundaryID:,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2624926814],OutboundNodes:[daemon-step-cbdf2-2564473569],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} phase Running -> Failed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2,Name:daemon-step-cbdf2,DisplayName:daemon-step-cbdf2,Type:Steps,TemplateName:daemon-example,TemplateRef:nil,Phase:Failed,BoundaryID:,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2624926814],OutboundNodes:[daemon-step-cbdf2-2564473569],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} message: child 'daemon-step-cbdf2-2564473569' failed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="node &NodeStatus{ID:daemon-step-cbdf2,Name:daemon-step-cbdf2,DisplayName:daemon-step-cbdf2,Type:Steps,TemplateName:daemon-example,TemplateRef:nil,Phase:Failed,BoundaryID:,Message:child 'daemon-step-cbdf2-2564473569' failed,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 21:00:00.345996222 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2624926814],OutboundNodes:[daemon-step-cbdf2-2564473569],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} finished: 2020-04-01 21:00:00.345996222 +0000 UTC" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Checking daemoned children of daemon-step-cbdf2" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Updating execution control of daemon-step-cbdf2-3257897963: {\"deadline\":\"0001-01-01T00:00:00Z\"}" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Signalling daemon-step-cbdf2-3257897963 of updates" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="https://172.17.0.1:443/api/v1/namespaces/argo/pods/daemon-step-cbdf2-3257897963/exec?command=sh&command=-c&command=kill+-s+USR2+%24%28pidof+argoexec%29&container=wait&stderr=true&stdout=true&tty=false"
time="2020-04-01T21:00:00Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Updated message  -> child 'daemon-step-cbdf2-2564473569' failed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=252287219 workflow=daemon-step-cbdf2
time="2020-04-01T21:00:00Z" level=info msg="Signal of daemon-step-cbdf2-3257897963 (wait) successfully issued" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:01Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:01Z" level=info msg="Labeled pod argo/daemon-step-cbdf2-2564473569 completed"
time="2020-04-01T21:00:01Z" level=info msg="Processing ready daemon pod: /api/v1/namespaces/argo/pods/daemon-step-cbdf2-3257897963"
time="2020-04-01T21:00:01Z" level=info msg="Skipping sync of execution control of pod daemon-step-cbdf2-3257897963. pod has been signaled to terminate" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:01Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:01Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:01Z" level=info msg="Processing ready daemon pod: /api/v1/namespaces/argo/pods/daemon-step-cbdf2-3257897963"
time="2020-04-01T21:00:01Z" level=info msg="Skipping sync of execution control of pod daemon-step-cbdf2-3257897963. pod has been signaled to terminate" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:01Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:03Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:03Z" level=info msg="Skipping sync of execution control of pod daemon-step-cbdf2-3257897963. pod has been signaled to terminate" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:03Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:04Z" level=info msg="Processing workflow" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:04Z" level=info msg="Setting node &NodeStatus{ID:daemon-step-cbdf2-3257897963,Name:daemon-step-cbdf2[0].influx(0),DisplayName:influx(0),Type:Pod,TemplateName:influxdb,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:172.16.25.72,Daemoned:*true,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2557669243],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} daemoned: 0xc000bb6e18 -> <nil>"
time="2020-04-01T21:00:04Z" level=info msg="Updating node &NodeStatus{ID:daemon-step-cbdf2-3257897963,Name:daemon-step-cbdf2[0].influx(0),DisplayName:influx(0),Type:Pod,TemplateName:influxdb,TemplateRef:nil,Phase:Running,BoundaryID:daemon-step-cbdf2,Message:,StartedAt:2020-04-01 20:59:40 +0000 UTC,FinishedAt:2020-04-01 20:59:53 +0000 UTC,PodIP:172.16.25.72,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[daemon-step-cbdf2-2557669243],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:,ResourcesDuration:ResourcesDuration{},} status Running -> Succeeded"
time="2020-04-01T21:00:04Z" level=info msg="Marking workflow completed" namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:04Z" level=info msg="Checking daemoned children of " namespace=argo workflow=daemon-step-cbdf2
time="2020-04-01T21:00:04Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=252287289 workflow=daemon-step-cbdf2
time="2020-04-01T21:00:05Z" level=info msg="Labeled pod argo/daemon-step-cbdf2-3257897963 completed"

```

**Execution logs**

```
argo -n argo logs daemon-step-cbdf2 --tail 100
daemon-step-cbdf2-3257897963: 
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:43Z InfluxDB starting, version 1.2.4, branch master, commit 77909d7c7826afe597b12d957996d6e16cd1afaa
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:43Z Go version go1.7.4, GOMAXPROCS set to 8
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:43Z Using configuration at: /etc/influxdb/influxdb.conf
daemon-step-cbdf2-3257897963:  8888888           .d888 888                   8888888b.  888888b.
daemon-step-cbdf2-3257897963:    888            d88P"  888                   888  "Y88b 888  "88b
daemon-step-cbdf2-3257897963:    888            888    888                   888    888 888  .88P
daemon-step-cbdf2-3257897963:    888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
daemon-step-cbdf2-3257897963:    888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
daemon-step-cbdf2-3257897963:    888   888  888 888    888 888  888   X88K   888    888 888    888
daemon-step-cbdf2-3257897963:    888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
daemon-step-cbdf2-3257897963:  8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"
daemon-step-cbdf2-3257897963: 
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Using data dir: /var/lib/influxdb/data service=store
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z opened service service=subscriber
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Starting monitor system service=monitor
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z 'build' registered for diagnostics monitoring service=monitor
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z 'runtime' registered for diagnostics monitoring service=monitor
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z 'network' registered for diagnostics monitoring service=monitor
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z 'system' registered for diagnostics monitoring service=monitor
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Starting precreation service with check interval of 10m0s, advance period of 30m0s service=shard-precreation
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Starting snapshot service service=snapshot
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Starting continuous query service service=continuous_querier
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Starting HTTP service service=httpd
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Authentication enabled:false service=httpd
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Listening on HTTP:[::]:8086 service=httpd
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Starting retention policy enforcement service with check interval of 30m0s service=retention
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Listening for signals
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Storing statistics in database '_internal' retention policy 'monitor', at interval 10s service=monitor
daemon-step-cbdf2-3257897963: [I] 2020-04-01T20:59:44Z Sending usage statistics to usage.influxdata.com
daemon-step-cbdf2-3257897963: [httpd] 10.113.3.100 - - [01/Apr/2020:20:59:53 +0000] "GET /ping HTTP/1.1" 204 0 "-" "kube-probe/1.15" bbff6a5a-745b-11ea-8001-000000000000 200
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:00Z /var/lib/influxdb/data/_internal/monitor/1 database index loaded in 7.573µs service=shard
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:01Z Signal received, initializing clean shutdown...
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:01Z Waiting for clean shutdown...
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:01Z shutting down monitor system service=monitor
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:01Z terminating storage of statistics service=monitor
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:01Z Precreation service terminating service=shard-precreation
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:01Z snapshot listener closed service=snapshot
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:01Z continuous query service terminating service=continuous_querier
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:01Z retention policy enforcement terminating service=retention
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:01Z closed service service=subscriber
daemon-step-cbdf2-3257897963: [I] 2020-04-01T21:00:01Z server shutdown completed
daemon-step-cbdf2-2564473569: http://{{steps.influx.ip}}:8086
daemon-step-cbdf2-2564473569: curl: (3) [globbing] nested brace in column 9

```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by simster7**
Fixes #2560 

When using a retry node, we would add the outputs of the retry node instead of the last child to the scope. Changed to add the outputs of the last child node.

Wonder how this went undetected for so long.

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1917,6 +1917,14 @@ func (woc *wfOperationCtx) executeScript(nodeName string, templateScope string,
 // buildLocalScope adds all of a nodes outputs to the local scope with the given prefix, as well
 // as the global scope, if specified with a globalName
 func (woc *wfOperationCtx) buildLocalScope(scope *wfScope, prefix string, node *wfv1.NodeStatus) {
+	// It may be that the node is a retry node, in which case we want to get the outputs of the last node
+	// in the retry group instead of the retry node itself.
+	if node.Type == wfv1.NodeTypeRetry {
```
Comment (alexec) [inline workflow/controller/operator.go:1922]: unit test?

Comment (simster7) [reply workflow/controller/operator.go:1922]: Added test!

**Comment by danxmoran** [comment]
Is there a chance that #2442 is related to this?

**Comment by simster7** [comment]
> Is there a chance that #2442 is related to this?

@danxmoran I'm actually not too sure. From your issue:

> When the 1st script completes successfully on its first try, everything works perfectly. On the other hand, if the 1st script fails, retries, and then succeeds, then its result is sometimes not substituted properly into the inputs of the 2nd script. This causes the 2nd script to fail.

If the issue were this, it wouldn't work even on the first successful try and it would always be deterministic. I'll take a look at your issue soon and see if it did in fact fix it.

**Comment by simster7** [comment]
Back-ported to 2.7
