### PR TITLE
chore: Fix UI TODOs

### LINKED ISSUE #1955: Fix UI TODOs
Fix all remaining TODOs in UI.

### PR DESCRIPTION
**Pull request by simster7**
Fixes #1955

### CODE REVIEW

File: ui/src/app/shared/utils.ts [hunk 1]
```diff
@@ -92,5 +92,33 @@ export const Utils = {
         } catch {
             return null;
         }
+    },
+
+    isNodeSuspended(node: models.NodeStatus): boolean {
```
Comment (alexec) [inline ui/src/app/shared/utils.ts]: I'm not a big fan of "util" or "common" files as they tend to get large and unwieldy. Could you create a separate file for this please?
