### PR TITLE
fix: Improve better handling on Pod deletion scenario 

### LINKED ISSUE #3857: stuck with deleted pods
Hi guys,
Argo version 2.9.5
As I shared already the Argo get YAML file to @simster7 privately I'm facing a similar issue as #3665 
In particular, this is a screenshot of Argo UI:

Screen Shot 2020-08-25 at 2 13 11 pm

I am also unable to find the following error in my logs:
`Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"workflow-XXXXXXXXX\": the object has been modified; please apply your changes to the latest version and try again Conflict`

Thanks for your time and effort in fixing that.
Cheers,
Fabio

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #3857

### CODE REVIEW

File: workflow/controller/controller.go [hunk 1]
```diff
@@ -564,6 +564,12 @@ func (wfc *WorkflowController) processNextPodItem() bool {
 		// we dequeued it.
 		return true
 	}
+	return wfc.enqueueWfFromPodLabel(obj, key.(string))
+}
+
+// enqueueWfFromPodLabel will extract the workflow name from pod label and
+// enqueue workflow for processing
+func (wfc *WorkflowController) enqueueWfFromPodLabel(obj interface{}, key string) bool {
```
Comment (alexec) [inline workflow/controller/controller.go:572]: minor: I think we don't need key here as you can determine key from the pod

File: workflow/controller/controller.go [hunk 2]
```diff
@@ -746,12 +748,15 @@ func (wfc *WorkflowController) newPodInformer() cache.SharedIndexInformer {
...
 				// IndexerInformer uses a delta queue, therefore for deletes we have to use this
 				// key function.
-				key, err := cache.DeletionHandlingMetaNamespaceKeyFunc(obj)
+				_, err := cache.DeletionHandlingMetaNamespaceKeyFunc(obj)
 				if err != nil {
 					return
 				}
 				// Enqueue the workflow for deleted pod
-				wfc.enqueueWfFromPodLabel(obj, key)
+				err = wfc.enqueueWfFromPodLabel(obj)
```
Comment (alexec) [inline workflow/controller/controller.go:756]: I think you can totally ignore this error with `_`

File: workflow/controller/controller.go [hunk 3]
```diff
@@ -746,12 +748,15 @@ func (wfc *WorkflowController) newPodInformer() cache.SharedIndexInformer {
 			DeleteFunc: func(obj interface{}) {
 				// IndexerInformer uses a delta queue, therefore for deletes we have to use this
 				// key function.
-				key, err := cache.DeletionHandlingMetaNamespaceKeyFunc(obj)
+				_, err := cache.DeletionHandlingMetaNamespaceKeyFunc(obj)
```
Comment (alexec) [inline workflow/controller/controller.go:751]: I think you don't need to do this at all?

File: workflow/controller/controller.go [hunk 4]
```diff
@@ -564,31 +564,33 @@ func (wfc *WorkflowController) processNextPodItem() bool {
 		// we dequeued it.
 		return true
 	}
-	return wfc.enqueueWfFromPodLabel(obj, key.(string))
+
+	err = wfc.enqueueWfFromPodLabel(obj)
+	if err != nil {
+		log.WithFields(log.Fields{"key": key}).Warn(err)
```
Comment (alexec) [inline workflow/controller/controller.go:570]: use `WithError(err)`?

File: workflow/controller/controller.go [hunk 5]
```diff
@@ -564,25 +564,33 @@ func (wfc *WorkflowController) processNextPodItem() bool {
...
+// enqueueWfFromPodLabel will extract the workflow name from pod label and
+// enqueue workflow for processing
+func (wfc *WorkflowController) enqueueWfFromPodLabel(obj interface{}) error {
 	pod, ok := obj.(*apiv1.Pod)
 	if !ok {
-		log.WithFields(log.Fields{"key": key}).Warn("Key in index is not a pod")
-		return true
+		return fmt.Errorf("Key in index is not a pod")
 	}
 	if pod.Labels == nil {
```
Comment (alexec) [inline workflow/controller/controller.go:582]: minor: I think this check is redundant

**Review by alexec — APPROVED** [review]
minor comments - back-port to v2.11?
