### PR TITLE
fix: Skip the Workflow not found error in Concurrency policy

### LINKED ISSUE #5024: Concurrency policy error
## Summary 

What happened/what you expected to happen?
level=error msg="Concurrency policy error: error stopping workflow test-cron-wf-1612456860: &{{{%!e(string=) %!e(string=)} {%!e(string=) %!e(string=) %!e(string=) %!e(*int64=<nil>)} %!e(string=Failure) %!e(string=workflows.argoproj.io \"test-cron-wf-1612456860\" not found) %!e(v1.StatusReason=NotFound) %!e(*v1.StatusDetails=&{test-cron-wf-1612456860 argoproj.io workflows  [] 0}) %!e(int32=404)}}" conditionType=SubmissionError 

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 


```
apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: test-cron-wf
spec:
  concurrencyPolicy: Replace
  schedule: '* * * * *'
  startingDeadlineSeconds: 0
  workflowSpec:
    arguments: {}
    entrypoint: whalesay
    templates:
    - arguments: {}
      container:
        args:
        - date; sleep 90
        command:
        - sh
        - -c
        image: alpine:3.6
        name: ""
        resources: {}
      inputs: {}
      metadata: {}
      name: whalesay
      outputs: {}

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

fixes #5024

### CODE REVIEW

File: workflow/cron/operator.go [hunk 1]
```diff
@@ -191,6 +191,10 @@ func (woc *cronWfOperationCtx) terminateOutstandingWorkflows(ctx context.Context
 		woc.log.Infof("stopping '%s'", wfObjectRef.Name)
 		err := util.TerminateWorkflow(ctx, woc.wfClient, wfObjectRef.Name)
 		if err != nil {
+			if errors.IsNotFound(err) {
```
Comment (sarabala1979) [inline workflow/cron/operator.go:194]: Not able to reproduce locally.   code will log the warning if the terminate workflow is already deleted

File: workflow/cron/operator.go [hunk 2]
```diff
@@ -191,6 +191,10 @@ func (woc *cronWfOperationCtx) terminateOutstandingWorkflows(ctx context.Context
...
+				woc.log.Warnf("%s workflow not found", wfObjectRef.Name)
```
Comment (simster7) [inline workflow/cron/operator.go:195]: A more descriptive log will make it easier to pinpoint if it comes up in the future
```suggestion
				woc.log.Warnf("workflow '%s' not found when trying to terminate outstanding workflows", wfObjectRef.Name)
```

**Review by simster7 — APPROVED** [review]
Conditional approval
