### PR TITLE
fix(archive): Fix edge-cast error for archiving. Fixes #2427

### LINKED ISSUE #2427: Updating the workflow archive entry for a retried workflow fails with "current transaction is aborted"
Checklist:

 * [ ] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:
One of my workflows failed with a transient error. I retried it through the UI and all of its steps succeeded, but the root node (a DAG template) was still marked as an Error. I looked through the logs and found this error in the UPPERIO debug logs:
```
pq: duplicate key value violates unique constraint "argo_archived_workflows_pkey"
```
I'm not sure if this is the cause of the Error state, but either way it looks like a problem.

**What you expected to happen**:
I expected the workflow controller to perform and update-or-insert when adding info to `argo_archived_workflows`, and not fail with a PK error on workflow retries.

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure if this depends on the archived workflow being in a failed state, but I'm able to reproduce this every time I retry a failed workflow that's already been archived.

**Anything else we need to know?**:
The log with the `pq` error shows that the controller is trying to run a SQL `UPDATE`, so I don't think the current implementation is too far off from what I'd expect. The SQL I see is:
```
UPDATE "argo_archived_workflows" SET "workflow" = $1, "phase" = $2, "startedat" = $3, "finishedat" = $4 WHERE ("clustername" = $5 AND "uid" = $6)
```
The arguments I see include the (large) workflow JSON. Wit that payload abbreviated, they are:
```
<workflow-json>, "Error", time.Time{wall:0x0, ext:63719642700, loc:(*time.Location)(0x257c120)}, time.Time{wall:0x18025983, ext:63719666144, loc:(*time.Location)(nil)}, "command-center", "cfc3c39f-8fc8-4a8c-b358-e80438392288"
```
---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the USERS.md.
* [ ] I've signed the CLA and required builds are green.

### CODE REVIEW

File: persist/sqldb/workflow_archive.go [hunk 1]
```diff
@@ -70,9 +70,15 @@ func (r *workflowArchive) ArchiveWorkflow(wf *wfv1.Workflow) error {
 		return err
 	}
 	return r.session.Tx(context.Background(), func(sess sqlbuilder.Tx) error {
-		// We assume that we're much more likely to be inserting rows that updating them, so we try and insert,
-		// and if that fails, then we update.
-		// There is no check for race condition here, last writer wins.
+		_, err := sess.
```
Comment (alexec) [inline persist/sqldb/workflow_archive.go]: we take a different, alternative approach - delete any records from the archive table (which will cascade to labels) and then just insert the archive record and labels

File: persist/sqldb/workflow_archive.go [hunk 2]
```diff
@@ -70,9 +70,15 @@ func (r *workflowArchive) ArchiveWorkflow(wf *wfv1.Workflow) error {
...
+			DeleteFrom(archiveTableName).
+			Where(db.Cond{"clustername": r.clusterName}).
+			And(db.Cond{"instanceid": r.instanceID}).
```
Comment (whynowy) [inline persist/sqldb/workflow_archive.go]: `instanceid` is not needed here, it's not part of the PK, and we don't have an index matching (clustername, instanceid, uid).

The indexes we have are:
1. PK combo
2. (clustername, instanceid, namespace)

File: persist/sqldb/workflow_archive.go (hunk 1 above)
Comment (whynowy) [reply persist/sqldb/workflow_archive.go]: 👍

File: persist/sqldb/workflow_archive.go (hunk 2 above)
Comment (alexec) [reply persist/sqldb/workflow_archive.go]: you're correct, the instance ID will act as a filter - I think we should keep this because it'll prevent one instance from delete workflows from another instance - thoughts

Comment (whynowy) [reply persist/sqldb/workflow_archive.go]: Assume there is a case like you mentioned, it doesn't solve your problem - record not getting deleted, you will still get dup_key error.

Comment (alexec) [reply persist/sqldb/workflow_archive.go]: I can't see when this will happen - you'd have needed to have re-configure your controller between invocations...?

Comment (whynowy) [reply persist/sqldb/workflow_archive.go]: This only happens when:
1. A workflow object already exists in the cluster with `instanceid01`, and archived with same instanceid;
2. Re-configure your controller to serve `instanceid02`, or there's another controller in the same cluster serving `instanceid02`;
3. Update the object's label to mark it as `instanceid02`;
4. retry - archive

Comment (whynowy) [reply persist/sqldb/workflow_archive.go]: If we consider this kind of cases, we might need `instanceid` as part of the PK. :)

Comment (alexec) [reply persist/sqldb/workflow_archive.go]: What happens if we assume instance ID never changes?

Comment (whynowy) [reply persist/sqldb/workflow_archive.go]: if wf object instance ID label never changes, no matter how controller config changes, there won't be a case like that.

Comment (alexec) [reply persist/sqldb/workflow_archive.go]: ok, so should I be  allowed to ask a controller to delete a workflow that belongs to another controller?

Comment (whynowy) [reply persist/sqldb/workflow_archive.go]: Well, if wf object instance ID label never changes, you will not experience the situation that there is a record with same (clustername, uid) but different instanceid existing in the DB;

If wf object instant ID label is changed, which means the current wf object you are working on, was already archived by another controller, and there's a DB record existing. In this case,  if you add `instanceid` condition in your delete sql, you will not delete the record, and you still get `duplicate key` error when you insert.

Comment (alexec) [reply persist/sqldb/workflow_archive.go]: ok, removed - can you please review?
