### PR TITLE
fix(controller): Increase the number of cron workflow workers from 2 to 8. Fixes #4211

### LINKED ISSUE #4211: Second Cronworkflow is not being executed if first cronworkflow has 60k child workflow objects
## Summary 
The current Cronworkflow controller has only one worker to process the cronworkflow.  
it should be configurable like workflow workers.

What happened/what you expected to happen?

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by simster7**
Fixes: https://github.com/argoproj/argo/issues/4211 and maybe one part of https://github.com/argoproj/argo/issues/4181

### CODE REVIEW

File: workflow/cron/controller.go [hunk 1]
```diff
@@ -56,8 +56,8 @@ type Controller struct {
 
 const (
 	cronWorkflowResyncPeriod    = 20 * time.Minute
-	cronWorkflowWorkers         = 2
-	cronWorkflowWorkflowWorkers = 2
+	cronWorkflowWorkers         = 8
+	cronWorkflowWorkflowWorkers = 8
```
Comment (simster7) [inline workflow/cron/controller.go:60]: Should these be configurable?

Comment (alexec) [reply workflow/cron/controller.go:60]: yes, but 2nd PR?

Comment (simster7) [reply workflow/cron/controller.go:60]: Sure

**Review by alexec — APPROVED** [review]
