### PR TITLE
fix: Fix logging problems. See #2589

### LINKED ISSUE #2589: v2.7.0 CLI argo logs for workflows are broken
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

`argo logs` in v2.7.0 for workflows are broken in many ways.

1. Some pods' logs are dropped, seemingly at random.
2. The logs from each pod are arranged in random order, not chronological.
3. Run with the `-f` flag, `argo logs` misses logs from pods that are started after the command is issued.
4. The `-w` flag is deprecated but also rejected, another breaking change.
5. The logs are labeled with the pod names, making the color scheme useless (they all get the same color).

**How to reproduce it (as minimally and precisely as possible)**:

Just run a simple script with multiple steps with logs.

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: logs-problems-
spec:
  entrypoint: plan
  templates:
  - name: plan
    steps:

    - - name: report-1
        template: report
        arguments:
          parameters:
          - name: message
            value: one

    - - name: report-2
        template: report
        arguments:
          parameters:
          - name: message
            value: two

    - - name: report-3
        template: report
        arguments:
          parameters:
          - name: message
            value: three

    - - name: report-4
        template: report
        arguments:
          parameters:
          - name: message
            value: four

    - - name: report-5
        template: report
        arguments:
          parameters:
          - name: message
            value: five

  - name: report
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.11
      command: [sh, -c]
      args: ["echo {{inputs.parameters.message}}"]
```

Here's literally the output I see on the command line:
```
$ argo logs -n virtual logs-problems-jfcrs -f
logs-problems-jfcrs-1210664: two
logs-problems-jfcrs-1959331710: three
logs-problems-jfcrs-1789405150: one
$ argo logs -n virtual logs-problems-jfcrs
logs-problems-jfcrs-1210664: two
logs-problems-jfcrs-1959331710: three
$ argo logs -n virtual logs-problems-jfcrs
logs-problems-jfcrs-1959331710: three
logs-problems-jfcrs-1043726436: four
logs-problems-jfcrs-1210664: two
logs-problems-jfcrs-3944066254: five
$ argo logs -n virtual logs-problems-jfcrs
logs-problems-jfcrs-3944066254: five
logs-problems-jfcrs-1789405150: one
logs-problems-jfcrs-1210664: two
logs-problems-jfcrs-1043726436: four
```

You can see that I ran the `-f` command before the fourth and fifth pods had started, so it ignores those. (I've been able to reproduce this pattern over multiple attempts.) The later calls without that flag grab a random subset of the logs and paste them in a random order. Moreover, all of those logs were printed in red, a useless color scheme.

Needless to say, this makes `argo logs` on the CLI completely unusable in v2.7.0.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the USERS.md.
* [x] I've signed the CLA and required builds are green. 

See #2589

Fixes bullet points 3 and 5 from #2589. I believe that point 2 is caused by Go routine scheduling. May fix 1.

### CODE REVIEW

File: util/logs/workflow-logger.go [hunk 1]
```diff
@@ -212,11 +207,8 @@ func (l *workflowLogger) Run(ctx context.Context) {
 						return
 					}
 					l.logCtx.WithFields(log.Fields{"eventType": event.Type, "podName": pod.GetName(), "phase": pod.Status.Phase}).Debug("Pod event")
-					switch pod.Status.Phase {
-					case corev1.PodRunning:
+					if pod.Status.Phase == corev1.PodRunning {
 						l.ensureWeAreStreaming(pod)
-					case corev1.PodSucceeded, corev1.PodFailed:
-						return
```
Comment (alexec) [inline util/logs/workflow-logger.go:219]: this was the bug that cancelled logging once a completed pod was encounter 🤦‍♂

File: cmd/argo/commands/logs.go [hunk 2]
```diff
@@ -100,7 +100,7 @@ func NewLogsCommand() *cobra.Command {
 					return
 				}
 				errors.CheckError(err)
-				fmt.Println(ansiFormat(fmt.Sprintf("%s: %s", event.PodName, event.Content), ansiColorCode(podName)))
+				fmt.Println(ansiFormat(fmt.Sprintf("%s: %s", event.PodName, event.Content), ansiColorCode(event.PodName)))
```
Comment (alexec) [inline cmd/argo/commands/logs.go:103]: fixes the coloring bug

**Comment by alexec** [comment]
> These changes LGTM, but we should make sure we fix points 2. and 4. in the original issue before closing it

I'm not sure we should fix 4 (even though it is a breaking change), lets discus at stand-up.
