### PR TITLE
fix(server): Re-establish watch on v1.Status errors. Fixes #3608

### LINKED ISSUE #3608: Re-establish watch on `watch object was not a workflow *v1.Status` error

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #3608

### CODE REVIEW

File: server/workflow/workflow_server.go [hunk 1]
```diff
@@ -171,8 +169,12 @@ func (s *workflowServer) WatchWorkflows(req *workflowpkg.WatchWorkflowsRequest,
...
 		case <-ctx.Done():
 			return nil
-		case event, open := <-watch.ResultChan():
-			if !open {
+		case event, ok := <-watch.ResultChan():
+			var wf *wfv1.Workflow
+			if ok {
+				wf, ok = event.Object.(*wfv1.Workflow)
+			}
+			if !ok {
```
Comment (simster7) [inline server/workflow/workflow_server.go:177]: Could you explain this? Not sure how this fixes the issue?

Comment (alexec) [reply server/workflow/workflow_server.go:177]: essentially, I'm assuming if the result channel is closed, or the object is not an workflow (I'm assuming that this is a `*api.Status` error), but I don't think we care what it is, we just want to re-establish:

```golang
type Event struct {
	Type EventType

	// Object is:
	//  * If Type is Added or Modified: the new state of the object.
	//  * If Type is Deleted: the state of the object immediately before deletion.
	//  * If Type is Bookmark: the object (instance of a type being watched) where
	//    only ResourceVersion field is set. On successful restart of watch from a
	//    bookmark resourceVersion, client is guaranteed to not get repeat event
	//    nor miss any events.
	//  * If Type is Error: *api.Status is recommended; other types may make sense
	//    depending on context.
	Object runtime.Object
}
```
