### PR TITLE
fix: Fix bug in deleting pods. Fixes #2571

### LINKED ISSUE #2571: When trying to delete a pod, and we do not find it, this should not be an error
```
time="2020-04-02T18:30:47Z" level=error msg="Failed to delete pod dev-devx-mpa-cost-res-analysis-argo-usw2-ppd-qal/mpa-cost-argo-kjt7l-2211751261 for gc: pods \"mpa-cost-argo-kjt7l-2211751261\" not found"
```

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the USERS.md.
* [ ] I've signed the CLA and required builds are green.

### CODE REVIEW

**Comment by alexec** [comment]
This bug was introduced in July 2019.

File: ui/src/app/workflows/components/workflow-list-item/workflow-list-item.tsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ export interface WorkflowListItemProps {
 }
 
 function wfDuration(workflow: models.WorkflowStatus, now: moment.Moment) {
-    const endTime = workflow.finishedAt ? moment(workflow.finishedAt) : now
```
Comment (alexec) [inline ui/src/app/workflows/components/workflow-list-item/workflow-list-item.tsx:20]: looks like master needed linting :(

File: workflow/common/util.go [hunk 2]
```diff
@@ -458,7 +458,7 @@ func DeletePod(c kubernetes.Interface, podName, namespace string) error {
 	for attempt := 0; attempt < deleteRetries; attempt++ {
 		err = c.CoreV1().Pods(namespace).Delete(podName, &metav1.DeleteOptions{})
 		if err == nil || apierr.IsNotFound(err) {
-			break
+			return nil
```
Comment (alexec) [inline workflow/common/util.go:461]: this is what you get when you do not write tests
