### PR TITLE
fix: Begin counting maxDuration from first child start

### LINKED ISSUE #2901: Retry Strategy doesn't work in GKE preemptible node (pod deleted)
Checklist:

 * [x] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
I configured the retry strategy as the following
```
retryStrategy:
      limit: 4
      retryPolicy: "Always"
      backoff:
        duration: "12s"
        factor: 5
        maxDuration: "200m"
```
and run the Argo workflow in a GKE preemptible nodes.
When GKE required resources back deleting the nodes, the retry strategy doesn't work.
I received a red warning /!\ without the retry.

**What you expected to happen**:
I expected the retry strategy to works properly because I setup **retryPolicy: "Always"** as well.

**How to reproduce it (as minimally and precisely as possible)**:
Create a workflow with the following retry Strategy and run it in GKE GCP in a preemptible node
```
retryStrategy:
      limit: 4
      retryPolicy: "Always"
      backoff:
        duration: "12s"
        factor: 5
        maxDuration: "200m"
```

**Anything else we need to know?**:

**Environment**:
GKE (GCP)
- Argo version: v2.7.6
```
$ argo version
argo: v2.7.6+70facdb.dirty
  BuildDate: 2020-04-28T17:09:06Z
  GitCommit: 70facdb67207dbe115a9029e365f8e974e6156bc
  GitTreeState: dirty
  GitTag: v2.7.6
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2020-02-06T03:31:35Z"
  compiler: gc
  gitCommit: f5757a1dee5a89cc5e29cd7159076648bf21a02b
  gitTreeState: clean
  gitVersion: v1.14.10-dispatcher
  goVersion: go1.12.12b4
  major: "1"
  minor: 14+
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-02-21T18:01:40Z"
  compiler: gc
  gitCommit: 145f9e21a4515947d6fb10819e5a336aff1b6959
  gitTreeState: clean
  gitVersion: v1.14.10-gke.27
  goVersion: go1.12.12b4
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- workflow result:
Screen Shot 2020-04-30 at 1 59 01 pm

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by simster7**
Fixes #2901 

MaxDuration now counts from first node start instead of first node finish. It is more reliable and makes more sense given the spec

Also adds a short-circuit feature that would fail a retry if waiting for the current backoff would exceed the max duration, saving the time it would have spent waiting.

### CODE REVIEW

File: workflow/controller/exec_control.go [hunk 1]
```diff
@@ -75,7 +75,7 @@ func (woc *wfOperationCtx) applyExecutionControl(pod *apiv1.Pod, wfNodesLock *sy
 	var newDeadline *time.Time
 	if woc.wf.Spec.Shutdown != "" {
 		_, onExitPod := pod.Labels[common.LabelKeyOnExit]
-		if woc.wf.Spec.Shutdown == wfv1.ShutdownStrategyTerminate || (woc.wf.Spec.Shutdown == wfv1.ShutdownStrategyStop && !onExitPod) {
+		if !woc.wf.Spec.Shutdown.ShouldExecute(onExitPod) {
```
Comment (simster7) [inline workflow/controller/exec_control.go:78]: This is unrelated to the main PR. It simply uses a utility function instead of dealing with the logic manually

**Comment by simster7** [comment]
Back-ported to v2.8.2
