### PR TITLE
fix(executor): windows output artifacts. Fixes #4082

### LINKED ISSUE #4082: Windows Output artifact does not work
## Summary 

Using the following workflow specification I expect to be able to produce an output artifact in windows:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: windows-output-artifact-
spec:
  entrypoint: artifact-example
  templates:
    - name: artifact-example
      steps:
        - - name: generate-artifact
            template: hello-world
        - - name: consume-artifact
            template: print-message
            arguments:
              artifacts:
                - name: message
                  from: "{{steps.generate-artifact.outputs.artifacts.hello-art}}"

    - name: hello-world
      container:
        image: mcr.microsoft.com/windows/nanoserver:1809
        command: ["cmd", "/c"]
        args:
          [
            "md C:\\helloworld && echo 'Hello World' > C:\\helloworld\\hello_world.txt && type C:\\helloworld\\hello_world.txt",
          ]
      nodeSelector:
        kubernetes.io/os: windows
      outputs:
        artifacts:
          - name: hello-art
            path: /helloworld/
            # archive or not doesn't really matter - both fail the same way.
            archive:
              none: {}
    - name: print-message
      inputs:
        artifacts:
          - name: message
            path: /tmp/message
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["cat /tmp/message/hello_world.txt"]
```

It doesn't necessary need the second step - the `wait` container fails to properly produce the artifact:

```
time="2020-09-21T09:00:16.012Z" level=info msg="Waiting on main container"
time="2020-09-21T09:00:17.932Z" level=info msg="main container started with container ID: 5dcf9e5e4c30bc83e18a2acbe793cc610040ff49ab65ee68c567d8b2ebe152cf"
time="2020-09-21T09:00:17.932Z" level=info msg="Starting annotations monitor"
time="2020-09-21T09:00:17.940Z" level=info msg="Starting deadline monitor"
time="2020-09-21T09:00:17.941Z" level=info msg="docker wait 5dcf9e5e4c30bc83e18a2acbe793cc610040ff49ab65ee68c567d8b2ebe152cf"
time="2020-09-21T09:00:18.008Z" level=info msg="Main container completed"
time="2020-09-21T09:00:18.008Z" level=info msg="No Script output reference in workflow. Capturing script output ignored"
time="2020-09-21T09:00:18.008Z" level=info msg="Capturing script exit code"
time="2020-09-21T09:00:18.008Z" level=info msg="Annotations monitor stopped"
time="2020-09-21T09:00:18.066Z" level=info msg="No output parameters"
time="2020-09-21T09:00:18.066Z" level=info msg="Saving output artifacts"
time="2020-09-21T09:00:18.067Z" level=info msg="Staging artifact: hello-art"
time="2020-09-21T09:00:18.067Z" level=info msg="Copying /helloworld/ from container base image layer to \\tmp\\argo\\outputs\\artifacts\\hello-art.tgz"
time="2020-09-21T09:00:18.067Z" level=info msg="Archiving 5dcf9e5e4c30bc83e18a2acbe793cc610040ff49ab65ee68c567d8b2ebe152cf:/helloworld/ to \\tmp\\argo\\outputs\\artifacts\\hello-art.tgz"
time="2020-09-21T09:00:18.068Z" level=info msg="sh -c docker cp -a 5dcf9e5e4c30bc83e18a2acbe793cc610040ff49ab65ee68c567d8b2ebe152cf:/helloworld/ - | gzip -1 > \\tmp\\argo\\outputs\\artifacts\\hello-art.tgz"
time="2020-09-21T09:00:18.941Z" level=info msg="Deadline monitor stopped"
time="2020-09-21T09:00:19.041Z" level=error msg="executor error: open \\tmp\\argo\\outputs\\artifacts\\hello-art.tgz: The system cannot find the file specified."
time="2020-09-21T09:00:19.041Z" level=info msg="Killing sidecars"
time="2020-09-21T09:00:19.049Z" level=info msg="Alloc=6403 TotalAlloc=14979 Sys=16138 NumGC=5 Goroutines=8"
```

I suspect the path is wrong: `\\tmp\\argo\\outputs\\artifacts\\hello-art.tgz` but I might be wrong - I didn't have a look at the code yet. 

What's additionally weird to me (but maybe that's intended): If I specify `archive: none: {}` (with newline in between of course) it doesn't work either, but also tries to do a gzip. Is this intended?

## Diagnostics

What version of Argo Workflows are you running?

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-09-21T09:04:42Z"
  generateName: windows-output-artifact-
  generation: 5
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Failed
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
      f:spec:
        .: {}
        f:arguments: {}
        f:entrypoint: {}
        f:templates: {}
      f:status: {}
    manager: argo
    operation: Update
    time: "2020-09-21T09:04:42Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:workflows.argoproj.io/completed: {}
          f:workflows.argoproj.io/phase: {}
      f:status:
        f:conditions: {}
        f:finishedAt: {}
        f:message: {}
        f:nodes:
          .: {}
          f:windows-output-artifact-jmdt6:
            .: {}
            f:children: {}
            f:displayName: {}
            f:finishedAt: {}
            f:id: {}
            f:message: {}
            f:name: {}
            f:outboundNodes: {}
            f:phase: {}
            f:startedAt: {}
            f:templateName: {}
            f:templateScope: {}
            f:type: {}
          f:windows-output-artifact-jmdt6-965764123:
            .: {}
            f:boundaryID: {}
            f:displayName: {}
            f:finishedAt: {}
            f:hostNodeName: {}
            f:id: {}
            f:message: {}
            f:name: {}
            f:phase: {}
            f:resourcesDuration:
              .: {}
              f:cpu: {}
              f:memory: {}
            f:startedAt: {}
            f:templateName: {}
            f:templateScope: {}
            f:type: {}
          f:windows-output-artifact-jmdt6-3135273321:
            .: {}
            f:boundaryID: {}
            f:children: {}
            f:displayName: {}
            f:finishedAt: {}
            f:id: {}
            f:message: {}
            f:name: {}
            f:phase: {}
            f:startedAt: {}
            f:templateName: {}
            f:templateScope: {}
            f:type: {}
        f:phase: {}
        f:resourcesDuration:
          .: {}
          f:cpu: {}
          f:memory: {}
        f:startedAt: {}
    manager: workflow-controller
    operation: Update
    time: "2020-09-21T09:04:51Z"
  name: windows-output-artifact-jmdt6
  namespace: argo
  resourceVersion: "109175093"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/windows-output-artifact-jmdt6
  uid: 0b680a67-7d0e-43cb-b9fe-cf1b8460ca53
spec:
  arguments: {}
  entrypoint: artifact-example
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: artifact-example
    outputs: {}
    steps:
    - - arguments: {}
        name: generate-artifact
        template: hello-world
    - - arguments:
          artifacts:
          - from: '{{steps.generate-artifact.outputs.artifacts.hello-art}}'
            name: message
        name: consume-artifact
        template: print-message
  - arguments: {}
    container:
      args:
      - md C:\helloworld && echo 'Hello World' > C:\helloworld\hello_world.txt &&
        type C:\helloworld\hello_world.txt
      command:
      - cmd
      - /c
      image: mcr.microsoft.com/windows/nanoserver:1809
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: hello-world
    nodeSelector:
      kubernetes.io/os: windows
    outputs:
      artifacts:
      - archive:
          none: {}
        name: hello-art
        path: /helloworld/hello_world.txt
  - arguments: {}
    container:
      args:
      - cat /tmp/message/hello_world.txt
      command:
      - sh
      - -c
      image: alpine:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: message
        path: /tmp/message
    metadata: {}
    name: print-message
    outputs: {}
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-09-21T09:04:51Z"
  message: child 'windows-output-artifact-jmdt6-965764123' failed
  nodes:
    windows-output-artifact-jmdt6:
      children:
      - windows-output-artifact-jmdt6-3135273321
      displayName: windows-output-artifact-jmdt6
      finishedAt: "2020-09-21T09:04:51Z"
      id: windows-output-artifact-jmdt6
      message: child 'windows-output-artifact-jmdt6-965764123' failed
      name: windows-output-artifact-jmdt6
      outboundNodes:
      - windows-output-artifact-jmdt6-965764123
      phase: Failed
      startedAt: "2020-09-21T09:04:42Z"
      templateName: artifact-example
      templateScope: local/windows-output-artifact-jmdt6
      type: Steps
    windows-output-artifact-jmdt6-965764123:
      boundaryID: windows-output-artifact-jmdt6
      displayName: generate-artifact
      finishedAt: "2020-09-21T09:04:49Z"
      hostNodeName: gke-dev-autoscaling-pool-window-e1efad56-g7lt
      id: windows-output-artifact-jmdt6-965764123
      message: 'failed to save outputs: verify serviceaccount argo:default has necessary
        privileges'
      name: windows-output-artifact-jmdt6[0].generate-artifact
      phase: Error
      resourcesDuration:
        cpu: 3
        memory: 3
      startedAt: "2020-09-21T09:04:42Z"
      templateName: hello-world
      templateScope: local/windows-output-artifact-jmdt6
      type: Pod
    windows-output-artifact-jmdt6-3135273321:
      boundaryID: windows-output-artifact-jmdt6
      children:
      - windows-output-artifact-jmdt6-965764123
      displayName: '[0]'
      finishedAt: "2020-09-21T09:04:51Z"
      id: windows-output-artifact-jmdt6-3135273321
      message: child 'windows-output-artifact-jmdt6-965764123' failed
      name: windows-output-artifact-jmdt6[0]
      phase: Failed
      startedAt: "2020-09-21T09:04:42Z"
      templateName: artifact-example
      templateScope: local/windows-output-artifact-jmdt6
      type: StepGroup
  phase: Failed
  resourcesDuration:
    cpu: 3
    memory: 3
  startedAt: "2020-09-21T09:04:42Z"
```

I'm on argo version 2.11 but using `argoexec:latest` due to testing of #3682.
```

time="2020-09-21T09:04:42Z" level=info msg="Processing workflow" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:42Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:42Z" level=info msg="Steps node windows-output-artifact-jmdt6 initialized Running" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:42Z" level=info msg="StepGroup node windows-output-artifact-jmdt6-3135273321 initialized Running" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:42Z" level=info msg="Pod node windows-output-artifact-jmdt6-965764123 initialized Pending" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:42Z" level=info msg="Created pod: windows-output-artifact-jmdt6[0].generate-artifact (windows-output-artifact-jmdt6-965764123)" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:42Z" level=info msg="Workflow step group node windows-output-artifact-jmdt6-3135273321 not yet completed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:42Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=109175000 workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:43Z" level=info msg="Processing workflow" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:43Z" level=info msg="Updating node windows-output-artifact-jmdt6-965764123 message: ContainerCreating"
time="2020-09-21T09:04:43Z" level=info msg="Skipped pod windows-output-artifact-jmdt6[0].generate-artifact (windows-output-artifact-jmdt6-965764123) creation: already exists" namespace=argo podPhase=Pending workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:43Z" level=info msg="Workflow step group node windows-output-artifact-jmdt6-3135273321 not yet completed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:43Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=109175012 workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:44Z" level=info msg="Processing workflow" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:44Z" level=info msg="Skipped pod windows-output-artifact-jmdt6[0].generate-artifact (windows-output-artifact-jmdt6-965764123) creation: already exists" namespace=argo podPhase=Pending workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:44Z" level=info msg="Workflow step group node windows-output-artifact-jmdt6-3135273321 not yet completed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:49Z" level=info msg="Processing workflow" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:49Z" level=info msg="Updating node windows-output-artifact-jmdt6-965764123 status Pending -> Running"
time="2020-09-21T09:04:49Z" level=info msg="Workflow step group node windows-output-artifact-jmdt6-3135273321 not yet completed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:49Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=109175066 workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:50Z" level=info msg="Processing workflow" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:50Z" level=info msg="Workflow step group node windows-output-artifact-jmdt6-3135273321 not yet completed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="Processing workflow" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="Updating node windows-output-artifact-jmdt6-965764123 status Running -> Error"
time="2020-09-21T09:04:51Z" level=info msg="Updating node windows-output-artifact-jmdt6-965764123 message: failed to save outputs: verify serviceaccount argo:default has necessary privileges"
time="2020-09-21T09:04:51Z" level=info msg="Step group node windows-output-artifact-jmdt6-3135273321 deemed failed: child 'windows-output-artifact-jmdt6-965764123' failed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="node windows-output-artifact-jmdt6-3135273321 phase Running -> Failed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="node windows-output-artifact-jmdt6-3135273321 message: child 'windows-output-artifact-jmdt6-965764123' failed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="node windows-output-artifact-jmdt6-3135273321 finished: 2020-09-21 09:04:51.582387653 +0000 UTC" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="step group windows-output-artifact-jmdt6-3135273321 was unsuccessful: child 'windows-output-artifact-jmdt6-965764123' failed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="Outbound nodes of windows-output-artifact-jmdt6-965764123 is [windows-output-artifact-jmdt6-965764123]" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="Outbound nodes of windows-output-artifact-jmdt6 is [windows-output-artifact-jmdt6-965764123]" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="node windows-output-artifact-jmdt6 phase Running -> Failed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="node windows-output-artifact-jmdt6 message: child 'windows-output-artifact-jmdt6-965764123' failed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="node windows-output-artifact-jmdt6 finished: 2020-09-21 09:04:51.582480574 +0000 UTC" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="Checking daemoned children of windows-output-artifact-jmdt6" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="Updated message  -> child 'windows-output-artifact-jmdt6-965764123' failed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="Marking workflow completed" namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="Checking daemoned children of " namespace=argo workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:51Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=109175093 workflow=windows-output-artifact-jmdt6
time="2020-09-21T09:04:52Z" level=info msg="Labeled pod completed" namespace=argo pod=windows-output-artifact-jmdt6-965764123
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by mweibel**
This is a preliminary change to fix #4082. 
After this change the following happens:

```
time="2020-09-21T11:59:10.713Z" level=info msg="Saving output artifacts"
time="2020-09-21T11:59:10.714Z" level=info msg="Staging artifact: render-files"
time="2020-09-21T11:59:10.714Z" level=info msg="Copying /render/ from container base image layer to \\tmp\\argo\\outputs\\artifacts\\render-files.tgz"
time="2020-09-21T11:59:10.714Z" level=info msg="Archiving fe5574c11e503bf7d7fe00202990d70f81f7d995867dd02d229623b41909a18b:/render/ to \\tmp\\argo\\outputs\\artifacts\\render-files.tgz"
time="2020-09-21T11:59:10.715Z" level=info msg="cmd /c docker cp -a fe5574c11e503bf7d7fe00202990d70f81f7d995867dd02d229623b41909a18b:/render/ - | gzip -1 > \\tmp\\argo\\outputs\\artifacts\\render-files.tgz"
time="2020-09-21T11:59:10.787Z" level=error msg="`cmd /c docker cp -a fe5574c11e503bf7d7fe00202990d70f81f7d995867dd02d229623b41909a18b:/render/ - | gzip -1 > \\tmp\\argo\\outputs\\artifacts\\render-files.tgz` failed: 'gzip' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"
time="2020-09-21T11:59:10.787Z" level=error msg="executor error: 'gzip' is not recognized as an internal or external command,\r\noperable program or batch file.\ngithub.com/argoproj/argo/errors.New\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/errors/errors.go:49\ngithub.com/argoproj/argo/errors.InternalError\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/errors/errors.go:60\ngithub.com/argoproj/argo/workflow/common.RunCommand\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/workflow/common/util.go:416\ngithub.com/argoproj/argo/workflow/common.RunShellCommand\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/workflow/common/util_windows.go:7\ngithub.com/argoproj/argo/workflow/executor/docker.(*DockerExecutor).CopyFile\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/workflow/executor/docker/docker.go:61\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).stageArchiveFile\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/workflow/executor/executor.go:387\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).saveArtifact\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/workflow/executor/executor.go:272\ngithub.com/argoproj/argo/workflow/executor.(*WorkflowExecutor).SaveArtifacts\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/workflow/executor/executor.go:258\ngithub.com/argoproj/argo/cmd/argoexec/commands.waitContainer\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:71\ngithub.com/argoproj/argo/cmd/argoexec/commands.NewWaitCommand.func1\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/cmd/argoexec/commands/wait.go:16\ngithub.com/spf13/cobra.(*Command).execute\n\tC:/Users/ContainerAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tC:/Users/ContainerAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950\ngithub.com/spf13/cobra.(*Command).Execute\n\tC:/Users/ContainerAdministrator/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887\nmain.main\n\tC:/Users/ContainerAdministrator/go/src/github.com/argoproj/argo/cmd/argoexec/main.go:17\nruntime.main\n\tc:/go/src/runtime/proc.go:203\nruntime.goexit\n\tc:/go/src/runtime/asm_amd64.s:1357"
time="2020-09-21T11:59:10.787Z" level=info msg="Killing sidecars"
```

So `gzip` obviously doesn't exist on Windows 😄 Will see what to do about this case. Maybe @lippertmarkus has an idea?
Same issue probably with `DockerExecutor#GetFileContents()` which uses `tar`.

Checklist:

* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by lippertmarkus** [comment]
Thanks for addressing this. I think the easiest solution would be to add gzip to the Docker image. This should be as simple as 
1) Installing gzip via chocolatey into the builder layer, just add `gzip` package here: https://github.com/argoproj/argo/blob/master/Dockerfile.windows#L22
2) Copy it to the `argoexec-base` layer [like we also do with docker CLI and git](https://github.com/argoproj/argo/blob/master/Dockerfile.windows#L42-L43): add `COPY --from=builder C:/ProgramData/chocolatey/bin/gzip.exe C:/app/gzip.exe`

Could you please try if that fixes the remaining error?

**Comment by alexec** [comment]
@lippertmarkus I'm going to create a Windows team and make you the first member. Do you think I should add anyone else?

**Comment by alexec** [comment]
@ricochet?

**Comment by lippertmarkus** [comment]
@mweibel Nevermind, I just remembered that `sh` and `gzip` executables don't work on `nanoserver` but only on `servercore` (see https://github.com/msys2/MSYS2-packages/issues/1493). 

Instead of using the much bigger `servercore` Docker image I would suggest switching to cmd like you tried in this PR and on Windows use 7zip instead of gzip to create the .tar.gz archive. It can also compress piped input from stdin like `type mytest.tar | 7za.exe a -tgzip -si mytest.tar.gz`.

This means we instead need to install 7zip into the Docker image:
1. Install 7zip via chocolatey into the builder layer, just add `7zip.portable` package here: https://github.com/argoproj/argo/blob/master/Dockerfile.windows#L22
2. Copy it to the argoexec-base layer [like we also do with docker CLI and git](https://github.com/argoproj/argo/blob/master/Dockerfile.windows#L42-L43): add `COPY --from=builder C:/ProgramData/chocolatey/lib/7zip.portable/tools/7z-extra/x64/7za.exe C:/app/7za.exe`

You then would need to change the code to run 7za instead of gzip when we're on Windows.

**Comment by lippertmarkus** [comment]
@alexec Thanks, what an honor :) I'm not sure but I think I was the only one who contributed to Windows support until now, wasn't I?

**Comment by alexec** [comment]
@argoproj/argo-windows  === @lippertmarkus :)

**Comment by mweibel** [comment]
@lippertmarkus please review. I adjusted as you told and it seems to work now:

```
time="2020-09-22T08:46:05.513Z" level=info msg="Staging artifact: hello-art"
time="2020-09-22T08:46:05.513Z" level=info msg="Copying /helloworld/hello_world.txt from container base image layer to \\tmp\\argo\\outputs\\artifacts\\hello-art.tgz"
time="2020-09-22T08:46:05.513Z" level=info msg="Archiving 93ca80547c68bb01272a22de92747cfecae4b172e3d7520b0afdcd18ba4b5269:/helloworld/hello_world.txt to \\tmp\\argo\\outputs\\artifacts\\hello-art.tgz"
time="2020-09-22T08:46:05.514Z" level=info msg="cmd /c docker cp -a 93ca80547c68bb01272a22de92747cfecae4b172e3d7520b0afdcd18ba4b5269:/helloworld/hello_world.txt - | 7za.exe a -tgzip -si -mx1 \\tmp\\argo\\outputs\\artifacts\\hello-art.tgz"
time="2020-09-22T08:46:05.679Z" level=info msg="Archiving completed"
time="2020-09-22T08:46:05.679Z" level=info msg="Untaring \\tmp\\argo\\outputs\\artifacts\\hello-art.tgz archive before upload"
time="2020-09-22T08:46:05.680Z" level=info msg="tar -xf \\tmp\\argo\\outputs\\artifacts\\hello-art.tgz -C \\tmp\\argo\\outputs\\artifacts/hello-art.tmpdir"
time="2020-09-22T08:46:05.702Z" level=info msg="S3 Save path: /tmp/argo/outputs/artifacts/hello_world.txt, key: windows-output-artifact-v7n4b/windows-output-artifact-v7n4b-387304899/hello_world.txt"
time="2020-09-22T08:46:05.702Z" level=info msg="Creating minio client minio.minio.svc.cluster.local:9000 using static credentials"
time="2020-09-22T08:46:05.702Z" level=info msg="Saving from /tmp/argo/outputs/artifacts/hello_world.txt to s3 (endpoint: minio.minio.svc.cluster.local:9000, bucket: k8s-helio-development-argo, key: windows-output-artifact-v7n4b/windows-output-artifact-v7n4b-387304899/hello_world.txt)"
time="2020-09-22T08:46:06.164Z" level=info msg="Successfully saved file: /tmp/argo/outputs/artifacts/hello_world.txt"
time="2020-09-22T08:46:06.164Z" level=info msg="Annotating pod with output"
time="2020-09-22T08:46:06.189Z" level=info msg="Killing sidecars"
time="2020-09-22T08:46:06.194Z" level=info msg="Alloc=7261 TotalAlloc=15784 Sys=15882 NumGC=5 Goroutines=11"
```

Let me know if I should add tests around it - though I might need some guidance on that. Also regarding code style let me know if there's things you'd like improved of course 👍

File: workflow/common/util_notwin.go [hunk 1]
```diff
@@ -0,0 +1,10 @@
+// +build !windows
+
+package common
+
+// RunShellCommand is a convenience function to use RunCommand for shell executions. It's os-specific
+// and runs `cmd` in windows (see `util_windows.go`)
+func RunShellCommand(arg ...string) ([]byte, error) {
```
Comment (lippertmarkus) [inline workflow/common/util_notwin.go:7]: For simplicity instead of build flags I would determine the OS at runtime via:
```golang
if runtime.GOOS == "windows" {
    // use cmd /c instead of sh -c
}
```

Then we could just move this function to `util.go` and don't need two additional files.

File: workflow/executor/docker/docker_windows.go [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+
+package docker
+
+import (
+	"compress/gzip"
+	"fmt"
+	"strconv"
+)
+
+func dockerCpCmd(containerID, sourcePath string, compressionLevel int, destPath string) string {
```
Comment (lippertmarkus) [inline workflow/executor/docker/docker_windows.go:11]: Can we rename to `getDockerCpCmd`? And again for simplicity and to remove redundant code I would go with checking `runtime.GOOS` like above and switch two variables based on this:
- `levelFlagParam`: `-mx` on Windows and `-` on Linux (use as prefix when assigning `levelFlag`)
- `gzipCmd`: `7za.exe a -tgzip -si %s %s` on Windows and `gzip %s > %s` on Linux (use as suffix for first param in `fmt.Sprintf`)

**Review by lippertmarkus — CHANGES_REQUESTED** [review]
@mweibel Thanks a lot for your effort. Two small comments:

File: workflow/executor/docker/docker_notwin.go [hunk 3]
```diff
@@ -0,0 +1,25 @@
+// +build !windows
```
Comment (alexec) [inline workflow/executor/docker/docker_notwin.go:1]: This is not quite the right way to do this. To have different versions of code for different platforms please refer to `chroot_windows.go` vs `chroot_darwin.go`.

Comment (mweibel) [reply workflow/executor/docker/docker_notwin.go:1]: I implemented it as such because there's no difference between linux & darwin, hence only a difference between windows and not windows is needed. 
As it works quite well like this (and I've seen [codebases](https://github.com/golang/go/blob/master/src/internal/testenv/testenv_notwin.go) using this, also a [blog post references this](https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool)) I'm not sure what you mean with "This is not quite the right way to do this". Possibly you mean that in the argo project you prefer to do it the other way. 

Anyway - I'll follow what @lippertmarkus proposed and solve it using `runtime.GOOS` checks, if that's the preferred way.

**Comment by alexec** [comment]
@mweibel I'd like to add you to @argoproj/argo-windows ok?

**Comment by mweibel** [comment]
I don't have much know-how about argo yet and less than about windows (just the need to use it atm 😄), but yeah. That's fine for me.

**Comment by mweibel** [comment]
FYI I updated the PR with the requested changes and squashed the commits into one. 
I didn't test the latest changes just yet, will do so soon.

**Review by lippertmarkus — APPROVED** [review]
Looks good to me, thanks. @alexec could you please also verify before merging when @mweibel finished testing?

**Comment by mweibel** [comment]
I tested using our own workflows as well as using the test workflow I pasted in #4082. Additionally I played with the archive strategy (none, default, tar with compressionLevel 9) and it all worked well. 

As requested in the issue template I added us to the list of users, too. 🙂

**Review by alexec — APPROVED** [review]

**Comment by mweibel** [comment]
@lippertmarkus @alexec I noticed that the changes are not yet in a release - I probably missed that I should make the changes based on branch `release-2.11` and merge against that. Should I try to backport this to get it into the next bugfix release?
