### PR TITLE
fix(cli): Show lint errors of all files

### LINKED ISSUE #2266: argo lint on multiple files should list all files with failures
# Summary

`argo lint` can run on either a list of files or an entire directory to verify multiple workflows. However, it doesn't give a complete report of the passing and failing workflows, but simply outputs the first failure it finds. It would be more useful if it gave a complete listing of whether the linter passes on each workflow file provided.

# Motivation

I frequently develop sets of multiple related workflows want to check all of them. But while I'm writing them, they might not all be fixed up yet. I want to easily be able to tell which ones have errors without having to run `argo lint` on each file individually in separate lines.

# Proposal

When running on either a directory or multiple files, `argo lint` should just continue after failure to the next file, echoing its error messages as they come in. As a bonus, it could print something after each file which passes to show that it checked that file.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by NikeNano**
Argo lint can run on either a list of files or an entire directory to verify multiple workflows. However, it doesn't give a complete report of the passing and failing workflows, but simply outputs the first failure it finds. This PR aims to solve this by instead logging the error in each workflow but continue to validate the remaining workflows. 

The solution is to use ```log.warn``` instead of ``` log.fatal``` for listing errors. log.Fatal result in equivalent to l.Printf() followed by a call to os.Exit(1) which is now avoided. 

Do we prefer to use log or fmt in the cli? 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [ ] Optional. I've added My organization is added to the USERS.md.
* [ ] I've signed the CLA and required builds are green.

### CODE REVIEW

File: cmd/argo/commands/lint.go [hunk 1]
```diff
@@ -56,7 +57,9 @@ func NewLintCommand() *cobra.Command {
 					errors.CheckError(err)
 				} else {
 					err := lint(file)
-					errors.CheckError(err)
+					if err != nil {
+						log.Warn(err)
+					}
```
Comment (simster7) [inline cmd/argo/commands/lint.go]: This code is incorrect. The error message for all the files would be displayed, but execution would continue. We need to both log all errors and stop execution.

File: cmd/argo/commands/lint.go [hunk 2]
```diff
@@ -56,7 +57,9 @@ func NewLintCommand() *cobra.Command {
 					errors.CheckError(err)
```
Comment (simster7) [inline cmd/argo/commands/lint.go]: If we attempt to lint a directory, would all the errors be shown as well or just the first one?

File: cmd/argo/commands/lint.go (hunk 1 above)
Comment (NikeNano) [reply cmd/argo/commands/lint.go]: Do you mean to stop the execution on the workflow which has errors? I thought the goal with the issue where not to stop the execution?

Comment (simster7) [reply cmd/argo/commands/lint.go]: Oh sorry, used a misnomer. I meant that even if there are errors "Workflow manifests validated" would still be printed and exit code would still be `0`. Some of our users might have scripts that consider that a successful lint, which it wasn't.

Comment (NikeNano) [reply cmd/argo/commands/lint.go]: Cool! Then I get it, will update.

File: cmd/argo/commands/lint.go (hunk 2 above)
Comment (NikeNano) [reply cmd/argo/commands/lint.go]: Will fix this!

**Comment by NikeNano** [comment]
Need to fix one last thing :)

File: cmd/argo/commands/lint.go [hunk 3]
```diff
@@ -22,6 +22,7 @@ func NewLintCommand() *cobra.Command {
 		Use:   "lint FILE...",
 		Short: "validate files or directories of workflow manifests",
 		Run: func(cmd *cobra.Command, args []string) {
+			var unvalidWf error
```
Comment (simster7) [inline cmd/argo/commands/lint.go:25]: Be specific that this is an error in the variable name
```suggestion
			var invalidWfErr error
```

File: cmd/argo/commands/lint.go [hunk 4]
```diff
@@ -37,32 +38,41 @@ func NewLintCommand() *cobra.Command {
 						return err
 					}
 				}
-				fmt.Printf("%s is valid\n", file)
+				fmt.Printf("%s is valid \u2713\n ", file)
```
Comment (simster7) [inline cmd/argo/commands/lint.go:41]: We don't want unicode characters in our messages.
```suggestion
				fmt.Printf("%s is valid\n ", file)
```

File: cmd/argo/commands/lint.go [hunk 5]
```diff
@@ -37,32 +38,41 @@ func NewLintCommand() *cobra.Command {
...
 						default:
 							return nil
 						}
-						return lint(path)
+						err = lint(path)
+						if err != nil {
+							unvalidWf = fmt.Errorf("unvalid workflow/workflows found")
+							log.Warn(fmt.Errorf("%w \u2717", err))
+						}
+						return nil
```
Comment (simster7) [inline cmd/argo/commands/lint.go:60]: We still want the error to be returned from the `filepath.Walk` function. It's ok to show the warning and return the original error.

File: cmd/argo/commands/lint.go [hunk 6]
```diff
@@ -37,32 +38,41 @@ func NewLintCommand() *cobra.Command {
...
+				fmt.Printf("%s is valid \u2713\n ", file)
 				return nil
 			}
-
 			for _, file := range args {
 				stat, err := os.Stat(file)
 				errors.CheckError(err)
 				if stat.IsDir() {
-					err := filepath.Walk(file, func(path string, info os.FileInfo, err error) error {
+					filepath.Walk(file, func(path string, info os.FileInfo, err error) error {
```
Comment (simster7) [inline cmd/argo/commands/lint.go:48]: We still want the original error returned.
```suggestion
					invalidWfErr = filepath.Walk(file, func(path string, info os.FileInfo, err error) error {
```

File: cmd/argo/commands/lint.go [hunk 7]
```diff
@@ -37,32 +38,41 @@ func NewLintCommand() *cobra.Command {
...
 						fileExt := filepath.Ext(info.Name())
 						switch fileExt {
 						case ".yaml", ".yml", ".json":
 						default:
 							return nil
 						}
-						return lint(path)
+						err = lint(path)
+						if err != nil {
+							unvalidWf = fmt.Errorf("unvalid workflow/workflows found")
```
Comment (simster7) [inline cmd/argo/commands/lint.go:57]: Don't make a new error, use the original returned by `lint`

File: cmd/argo/commands/lint.go [hunk 8]
```diff
@@ -37,32 +38,41 @@ func NewLintCommand() *cobra.Command {
...
+							log.Warn(fmt.Errorf("%w \u2717", err))
```
Comment (simster7) [inline cmd/argo/commands/lint.go:58]: We don't want to use Unicode characters, reporting the raw error is fine.

What would be nice is if you prepended the error with the file name. Something like `workflow1.yaml: this is the error message`

File: cmd/argo/commands/lint.go [hunk 9]
```diff
@@ -37,32 +38,41 @@ func NewLintCommand() *cobra.Command {
...
-						log.Warn(err)
+						unvalidWf = fmt.Errorf("unvalidWf workflow/workflows found")
+						log.Warn(fmt.Errorf("%w \u2717", err))
 					}
 				}
+				err = nil
+			}
+			if unvalidWf != nil {
+				errors.CheckError(unvalidWf)
+			} else {
```
Comment (simster7) [inline cmd/argo/commands/lint.go:73]: This `else` is not needed, since `errors.CheckError` will stop execution with a `fatal`.

File: cmd/argo/commands/lint.go [hunk 10]
```diff
@@ -36,30 +38,41 @@ func NewLintCommand() *cobra.Command {
 						return err
 					}
 				}
-				fmt.Printf("%s is valid\n", file)
+				fmt.Printf("%s is valid \u2713\n ", file)
 				return nil
 			}
-
```
Comment (simster7) [inline cmd/argo/commands/lint.go:42]: Add this linebreak back please.

File: cmd/argo/commands/lint.go [hunk 11]
```diff
@@ -36,30 +38,41 @@ func NewLintCommand() *cobra.Command {
...
+							log.Warn(fmt.Errorf("%w \u2717", err))
+						}
+						return nil
 					})
-					errors.CheckError(err)
 				} else {
 					err := lint(file)
-					errors.CheckError(err)
+					if err != nil {
+						unvalidWf = fmt.Errorf("unvalidWf workflow/workflows found")
```
Comment (simster7) [inline cmd/argo/commands/lint.go:65]: Same here. No need to make a new error.

File: cmd/argo/commands/lint.go [hunk 12]
```diff
@@ -36,30 +38,41 @@ func NewLintCommand() *cobra.Command {
...
+						log.Warn(fmt.Errorf("%w \u2717", err))
```
Comment (simster7) [inline cmd/argo/commands/lint.go:66]: Same here. We don't want unicode. You can prepend the error message with the name of the file that caused it.

File: cmd/argo/commands/lint.go (hunk 5 above)
Comment (NikeNano) [reply cmd/argo/commands/lint.go:60]: I had issues returning the error resulted in that the ```filepath.Walk ``` broke execution and did not complete for folders. I will verify this again.

Comment (NikeNano) [reply cmd/argo/commands/lint.go:60]: [Here](https://golang.org/pkg/path/filepath/#WalkFunc) is the documentation on file path.Walk as I understand from ``` ...  In the case of an error, the info argument will be nil. If an error is returned, processing stops. The sole exception is when the function returns the special value SkipDir. ...``` I can not return an error if I like to continue the execution. Therefore I create a new error outside of the function which I use to capture that the file path.walk has not been successful for all files. Maybe I am missing something? @simster7.

Comment (NikeNano) [reply cmd/argo/commands/lint.go:60]: [Here](https://golang.org/pkg/path/filepath/#WalkFunc) is the documentation on filepath.WalkFunc. Which is used by 
```
func Walk(root string, walkFn WalkFunc) error
```
as I understand from ``` ...  In the case of an error, the info argument will be nil. If an error is returned, processing stops. The sole exception is when the function returns the special value SkipDir. ...``` I can not return an error if I like to continue the execution. Therefore I create a new error outside of the function which I use to capture that the file path.walk has not been successful for all files. Maybe I am missing something? @simster7.

File: cmd/argo/commands/lint.go (hunk 8 above)
Comment (NikeNano) [reply cmd/argo/commands/lint.go]: The current behaviour is: 
``` 
WARN[0000] /Users/niklashansson/Documents/go/src/github.com/argoproj/argo/test/e2e/functional/steps.yaml failed to parse: error unmarshaling JSON: while decoding JSON: json: unknown field "kiiind" 
```

File: cmd/argo/commands/lint.go [hunk 13]
```diff
@@ -44,20 +46,31 @@ func NewLintCommand() *cobra.Command {
...
 						fileExt := filepath.Ext(info.Name())
 						switch fileExt {
 						case ".yaml", ".yml", ".json":
 						default:
 							return nil
 						}
-						return lint(path)
+						err = lint(path)
+						if err != nil {
+							invalidWfErr = fmt.Errorf("Unvalid workflow/workflows found")
```
Comment (simster7) [inline cmd/argo/commands/lint.go:58]:
```suggestion
							invalidWfErr = fmt.Errorf("Invalid workflow/workflows found")
```

File: cmd/argo/commands/lint.go [hunk 14]
```diff
@@ -44,20 +46,31 @@ func NewLintCommand() *cobra.Command {
...
+							log.Warn(err)
+						}
+						return nil
 					})
-					errors.CheckError(err)
 				} else {
 					err := lint(file)
-					errors.CheckError(err)
+					if err != nil {
+						invalidWfErr = fmt.Errorf("Unvalid workflow/workflows found")
```
Comment (simster7) [inline cmd/argo/commands/lint.go:66]:
```suggestion
						invalidWfErr = fmt.Errorf("Invalid workflow/workflows found")
```

File: cmd/argo/commands/lint.go (hunk 5 above)
Comment (simster7) [reply cmd/argo/commands/lint.go]: Alright, let's leave this as is then.

File: cmd/argo/commands/lint.go (hunk 8 above)
Comment (simster7) [reply cmd/argo/commands/lint.go]: Ah got it. It's fine as is then 🙂

**Comment by simster7** [comment]
Back-ported to 2.7
