### PR TITLE
fix: Workflow should fail on Pod failure before container starts Fixes #3879

### LINKED ISSUE #3879: Pod's phase is failed, but the workflow node status is succeeded.
## Summary 

What happened/what you expected to happen?
Pod's phase is failed, but the workflow node status is succeeded.

## Diagnostics

What version of Argo Workflows are you running?
v2.7.0

```yaml
Paste the workflow here, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

The pod's yaml
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    ProviderCreate: done
    k8s.aliyun.com/eci-image-cache: "true"
    k8s.aliyun.com/eci-instance-cpu: "48.000"
    k8s.aliyun.com/eci-instance-id: eci-bp16ie6rtdjkawmxzpp2
    k8s.aliyun.com/eci-instance-mem: "186.00"
    k8s.aliyun.com/eci-instance-spec: ecs.gn6i-c24g1.12xlarge
    k8s.aliyun.com/eci-instance-zone: cn-hangzhou-i
    k8s.aliyun.com/eci-kube-proxy-enabled: "true"
    k8s.aliyun.com/eci-security-group: sg-bp14u2bufi0926ycat9w
    k8s.aliyun.com/eci-use-specs: ecs.gn6i-c24g1.12xlarge
    k8s.aliyun.com/eci-vswitch: vsw-bp10d0kcp9077dqzzu21z
    workflows.argoproj.io/node-name: fusion-metrics-wf-0f95b86a-f7aa-4ac7-85a9-7d6f244177[2].generate-metrics-step(4:groudTruthOssPath:oss://inceptio-groundtruth/annotations/sequence/2020/03/18/53ecb9a8-d89e-4c06-8b35-59ea72d97d22/,momentId:53ecb9a8-d89e-4c06-8b35-59ea72d97d22)[0].regenerate-step(0)
    workflows.argoproj.io/template: '{"name":"regenerate","arguments":{},"inputs":{"parameters":[{"name":"moment_id","value":"53ecb9a8-d89e-4c06-8b35-59ea72d97d22"}]},"outputs":{},"affinity":{"nodeAffinity":{"preferredDuringSchedulingIgnoredDuringExecution":[{"weight":100,"preference":{"matchExpressions":[{"key":"gpu_node","operator":"In","values":["true"]}]}}]}},"metadata":{"annotations":{"k8s.aliyun.com/eci-image-cache":"true","k8s.aliyun.com/eci-use-specs":"ecs.gn6i-c24g1.12xlarge"}},"script":{"name":"","image":"registry-vpc.cn-hangzhou.aliyuncs.com/inceptio/infra_fusion-metrics-regenerate:v20200720-4160093","command":["bash"],"env":[{"name":"MOMENT_ID","value":"53ecb9a8-d89e-4c06-8b35-59ea72d97d22"},{"name":"CYBERTRON_COMMIT_ID","value":"50fffb56952906a7938e3becd6005b3f04251a7d"},{"name":"LAUNCH_NAME","value":"perception/fusion/fusion_replay_metrics_launch"},{"name":"REGENERATED_BUCKET","valueFrom":{"configMapKeyRef":{"name":"cluster-configs","key":"moment_regenerated_oss_bucket"}}},{"name":"GITLAB_TOKEN","valueFrom":{"secretKeyRef":{"name":"argo-hubble-secrets","key":"gitlab-read-repository-token"}}},{"name":"CAS_TOKEN","valueFrom":{"secretKeyRef":{"name":"cas-service-token","key":"token"}}}],"resources":{"limits":{"nvidia.com/gpu":"2"}},"volumeMounts":[{"name":"credentials-volume","mountPath":"/root/.jfrog/jfrog-cli.conf","subPath":"jfrog-cli.conf"},{"name":"credentials-volume","mountPath":"/root/.ossutilconfig","subPath":".ossutilconfig"},{"name":"artifacts-volume-claim","mountPath":"/data"}],"source":"set
      -ex\n\ncp /data/cybertron.tar /root \u0026\u0026 cd /root \u0026\u0026 tar -xf
      cybertron.tar \u0026\u0026 rm cybertron.tar \u0026\u0026 cd cybertron\nTS1=$(date
      +%s)\n\nIDL_RECORD_IO=irs/common/recorder/idl_record_io.h\nMAJOR=$(cat $IDL_RECORD_IO
      | sed -rn ''s/^.*kCurrentRepoVersionMajor\\ *=\\ *([0-9]*);/\\1/p'')\nMINOR=$(cat
      $IDL_RECORD_IO | sed -rn ''s/^.*kCurrentRepoVersionMinor\\ *=\\ *([0-9]*);/\\1/p'')\nIDL=$(cat
      $IDL_RECORD_IO | sed -rn ''s/^.*kCurrentIdlHiddenVersion\\ *=\\ *([0-9]*);/\\1/p'')\ndataset
      client \\\n  dl moments/$MOMENT_ID \\\n  --token=$CAS_TOKEN \\\n  --target=dataset-server.chariot:50050
      \\\n  --dataset-process-target=dataset-server.chariot:50051 \\\n  --target-path=/root/moments
      \\\n  --idl-version=${MAJOR}.${MINOR}.${IDL}\n\nTS2=$(date +%s)\nDIFF=$(( $TS2
      - $TS1 ))\necho \"fetch dataset took $DIFF seconds\"\n\ncd /root/moments/${MOMENT_ID:0:2}/${MOMENT_ID}\nif
      [ ! -d \"rec\" ]; then\n  mkdir rec \u0026\u0026 mv *.rec rec\nfi\n\nTS3=$(date
      +%s)\nDIFF=$(( $TS3 - $TS2 ))\necho \"mv dataset took $DIFF seconds\"\n\nMISSION_ID=$(curl
      -s -H \"authorization: Bearer $CAS_TOKEN\" \"http://chariot-gateway.chariot:8080/v1alpha2/moments/$MOMENT_ID\"
      \\\n  | jq .mission_id \\\n  | sed -e ''s/^\"//'' -e ''s/\"$//'')\nMAP=$(curl
      -s -H \"authorization: Bearer $CAS_TOKEN\" \"http://chariot-gateway.chariot:8080/v1alpha2/missions/$MISSION_ID\"
      \\\n  | jq .map \\\n  | sed -e ''s/^\"//'' -e ''s/\"$//'')\nVEHICLE_ID=$(curl
      -s -H \"authorization: Bearer $CAS_TOKEN\" \"http://chariot-gateway.chariot:8080/v1alpha2/missions/$MISSION_ID\"
      \\\n  | jq .vehicle.instance \\\n  | sed -e ''s/^\"//'' -e ''s/\"$//'')\n\ncd
      /root/cybertron\npip3 install irs/launch/launch irs/launch/launch_ros irs/launch/launch_yaml
      irs/launch/test_launch_ros irs/launch/osrf_pycommon\ncp -a /root/moments/${MOMENT_ID:0:2}/$MOMENT_ID/config/calibration
      /root/cybertron/config/\n\nchariot replay --name=$LAUNCH_NAME \\\n  --file=bundle.yaml
      \\\n  --map=$MAP \\\n  --vehicle-id=$VEHICLE_ID \\\n  --timeout=600 \\\n  --replay-rec-path=/root/moments/${MOMENT_ID:0:2}/$MOMENT_ID
      \\\n  --output=/root/moments-regenerated/${MOMENT_ID:0:2}/$MOMENT_ID\n\nTS4=$(date
      +%s)\nDIFF=$(( $TS4 - $TS3 ))\necho \"chariot replay took $DIFF seconds\"\n\n#
      free space\nrm -rf /root/moments/${MOMENT_ID:0:2}/$MOMENT_ID\nCONVERTER_PY=interfaces/tools/gems/pb_converter/gems_rec_convert.py\npython3
      $CONVERTER_PY \\\n  --exec_path=/root/cybertron \\\n  --input_path=/root/moments-regenerated/${MOMENT_ID:0:2}/$MOMENT_ID/rec
      \\\n  --output_path=/root/moments-regenerated/${MOMENT_ID:0:2}/$MOMENT_ID/pb\n\nossutil
      cp --config-file=/root/.ossutilconfig -r -f \\\n  /root/moments-regenerated/${MOMENT_ID:0:2}/$MOMENT_ID
      \\\n  oss://$REGENERATED_BUCKET/${MOMENT_ID:0:2}/$MOMENT_ID/$LAUNCH_NAME/$CYBERTRON_COMMIT_ID\n\nTS5=$(date
      +%s)\nDIFF=$(( $TS5 - $TS4 ))\necho \"rec-pb converter replay took $DIFF seconds\"\n"},"retryStrategy":{"limit":2},"tolerations":[{"key":"gpu_node","operator":"Equal","value":"true","effect":"NoSchedule"},{"key":"virtual-kubelet.io/provider","operator":"Equal","value":"alibabacloud","effect":"NoSchedule"}]}'
  creationTimestamp: "2020-08-25T03:18:34Z"
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/controller-instanceid: kraken
    workflows.argoproj.io/workflow: fusion-metrics-wf-0f95b86a-f7aa-4ac7-85a9-7d6f244177
  name: fusion-metrics-wf-0f95b86a-f7aa-4ac7-85a9-7d6f244177-1580075001
  namespace: argo-hubble
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: Workflow
    name: fusion-metrics-wf-0f95b86a-f7aa-4ac7-85a9-7d6f244177
    uid: cd4490d0-e680-11ea-b659-0695ecaac99c
  resourceVersion: "1042943700"
  selfLink: /api/v1/namespaces/argo-hubble/pods/fusion-metrics-wf-0f95b86a-f7aa-4ac7-85a9-7d6f244177-1580075001
  uid: a8a231e4-e681-11ea-a15b-72a22667324f
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: gpu_node
            operator: In
            values:
            - "true"
        weight: 100
  containers:
  - command:
    - argoexec
    - wait
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: aliyun_logs_workflow
      value: stdout
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
      value: k8sapi
    image: registry-vpc.cn-hangzhou.aliyuncs.com/inceptio/argoproj_argoexec:v2.7.0
    imagePullPolicy: IfNotPresent
    name: wait
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/podmetadata
      name: podmetadata
    - mountPath: /mainctrfs/root/.jfrog/jfrog-cli.conf
      name: credentials-volume
      subPath: jfrog-cli.conf
    - mountPath: /mainctrfs/root/.ossutilconfig
      name: credentials-volume
      subPath: .ossutilconfig
    - mountPath: /mainctrfs/data
      name: artifacts-volume-claim
    - mountPath: /mainctrfs/argo/staging
      name: argo-staging
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-t5xcm
      readOnly: true
  - args:
    - /argo/staging/script
    command:
    - bash
    env:
    - name: MOMENT_ID
      value: 53ecb9a8-d89e-4c06-8b35-59ea72d97d22
    - name: CYBERTRON_COMMIT_ID
      value: 50fffb56952906a7938e3becd6005b3f04251a7d
    - name: LAUNCH_NAME
      value: perception/fusion/fusion_replay_metrics_launch
    - name: REGENERATED_BUCKET
      valueFrom:
        configMapKeyRef:
          key: moment_regenerated_oss_bucket
          name: cluster-configs
    - name: GITLAB_TOKEN
      valueFrom:
        secretKeyRef:
          key: gitlab-read-repository-token
          name: argo-hubble-secrets
    - name: CAS_TOKEN
      valueFrom:
        secretKeyRef:
          key: token
          name: cas-service-token
    image: registry-vpc.cn-hangzhou.aliyuncs.com/inceptio/infra_fusion-metrics-regenerate:v20200720-4160093
    imagePullPolicy: IfNotPresent
    name: main
    resources:
      limits:
        nvidia.com/gpu: "2"
      requests:
        nvidia.com/gpu: "2"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /root/.jfrog/jfrog-cli.conf
      name: credentials-volume
      subPath: jfrog-cli.conf
    - mountPath: /root/.ossutilconfig
      name: credentials-volume
      subPath: .ossutilconfig
    - mountPath: /data
      name: artifacts-volume-claim
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-t5xcm
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: acr-credential-0cd66774c2e1635329078c8ad94a7d92
  - name: acr-credential-90a511cb8249950d96ce0336cae093f0
  initContainers:
  - command:
    - argoexec
    - init
    env:
    - name: ARGO_POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: aliyun_logs_workflow
      value: stdout
    - name: ARGO_CONTAINER_RUNTIME_EXECUTOR
      value: k8sapi
    image: registry-vpc.cn-hangzhou.aliyuncs.com/inceptio/argoproj_argoexec:v2.7.0
    imagePullPolicy: IfNotPresent
    name: init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /argo/podmetadata
      name: podmetadata
    - mountPath: /argo/staging
      name: argo-staging
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-t5xcm
      readOnly: true
  nodeName: virtual-node-eci-0
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    key: gpu_node
    operator: Equal
    value: "true"
  - effect: NoSchedule
    key: virtual-kubelet.io/provider
    operator: Equal
    value: alibabacloud
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - downwardAPI:
      defaultMode: 420
      items:
      - fieldRef:
          apiVersion: v1
          fieldPath: metadata.annotations
        path: annotations
    name: podmetadata
  - name: credentials-volume
    secret:
      defaultMode: 420
      secretName: argo-hubble-secrets
  - name: artifacts-volume-claim
    persistentVolumeClaim:
      claimName: fusion-metrics-wf-0f95b86a-f7aa-4ac7-85a9-7d6f244177-artifacts-volume-claim
  - emptyDir: {}
    name: argo-staging
  - name: default-token-t5xcm
    secret:
      defaultMode: 420
      secretName: default-token-t5xcm
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-25T03:18:34Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: eci://a1c99ce37a6a55a938e021dbf9348707ee8cb1590110cbba5377692fa5d2015c
    image: registry-vpc.cn-hangzhou.aliyuncs.com/inceptio/infra_fusion-metrics-regenerate:v20200720-4160093
    imageID: eci://registry-vpc.cn-hangzhou.aliyuncs.com/inceptio/infra_fusion-metrics-regenerate:v20200720-4160093
    lastState:
      waiting: {}
    name: main
    ready: false
    restartCount: 0
    state:
      waiting: {}
  - containerID: eci://93d74d2a93bb7fd23309a98fb8c1372b30848a241d04d2f40b79dd6416a63edd
    image: registry-vpc.cn-hangzhou.aliyuncs.com/inceptio/argoproj_argoexec:v2.7.0
    imageID: eci://registry-vpc.cn-hangzhou.aliyuncs.com/inceptio/argoproj_argoexec:v2.7.0
    lastState:
      waiting: {}
    name: wait
    ready: false
    restartCount: 0
    state:
      waiting: {}
  hostIP: 172.30.2.104
  initContainerStatuses:
  - containerID: eci://39bb85ba062466e052286d199e35fa67cc3694dfe099e2a4fee445bf128363b3
    image: registry-vpc.cn-hangzhou.aliyuncs.com/inceptio/argoproj_argoexec:v2.7.0
    imageID: ""
    lastState:
      waiting: {}
    name: init
    ready: false
    restartCount: 0
    state:
      waiting: {}
  phase: Failed
```

The workflow node status yaml
```yaml
id: fusion-metrics-wf-0f95b86a-f7aa-4ac7-85a9-7d6f244177-1580075001
name: fusion-metrics-wf-0f95b86a-f7aa-4ac7-85a9-7d6f244177[2].generate-metrics-step(4:groudTruthOssPath:oss://inceptio-groundtruth/annotations/sequence/2020/03/18/53ecb9a8-d89e-4c06-8b35-59ea72d97d22/,momentId:53ecb9a8-d89e-4c06-8b35-59ea72d97d22)[0].regenerate-step(0)
type: Pod
templateName: regenerate
phase: Succeeded
boundaryID: fusion-metrics-wf-0f95b86a-f7aa-4ac7-85a9-7d6f244177-2612786667
startedAt: 2020-08-25T03:18:34Z
finishedAt: 2020-08-25T03:18:46Z
inputs: {"parameters":[{"name":"moment_id","value":"53ecb9a8-d89e-4c06-8b35-59ea72d97d22"}]}
children: fusion-metrics-wf-0f95b86a-f7aa-4ac7-85a9-7d6f244177-2854534890
```

You can see the pod's phase is failed, but the workflow node status is succeeded.
According to https://github.com/argoproj/argo/blob/v2.7.0/workflow/controller/operator.go#L1070-L1074, because the containerStatues's terminated is null, so the node will update to succeeded, https://github.com/argoproj/argo/blob/v2.7.0/workflow/controller/operator.go#L1165.
I'm not sure is argo's bug or the wrong pod container's status.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #3879

### CODE REVIEW

File: workflow/controller/operator_test.go [hunk 1]
```diff
@@ -4644,3 +4644,199 @@ func TestStorageQuota(t *testing.T) {
...
+      ],
+      "qosClass": "BestEffort",
+      "startTime": "2020-08-27T18:14:19Z"
+   }
+}
+`
+
+func TestPodFailureWithContainerWaitingState(t *testing.T) {
+	var pod apiv1.Pod
+	err := json.Unmarshal([]byte(podWithFailed), &pod)
```
Comment (alexec) [inline workflow/controller/operator_test.go:4836]: testutil.MustUnmarshallYAML
