### PR TITLE
fix(controller): Revert prepending ExecutorScriptSourcePath which brought a breaking change in args handling

### LINKED ISSUE #4782: prepending ExecutorScriptSourcePath breaks using script with args without command
## Summary 

We use a script with an `args` with `sh` (and not a `command`). Our image has an entrypoint and exec the rest of the arguments with something like `exec "$@"`.
The PR https://github.com/argoproj/argo/pull/4492 breaks these types of workflows (see the example below).

I don't know what should be the right behavior but executing the entrypoint before a script is pretty convenient. For instance, we use it to do some privileged actions and then we drop privileges before executing the workflow's script.

## Diagnostics

What Kubernetes provider are you using? Baremetal

What version of Argo Workflows are you running? v2.12.2

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-args-script
spec:
  entrypoint: test
  templates:
  - name: test
    script:
      image: mrfreezeex/test-argow-script:v1
      args: [sh]
      source: |
        echo "This message won't be shown!"
```

My test image is built using these files :

Dockerfile :
```
FROM alpine

COPY entrypoint.sh entrypoint.sh

ENTRYPOINT entrypoint.sh
CMD echo hello
```

entrypoint.sh :
```
#!/bin/sh

exec "$@"
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by MrFreezeex**
This reverts commit 64ae33034d30a943dca71b0c5e4ebd97018448bf.

This PR reverts #4492 which changes the way args are passed to a script template. Due to this change we are not able to override `args` with a docker image and an entrypoint with an `exec "$@"` in argo workflow 2.12.x.

This is convenient to execute the docker entrypoint of the base image and then execute the script in the workflow. We use it to do some privileged action and then drop those privileges before executing the script passed in the workflow. You can find more information in #4782 with an example to test the behavior that brokes in 2.12.x.

This revert will obviously break the behavior that the author of this commit has intended to introduce so I don't know if reverting is the best things to do...

Resolves #4782

### CODE REVIEW

**Comment by alexec** [comment]
Did you author these changes originally?

**Comment by MrFreezeex** [comment]
> Did you author these changes originally?

No I didn't. The original author is @ivancili  in PR #4492. You can find an explanation of why this has been introduced in issue #4481. This broke our use of script template as described in this PR and in issue #4782.

**Comment by alexec** [comment]
@ivancili would you like to chip it? Would you like to propose a fix so everyone is happy?

**Comment by ivancili** [comment]
@alexec @MrFreezeex In my opinion, the correct behavior of a script template should include the ability to pass arbitrary args to the script (one way, or another). The example provided in [this issue](https://github.com/argoproj/argo/issues/4782) seems like an incorrect usage to me, though. I would just put the **[sh]** into **command** section of the template, or prepare the entrypoint of the base image fully. Nevertheless, I see your point, and I realize my PR introduced a breaking change and it should be fixed, I apologize for the inconvenience.

Here are my proposals on how to fix this:

1. Add a flag to the script template which indicates whether **args** should be added before or after the script, notice the flag **argsPosition** in this example (name and data type of the flag can be further discussed):
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-args-script
spec:
  entrypoint: test
  templates:
  - name: test
    script:
      image: mrfreezeex/test-argow-script:v1
      args: [sh]
      argsPosition: prepend  # other option is append
      source: |
        echo "This message will be shown!"
```
2. Add separate field called **sourceArgs**, which will then allow users to specify both container args and script args at the same time, without these kinds of problems. Container args will be added before script, and **sourceArgs** after the script. But in this case you have to be careful in how you write your container image entrypoint/args. Example:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test-args-script
spec:
  entrypoint: test
  templates:
  - name: test
    script:
      image: mrfreezeex/test-argow-script:v1
      args: [sh]
      sourceArgs:
        - "Hello"
      source: |
        echo "This message will be shown!"
        echo $1 there                  # prints "Hello there"
```
3. Revert my commit and just use Go templates to parametrize the script source (as it were before)

Let me know your thoughts.

**Comment by MrFreezeex** [comment]
> @alexec @MrFreezeex In my opinion, the correct behavior of a script template should include the ability to pass arbitrary args to the script (one way, or another). The example provided in [this issue](https://github.com/argoproj/argo/issues/4782) seems like an incorrect usage to me, though. I would just put the **[sh]** into **command** section of the template, or prepare the entrypoint of the base image fully. Nevertheless, I see your point, and I realize my PR introduced a breaking change and it should be fixed, I apologize for the inconvenience.
> 
> Here are my proposals on how to fix this:
> 
> 1. Add a flag to the script template which indicates whether **args** should be added before or after the script, notice the flag **argsPosition** in this example (name and data type of the flag can be further discussed):
> 
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: Workflow
> metadata:
>   name: test-args-script
> spec:
>   entrypoint: test
>   templates:
>   - name: test
>     script:
>       image: mrfreezeex/test-argow-script:v1
>       args: [sh]
>       argsPosition: prepend  # other option is append
>       source: |
>         echo "This message will be shown!"
> ```
> 
> 1. Add separate field called **sourceArgs**, which will then allow users to specify both container args and script args at the same time, without these kinds of problems. Container args will be added before script, and **sourceArgs** after the script. But in this case you have to be careful in how you write your container image entrypoint/args. Example:
> 
> ```yaml
> apiVersion: argoproj.io/v1alpha1
> kind: Workflow
> metadata:
>   name: test-args-script
> spec:
>   entrypoint: test
>   templates:
>   - name: test
>     script:
>       image: mrfreezeex/test-argow-script:v1
>       args: [sh]
>       sourceArgs:
>         - "Hello"
>       source: |
>         echo "This message will be shown!"
>         echo $1 there                  # prints "Hello there"
> ```
> 
> 1. Revert my commit and just use Go templates to parametrize the script source (as it were before)
> 
> Let me know your thoughts.

From my point of view, I think that the `sourceArgs` would be the best options of the three. Kubernetes users are used to having default commands/args handling and breaking this behavior in argo workflow would be a bit weird. This also would be a non breaking change as we would add a new field with a totally different behavior.

**Comment by MrFreezeex** [comment]
I updated my PR to add sourceArgs instead of reverting the commit.

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 1]
```diff
@@ -2108,8 +2108,11 @@ type ExecutorConfig struct {
 type ScriptTemplate struct {
 	apiv1.Container `json:",inline" protobuf:"bytes,1,opt,name=container"`
 
+	// Arguments to be passed to the script
+	SourceArgs []string `json:"sourceArgs" protobuf:"bytes,2,opt,name=sourceArgs"`
```
Comment (alexec) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:2112]: anyway we can avoid a new item? we already have args

Comment (MrFreezeex) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:2112]: If we want to preserve the old behavior and have an alternative to pass arguments to the script, I don't think we have the choice. If you don't want to add a new field, It's a matter of choosing between the old and the new behavior.

Comment (alexec) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:2112]: I don't think a new field for args will pass review I'm afraid (I maybe wrong).

Basically, we need a flag to determine where the script goes in the args, start or end.

How about:

`AppendScript` *bool

* nil or true - > it is appended to the end - this would be default behaviour
* false -> it is inserted at the start

Comment (MrFreezeex) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:2112]: I can do that this would fix my issue and avoid me the patch on our version of argo, but with this kind of option a user can't choose at the same time the args of the image's entrypoint and the args of the script. This is not something I am interested in but this will reduce the possibilities further.

Also It feels a bit weird to break by default the behavior of kubernetes that execute the command and then append args and adding a new field like I did would resolve this.

Either way If we settle on something I can easily do the change.

Comment (alexec) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:2112]: what about supporting some kind of parametreizabel arg?

E.g 

```
args: ["exec", "${argo.script.path}"]
```

Comment (MrFreezeex) [reply pkg/apis/workflow/v1alpha1/workflow_types.go]: I like this approach! I updated my PR, let me know if you find this better. I will try to add some docs for this behavior after that.

**Comment by jessesuen** [comment]
Since https://github.com/argoproj/argo/pull/4492 introduced a regression/change in behavior, it should be reverted. If there is confusion about how script templates work, we should document the behavior better rather than implement additional knobs, especially since there are alternatives to achieve the desired use case. Can we simplify this PR to just a revert of https://github.com/argoproj/argo/pull/4492?

**Comment by MrFreezeex** [comment]
> Since #4492 introduced a regression/change in behavior, it should be reverted. If there is confusion about how script templates work, we should document the behavior better rather than implement additional knobs, especially since there are alternatives to achieve the desired use case. Can we simplify this PR to just a revert of #4492?

I just did that but for some reasons now a test is failing :
```
    --- FAIL: TestFunctionalSuite/TestDeletingRunningPod (44.63s)
Error:         functional_test.go:61: timeout after 30s waiting for condition to be done
```

I don't think that's something related to this code change but I retried It once already... Do you know if this test can be a bit flaky sometimes ?

**Comment by alexec** [comment]
TestDeletingRunningPod is broken

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
@ivancili we've reverted your commit because it was a breaking change that resulted in a regression. Would you like to consider suggesting a new way to do this that is non-breaking?

**Comment by henrywangx** [comment]
Hi guys @alexec @ivancili @MrFreezeex ,
