### PR TITLE
Fiixed: persistentvolumeclaims already exists #1130

### LINKED ISSUE #1130: persistentvolumeclaims already exists
BUG REPORT

**What happened**:
```
$ argo submit --watch generic.yaml -n argo
Name:                generic-nf42h
Namespace:           argo
ServiceAccount:      default
Status:              Error
Message:             persistentvolumeclaims "generic-nf42h-workdir" already exists
Created:             Fri Dec 14 12:16:30 -0500 (1 second ago)
Started:             Fri Dec 14 12:16:30 -0500 (1 second ago)
Finished:            Fri Dec 14 12:16:30 -0500 (1 second ago)
Duration:            0 seconds
Parameters:
  revision:          master

STEP              PODNAME                  DURATION  MESSAGE
 ● generic-nf42h
 └---◷ provision  generic-nf42h-319909044  1s
```

**What you expected to happen**:
`generic-nf42h-workdir` didn't exist before running, and exists after running.. There shouldn't have been an error.

**How to reproduce it (as minimally and precisely as possible)**:
I'm thinking this has to do with me running a bare metal kubernetes cluster with rook.. But I can't find any logs that clarify what is going wrong.

**Anything else we need to know?**:
The first step completes successfully but if I have a second step it never reaches it.

**Environment**:
- Argo version:
```
$ argo version
argo: v2.2.1
  BuildDate: 2018-10-11T16:25:59Z
  GitCommit: 3b52b26190163d1f72f3aef1a39f9f291378dafb
  GitTreeState: clean
  GitTag: v2.2.1
  GoVersion: go1.10.3
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: 2018-10-24T06:54:59Z
  compiler: gc
  gitCommit: 17c77c7898218073f14c8d573582e8d2313dc740
  gitTreeState: clean
  gitVersion: v1.12.2
  goVersion: go1.10.4
  major: "1"
  minor: "12"
  platform: darwin/amd64
serverVersion:
  buildDate: 2018-12-03T20:56:12Z
  compiler: gc
  gitCommit: ddf47ac13c1a9483ea035a79cd7c10005ff21a6d
  gitTreeState: clean
  gitVersion: v1.13.0
  goVersion: go1.11.2
  major: "1"
  minor: "13"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:
- workflow result:
```
$ argo get <workflowname>
NAME            STATUS   AGE   DURATION
generic-9rq8z   Error    10s   0s
```
- executor logs:
```
$ kubectl logs <failedpodname> -c main
total 20
drwxr-xr-x    3 root     root          4096 Dec 14 17:33 .
drwxr-xr-x    1 root     root            28 Dec 14 17:33 ..
-rw-r--r--    1 root     root             0 Dec 14 17:33 file
drwx------    2 root     root         16384 Dec 14 17:33 lost+found
$ kubectl logs <failedpodname> -c wait
time="2018-12-14T17:33:22Z" level=info msg="Creating a docker executor"
time="2018-12-14T17:33:22Z" level=info msg="Executor (version: v2.2.0, build_date: 2018-08-30T08:52:54Z) initialized with template:\narchiveLocation: {}\ncontainer:\n  args:\n  - touch file; ls -al\n  command:\n  - sh\n  - -c\n  image: alpine/git\n  name: \"\"\n  resources: {}\n  volumeMounts:\n  - mountPath: /src\n    name: workdir\n  workingDir: /src\ninputs: {}\nmetadata: {}\nname: git-clone\noutputs: {}\n"
time="2018-12-14T17:33:22Z" level=info msg="Waiting on main container"
time="2018-12-14T17:33:23Z" level=info msg="main container started with container ID: 328ceb2261c0861eb60763c8531a9764a78898b1f715f71398586bd461606a43"
time="2018-12-14T17:33:23Z" level=info msg="Starting annotations monitor"
time="2018-12-14T17:33:23Z" level=info msg="docker wait 328ceb2261c0861eb60763c8531a9764a78898b1f715f71398586bd461606a43"
time="2018-12-14T17:33:23Z" level=info msg="Starting deadline monitor"
time="2018-12-14T17:33:23Z" level=info msg="Main container completed"
time="2018-12-14T17:33:23Z" level=info msg="No sidecars"
time="2018-12-14T17:33:23Z" level=info msg="No output artifacts"
time="2018-12-14T17:33:23Z" level=info msg="No output parameters"
time="2018-12-14T17:33:23Z" level=info msg="Annotations monitor stopped"
time="2018-12-14T17:33:23Z" level=info msg="Alloc=4412 TotalAlloc=11248 Sys=10086 NumGC=4 Goroutines=9"
```
- workflow-controller logs:
```
$ kubectl logs -n kube-system $(kubectl get pods -l app=argo-workflow-controller -n kube-system -o name)
time="2018-12-14T17:33:18Z" level=info msg="Processing workflow" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:18Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:18Z" level=info msg="Creating pvc generic-9rq8z-workdir" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:18Z" level=error msg="generic-9rq8z pvc create error: persistentvolumeclaims \"generic-9rq8z-workdir\" already exists" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:18Z" level=info msg="Updated phase Running -> Error" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:18Z" level=info msg="Updated message  -> persistentvolumeclaims \"generic-9rq8z-workdir\" already exists" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:18Z" level=info msg="Marking workflow completed" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:18Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"generic-9rq8z\": the object has been modified; please apply your changes to the latest version and try again" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:18Z" level=info msg="Re-appying updates on latest version and retrying update" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:18Z" level=info msg="Update retry attempt 1 successful" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:18Z" level=info msg="Workflow update successful" namespace=argo workflow=generic-9rq8z
time="2018-12-14T17:33:39Z" level=info msg="Alloc=4414 TotalAlloc=35407 Sys=16650 NumGC=39 Goroutines=62"
```

Workflow:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: generic-
spec:
  entrypoint: runtest
  arguments:
    parameters:
    - name: revision
      value: master
  volumeClaimTemplates:
  - metadata:
      name: workdir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
  templates:
  - name: runtest
    steps:
    - - name: provision
        template: git-clone

  - name: git-clone
    container:
      image: alpine/git
      workingDir: /src
      command: [sh, -c]
      args: [ "touch file; ls -al" ]
      volumeMounts:
      - name: workdir
        mountPath: /src
```

### PR DESCRIPTION
**Pull request by sarabala1979**
This PR will resolve #1130

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -913,6 +920,10 @@ func (woc *wfOperationCtx) createPVCs() error {
 	return nil
 }
 
+func isPVCExistErr(err error) bool {
+	return strings.Contains(err.Error(), "persistentvolumeclaims") && strings.Contains(err.Error(), "already exists")
```
Comment (jessesuen) [inline workflow/controller/operator.go]: There is an API library provided by kubernetes to detect the already exists error that is not as fragile as this. Also this change does not implement the requirement of checking ownership reference before ignoring the error.

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -896,6 +896,15 @@ func (woc *wfOperationCtx) createPVCs() error {
 			*metav1.NewControllerRef(woc.wf, wfv1.SchemaGroupVersionKind),
 		}
 		pvc, err := pvcClient.Create(&pvcTmpl)
+		if err != nil && apierr.IsAlreadyExists(err) {
+			woc.log.Infof("%s pvc has already exists. Workflow is re-using it", pvcTmpl.Name)
+			pvc, err = pvcClient.Get(pvcTmpl.Name, metav1.GetOptions{})
+			if pvc.OwnerReferences == nil {
+				return errors.New(errors.CodeForbidden, "%s pvc has already exists and ownerreference is different")
```
Comment (jessesuen) [inline workflow/controller/operator.go]: Checking `pvc.OwnerReferences  == nil` is not enough. We need to iterate ownership references and verify that our reference is *not*  there.

File: workflow/controller/operator.go [hunk 3]
```diff
@@ -897,9 +897,30 @@ func (woc *wfOperationCtx) createPVCs() error {
...
+		if err != nil && apierr.IsAlreadyExists(err) {
+			woc.log.Infof("%s pvc has already exists. Workflow is re-using it", pvcTmpl.Name)
+			pvc, err = pvcClient.Get(pvcTmpl.Name, metav1.GetOptions{})
+			if err != nil {
+				return err
+			}
+			hasOwnerReference := false
+			for i := range pvc.OwnerReferences {
+				ownerRef := pvc.OwnerReferences[i]
+				if ownerRef.UID != "" && ownerRef.UID == woc.wf.UID {
```
Comment (jessesuen) [inline workflow/controller/operator.go]: The check for `ownerRef.UID != ""` is unnecessary.  kubernetes guarantees that all entries in ownerReferences has non-empty UID.
