### PR TITLE
fix: Report metric emission errors via Conditions

### LINKED ISSUE #2675: Enhance reporting of metric emssision errors
Currently, errors encountered during metric emission are only logged via the controller and not displayed to the user in any way. Fix this, perhaps by making use of `Status.Conditions`

### PR DESCRIPTION
**Pull request by simster7**
Fixes #2675 

image

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -2476,6 +2476,17 @@ func (woc *wfOperationCtx) computeMetrics(metricList []*wfv1.Prometheus, localSc
 	}
 }
 
+func (woc *wfOperationCtx) reportMetricEmissionError(errorString string) {
+	woc.wf.Status.Conditions.UpsertConditionMessage(
+		wfv1.WorkflowCondition{
```
Comment (alexec) [inline workflow/controller/operator.go:2481]: tests?

Comment (simster7) [reply workflow/controller/operator.go:2481]: I would say adding a test for this is unnecessary. It simply appends a string in a list element.

Comment (alexec) [reply workflow/controller/operator.go:2481]: is it hard to test?

Comment (simster7) [reply workflow/controller/operator.go:2481]: Quite the opposite. In my opinion a test for this simple behavior would be too trivial to warrant itself, but I am open to other opinions.

Regardless, I added a test for this.

File: pkg/apis/workflow/v1alpha1/workflow_types_test.go [hunk 2]
```diff
@@ -57,3 +57,9 @@ func TestNodes_GetResourcesDuration(t *testing.T) {
 		"bar": NodeStatus{ResourcesDuration: ResourcesDuration{corev1.ResourceMemory: 2}},
 	}.GetResourcesDuration())
 }
+
+func TestWorkflowConditions_UpsertConditionMessage(t *testing.T) {
+	wfCond := WorkflowConditions{WorkflowCondition{Type:WorkflowConditionCompleted, Message:"Hello"}}
```
Comment (golangcibot) [inline pkg/apis/workflow/v1alpha1/workflow_types_test.go:62]: File is not `goimports`-ed with -local github.com/argoproj/argo (from `goimports`)

**Comment by simster7** [comment]
Back-ported to 2.7
