### PR TITLE
fix: Allow ints for sequence start/end/count. Fixes #3420

### LINKED ISSUE #3420: Sequence.start/end/count should be `IntOrString`
Along with start and end. Otherwise they will not pass schema validation.

This is interesting, as we have temptable fields (so they must support string) but once templated must be numbers. If not templated, they must be numbers.

@sarabala1979 could you think of any other fields that might be defined as `string` but should also support `int`?

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

 Fixes #3420

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -2387,19 +2387,19 @@ func generateNodeName(name string, index int, desc interface{}) string {
 func expandSequence(seq *wfv1.Sequence) ([]wfv1.Item, error) {
 	var start, end int
 	var err error
-	if seq.Start != "" {
-		start, err = strconv.Atoi(seq.Start)
+	if seq.Start != nil {
+		start, err = strconv.Atoi(seq.Start.String())
```
Comment (alexec) [inline workflow/controller/operator.go:2391]: `IntString` does have `InvVal`, but that method swallows errors
