### PR TITLE
fix(ui): handle logging disconnects gracefully. Fixes #4117

### LINKED ISSUE #4117: v2.11: UI repeated `Failed to load logs`
## Summary 

Open a workflow where we did not get the logs. You will see this error.

image

Also, we appear to now double-write the logs to the log viewer.

## Diagnostics

What version of Argo Workflows are you running?

v2.11

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by dcherman**
When the API finishes streaming logs from a given container, it's normal for
the server to close the connection which results in an error being emitted in the browser.
When one of those errors is received, we check whether or not the node is still pending or
running which allows us to differentiate between a disconnection that happens due to a network
error, and a disconnect that happens due to the completion of log streaming.

Fixes #4117

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

File: ui/src/app/shared/services/workflows-service.ts [hunk 1]
```diff
@@ -118,27 +120,66 @@ export class WorkflowsService {
...
+    }
+
+    public getContainerLogsFromArtifact(workflow: Workflow, nodeId: string, container: string, archived: boolean) {
+        return Observable.of(this.hasArtifactLogs(workflow, nodeId, container))
+            .switchMap(hasArtifactLogs => {
+                if (!hasArtifactLogs) {
+                    throw new Error('no artifact logs are available');
+                }
+
+                return Observable.fromPromise(requests.get(this.getArtifactLogsUrl(workflow, nodeId, container, archived)));
```
Comment (dcherman) [inline ui/src/app/shared/services/workflows-service.ts:166]: One notable problem here is that when you're running a local instance of the UI via `argo server`, this actually hangs for ~30s if your artifact repository is not available externally since you can't resolve the hostname if it's a `.cluster.local` address, so that is not a good user experience.

File: ui/src/app/shared/services/workflows-service.ts [hunk 2]
```diff
@@ -118,27 +120,66 @@ export class WorkflowsService {
...
+
+    public async isWorkflowNodePendingOrRunning(workflow: Workflow, nodeId: string) {
+        if (this.isNodePendingOrRunning(workflow.status.nodes[nodeId])) {
+            return false;
+        }
+
+        // TODO: What happens if we're offline when we make this request?  We should figure out what errors we should
+        // retry on, and what errors we should allow to occur, then transform this to an Observable that implements
+        // all of that
+        const updatedWorkflow = await this.get(workflow.metadata.namespace, workflow.metadata.name);
```
Comment (dcherman) [inline ui/src/app/shared/services/workflows-service.ts:154]: Do we want to retry indefinitely in the event that we receive a network failure?  It's relatively straightforward to implement, but want to confirm first

**Comment by dcherman** [comment]
@simster7 I think you've been working on implementing Jest - is that something we might be able to land soon?  Would love to write some unit tests for this code

File: ui/src/app/shared/services/workflows-service.ts (hunk 2 above)
Comment (alexec) [reply ui/src/app/shared/services/workflows-service.ts:154]: No. Just once. Provide a way for the user to refresh, e.g. use `<ErrorNotice onReload={...}/>`

**Comment by simster7** [comment]
> @simster7 I think you've been working on implementing Jest - is that something we might be able to land soon? Would love to write some unit tests for this code

Unfortunately it doesn't seem like we'll be able to land Jest in the near future, the UI is currently not well-maintained and adding Jest highlights a bunch of issues with it that will need to be fixed before it's implemented. You can see my progress in https://github.com/argoproj/argo/pull/3805.

I'll try to prototype an MVP Jest just for unit testing this week and see if I can make it work, but no promises 🙂

**Review by alexec — CHANGES_REQUESTED** [review]
Can I request addition of screenshots to show the feature in action - as well as error scenarios please?

**Comment by dcherman** [comment]
Sure; still need to implement the `ErrorNotice` which I'll try to work on tonight as well.

**Comment by dcherman** [comment]
@alexec Here's one better, I took a quick GIF of the the feature in action including retries (simulated by setting the network to offline in the console):

ezgif-2-4e1bd0e2be1e

File: ui/src/app/shared/services/workflows-service.ts (hunk 1 above)
Comment (dcherman) [reply ui/src/app/shared/services/workflows-service.ts:160]: For the non-archived case, I swapped this back to loading from the cluster first since the UX was impacted too much by this change imo.

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 3]
```diff
@@ -65,12 +70,8 @@ export class WorkflowLogsViewer extends React.Component<WorkflowLogsViewerProps,
...
                                 source={{
                                     key: `${this.props.workflow.metadata.name}-${this.props.container}`,
-                                    loadLogs: () => {
-                                        return services.workflows.getContainerLogs(this.props.workflow, this.props.nodeId, this.props.container, this.props.archived).map(log => {
-                                            return log ? log + '\n' : '';
-                                        });
-                                    },
-                                    shouldRepeat: () => this.isCurrentNodeRunningOrPending()
+                                    loadLogs: () => Observable.from(this.state.lines),
+                                    shouldRepeat: () => false
```
Comment (dcherman) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:74]: Copied this from the #4131 to avoid the hot loop that was referenced there

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 4]
```diff
@@ -98,15 +99,14 @@ export class WorkflowLogsViewer extends React.Component<WorkflowLogsViewerProps,
...
         this.subscription = services.workflows.getContainerLogs(this.props.workflow, this.props.nodeId, this.props.container, this.props.archived).subscribe(
             log => {
                 this.setState(state => {
                     const newState = {...state, loaded: true};
-
-                    if (log) {
-                        newState.lines = newState.lines.concat(log.split('\n'));
-                    }
-
+                    newState.lines.push(log + '\n');
```
Comment (dcherman) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:109]: With the refactor to the observables, each value that is emitted is guaranteed to be a single line of logs (rather than potentially being undefined), so we no longer need to guard against that case.

**Comment by alexec** [comment]
I can see two error messages in your screenshot?

**Comment by dcherman** [comment]
I had left the original "Failed to load logs:" message in addition to the error notice since I felt like it gave context to what the error below was related to, though that can also be inferred based on it being the log viewer.  Can easily remove that if needed.

**Comment by alexec** [comment]
i don't think we should duplicate error messages - could you please remove it?

**Comment by dcherman** [comment]
Done

File: ui/src/app/shared/services/workflows-service.ts (hunk 1 above)
Comment (dcherman) [reply ui/src/app/shared/services/workflows-service.ts:160]: Note to self: test pod deletion and ensure that the fallback to log archives works correctly.  if it does, this will also correct https://github.com/argoproj/argo/issues/3953

**Review by alexec — APPROVED** [review]
LGTM. I'll let this soak on master a bit before back-porting.
