### PR TITLE
fix: Consider offloaded and compressed node in retry and resume

### LINKED ISSUE #2592: CLI/API doesn't properly support workflow compression or node offload
Checklist:

 * [X] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

Argo CLI/API doesn't properly support workflow compression or node offload, for example:
- workflow retry in RetryWorkflow in workflow_server.go doesn't support either of these
- workflow resume supports decompression but not recompression or node offload

**What you expected to happen**:

All API (and therefore CLI) commands to support both

**Environment**:
- Argo version: 2.7

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by simster7**
Fixes #2592

~Still needs tests~ Done

### CODE REVIEW

File: workflow/packer/packer.go [hunk 1]
```diff
@@ -59,7 +59,7 @@ func IsTooLargeError(err error) bool {
 	return err != nil && strings.HasPrefix(err.Error(), tooLarge)
 }
 
-func CompressWorkflow(wf *wfv1.Workflow) error {
+func CompressWorkflowIfNeeded(wf *wfv1.Workflow) error {
```
Comment (simster7) [inline workflow/packer/packer.go:62]: Changed the name to better reflect that this function is a no-op if compression is not needed.

File: test/e2e/cli_with_server_test.go [hunk 2]
```diff
@@ -97,6 +97,27 @@ func (s *CLIWithServerSuite) TestArchive() {
 	})
 }
 
+
```
Comment (golangcibot) [inline test/e2e/cli_with_server_test.go:100]: File is not `goimports`-ed with -local github.com/argoproj/argo (from `goimports`)
```suggestion

```

File: test/e2e/cli_test.go [hunk 3]
```diff
@@ -470,7 +470,12 @@ func (s *CLISuite) TestWorkflowLint() {
 	})
 }
 
-func (s *CLISuite) TestWorkflowRetry() {
+func (s *CLISuite) TestWorkflowRetryNoPersistence() {
```
Comment (alexec) [inline test/e2e/cli_test.go:473]: rather than rename, move this test to the new file

File: workflow/util/util.go [hunk 4]
```diff
@@ -341,7 +342,7 @@ func SuspendWorkflow(wfIf v1alpha1.WorkflowInterface, workflowName string) error
 
 // ResumeWorkflow resumes a workflow by setting spec.suspend to nil and any suspended nodes to Successful.
 // Retries conflict errors
-func ResumeWorkflow(wfIf v1alpha1.WorkflowInterface, workflowName string, nodeFieldSelector string) error {
+func ResumeWorkflow(wfIf v1alpha1.WorkflowInterface, workflowName string, nodeFieldSelector string, repo sqldb.OffloadNodeStatusRepo) error {
```
Comment (alexec) [inline workflow/util/util.go:345]: Having a utility function where some of the parameters are services stinks. Ideally we should have a `resumeService`, but not today. 
I feel like repo should be the second parameter?

File: workflow/util/util.go [hunk 5]
```diff
@@ -353,7 +354,7 @@ func ResumeWorkflow(wfIf v1alpha1.WorkflowInterface, workflowName string, nodeFi
 
 			err = packer.DecompressWorkflow(wf)
 			if err != nil {
-				log.Fatal(err)
+				log.Fatalf("unable to decompress workflow: %s", err)
```
Comment (alexec) [inline workflow/util/util.go:357]: uh - panic? surely we should return the error

File: workflow/util/util.go [hunk 6]
```diff
@@ -362,17 +363,50 @@ func ResumeWorkflow(wfIf v1alpha1.WorkflowInterface, workflowName string, nodeFi
 				workflowUpdated = true
 			}
 
+			nodes := wf.Status.Nodes
+			if wf.Status.IsOffloadNodeStatus() {
+				if !repo.IsEnabled() {
+					return false, fmt.Errorf(sqldb.OffloadNodeStatusDisabledWarning)
```
Comment (alexec) [inline workflow/util/util.go:369]: is this warning or error?

File: workflow/util/util.go [hunk 7]
```diff
@@ -578,12 +612,18 @@ func convertNodeID(newWf *wfv1.Workflow, regex *regexp.Regexp, oldNodeID string,
 }
 
 // RetryWorkflow updates a workflow, deleting all failed steps as well as the onExit node (and children)
-func RetryWorkflow(kubeClient kubernetes.Interface, wfClient v1alpha1.WorkflowInterface, wf *wfv1.Workflow) (*wfv1.Workflow, error) {
+func RetryWorkflow(kubeClient kubernetes.Interface, wfClient v1alpha1.WorkflowInterface, wf *wfv1.Workflow, repo sqldb.OffloadNodeStatusRepo) (*wfv1.Workflow, error) {
```
Comment (alexec) [inline workflow/util/util.go:615]: as above - services should probably the first arguments

File: workflow/util/util.go [hunk 8]
```diff
@@ -578,12 +612,18 @@ func convertNodeID(newWf *wfv1.Workflow, regex *regexp.Regexp, oldNodeID string,
...
 	switch wf.Status.Phase {
 	case wfv1.NodeFailed, wfv1.NodeError:
 	default:
 		return nil, errors.Errorf(errors.CodeBadRequest, "workflow must be Failed/Error to retry")
 	}
+
+	err := packer.DecompressWorkflow(wf)
+	if err != nil {
+		log.Fatalf("unable to decompress workflow: %s", err)
```
Comment (alexec) [inline workflow/util/util.go:624]: panic?

File: workflow/util/util.go [hunk 9]
```diff
@@ -634,16 +686,36 @@ func RetryWorkflow(kubeClient kubernetes.Interface, wfClient v1alpha1.WorkflowIn
...
+	}
+
 	newWF.Status.StoredTemplates = make(map[string]wfv1.Template)
 	for id, tmpl := range wf.Status.StoredTemplates {
 		newWF.Status.StoredTemplates[id] = tmpl
 	}
 
+	err = packer.CompressWorkflowIfNeeded(newWF)
+	if err != nil {
+		log.Fatalf("unable to compress workflow: %s", err)
```
Comment (alexec) [inline workflow/util/util.go:716]: panic?

File: test/e2e/cli_test.go (hunk 3 above)
Comment (simster7) [reply test/e2e/cli_test.go:473]: There are two tests now, one with persistence and one without. This is without and still has behavior to be tested here. It shouldn't be moved out.

File: workflow/util/util.go (hunk 6 above)
Comment (simster7) [reply workflow/util/util.go:369]: Error. If you're not able to get the offloaded nodes to modify them, how can you resume the workflow?

Comment (alexec) [reply workflow/util/util.go:369]: maybe we should rename `OffloadNodeStatusDisabledWarning` to `OffloadNodeStatusDisabled` status? or maybe we should provide a sentinel error to use?

Comment (simster7) [reply workflow/util/util.go:369]: I would support renaming to `OffloadNodeStatusDisabled`.

How would the sentinel error work? Not sure how it would be use here.

Comment (simster7) [reply workflow/util/util.go]: Renamed to `OffloadNodeStatusDisabled`

**Comment by simster7** [comment]
Back-ported to 2.7
