### PR TITLE
ci: Make builds marginally faster. Fixes #3515

### LINKED ISSUE #3515: v2.9.3 Docker images report they are v2.10.0-rc1
**What happened**:

Pulling the `argoproj/argocli:v2.9.3` and `argoproj/workflow-controller:v2.9.3` Docker images appears to produce the v2.10.0-rc1 versions of the programs (unable to verify if this is just an incorrect string or a wholly incorrect image). The GitCommit and GitTag fields both suggest this isn't just an incorrect string in the 2.9.3 build.

Specifically:

**argocli**
```
$ podman run --rm argoproj/argocli:v2.9.3 version
argo: v2.10.0-rc1
  BuildDate: 2020-07-17T19:44:22Z
  GitCommit: 616c79df09c435fa7659bf7e5194529d948ee93b
  GitTreeState: clean
  GitTag: v2.10.0-rc1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
time="2020-07-18T18:00:23Z" level=fatal msg="invalid configuration: no configuration has been provided"
```

**workflow-controller**
```
$ podman run --rm argoproj/workflow-controller:v2.9.3 version
workflow-controller: v2.10.0-rc1
  BuildDate: 2020-07-17T19:50:17Z
  GitCommit: 616c79df09c435fa7659bf7e5194529d948ee93b
  GitTreeState: clean
  GitTag: v2.10.0-rc1
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```

**What you expected to happen**:

I expected argocli and the workflow-controller images to return version 2.9.3. I'd also expect the Argo commits and tags to point to 9407e19b3a1c61ad4043e382484fd0b6b15574f2 and v2.9.3, respectively.

**How to reproduce it (as minimally and precisely as possible)**:

**podman**
```
$ podman run --rm argoproj/argocli:v2.9.3 version
$ podman run --rm argoproj/workflow-controller:v2.9.3 version
```

**docker**
```
$ docker run --rm argoproj/argocli:v2.9.3 version
$ docker run --rm argoproj/workflow-controller:v2.9.3 version
```

**Anything else we need to know?**:

This does not appear to apply to the binaries under the 2.9.3 release. The v2.9.2 images also correctly report their version, commit, and tag.

**Environment**:

Podman and Docker.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

## Improvements

* Docker Image CI: 14m 
* CI: 14m
  * Test: 5m -> 3m30
  * Test E2E: 14m -> 13m
  * Test Cron: 8m -> 8m
  * Codegen: 8m -> 7m30
  * UI: 32s

There are some slow tests, but no single test which is much worse that other tests. So no improvement to be made there today.
Fixes #3515

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -7,13 +7,11 @@ BUILD_DATE             = $(shell date -u +'%Y-%m-%dT%H:%M:%SZ')
...
 GIT_REMOTE             = origin
 GIT_BRANCH             = $(shell git rev-parse --symbolic-full-name --verify --quiet --abbrev-ref HEAD)
-GIT_TAG                = $(shell git describe --exact-match --tags HEAD 2>/dev/null || git rev-parse --short=8 HEAD 2>/dev/null)
+GIT_TAG                = $(shell git describe --tags --abbrev=0)
 GIT_TREE_STATE         = $(shell if [ -z "`git status --porcelain`" ]; then echo "clean" ; else echo "dirty"; fi)
 
 export DOCKER_BUILDKIT = 1
 
-# To allow you to build with or without cache for debugging purposes.
-DOCKER_BUILD_OPTS     := --no-cache
```
Comment (alexec) [inline Makefile:16]: no longer needed, all builds are done an Github Actions - we should always cache

File: Makefile [hunk 2]
```diff
@@ -475,14 +475,11 @@ ifneq ($(findstring release,$(GIT_BRANCH)),)
...
 	# Commit if any changes
 	git diff --quiet || git commit -am "Update manifests to $(VERSION)"
-	git tag $(VERSION)
+    # use "annotated" tag, rather than "lightweight", so in future we can distingush from "stable"
+	git tag -a $(VERSION) -m $(VERSION)
 
 .PHONY: publish-release
-publish-release: check-version-warning build
-	# Push images to Docker Hub
-	docker push $(IMAGE_NAMESPACE)/argocli:$(VERSION)
```
Comment (alexec) [inline Makefile:483]: we never push locally for releases

File: test/e2e/fixtures/e2e_suite.go [hunk 3]
```diff
@@ -36,29 +36,6 @@ const Label = "argo-e2e"
 // Cron tests run in parallel, so use a different label so they are not deleted when a new test runs
 const LabelCron = Label + "-cron"
 
-var imageTag string
-
-func init() {
```
Comment (alexec) [inline test/e2e/fixtures/e2e_suite.go:41]: unreliable code removed in v2.9
