### PR TITLE
fix(test): Fixed Flaky e2e tests TestSynchronizationWfLevelMutex and TestResourceTemplateStopAndTerminate/ResourceTemplateStop

### LINKED ISSUE #4559: Flakey test `TestResourceTemplateStopAndTerminate/ResourceTemplateStop`
Flakey, not as often as other examples.

https://github.com/argoproj/argo/pull/4470/checks?check_run_id=1422010222

```
        --- FAIL: TestCLIWithServerOverHTTP1Suite/TestResourceTemplateStopAndTerminate/ResourceTemplateStop (0.21s)
            cli_test.go:1291: 
                	Error Trace:	cli_test.go:1291
                	            				when.go:288
                	            				when.go:297
                	            				cli_test.go:1290
                	            				suite.go:77
                	Error:      	"Name:                resource-tmpl-wf\nNamespace:           argo\nServiceAccount:      default\nStatus:              Pending\nCreated:             Thu Nov 19 03:28:12 +0000 (now)\nProgress:            \n" does not contain "Running"
                	Test:       	
```

### LINKED ISSUE #4629: "TestSynchronizationWfLevelMutex" is flakey
https://github.com/argoproj/argo/pull/4628/checks?check_run_id=1487504071

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #4559 
Fixes #4629

### CODE REVIEW

File: test/e2e/cli_test.go [hunk 1]
```diff
@@ -1254,7 +1254,7 @@ func (s *CLISuite) TestSynchronizationWfLevelMutex() {
 		RunCli([]string{"get", "synchronization-wf-level-mutex"}, func(t *testing.T, output string, err error) {
 			assert.Contains(t, output, "Pending")
 		}).
-		WaitForWorkflow().
+		WaitForWorkflow(fixtures.ToBeCompleted, 120*time.Second).
```
Comment (alexec) [inline test/e2e/cli_test.go:1257]: this is really too long for any e2e test to run - does it typically take 2m?

Comment (sarabala1979) [reply test/e2e/cli_test.go:1257]: In my local, each workflow takes 50s to 1.10m based on the resource in k3d.  that's why I  configured two conditions `complete` and timeout.

**Review by alexec — APPROVED** [review]
2m is a long amount of time for one or our e2e tests, but lets try it out anyway
