### PR TITLE
fix(ui): Ignore referenced nodes that don't exist in UI. Fixes #4079

### LINKED ISSUE #4079: Cannot read property type of undefined
## Summary 

What happened/what you expected to happen?
I am trying to execute a workflow, and the ui return this error.
I am expecting that i can see workflow ui correctly.
http://localhost:2746/workflows/default/xxxxxx-pipeline-xxxx

image

## Diagnostics

What version of Argo Workflows are you running?
v2.11.0

```yaml
Paste the workflow here, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by simster7**
Fixes https://github.com/argoproj/argo/issues/4079

### CODE REVIEW

File: ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx [hunk 1]
```diff
@@ -327,6 +315,9 @@ export class WorkflowDag extends React.Component<WorkflowDagProps, WorkflowDagRe
                 return;
             }
 
+            // Ensure that all children actually exist
+            children = children.filter(child => allNodes[child]);
```
Comment (alexec) [inline ui/src/app/workflows/components/workflow-dag/workflow-dag.tsx:319]: nice

**Review by alexec — APPROVED** [review]

**Comment by simster7** [comment]
E2E Failure unrelated

**Comment by simster7** [comment]
Back-ported to 2.11
