### PR TITLE
fix: Remove duplicate node event. Fixes #2961

### LINKED ISSUE #2961: Duplicated events for Workflow Node Event
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

Duplicated Workflow Node Events are emitted for task/step while running workflow.
The event duplication happens on both Steps and DAG.

https://github.com/argoproj/argo/blob/master/docs/workflow-events.md

**What you expected to happen**:

Workflow Node Events should be emitted only once for each task/step completion.

**How to reproduce it (as minimally and precisely as possible)**:

Can be reproduced by running examples with multiple tasks/steps.

https://github.com/argoproj/argo/blob/master/examples/dag-diamond.yaml
https://github.com/argoproj/argo/blob/master/examples/steps.yaml

**Anything else we need to know?**:

- Last task/step in DAG/Steps has no event duplication.
- The difference between duplicated events seems to be only resourceVersion of the involvedObject (=Workflow).
- Argo CLI hasn't been used. (Only kubectl command)

**Environment**:

- Argo version: 2.8.0-rc3
```
$ argo version
```
- Kubernetes version :  v1.17.4-gke.10
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:

None.

**Logs**

Following logs are event logs from `kubectl describe wf`.

DAG with Task A only: No event duplication
```
Events:
  Type    Reason                 Age        From               Message
  ----    ------                 ----       ----               -------
  Normal  WorkflowRunning        <invalid>  dag-diamond-dzkhc  Workflow Running
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-dzkhc  Succeeded node dag-diamond-dzkhc.A
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-dzkhc  Succeeded node dag-diamond-dzkhc
  Normal  WorkflowSucceeded      <invalid>  dag-diamond-dzkhc  Workflow completed
```

DAG with Task A,B: Event duplication for Task A.
```
Events:
  Type    Reason                 Age        From               Message
  ----    ------                 ----       ----               -------
  Normal  WorkflowRunning        <invalid>  dag-diamond-jgxfq  Workflow Running
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jgxfq  Succeeded node dag-diamond-jgxfq.A
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jgxfq  Succeeded node dag-diamond-jgxfq.A
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jgxfq  Succeeded node dag-diamond-jgxfq.B
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jgxfq  Succeeded node dag-diamond-jgxfq
  Normal  WorkflowSucceeded      <invalid>  dag-diamond-jgxfq  Workflow completed
```

DAG with Task A,B,C,D: Event duplication for Task A,B,C
```
Events:
  Type    Reason                 Age        From               Message
  ----    ------                 ----       ----               -------
  Normal  WorkflowRunning        <invalid>  dag-diamond-jzt9b  Workflow Running
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jzt9b  Succeeded node dag-diamond-jzt9b.A
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jzt9b  Succeeded node dag-diamond-jzt9b.A
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jzt9b  Succeeded node dag-diamond-jzt9b.B
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jzt9b  Succeeded node dag-diamond-jzt9b.C
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jzt9b  Succeeded node dag-diamond-jzt9b.C
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jzt9b  Succeeded node dag-diamond-jzt9b.D
  Normal  WorkflowNodeSucceeded  <invalid>  dag-diamond-jzt9b  Succeeded node dag-diamond-jzt9b
  Normal  WorkflowSucceeded      <invalid>  dag-diamond-jzt9b  Workflow completed

```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to USERS.md.

Fixes #2961

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -766,7 +766,6 @@ func (woc *wfOperationCtx) podReconciliation() error {
 				if woc.shouldPrintPodSpec(node) {
 					printPodSpecLog(pod, woc.wf.Name)
 				}
-				woc.onNodeComplete(&node)
```
Comment (alexec) [inline workflow/controller/operator.go:769]: this is the only actual change

File: Makefile [hunk 2]
```diff
@@ -114,6 +122,15 @@ define restore_go_mod
 	# Restore the back-ups.
 	mv dist/go.mod dist/go.sum .
 endef
+# docker_build,image_name,binary_name,marker_file_name
+define docker_build
```
Comment (alexec) [inline Makefile:126]: this allows fast dev builds
