### PR TITLE
fix(ui): Report errors when uploading files. Fixes #3994

### LINKED ISSUE #3994: Upload via UI does not always seem to work
## Summary 

When creating a new workflow, if you upload a file, and you're in JSON mode not YAML mode, it does not work.

## Diagnostics

What version of Argo Workflows are you running?

```
master
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] ~~I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~~
* [ ] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

 Fixes #3994

### CODE REVIEW

File: ui/src/app/shared/components/resource-editor/resource-editor.tsx [hunk 1]
```diff
@@ -31,7 +31,7 @@ const LOCAL_STORAGE_KEY = 'ResourceEditorLang';
 export class ResourceEditor<T> extends React.Component<Props<T>, State> {
     private set lang(lang: string) {
         try {
-            this.setState({lang, error: null, value: stringify(parse(this.state.value), lang)});
+            this.setState(state => ({lang, error: null, value: stringify(parse(state.value), lang)}));
```
Comment (alexec) [inline ui/src/app/shared/components/resource-editor/resource-editor.tsx:34]: we should not reference `this.state` in `setState(..)` - can create inconsistent state

**Review by simster7 — APPROVED** [review]
