### PR TITLE
fix: Don't error when optional artifacts are not found

### LINKED ISSUE #2429: optional output artifacts do not work on composite templates
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
Optional output artifacts are meant to handle the case when the file being created does not exist; they simply do not create the artifact. They work great for container and script templates. But this same functionality does not apply to output artifacts of composite (script/dag) templates, and it should.

Here's an example:
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: artifact-passing-
spec:
  entrypoint: artifact-example
  templates:
  - name: artifact-example
    steps:
    - - name: skip-artifact-generation
        template: conditional-whalesay
        arguments:
          parameters:
          - name: proceed
            value: false

  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args: ["sleep 1; cowsay hello world | tee /tmp/hello_world.txt"]
    outputs:
      artifacts:
      - name: hello-art
        path: /tmp/hello_world.txt

  - name: conditional-whalesay
    inputs:
      parameters:
      - name: proceed
    steps:
    - - name: whalesay
        template: whalesay
        when: "{{inputs.parameters.proceed}}"
    outputs:
      artifacts:
      - name: hello-art
        from: "{{steps.whalesay.outputs.artifacts.hello-art}}"
        optional: true
```

Here are the logs when I run this (which should do nothing, but it fails).

```
STEP                                                    PODNAME  DURATION  MESSAGE
 ✖ layered-artifact-tt5jq (artifact-example)                               child 'layered-artifact-tt5jq[0].skip-artifact-generation' errored
 └---⚠ skip-artifact-generation (conditional-whalesay)                     Unable to resolve: {{steps.whalesay.outputs.artifacts.hello-art}}
     └---○ whalesay (whalesay)                                             when 'false' evaluated false
```

In this example, I want to produce an artifact at a lower level of nesting, then pass it to the higher level. However, I'm using this layering in order to only conditionally run this step (why do I want to do that? because it's [the only way](https://github.com/argoproj/argo/issues/2057) I can get a global output parameter into a WorkflowTemplate). I need the upper template to inherit the optionality of its output artifact from the lower template, but it doesn't work.

I've tried this in both Argo v2.4.1 and v2.6.2 and it unsurprisingly fails the same in both.

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by simster7**
Fixes #2429

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1739,6 +1739,11 @@ func getTemplateOutputsFromScope(tmpl *wfv1.Template, scope *wfScope) (*wfv1.Out
 		for _, art := range tmpl.Outputs.Artifacts {
 			resolvedArt, err := scope.resolveArtifact(art.From)
 			if err != nil {
+				// If the artifact was not found and is optional, don't mark an error
+				if strings.Contains(err.Error(), "Unable to resolve") && art.Optional {
```
Comment (simster7) [inline workflow/controller/operator.go]: Even though we are doing string comparison to distinguish the error here, this behavior is covered by a test. After _much_ though and considering other alternatives (such as creating a custom error type), I decided this is the best way to go forward. Opinions welcome.

**Comment by simster7** [comment]
Back-ported to 2.6
