### PR TITLE
fix(executor): set artifact mode recursively. Fixes #3444

### LINKED ISSUE #3444: Artifact mode is not recursive
Argo version: 2.9.2

Artifact directory items in  do not get their mode set recursively. By setting a mode I'd expect every children to receive same permissions, but now if directory contains nested items, and container does not run as root, they are unable to access them.
 
Can be reproduced by uploading some files to bucket:

```
touch test.txt
gsutil cp test.txt gs://[BUCKET]/parent/test.txt
gsutil cp test.txt gs://[BUCKET]/parent/child/test.txt
```

Then starting a workflow:

```
metadata:
  generateName: not-working-
spec:
  entrypoint: work
  templates:
    - name: work
      container:
        name: main
        image: alpine
        command:
          - ls
          - -la
          - /home/data
          - "&&"
          - ls
          - -la
          - /home/data/child
      inputs:
        artifacts:
          - name: data
            path: /home/data
            mode: 0777
            gcs:
              bucket: [BUCKET]
              key: parent
              serviceAccountKeySecret:
                name: my-gcs-credentials
                key: serviceAccountKey
```

Container output looks like:

```
2020-07-10T09:07:40.353777421Z /home/data:
2020-07-10T09:07:40.35414018Z total 12
2020-07-10T09:07:40.354155704Z drwxrwxrwx    3 root     root          4096 Jul 10 09:07 .
2020-07-10T09:07:40.354183878Z drwxr-xr-x    1 root     root          4096 Jul 10 09:07 ..
2020-07-10T09:07:40.354201555Z drwx------    2 root     root          4096 Jul 10 09:07 child
2020-07-10T09:07:40.354206473Z -rw-r--r--    1 root     root             0 Jul 10 09:07 test.txt
2020-07-10T09:07:40.354211338Z
2020-07-10T09:07:40.354215825Z /home/data/child:
2020-07-10T09:07:40.354220523Z total 8
2020-07-10T09:07:40.354225122Z drwx------    2 root     root          4096 Jul 10 09:07 .
2020-07-10T09:07:40.354229791Z drwxrwxrwx    3 root     root          4096 Jul 10 09:07 ..
2020-07-10T09:07:40.354234687Z -rw-r--r--    1 root     root             0 Jul 10 09:07 test.txt
```

We can observe that /home/data got expected 777, but both parent "test.txt" or nested directories are using other permissions.

I think that this could also be similar to https://github.com/argoproj/argo/issues/1583

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by AntoineDao**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

This PR fixes #3444 by recursively setting permissions inside of an artifact folder. The thinking behind doing this here rather than through a script is that setting non-root permissions on an artifact should probably be done by a `root` user such as the `executor` in the task pod. This then leaves the `main` pod to run as non-root and not have to handle changing file/folder permissions there.

### CODE REVIEW

File: workflow/executor/executor.go [hunk 1]
```diff
@@ -211,6 +211,12 @@ func (we *WorkflowExecutor) LoadArtifacts() error {
 			if err != nil {
 				return errors.InternalWrapError(err)
 			}
+			err = filepath.Walk(artPath, func(path string, f os.FileInfo, err error) error {
+				return os.Chmod(path, os.FileMode(*art.Mode))
```
Comment (alexec) [inline workflow/executor/executor.go:215]: what do I do if I want different permission for directories and files?

Comment (AntoineDao) [reply workflow/executor/executor.go:215]: Hadn't considered that use case actually. My understanding is that this feature wasn't used too much and the issue this PR is related to denoted a bug.

You guys have a much better understanding of what users will expect at this point so do you think it's worth adding something to the API to allow some sort of `recursive mode` implementation? Happy to add it if we think it's best that way! 😄

Comment (alexec) [reply workflow/executor/executor.go:215]: I think we may want to add a boolean flag for recursion (e.g. `art.RecurseMode`). Let. me chat with the core team.

Comment (alexec) [reply workflow/executor/executor.go:215]: Ok. Can we please request a new flag so you can opt in to this feature? At the moment it may break peoples workflows because it changes the permission of files that were not changed before.

Comment (AntoineDao) [reply workflow/executor/executor.go:215]: On it! Thanks for the quick response! 😄

**Comment by AntoineDao** [comment]
Well that magically passed the e2e tests after updating from `master` 🤷‍♂️ Good for you to review @alexec 😄

**Comment by alexec** [comment]
Looking good so far. We need @jessesuen to approve the proto file changes and we should have some kind of e2e test.

File: workflow/executor/executor.go [hunk 2]
```diff
@@ -211,6 +211,15 @@ func (we *WorkflowExecutor) LoadArtifacts() error {
 			if err != nil {
 				return errors.InternalWrapError(err)
 			}
+
+			if art.RecurseMode {
+				err = filepath.Walk(artPath, func(path string, f os.FileInfo, err error) error {
```
Comment (alexec) [inline workflow/executor/executor.go:216]: this needs a test please

**Comment by AntoineDao** [comment]
Not entirely sure why the `test-e2e` suite has failed. It seems only on test failed from the functional tests suite: https://github.com/argoproj/argo/pull/3832/checks?check_run_id=1041945085#step:11:9317. It's worth noting that the new tests I just write did in fact pass (for what it's worth 🙃).

File: test/e2e/functional_test.go [hunk 3]
```diff
@@ -65,6 +65,58 @@ func (s *FunctionalSuite) TestResourceQuota() {
 		})
 }
 
+// Test setting input artifact permission mode with and without the "recurseMode" boolean toggle
+func (s *FunctionalSuite) TestRecursiveArtifactMode() {
+	// Note: the "recurseMode" key is only used if it is set at the template input level rather than task
+	// argument. This behaviour is confirmed by the "artifact-mode-recurse-argument" step which shows
+	// that despite setting "recurseMode" to "true" in the task arguments the mode of the contents of
+	// the "message" artifact folder are not changed to "777".
+	s.Given().
```
Comment (alexec) [inline test/e2e/functional_test.go:74]: I think we might be better off with a unit test instead - is that possible please?

**Review by alexec — DISMISSED** [review]

File: test/e2e/functional_test.go (hunk 3 above)
Comment (AntoineDao) [reply test/e2e/functional_test.go:74]: No worries. Are you just wanting the test for the `LoadArtifacts` function?

Comment (alexec) [reply test/e2e/functional_test.go:74]: I always like to thing about what behaviour or feature is tested, rather than what software component is tested.

There, could the test make sure that recursive mode is applied when specified.

**Comment by AntoineDao** [comment]
I'm at a bit of a loss here. I preferred the `e2e` test as it covered the use case of setting the `recurseMode` key in the workflow spec all the way down to checking the mode of the file is set correctly.

Running the unit test for the now extracted `chmod` function is also useful but seems difficult to test properly though Github Actions. The failing test passes fine on my machine and runs through a standard `setUp` and `tearDown` process to create a directory with a file inside which is then tested for permissions after the `chmod` function is run. Github actions is throwing a `permission denied` error when creating the file as part of the `setUp` section of the unit test and I have no idea how to debug/override this without running a `sudo make test` which doesn't sound like a good idea 🙃

Any thoughts on whether it would be ok to stick to the `e2e` test I initially proposed here? Happy to use a unit test if you think it's best but I will probably need a bit of guidance if that's the case as I'm a bit blocked here.

Cheers!

File: workflow/executor/executor_test.go [hunk 4]
```diff
@@ -194,3 +195,62 @@ func TestIsTarball(t *testing.T) {
 		assert.Equal(t, test.isTarball, ok, test.path)
 	}
 }
+
+func TestChmod(t *testing.T) {
+	TmpDirName := "testdata/tmpdir"
```
Comment (alexec) [inline workflow/executor/executor_test.go:200]: this is the right direction. I think you should use `ioutil.TempDir` to create the directory and create a subdirectory and file in that dir and then verify.

Comment (AntoineDao) [reply workflow/executor/executor_test.go:200]: Thanks for the hint 😄

Comment (AntoineDao) [reply workflow/executor/executor_test.go]: Great success!

File: workflow/executor/executor_test.go [hunk 5]
```diff
@@ -194,3 +196,64 @@ func TestIsTarball(t *testing.T) {
...
+
+		// Check file mode mode if set
+		filePermission, err := os.Stat(tempFile.Name())
+		assert.NoError(t, err)
+		assert.Equal(t, filePermission.Mode().String(), test.permissions.file)
+
+		fmt.Printf("FILE NAME: %s\n", tempFile.Name())
+
+		// TearDown test by removing directory and file
+		err = os.RemoveAll(tempDir)
```
Comment (alexec) [inline workflow/executor/executor_test.go:255]: defer?

File: workflow/executor/executor_test.go [hunk 6]
```diff
@@ -194,3 +196,64 @@ func TestIsTarball(t *testing.T) {
...
+			0777,
+			true,
+			perm{
+				"drwxrwxrwx",
+				"-rwxrwxrwx",
+			},
+		},
+	}
+
+	for _, test := range tests {
```
Comment (alexec) [inline workflow/executor/executor_test.go:230]: looks good

**Comment by alexec** [comment]
Please update with master as you create your own conflicts! :)

**Comment by AntoineDao** [comment]
I live to perpetually make my life more difficult :smile: Thanks for the support through this odyssey! Will update just now

File: workflow/executor/executor_test.go (hunk 5 above)
Comment (AntoineDao) [reply workflow/executor/executor_test.go]: Good shout. Implemented.

**Comment by AntoineDao** [comment]
Done :smile:

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 7]
```diff
@@ -677,8 +677,11 @@ type Artifact struct {
 	// Make Artifacts optional, if Artifacts doesn't generate or exist
 	Optional bool `json:"optional,omitempty" protobuf:"varint,8,opt,name=optional"`
 
+	// SubPath allows an artifact to be sourced from a subpath within the specified source
+	SubPath string `json:"subPath,omitempty" protobuf:"bytes,9,opt,name=subPath"`
```
Comment (alexec) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:681]: this should be number 10

File: server/auth/mocks/Gatekeeper.go [hunk 8]
```diff
@@ -1,4 +1,4 @@
-// Code generated by mockery v1.1.1. DO NOT EDIT.
```
Comment (alexec) [inline server/auth/mocks/Gatekeeper.go]: revert this and similar changes please

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 9]
```diff
@@ -677,11 +677,11 @@ type Artifact struct {
 	// Make Artifacts optional, if Artifacts doesn't generate or exist
 	Optional bool `json:"optional,omitempty" protobuf:"varint,8,opt,name=optional"`
 
-	// SubPath allows an artifact to be sourced from a subpath within the specified source
-	SubPath string `json:"subPath,omitempty" protobuf:"bytes,9,opt,name=subPath"`
-
 	// If mode is set, apply the permission recursively into the artifact if it is a folder
-	RecurseMode bool `json:"recurseMode,omitempty" protobuf:"varint,10,opt,name=recurseMode"`
+	RecurseMode bool `json:"recurseMode,omitempty" protobuf:"varint,9,opt,name=recurseMode"`
```
Comment (alexec) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:681]: sorry - I meant - lets not change the numbers once allocated

Comment (AntoineDao) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:681]: So back to how it was originally here:
https://github.com/argoproj/argo/pull/3832#discussion_r480457189

The reason it appeared as a `diff` originally is because I ran the codegen between merging from master and committing.

**Review by alexec — CHANGES_REQUESTED** [review]
Can you sync with master and we're ready to go.

**Review by alexec — APPROVED** [review]

**Comment by AntoineDao** [comment]
Thanks again for bearing with me through this process 😄
