### PR TITLE
fix: Ensure target task's onExit handlers are run

### LINKED ISSUE #3710: Argo OnExit does not work properly when using step template in a dag
## Summary 

Argo OnExit does not work properly when using step template in a dag

## Diagnostics

Argo version: v2.9.4

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-primay-branch-
spec:
  entrypoint: statis
  templates:
  - name: a
    container:
      image:  docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
  - name: exit
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["exit!"]
  - name: steps
    steps:
      - - name: step-a
          template: a
  - name: statis
    dag:
      tasks:
      - name: A
        onExit: exit
        template: steps # <--- if change "a", it works!!
```

In above case, exit will never be called.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by simster7**
Fixes #3710

### CODE REVIEW

File: workflow/controller/dag.go [hunk 1]
```diff
@@ -232,6 +232,21 @@ func (woc *wfOperationCtx) executeDAG(nodeName string, tmplCtx *templateresoluti
...
+
+		// It is possible that target tasks are not reconsidered (i.e. executeDAGTask is not called on them) once they are
+		// complete (since the DAG itself will have succeeded). To ensure that their exit handlers are run we also run them here. Note that
+		// calls to runOnExitNode are idempotent: it is fine if they are called more than once for the same task.
+		taskNode := dagCtx.getTaskNode(taskName)
+		if taskNode != nil && taskNode.Fulfilled() {
+			if taskNode.Completed() {
+				// Run the node's onExit node, if any. Since this is a target task, we don't need to consider the status
+				// of the onExit node before continuing. That will be done in assesDAGPhase
+				_, _, err := woc.runOnExitNode(dagCtx.GetTask(taskName).OnExit, taskName, taskNode.Name, dagCtx.boundaryID, dagCtx.tmplCtx)
```
Comment (sarabala1979) [inline workflow/controller/dag.go:244]: Will `runOnExitNode` execute the `template` every call (create pod)?

Comment (simster7) [reply workflow/controller/dag.go:244]: From the comment above:

> Note that calls to `runOnExitNode` are idempotent: it is fine if they are called more than once for the same task.

File: workflow/controller/dag.go [hunk 2]
```diff
@@ -232,6 +232,21 @@ func (woc *wfOperationCtx) executeDAG(nodeName string, tmplCtx *templateresoluti
 	// kick off execution of each target task asynchronously
 	for _, taskName := range targetTasks {
 		woc.executeDAGTask(dagCtx, taskName)
+
+		// It is possible that target tasks are not reconsidered (i.e. executeDAGTask is not called on them) once they are
```
Comment (sarabala1979) [inline workflow/controller/dag.go:236]: Do you think we can move out the `runOnExitNode` from `executeDAGTask` and handle it here, So OnExitNode logic will be one place instead of checking multiple places?

File: workflow/controller/dag.go (hunk 1 above)
Comment (sarabala1979) [reply workflow/controller/dag.go:244]: Got it. POD won't be created if it is already created from the previous call.

File: workflow/controller/dag.go (hunk 2 above)
Comment (simster7) [reply workflow/controller/dag.go:236]: No. This only loops through `targetTasks`, not all tasks. We recurse into the non-leaf nodes through `executeDAGTask` where the other `onExitNode` logic is.

Comment (sarabala1979) [reply workflow/controller/dag.go:236]: I think `runOnExitNode` may not run if `task` is already visited. 

Do you think if you arrange the code like this will fix the problem? In this case, there is no duplicate code and `runOnExitNode` logic is in one place.  

```
func (woc *wfOperationCtx) executeDAGTask(dagCtx *dagContext, taskName string) {
	node := dagCtx.getTaskNode(taskName)
	task := dagCtx.GetTask(taskName)
	if node != nil && node.Fulfilled() {
		if node.Completed() {
			// Run the node's onExit node, if any.
			hasOnExitNode, onExitNode, err := woc.runOnExitNode(task.OnExit, task.Name, node.Name, dagCtx.boundaryID, dagCtx.tmplCtx)
			if hasOnExitNode && (onExitNode == nil || !onExitNode.Fulfilled() || err != nil) {
				// The onExit node is either not complete or has errored out, return.
				return
			}
		}
		return
	}
	
	if _, ok := dagCtx.visited[taskName]; ok {
		return
	}
	dagCtx.visited[taskName] = true
```

Comment (simster7) [reply workflow/controller/dag.go:236]: > I think runOnExitNode may not run if task is already visited.

This is not the case. Every task will be visited once during each operation and will have a chance to run an `onExit` node if it is Fulfilled, Completed, and has an `onExit` node declared.

> Do you think if you arrange the code like this will fix the problem?

No. The issue is that a target task my call `executeTemplate` below and finish the DAG from that call, ensuring that there are no more calls to `executeDAGTask` (and therefore `runOnExitNode`). Rearranging the code in the way you suggested will not solve this and would actually be worse because there would be more unnecessary calls to `runOnExit` node.

Comment (simster7) [reply workflow/controller/dag.go:236]: Because we do "short-circuiting" we will need the `runOnExit` code in at least two places. The candidates are (1) where I have added it now, or (2) following `executeTempalte` near the end of this function. I decided on (1), because (2) would make unnecessary calls to `runOnExitNode` without any benefit.

**Comment by sarabala1979** [comment]
Small Suggestion, try to avoid the `runOnExitNode` twice. Try to see this will solve this issue. 
```
func (woc *wfOperationCtx) executeDAGTask(dagCtx *dagContext, taskName string) {
	node := dagCtx.getTaskNode(taskName)
	task := dagCtx.GetTask(taskName)
	if node != nil && node.Fulfilled() {
		return
	}
```

**Comment by simster7** [comment]
> Try to see this will solve this issue.

Tried it without success
