### PR TITLE
fix(offloading): Change offloaded nodes datatype to JSON to support 1GB. Fixes #2246

### LINKED ISSUE #2246: Offloaded nodes does not fit into MySQL TEXT field
**What happened**:

Used nodes offloading feature. When offloading started, I immediately received error:
`msg="Updated message  -> Error 1406: Data too long for column 'nodes' at row 1"`

This seems to be due to TEXT field being limited to 64 kilobytes. Instead of TEXT, we should use at least MEDIUMTEXT which allows to store 16 megabytes of data.

**What you expected to happen**:

Offloading works.

**How to reproduce it (as minimally and precisely as possible)**:

I think it might depend on your workflow, but in general this should happen when large nodes are offloaded into mysql database.

**Anything else we need to know?**:

**Environment**:
- Argo version: v2.5.0-rc12
- Kubernetes version : v1.13.12-gke.25

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the README.
* [x] I've signed the CLA and required builds are green. 

 Fixes #2246

This can be merged as soon as builds are green and should be manually back-ported to v2.5

### CODE REVIEW

File: persist/sqldb/noopChange.go [hunk 1]
```diff
@@ -0,0 +1,10 @@
+package sqldb
+
+import "upper.io/db.v3/lib/sqlbuilder"
+
+type noopChange struct {
```
Comment (golangcibot) [inline persist/sqldb/noopChange.go]: type `noopChange` is unused (from `unused`)
