### PR TITLE
fix(ui): Provide a link to archived logs. Fixes #2300

### LINKED ISSUE #2300: Logs does not automatically fail over to artifact in v2.5.1
I'm not sure if this is quite fixed. On v2.5.1, I'm getting:

```
 Waiting for data...
```

When the underlying pod does not exist anymore.

_Originally posted by @MrSaints in https://github.com/argoproj/argo/pull/2139#issuecomment-590456761_

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [ ] Optional. I've added My organization is added to the README.
* [ ] I've signed the CLA and required builds are green. 

Screen Shot 2020-02-24 at 10 05 58 AM

Fixes #2300.
Not quite a fix - but I think it will be good enough.
Needs back-porting to v2.5.

### CODE REVIEW

File: ui/src/app/shared/services/workflows-service.ts [hunk 1]
```diff
@@ -76,10 +76,14 @@ export class WorkflowsService {
             );
     }
 
+    public getMainLogsUrl(workflow: Workflow, nodeId: string, container: string, archived: boolean) {
+        return this.getArtifactDownloadUrl(workflow, nodeId, container + '-logs', archived);
+    }
+
     public getArtifactDownloadUrl(workflow: Workflow, nodeId: string, artifactName: string, archived: boolean) {
         return archived
-            ? `artifacts-by-uid/${workflow.metadata.uid}/${nodeId}/${encodeURIComponent(artifactName)}?Authorization=${localStorage.getItem('token')}`
```
Comment (alexec) [inline ui/src/app/shared/services/workflows-service.ts]: this is dead code and should have been deleted a while ago

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 2]
```diff
@@ -88,6 +88,16 @@ export class WorkflowLogsViewer extends React.Component<WorkflowLogsViewerProps,
                         </div>
                     )}
                 </div>
+                {this.state.lines.length === 0 && (
+                    <p>
+                        Still waiting for data or an error? Try getting{' '}
+                        <a href={services.workflows.getArtifactLogsUrl(this.props.workflow, this.props.nodeId, this.props.container, this.props.archived)}>
+                            {' '}
```
Comment (simster7) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx]:
```suggestion
```
?
