### PR TITLE
fix(controller): Prevent panic on nil node. Fixes #3436

### LINKED ISSUE #3436: Panic when volumeMount does not exist
Checklist:

 * [x] I've included the version.
 * [ ] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

~~When submitting a workflow that depends on a `WorkflowTemplate`, the workflow crashes and immediately fails (without jumping to onExit).~~

Turns out that the crash actually occurred due to a `volumeMount` not existing.

The message in `argo watch` is "Message:             runtime error: invalid memory address or nil pointer dereference"

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

The same workflow used to work in Argo v2.8.2

**Environment**:

- Argo version:
```
$ argo version

argo: v2.9.2
  BuildDate: 2020-07-08T23:55:01Z
  GitCommit: 65c2bd44e45c11e0a0b03adeef8d6800b72cd551
  GitTreeState: clean
  GitTag: v2.9.2
  GoVersion: go1.13.4
  Compiler: gc
  Platform: darwin/amd64
```
- Kubernetes version :
```
$ kubectl version -o yaml

clientVersion:
  buildDate: "2020-05-21T14:51:23Z"
  compiler: gc
  gitCommit: 2e7996e3e2712684bc73f0dec0200d64eec7fe40
  gitTreeState: clean
  gitVersion: v1.18.3
  goVersion: go1.14.3
  major: "1"
  minor: "18"
  platform: darwin/amd64
serverVersion:
  buildDate: "2020-03-12T20:55:23Z"
  compiler: gc
  gitCommit: 8d8aa39598534325ad77120c120a22b3a990b5ea
  gitTreeState: clean
  gitVersion: v1.17.4
  goVersion: go1.13.8
  major: "1"
  minor: "17"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

- workflow-controller logs:

```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)

2020-07-09T17:27:32.816871832Z time="2020-07-09T17:27:32Z" level=info msg="Processing workflow" namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.816928736Z time="2020-07-09T17:27:32Z" level=info msg="Updated phase  -> Running" namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.825983852Z time="2020-07-09T17:27:32Z" level=info msg="Steps node test-workflow-xqv44 initialized Running" namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.826032384Z time="2020-07-09T17:27:32Z" level=info msg="StepGroup node test-workflow-xqv44-3078889322 initialized Running" namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.827444929Z time="2020-07-09T17:27:32Z" level=info msg="Steps node test-workflow-xqv44-4071128617 initialized Running" namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.827485903Z time="2020-07-09T17:27:32Z" level=info msg="StepGroup node test-workflow-xqv44-985411005 initialized Running" namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.828114123Z time="2020-07-09T17:27:32Z" level=info msg="Pod node test-workflow-xqv44-137232839 initialized Pending" namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.828794253Z time="2020-07-09T17:27:32Z" level=error msg="Recovered from panic" namespace=default r="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 532 [running]:
runtime/debug.Stack(0xc08d9b674e, 0x173d160, 0x28710d0)
    /usr/local/go/src/runtime/debug/stack.go:24
+0x9d
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate.func2(0xc001ea0580)
    /go/src/github.com/argoproj/argo/workflow/controller/operator.go:161
+0xc4
panic(0x173d160, 0x28710d0)
    /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc001ea0580, 0xc00cfd0f80, 0x77, 0x1bb9bc0, 0xc0006e4420, 0xc00ab578c0, 0xc0064cac60, 0x5, 0x6, 0x0, ...)
    /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1510
+0x1866
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc001ea0580, 0xc0064caf20, 0x2, 0x4, 0xc002908380, 0x68, 0xc0012563b8, 0x1bb9b00)
    /go/src/github.com/argoproj/argo/workflow/controller/steps.go:233 +0x11e1
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc001ea0580, 0xc0029081c0, 0x65, 0xc00ab578c0, 0xc009296cf0, 0x23, 0xc00a583440, 0x1bb9bc0, 0xc00069d970, 0xc0012585b8, ...)
    /go/src/github.com/argoproj/argo/workflow/controller/steps.go:91
+0x46e
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc001ea0580, 0xc0029081c0, 0x65, 0x1bb9bc0, 0xc00069d970, 0xc00ab56c40, 0xc000988580, 0x6, 0x6, 0x0, ...)
    /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1496
+0x19a4
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeStepGroup(0xc001ea0580, 0xc00069d8c0, 0x1, 0x4, 0xc009cc1880, 0x20, 0xc001259950, 0x1bb9b00)
    /go/src/github.com/argoproj/argo/workflow/controller/steps.go:233
+0x11e1
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps(0xc001ea0580, 0xc00e5583a0, 0x1d, 0xc00ab56c40, 0xc009296870, 0x23, 0xc00a582240, 0x1bb9bc0, 0xc001ea0a50, 0xc0006bfef0, ...)
    /go/src/github.com/argoproj/argo/workflow/controller/steps.go:91
+0x46e
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate(0xc001ea0580, 0xc00e5583a0, 0x1d, 0x1bb9bc0, 0xc001ea0a50, 0xc00ab56ac0, 0xc001ea0790, 0x3, 0x3, 0x0, ...)
    /go/src/github.com/argoproj/argo/workflow/controller/operator.go:1496
+0x19a4
github.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate(0xc001ea0580)
    /go/src/github.com/argoproj/argo/workflow/controller/operator.go:287 +0x125d
github.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem(0xc0004d1180, 0x0)
    /go/src/github.com/argoproj/argo/workflow/controller/controller.go:433 +0x8c2
github.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker(0xc0004d1180)
    /go/src/github.com/argoproj/argo/workflow/controller/controller.go:359 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00108c1f0)
    /go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00108c1f0, 0x3b9aca00, 0x0, 0x1, 0xc0006aa9c0)
    /go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00108c1f0, 0x3b9aca00, 0xc0006aa9c0)
    /go/pkg/mod/k8s.io/apimachinery@v0.16.7-beta.0/pkg/util/wait/wait.go:88
+0x4d
created by github.com/argoproj/argo/workflow/controller.(*WorkflowController).Run
    /go/src/github.com/argoproj/argo/workflow/controller/controller.go:172 +0x975
" workflow=test-workflow-xqv44

2020-07-09T17:27:32.828856307Z time="2020-07-09T17:27:32Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.828865379Z time="2020-07-09T17:27:32Z" level=info msg="Updated message  -> runtime error: invalid memory address or nil pointer dereference" namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.828873448Z time="2020-07-09T17:27:32Z" level=info msg="Marking workflow completed" namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.828881787Z time="2020-07-09T17:27:32Z" level=info msg="Checking daemoned children of " namespace=default workflow=test-workflow-xqv44
2020-07-09T17:27:32.839810882Z time="2020-07-09T17:27:32Z" level=info msg="Workflow update successful" namespace=default phase=Error resourceVersion=51728589 workflow=test-workflow-xqv44
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #3436

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1508,7 +1508,7 @@ func (woc *wfOperationCtx) executeTemplate(nodeName string, orgTmpl wfv1.Templat
 		return woc.initializeNode(nodeName, wfv1.NodeTypeSkipped, templateScope, orgTmpl, opts.boundaryID, wfv1.NodeError, err.Error()), err
 	}
 	if err != nil {
-		node = woc.markNodeError(node.Name, err)
+		node = woc.markNodeError(nodeName, err)
```
Comment (alexec) [inline workflow/controller/operator.go:1511]: this is old code - so I don't think it is actually underlying problem - but it is masking something else
