### PR TITLE
fix(server): use the correct name when downloading artifacts

### LINKED ISSUE #4252: Disabling compression for binary output artifact works but gives <artifact-name>.gz when downloaded from the UI
## Summary 

I am using the `script` template to execute a machine learning training python script which generates the model as a binary file having __.sav__ extension. Then I am exposing the model binary as an artifact, with compression disabled.

In minio, I can see that model file is present uncompressed, but on the UI the same uncompressed file shows up with a ".tgz" extension.

I am using the `k8sapi` executor to run the workflows

Attachments/Screenshots:
#### 1. File in minio - uncompressed binary as expected
image

#### 2. UI Screenshot
image

#### 3. Artifact downloaded from UI 
`model.tgz` which is the same uncompressed binary `IrisClassifier.sav` is incorrectly named as __model.tgz__ instead of __model.sav__ 
image

#### 4. Executable workflow

[sklearn-iris.txt](https://github.com/argoproj/argo/files/5355761/sklearn-iris.txt)

Rename above attachment to sklearn-iris.__yaml__ and then 

```bash
argo submit ${workflowFile} --serviceaccount ${serviceaccount} --namespace ${namespace} 
```

### What Kubernetes provider are you using? 
Azure Aks

### What version of Argo Workflows are you running? 
v2.11.2

### Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-10-09T14:20:17Z"
  generateName: sklearn-iris-training-
  generation: 6
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Succeeded
  name: sklearn-iris-training-96j9n
  namespace: testing
  resourceVersion: "5619238"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/testing/workflows/sklearn-iris-training-96j9n
  uid: 28e3f15c-35f9-4caa-a671-8f96840f144c
spec:
  arguments: {}
  entrypoint: iris-model-training
  serviceAccountName: argo-workflow-service-account
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: iris-model-training
    outputs: {}
    steps:
    - - arguments: {}
        name: generate-iris-model
        template: model-training
  - arguments: {}
    inputs: {}
    metadata: {}
    name: model-training
    outputs:
      artifacts:
      - archive:
          none: {}
        name: model
        path: /workspace/IrisClassifier.sav
    script:
      command:
      - bash
      image: python:3.7
      name: ""
      resources: {}
      source: "cd /workspace\nwget https://raw.githubusercontent.com/SeldonIO/seldon-core/master/examples/models/sklearn_iris/train_iris.py\npip
        install scikit-learn==0.20.3 joblib==0.16.0\npython train_iris.py \nls -lrth\n"
      volumeMounts:
      - mountPath: /workspace
        name: workspace
  volumes:
  - emptyDir: {}
    name: workspace
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-10-09T14:20:37Z"
  nodes:
    sklearn-iris-training-96j9n:
      children:
      - sklearn-iris-training-96j9n-3701877419
      displayName: sklearn-iris-training-96j9n
      finishedAt: "2020-10-09T14:20:37Z"
      id: sklearn-iris-training-96j9n
      name: sklearn-iris-training-96j9n
      outboundNodes:
      - sklearn-iris-training-96j9n-739202604
      phase: Succeeded
      startedAt: "2020-10-09T14:20:17Z"
      templateName: iris-model-training
      templateScope: local/sklearn-iris-training-96j9n
      type: Steps
    sklearn-iris-training-96j9n-739202604:
      boundaryID: sklearn-iris-training-96j9n
      displayName: generate-iris-model
      finishedAt: "2020-10-09T14:20:35Z"
      hostNodeName: *redacted*
      id: sklearn-iris-training-96j9n-739202604
      name: sklearn-iris-training-96j9n[0].generate-iris-model
      outputs:
        artifacts:
        - archive:
            none: {}
          name: model
          path: /workspace/IrisClassifier.sav
          s3:
            accessKeySecret:
              key: accesskey
              name: argo-workflow-minio
            bucket: argo-artifacts
            endpoint: argo-workflow-minio:9000
            insecure: true
            key: sklearn-iris-training-96j9n/sklearn-iris-training-96j9n-739202604/IrisClassifier.sav
            secretKeySecret:
              key: secretkey
              name: argo-workflow-minio
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 27
        memory: 27
      startedAt: "2020-10-09T14:20:17Z"
      templateName: model-training
      templateScope: local/sklearn-iris-training-96j9n
      type: Pod
    sklearn-iris-training-96j9n-3701877419:
      boundaryID: sklearn-iris-training-96j9n
      children:
      - sklearn-iris-training-96j9n-739202604
      displayName: '[0]'
      finishedAt: "2020-10-09T14:20:37Z"
      id: sklearn-iris-training-96j9n-3701877419
      name: sklearn-iris-training-96j9n[0]
      phase: Succeeded
      startedAt: "2020-10-09T14:20:17Z"
      templateName: iris-model-training
      templateScope: local/sklearn-iris-training-96j9n
      type: StepGroup
  phase: Succeeded
  resourcesDuration:
    cpu: 27
    memory: 27
  startedAt: "2020-10-09T14:20:17Z"
```
### Paste the logs from the workflow controller:
```text
time="2020-10-09T14:20:17Z" level=info msg="Processing workflow" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:17Z" level=info msg="Updated phase  -> Running" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:17Z" level=info msg="Steps node sklearn-iris-training-96j9n initialized Running" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:17Z" level=info msg="StepGroup node sklearn-iris-training-96j9n-3701877419 initialized Running" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:17Z" level=info msg="Pod node sklearn-iris-training-96j9n-739202604 initialized Pending" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:17Z" level=info msg="Created pod: sklearn-iris-training-96j9n[0].generate-iris-model (sklearn-iris-training-96j9n-739202604)" namespace=testing workflow=sklearn-iris-training-96j9
time="2020-10-09T14:20:17Z" level=info msg="Workflow step group node sklearn-iris-training-96j9n-3701877419 not yet completed" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:17Z" level=info msg="Workflow update successful" namespace=testing phase=Running resourceVersion=5619181 workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:18Z" level=info msg="Processing workflow" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:18Z" level=info msg="Updating node sklearn-iris-training-96j9n-739202604 message: PodInitializing"
time="2020-10-09T14:20:18Z" level=info msg="Skipped pod sklearn-iris-training-96j9n[0].generate-iris-model (sklearn-iris-training-96j9n-739202604) creation: already exists" namespace=testing podPhase=Pending workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:18Z" level=info msg="Workflow step group node sklearn-iris-training-96j9n-3701877419 not yet completed" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:18Z" level=info msg="Workflow update successful" namespace=testing phase=Running resourceVersion=5619185 workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:19Z" level=info msg="Processing workflow" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:19Z" level=info msg="Skipped pod sklearn-iris-training-96j9n[0].generate-iris-model (sklearn-iris-training-96j9n-739202604) creation: already exists" namespace=testing podPhase=Pending workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:19Z" level=info msg="Workflow step group node sklearn-iris-training-96j9n-3701877419 not yet completed" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:20Z" level=info msg="Processing workflow" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:20Z" level=info msg="Skipped pod sklearn-iris-training-96j9n[0].generate-iris-model (sklearn-iris-training-96j9n-739202604) creation: already exists" namespace=testing podPhase=Pending workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:20Z" level=info msg="Workflow step group node sklearn-iris-training-96j9n-3701877419 not yet completed" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:21Z" level=info msg="Processing workflow" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:21Z" level=info msg="Updating node sklearn-iris-training-96j9n-739202604 status Pending -> Running"
time="2020-10-09T14:20:21Z" level=info msg="Workflow step group node sklearn-iris-training-96j9n-3701877419 not yet completed" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:21Z" level=info msg="Workflow update successful" namespace=testing phase=Running resourceVersion=5619204 workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:22Z" level=info msg="Processing workflow" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:22Z" level=info msg="Workflow step group node sklearn-iris-training-96j9n-3701877419 not yet completed" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:36Z" level=info msg="Processing workflow" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:36Z" level=info msg="Setting node sklearn-iris-training-96j9n-739202604 outputs"
time="2020-10-09T14:20:36Z" level=info msg="Workflow step group node sklearn-iris-training-96j9n-3701877419 not yet completed" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:36Z" level=info msg="Workflow update successful" namespace=testing phase=Running resourceVersion=5619235 workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="Processing workflow" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="Updating node sklearn-iris-training-96j9n-739202604 status Running -> Succeeded"
time="2020-10-09T14:20:37Z" level=info msg="Step group node &NodeStatus{ID:sklearn-iris-training-96j9n-3701877419,Name:sklearn-iris-training-96j9n[0],DisplayName:[0],Type:StepGroup,TemplateName:iris-model-training,TemplateRef:nil,Phase:Running,BoundaryID:sklearn-iris-training-96j9n,Message:,StartedAt:2020-10-09 14:20:17 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[sklearn-iris-training-96j9n-739202604],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:local/sklearn-iris-training-96j9n,ResourcesDuration:ResourcesDuration{},HostNodeName:,MemoizationStatus:nil,SynchronizationStatus:nil,} successful" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="node sklearn-iris-training-96j9n-3701877419 phase Running -> Succeeded" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="node sklearn-iris-training-96j9n-3701877419 finished: 2020-10-09 14:20:37.08788491 +0000 UTC" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="Outbound nodes of sklearn-iris-training-96j9n-739202604 is [sklearn-iris-training-96j9n-739202604]" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="Outbound nodes of sklearn-iris-training-96j9n is [sklearn-iris-training-96j9n-739202604]" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="node sklearn-iris-training-96j9n phase Running -> Succeeded" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="node sklearn-iris-training-96j9n finished: 2020-10-09 14:20:37.087981011 +0000 UTC" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="Checking daemoned children of sklearn-iris-training-96j9n" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="Updated phase Running -> Succeeded" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="Marking workflow completed" namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="Checking daemoned children of " namespace=testing workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:37Z" level=info msg="Workflow update successful" namespace=testing phase=Succeeded resourceVersion=5619238 workflow=sklearn-iris-training-96j9n
time="2020-10-09T14:20:38Z" level=info msg="Labeled pod completed" namespace=testing pod=sklearn-iris-training-96j9n-739202604```

```

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by dcherman**
When artifacts are uploaded to whatever repository is in use, they're stored
under a key that includes both the intended file name as well as the extension
to use based on whether or not compression was used when it was created.

Use that key as the file name when returning artifacts for download rather than
just "filename.tgz", that way we don't incorrectly identify non-compressed artifacts
as compressed tarballs.

Fixes #4252

### CODE REVIEW

File: server/artifacts/artifact_server.go [hunk 1]
```diff
@@ -27,10 +28,15 @@ type ArtifactServer struct {
...
+	artDriverFactory  artifact.NewDriverFunc
 }
 
 func NewArtifactServer(authN auth.Gatekeeper, hydrator hydrator.Interface, wfArchive sqldb.WorkflowArchive, instanceIDService instanceid.Service) *ArtifactServer {
-	return &ArtifactServer{authN, hydrator, wfArchive, instanceIDService}
+	return newArtifactServer(authN, hydrator, wfArchive, instanceIDService, artifact.NewDriver)
+}
+
+func newArtifactServer(authN auth.Gatekeeper, hydrator hydrator.Interface, wfArchive sqldb.WorkflowArchive, instanceIDService instanceid.Service, artDriverFactory artifact.NewDriverFunc) *ArtifactServer {
+	return &ArtifactServer{authN, hydrator, wfArchive, instanceIDService, artDriverFactory}
```
Comment (dcherman) [inline server/artifacts/artifact_server.go:39]: Allowing a mock driver factory to be used was the simplest way that I could think of to enable the proposed change to be tested since only the S3/GCS/OSS drivers support `Key` since they're the only ones that support outputs.

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 2]
```diff
@@ -924,6 +924,22 @@ func (a *ArtifactLocation) GetType() ArtifactLocationType {
...
+
+	if a.OSS != nil {
+		return a.OSS.Key
+	}
+
+	if a.GCS != nil {
+		return a.GCS.Key
+	}
+
+	return ""
```
Comment (dcherman) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:940]: Should this return an error instead of `""`?  Went back and forth on this a bit since only a subset of `ArtifactLocation`s support outputs and therefore keys.

Alternatively, I could do this logic in the artifact server itself.

**Comment by dcherman** [comment]
An alternate approach/solution to this is actually to look at the first few hundred bytes of the artifact and use that to determine whether or not the artifact is a tar, gzip, or zip file and append the appropriate extension to the file name that was being returned.  That was actually my original approach before I realized that the artifact was already stored with the appropriate extension in the artifact repo.

**Comment by dcherman** [comment]
Also noting that rather than loading the entire file into memory from disk, we might want to consider writing directly to the http response.  I haven't tested this yet, but I'll get that the `argo-server` might go OOM with very large artifacts.

**Review by alexec — APPROVED** [review]
LGTM

File: pkg/apis/workflow/v1alpha1/workflow_types.go (hunk 2 above)
Comment (alexec) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:940]: empty is fine

**Comment by alexec** [comment]
Merged into https://github.com/argoproj/argo/releases/tag/v2.12.0-rc4
