### PR TITLE
fix(controller): Do not crash if cm is empty. Fixes #2069

### LINKED ISSUE #2069: invalid config can allow updateConfig to put controller in invalid state
# Summary

See #2066, it is possible for `updateConfig` to fail at various points leaving the controller in a potentially invalid or unrecoverable state.

# Motivation

Avoid having the controller in a bad state.

# Proposal

Rather than load the config, and then iterate over values returning an error part way thought, we should create and validate a replacement configuration and set it all at once.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the README.
* [x] I've signed the CLA and required builds are green. 

Fixes #2069

### CODE REVIEW

File: workflow/controller/config_controller.go [hunk 1]
```diff
@@ -35,7 +35,7 @@ func (wfc *WorkflowController) updateConfig(cm *apiv1.ConfigMap) error {
 	configStr, ok := cm.Data[common.WorkflowControllerConfigMapKey]
 	if !ok {
 		log.Warnf("ConfigMap '%s' does not have key '%s'", wfc.configMap, common.WorkflowControllerConfigMapKey)
-		return nil
+		configStr = ""
 	}
 	var config config.WorkflowControllerConfig
 	err := yaml.Unmarshal([]byte(configStr), &config)
```
Comment (simster7) [inline workflow/controller/config_controller.go]: This doesn't error when `configStr` is empty, correct?

Comment (alexec) [reply workflow/controller/config_controller.go]: this is fine - I've tested it

File: workflow/controller/config_controller.go [hunk 2]
```diff
@@ -35,7 +35,7 @@ func (wfc *WorkflowController) updateConfig(cm *apiv1.ConfigMap) error {
 	configStr, ok := cm.Data[common.WorkflowControllerConfigMapKey]
 	if !ok {
 		log.Warnf("ConfigMap '%s' does not have key '%s'", wfc.configMap, common.WorkflowControllerConfigMapKey)
-		return nil
+		configStr = ""
 	}
```
Comment (sarabala1979) [inline workflow/controller/config_controller.go]: can we add a return statement here
