### PR TITLE
fix: Add input paremeters to metric scope

### LINKED ISSUE #2642: Custom metric with label based on inputs parameters not generated
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

Custom metric with label based on inputs parameters not generated

**How to reproduce it (as minimally and precisely as possible)**:

Sample YAML that i use for reproducing the bug (i'm using kubectl to apply, so i used a ```name``` metadata):

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: test
  namespace: argo
spec:
  # invoke the whalesay template with
  # "hello world" as the argument
  # to the message parameter
  entrypoint: whalesay
  arguments:
    parameters:
    - name: message
      value: hello
  templates:
  - name: whalesay
    inputs:
      parameters:
      - name: message       # parameter declaration
    serviceAccountName: argo
    container:
      # run cowsay with that message input parameter as args
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
    metrics:
      prometheus:
        - gauge:
            value: '{{duration}}'
          help: Duration of the template in seconds
          labels:
            - key: message
              value: "{{inputs.parameters.message}}"
          name: whalesay
```

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
v2.7.0
```
- Kubernetes version :
```
v1.17.3 (K3S)
```

**Logs**

```
time="2020-04-08T16:51:58Z" level=error msg="unable to substitute parameters for metric 'whalesay': failed to resolve {{inputs.parameters.message}}" namespace=argo workflow=test

```

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by simster7**
Fixes #2642

### CODE REVIEW

File: workflow/controller/steps.go [hunk 1]
```diff
@@ -461,6 +461,13 @@ func (woc *wfOperationCtx) prepareMetricScope(node *wfv1.NodeStatus) (map[string
 		localScope["status"] = string(node.Phase)
 	}
 
+	if node.Inputs != nil {
```
Comment (sarabala1979) [inline workflow/controller/steps.go:464]: Will all input parameters add into metrics?

**Comment by simster7** [comment]
Back-ported to 2.7
