### PR TITLE
fix(controller): Fix throttler. Fixes #1554 and #4081

### LINKED ISSUE #1554: controller.runWorker for wfc.throttler.Next(key) bug
https://github.com/argoproj/argo/blob/master/workflow/controller/controller.go#L262

```
	if key, ok = wfc.throttler.Next(key); !ok {
		log.Warnf("Workflow %s processing has been postponed due to max parallelism limit", key)
		return true
	}
```
https://github.com/argoproj/argo/blob/master/workflow/controller/throttler.go#L65

```
	if t.parallelism < 1 || t.parallelism > len(t.inProgress) {
		next := t.pending.pop()
		t.inProgress[next.key] = true
		return next.key, true
	}
```

if the key returned by Next function is changed, the workflow value must change follow. but now the runWorker.processNextItem code use the old workflow value

### LINKED ISSUE #4081: v2.11: workflow-controller-configmap parallelism not being honored.
## Summary 
I set the "across workflow parallelism" in workflow-controller-config to 5.
```
apiVersion: v1
data:
  config: |
    parallelism: 5
    nodeEvents:
      enabled: true
    workflowDefaults:
      spec:
        ttlStrategy:
          secondsAfterSuccess: 5
        parallelism: 5
kind: ConfigMap
```

Then submitted 10 workflows at once and all of them went into running state

abmallic@MININT-8H2H4GR:~/argo/argo_workflows$ kg workflow
NAME                        STATUS    AGE
dag-diamon-coinflip-5c55t   Running   7s
dag-diamon-coinflip-fczh5   Running   13s
dag-diamon-coinflip-hr4k7   Running   8s
dag-diamon-coinflip-m46cv   Running   11s
dag-diamon-coinflip-mq4rl   Running   10s
dag-diamon-coinflip-rx2nv   Running   12s
dag-diamon-coinflip-vcx66   Running   12s
dag-diamon-coinflip-wkf6r   Running   6s
dag-diamon-coinflip-xvjpj   Running   6s
dag-diamon-coinflip-zsmqs   Running   9s

What happened/what you expected to happen?
5 of them should have gone into running state

## Diagnostics

What version of Argo Workflows are you running?
2.11

```apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-09-21T08:28:24Z"
  generateName: dag-diamon-coinflip-
  generation: 4
  labels:
    workflows.argoproj.io/phase: Running
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
      f:spec:
        .: {}
        f:arguments: {}
        f:entrypoint: {}
        f:podGC:
          .: {}
          f:strategy: {}
        f:templates: {}
      f:status:
        .: {}
        f:finishedAt: {}
    manager: argo
    operation: Update
    time: "2020-09-21T08:28:24Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:workflows.argoproj.io/phase: {}
      f:spec:
        f:parallelism: {}
        f:ttlStrategy:
          .: {}
          f:secondsAfterSuccess: {}
      f:status:
        f:nodes:
          .: {}
          f:dag-diamon-coinflip-5c55t:
            .: {}
            f:children: {}
            f:displayName: {}
            f:finishedAt: {}
            f:id: {}
            f:name: {}
            f:phase: {}
            f:startedAt: {}
            f:templateName: {}
            f:templateScope: {}
            f:type: {}
          f:dag-diamon-coinflip-5c55t-758823825:
            .: {}
            f:boundaryID: {}
            f:children: {}
            f:displayName: {}
            f:finishedAt: {}
            f:id: {}
            f:name: {}
            f:phase: {}
            f:startedAt: {}
            f:templateName: {}
            f:templateScope: {}
            f:type: {}
          f:dag-diamon-coinflip-5c55t-2710044213:
            .: {}
            f:boundaryID: {}
            f:children: {}
            f:displayName: {}
            f:finishedAt: {}
            f:id: {}
            f:name: {}
            f:phase: {}
            f:startedAt: {}
            f:templateName: {}
            f:templateScope: {}
            f:type: {}
          f:dag-diamon-coinflip-5c55t-3805981268:
            .: {}
            f:boundaryID: {}
            f:displayName: {}
            f:finishedAt: {}
            f:hostNodeName: {}
            f:id: {}
            f:name: {}
            f:phase: {}
            f:startedAt: {}
            f:templateName: {}
            f:templateScope: {}
            f:type: {}
        f:phase: {}
        f:startedAt: {}
    manager: workflow-controller
    operation: Update
    time: "2020-09-21T08:28:28Z"
  name: dag-diamon-coinflip-5c55t
  namespace: argo
  resourceVersion: "2958114"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/dag-diamon-coinflip-5c55t
  uid: 12cb8123-a6be-4676-8902-b8b6b4fdc0cc
spec:
  arguments: {}
  entrypoint: diamond
  parallelism: 5
  podGC:
    strategy: OnWorkflowSuccess
  templates:
  - arguments: {}
    dag:
      tasks:
      - arguments: {}
        name: A
        template: coinflip
      - arguments: {}
        dependencies:
        - A
        name: B
        template: coinflip
      - arguments: {}
        dependencies:
        - A
        name: C
        template: coinflip
      - arguments: {}
        dependencies:
        - B
        - C
        name: D
        template: coinflip
    inputs: {}
    metadata: {}
    name: diamond
    nodeSelector:
      agentpool: argoworkload
    outputs: {}
  - arguments: {}
    inputs: {}
    metadata: {}
    name: coinflip
    nodeSelector:
      agentpool: argoworkload
    outputs: {}
    steps:
    - - arguments: {}
        name: flip-coin
        template: flip-coin
    - - arguments: {}
        name: heads
        template: found-heads
        when: '{{steps.flip-coin.outputs.result}} == heads'
      - arguments: {}
        name: tails
        template: coinflip
        when: '{{steps.flip-coin.outputs.result}} == tails'
  - arguments: {}
    inputs: {}
    metadata: {}
    name: flip-coin
    nodeSelector:
      agentpool: argoworkload
    outputs: {}
    script:
      command:
      - python
      image: python:alpine3.6
      name: ""
      resources: {}
      source: |
        import random
        import time
        time.sleep(60)
        result = "heads" if random.randint(0,1) == 0 else "tails"
        print(result)
  - arguments: {}
    container:
      args:
      - echo "it was heads"
      command:
      - sh
      - -c
      image: alpine:3.6
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: found-heads
    nodeSelector:
      agentpool: argoworkload
    outputs: {}
  ttlStrategy:
    secondsAfterSuccess: 5
status:
  finishedAt: null
  nodes:
    dag-diamon-coinflip-5c55t:
      children:
      - dag-diamon-coinflip-5c55t-758823825
      displayName: dag-diamon-coinflip-5c55t
      finishedAt: null
      id: dag-diamon-coinflip-5c55t
      name: dag-diamon-coinflip-5c55t
      phase: Running
      startedAt: "2020-09-21T08:28:24Z"
      templateName: diamond
      templateScope: local/dag-diamon-coinflip-5c55t
      type: DAG
    dag-diamon-coinflip-5c55t-758823825:
      boundaryID: dag-diamon-coinflip-5c55t
      children:
      - dag-diamon-coinflip-5c55t-2710044213
      displayName: A
      finishedAt: null
      id: dag-diamon-coinflip-5c55t-758823825
      name: dag-diamon-coinflip-5c55t.A
      phase: Running
      startedAt: "2020-09-21T08:28:24Z"
      templateName: coinflip
      templateScope: local/dag-diamon-coinflip-5c55t
      type: Steps
    dag-diamon-coinflip-5c55t-2710044213:
      boundaryID: dag-diamon-coinflip-5c55t-758823825
      children:
      - dag-diamon-coinflip-5c55t-3805981268
      displayName: '[0]'
      finishedAt: null
      id: dag-diamon-coinflip-5c55t-2710044213
      name: dag-diamon-coinflip-5c55t.A[0]
      phase: Running
      startedAt: "2020-09-21T08:28:24Z"
      templateName: coinflip
      templateScope: local/dag-diamon-coinflip-5c55t
      type: StepGroup
    dag-diamon-coinflip-5c55t-3805981268:
      boundaryID: dag-diamon-coinflip-5c55t-758823825
      displayName: flip-coin
      finishedAt: null
      hostNodeName: aks-argoworkload-29252569-vmss00001o
      id: dag-diamon-coinflip-5c55t-3805981268
      name: dag-diamon-coinflip-5c55t.A[0].flip-coin
      phase: Running
      startedAt: "2020-09-21T08:28:24Z"
      templateName: flip-coin
      templateScope: local/dag-diamon-coinflip-5c55t
      type: Pod
  phase: Running
  startedAt: "2020-09-21T08:28:24Z"

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #1554
Fixes #4081

### CODE REVIEW

File: workflow/sync/throttler.go [hunk 1]
```diff
@@ -4,97 +4,80 @@ import (
...
-		t.queue.Add(next.key)
+	for t.pending.Len() > 0 && t.parallelism > len(t.inProgress) {
+		key := t.pending.pop().key
+		t.inProgress[key] = true
+		t.queue(key)
 	}
 }
 
 type item struct {
-	key          interface{}
```
Comment (alexec) [inline workflow/sync/throttler.go:89]: I've tightened up this type to reduce future bugs.

File: workflow/sync/throttler.go [hunk 2]
```diff
@@ -4,97 +4,80 @@ import (
...
 type Throttler interface {
-	Add(key interface{}, priority int32, creationTime time.Time)
+	Add(key string, priority int32, creationTime time.Time)
 	// Next returns true if item should be processed by controller now or return false.
-	Next(key interface{}) (interface{}, bool)
+	Progress(key string) bool
 	// Remove notifies throttler that item processing is done. In responses the throttler triggers processing of previously throttled items.
-	Remove(key interface{})
-	// SetParallelism update throttler parallelism limit.
-	SetParallelism(parallelism int)
```
Comment (alexec) [inline workflow/sync/throttler.go:19]: I've removed this which does mandate you restart the controller when you change this config item. This is to reduce complexity-bugs.

**Comment by alexec** [comment]
Converting back to draft. Want to see if I get the reported of the related issue to test this.

**Comment by alexec** [comment]
@sarabala1979 bump!

File: workflow/controller/controller.go [hunk 3]
```diff
@@ -158,7 +161,7 @@ func (wfc *WorkflowController) runTTLController(ctx context.Context) {
 }
 
 func (wfc *WorkflowController) runCronController(ctx context.Context) {
-	cronController := cron.NewCronController(wfc.wfclientset, wfc.restConfig, wfc.dynamicInterface, wfc.namespace, wfc.GetManagedNamespace(), wfc.Config.InstanceID, wfc.metrics, wfc.eventRecorderManager)
+	cronController := cron.NewCronController(wfc.wfclientset, wfc.dynamicInterface, wfc.namespace, wfc.GetManagedNamespace(), wfc.Config.InstanceID, wfc.metrics, wfc.eventRecorderManager)
```
Comment (sarabala1979) [inline workflow/controller/controller.go:164]: Can you keep on throttler change in this PR  and move all other changes to separate PR? It will be easy to revert in the future if there is any issue

File: workflow/controller/controller_test.go [hunk 4]
```diff
@@ -121,85 +121,110 @@ func (t testEventRecorderManager) Get(string) record.EventRecorder {
...
 		hydrator:             hydratorfake.Noop,
 		estimatorFactory:     estimation.DummyEstimatorFactory,
-		metrics:              metrics.New(metrics.ServerConfig{}, metrics.ServerConfig{}),
 		eventRecorderManager: &testEventRecorderManager{eventRecorder: record.NewFakeRecorder(16)},
 		archiveLabelSelector: labels.Everything(),
 		cacheFactory:         controllercache.NewCacheFactory(kube, "default"),
 	}
-	controller.podInformer = controller.newPodInformer()
-	return cancel, controller
+
```
Comment (sarabala1979) [inline workflow/controller/controller_test.go:162]: same here

File: workflow/sync/throttler.go [hunk 5]
```diff
@@ -4,97 +4,85 @@ import (
...
+	if t.parallelism == 0 {
+		return
 	}
-}
-
-func (t *throttler) Add(key interface{}, priority int32, creationTime time.Time) {
-	t.lock.Lock()
-	defer t.lock.Unlock()
 	t.pending.add(key, priority, creationTime)
+	t.queueThrottled()
```
Comment (sarabala1979) [inline workflow/sync/throttler.go:47]: I like this.

File: workflow/sync/throttler.go [hunk 6]
```diff
@@ -4,97 +4,85 @@ import (
...
 
 func (t *throttler) queueThrottled() {
-	for t.pending.Len() > 0 && (t.parallelism < 1 || t.parallelism > len(t.inProgress)) {
-		next := t.pending.pop()
-		t.inProgress[next.key] = true
-		t.queue.Add(next.key)
+	for t.pending.Len() > 0 && t.parallelism > len(t.inProgress) {
+		key := t.pending.pop().key
+		t.inProgress[key] = true
+		t.queue(key)
```
Comment (sarabala1979) [inline workflow/sync/throttler.go:72]: very clean implementation

**Review by sarabala1979 — COMMENTED** [review]
Please merge https://github.com/argoproj/argo/pull/4453 to master first.
This should have the only throttler changes

**Review by sarabala1979 — APPROVED** [review]
