### PR TITLE
fix(controller): Refactor the Merge Workflow, WorkflowTemplate and WorkflowDefaults

### LINKED ISSUE #4246: `workflowDefaults` in `workflow-controller-configmap` doesn't work?
## Summary 

I added a customized `label` (as suggested by [this example](https://argoproj.github.io/argo/default-workflow-specs/)) and a `serviceAccountName` into the `workflowDefaults` section in `workflow-controller-configmap`. Both doesn't work.

## Diagnostics

What Kubernetes provider are you using? 

EKS.

What version of Argo Workflows are you running? 

```
kubectl exec -it argo-server-**** -- argo version
argo: v2.10.0
  BuildDate: 2020-08-18T23:15:20Z
  GitCommit: 195c6d8310a70b07043b9df5c988d5a62dafe00d
  GitTreeState: clean
  GitTag: v2.10.0
  GoVersion: go1.13.4
  Compiler: gc
  Platform: linux/amd64
```

Paste a workflow that reproduces the bug, including status:

I have my `workflow-controller-configmap` as seen below.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  workflowDefaults: |
    metadata:
      labels:
        foo: bar
    spec:
      serviceAccountName: argo
```

Created a trivial WorkflowTemplate

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cynthia-say
spec:
  entrypoint: cynthia-say
  templates:
  - name: cynthia-say
    container:
      image: busybox:1.32.0
      command: ["echo"]
      args: ["hello", "cynthia"]
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"
```

and they I can see (1) the label is not applied, and (2) the service account mounted is not the one I specified:

```
$ kubectl describe pod cynthia-say-xxxxx

...
Labels:             workflows.argoproj.io/completed=true
                    workflows.argoproj.io/workflow=cynthia-say-29nnv
Annotations:        kubernetes.io/psp: eks.privileged
                    workflows.argoproj.io/node-name: cynthia-say-29nnv
                    workflows.argoproj.io/template:
                      {"name":"cynthia-say","arguments":{},"inputs":{},"outputs":{},"metadata":{},"container":{"name":"","image":"busybox:1.32.0","command":["ec...
...
Containers:
  wait:
  ...
    Mounts:
      ...
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qghdc (ro)
  main:
    ...
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-qghdc (ro)
```

I should be getting the token from the right service account `/var/run/secrets/kubernetes.io/serviceaccount from argo-token-sm88z (ro)`.

### LINKED ISSUE #4267: WorkflowTemplate and synchronization lock bug
## Summary 

Synchronization lock on workflow execution defined in WorkflowTemplate not taken into account when creating a Workflow from the WorkflowTemplate.

If the synchronization lock is made on a template execution, all is working fine.

## Diagnostics

What Kubernetes provider are you using? K3S

What version of Argo Workflows are you running? v2.11.3

Workflow template definition:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: synchronization-test
spec:
  entrypoint: synchronization-test
  synchronization:
    semaphore:
      configMapKeyRef:
        name: synchronization-test
        key: workflow
  templates:
    - name: synchronization-test
      serviceAccountName: testssl
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["sleep 60"]
```

Workflow result:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-10-13T11:06:38Z"
  generateName: synchronization-test-
  generation: 5
  labels:
    submit-from-ui: "true"
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/creator: system-serviceaccount-argo-argo-server
    workflows.argoproj.io/phase: Succeeded
    workflows.argoproj.io/workflow-template: synchronization-test
  managedFields:
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:submit-from-ui: {}
          f:workflows.argoproj.io/creator: {}
          f:workflows.argoproj.io/workflow-template: {}
      f:spec:
        .: {}
        f:arguments: {}
        f:entrypoint: {}
        f:workflowTemplateRef:
          .: {}
          f:name: {}
      f:status:
        .: {}
        f:storedTemplates:
          .: {}
          f:namespaced/synchronization-test/synchronization-test:
            .: {}
            f:arguments: {}
            f:container:
              .: {}
              f:args: {}
              f:command: {}
              f:image: {}
              f:name: {}
              f:resources: {}
            f:inputs: {}
            f:metadata: {}
            f:name: {}
            f:outputs: {}
            f:serviceAccountName: {}
    manager: argo
    operation: Update
    time: "2020-10-13T11:06:38Z"
  - apiVersion: argoproj.io/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          f:workflows.argoproj.io/completed: {}
          f:workflows.argoproj.io/phase: {}
      f:status:
        f:conditions: {}
        f:finishedAt: {}
        f:nodes:
          .: {}
          f:synchronization-test-78ds7:
            .: {}
            f:displayName: {}
            f:finishedAt: {}
            f:hostNodeName: {}
            f:id: {}
            f:name: {}
            f:phase: {}
            f:resourcesDuration:
              .: {}
              f:cpu: {}
              f:memory: {}
            f:startedAt: {}
            f:templateRef:
              .: {}
              f:name: {}
              f:template: {}
            f:templateScope: {}
            f:type: {}
        f:phase: {}
        f:resourcesDuration:
          .: {}
          f:cpu: {}
          f:memory: {}
        f:startedAt: {}
        f:storedWorkflowTemplateSpec:
          .: {}
          f:arguments: {}
          f:entrypoint: {}
          f:synchronization:
            .: {}
            f:semaphore:
              .: {}
              f:configMapKeyRef:
                .: {}
                f:key: {}
                f:name: {}
          f:templates: {}
    manager: workflow-controller
    operation: Update
    time: "2020-10-13T11:07:43Z"
  name: synchronization-test-78ds7
  namespace: default
  resourceVersion: "80196099"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/default/workflows/synchronization-test-78ds7
  uid: a4c5446e-49b7-4c75-ab34-0f6f42bd8192
spec:
  arguments: {}
  entrypoint: synchronization-test
  workflowTemplateRef:
    name: synchronization-test
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-10-13T11:07:42Z"
  nodes:
    synchronization-test-78ds7:
      displayName: synchronization-test-78ds7
      finishedAt: "2020-10-13T11:07:41Z"
      hostNodeName: anytrack-2
      id: synchronization-test-78ds7
      name: synchronization-test-78ds7
      phase: Succeeded
      resourcesDuration:
        cpu: 122
        memory: 122
      startedAt: "2020-10-13T11:06:38Z"
      templateRef:
        name: synchronization-test
        template: synchronization-test
      templateScope: local/
      type: Pod
  phase: Succeeded
  resourcesDuration:
    cpu: 122
    memory: 122
  startedAt: "2020-10-13T11:06:38Z"
  storedTemplates:
    namespaced/synchronization-test/synchronization-test:
      arguments: {}
      container:
        args:
        - sleep 60
        command:
        - sh
        - -c
        image: alpine:latest
        name: ""
        resources: {}
      inputs: {}
      metadata: {}
      name: synchronization-test
      outputs: {}
      serviceAccountName: testssl
  storedWorkflowTemplateSpec:
    arguments: {}
    entrypoint: synchronization-test
    synchronization:
      semaphore:
        configMapKeyRef:
          key: workflow
          name: synchronization-test
    templates:
    - arguments: {}
      container:
        args:
        - sleep 60
        command:
        - sh
        - -c
        image: alpine:latest
        name: ""
        resources: {}
      inputs: {}
      metadata: {}
      name: synchronization-test
      outputs: {}
      serviceAccountName: testssl

```
**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### LINKED ISSUE #4344: workflowDefaults not propagated to workflowTemplate
## Summary 

As part of the workflow controller configmap, we configure workflowDefaults such as volumes.
Since we upgraded from v2.8.0 to v2.11.6 our workflows fail with:

`volume 'github-keypair' not found in workflow spec`

`kubectl get wf WORKFLOW_NAME -o yaml` does list the missing volume..

`argo resubmit WORKFLOW_NAME ` does not show the same issue. the workflow completes as expected

It's worth noting that this only happens when there is a volumeMount of the particular volume in a workflowTemplate.

To reproduce:

1. Apply workflowDefaults to the workflow configmap
```
    workflowDefaults:
      spec:
        ttlSecondsAfterFinished: 86400
        activeDeadlineSeconds: 7200
        volumes:
        - name: github-keypair
          secret:
            secretName: github-keypair # name of an existing k8s secret
            defaultMode: 256
```
2. Create a workflowTemplate with volumeMount
```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-template
spec:
  templates:
  - name: sayhi
    container:
      image: busybox
      command: [sh, -c]
      args:
      - | 
        echo "hi"
      volumeMounts:
      - name: github-keypair
        mountPath: /root/.ssh/id_rsa
        subPath: id_rsa
```

3. Create a workflow that uses the workflowTemplate
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: testwf-
spec:
  entrypoint: test
  templates:
  - name: test
    steps:
    - - name: sayhi
        templateRef:
          name: test-template
          template: sayhi
```

## Diagnostics

What Kubernetes provider are you using? 

Azure AKS

What version of Argo Workflows are you running? 

v2.11.6

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 

metadata:
  creationTimestamp: "2020-10-22T08:40:28Z"
  generateName: 2-build-wf-d
  generation: 2
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Failed
  name: 2-build-wf-djfht7
  namespace: argo
  resourceVersion: "11826795"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/2-build-wf-djfht7
  uid: 9c7f4a24-fad6-4bc1-909f-3835b2ecd61e
spec:
  activeDeadlineSeconds: 7200
  arguments: {}
  entrypoint: test
  nodeSelector:
    agentpool: argopool
  serviceAccountName: argo
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: test
    outputs: {}
    steps:
    - - arguments: {}
        name: sayhi
        templateRef:
          name: test-template
          template: sayhi
  tolerations:
  - effect: NoSchedule
    key: kubernetes.azure.com/scalesetpriority
    operator: Equal
    value: spot
  - effect: NoSchedule
    key: argo
    operator: Equal
    value: dedicated
  ttlSecondsAfterFinished: 86400
  volumes:
  - name: github-keypair
    secret:
      defaultMode: 256
      secretName: github-keypair
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-10-22T08:40:28Z"
  message: child '2-build-wf-djfht7[0].sayhi' errored
  nodes:
    2-build-wf-djfht7:
      children:
      - 2-build-wf-djfht7-1142771230
      displayName: 2-build-wf-djfht7
      finishedAt: "2020-10-22T08:40:28Z"
      id: 2-build-wf-djfht7
      message: child '2-build-wf-djfht7[0].sayhi' errored
      name: 2-build-wf-djfht7
      outboundNodes:
      - 2-build-wf-djfht7-2052941128
      phase: Failed
      startedAt: "2020-10-22T08:40:28Z"
      templateName: test
      templateScope: local/2-build-wf-djfht7
      type: Steps
    2-build-wf-djfht7-1142771230:
      boundaryID: 2-build-wf-djfht7
      children:
      - 2-build-wf-djfht7-2052941128
      displayName: '[0]'
      finishedAt: "2020-10-22T08:40:28Z"
      id: 2-build-wf-djfht7-1142771230
      message: child '2-build-wf-djfht7[0].sayhi' errored
      name: 2-build-wf-djfht7[0]
      phase: Error
      startedAt: "2020-10-22T08:40:28Z"
      templateName: test
      templateScope: local/2-build-wf-djfht7
      type: StepGroup
    2-build-wf-djfht7-2052941128:
      boundaryID: 2-build-wf-djfht7
      displayName: sayhi
      finishedAt: "2020-10-22T08:40:28Z"
      id: 2-build-wf-djfht7-2052941128
      message: volume 'github-keypair' not found in workflow spec
      name: 2-build-wf-djfht7[0].sayhi
      phase: Error
      startedAt: "2020-10-22T08:40:28Z"
      templateRef:
        name: test-template
        template: sayhi
      templateScope: local/2-build-wf-djfht7
      type: Pod
  phase: Failed
  startedAt: "2020-10-22T08:40:28Z"
  storedTemplates:
    namespaced/test-template/sayhi:
      arguments: {}
      container:
        args:
        - |
          echo "hi"
        command:
        - sh
        - -c
        image: busybox
        name: ""
        resources: {}
        volumeMounts:
        - mountPath: /root/.ssh/id_rsa
          name: github-keypair
          subPath: id_rsa
      inputs: {}
      metadata: {}
      name: sayhi
      outputs: {}
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

time="2020-10-22T08:40:28Z" level=info msg="Processing workflow" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Steps node 2-build-wf-djfht7 initialized Running" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="StepGroup node 2-build-wf-djfht7-1142771230 initialized Running" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Pod node 2-build-wf-djfht7-2052941128 initialized Pending" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=error msg="Mark error node" error="volume 'github-keypair' not found in workflow spec" namespace=argo nodeName="2-build-wf-djfht7[0].sayhi" workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="node 2-build-wf-djfht7-2052941128 phase Pending -> Error" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="node 2-build-wf-djfht7-2052941128 message: volume 'github-keypair' not found in workflow spec" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="node 2-build-wf-djfht7-2052941128 finished: 2020-10-22 08:40:28.32716929 +0000 UTC" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Step group node 2-build-wf-djfht7-1142771230 deemed errored due to child 2-build-wf-djfht7[0].sayhi error: volume 'github-keypair' not found in workflow spec" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="node 2-build-wf-djfht7-1142771230 phase Running -> Error" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="node 2-build-wf-djfht7-1142771230 message: child '2-build-wf-djfht7[0].sayhi' errored" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="node 2-build-wf-djfht7-1142771230 finished: 2020-10-22 08:40:28.327505204 +0000 UTC" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="step group 2-build-wf-djfht7-1142771230 was unsuccessful: child '2-build-wf-djfht7[0].sayhi' errored" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Outbound nodes of 2-build-wf-djfht7-2052941128 is [2-build-wf-djfht7-2052941128]" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Outbound nodes of 2-build-wf-djfht7 is [2-build-wf-djfht7-2052941128]" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="node 2-build-wf-djfht7 phase Running -> Failed" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="node 2-build-wf-djfht7 message: child '2-build-wf-djfht7[0].sayhi' errored" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="node 2-build-wf-djfht7 finished: 2020-10-22 08:40:28.327938123 +0000 UTC" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Checking daemoned children of 2-build-wf-djfht7" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Updated phase Running -> Failed" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Updated message  -> child '2-build-wf-djfht7[0].sayhi' errored" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Marking workflow completed" namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Checking daemoned children of " namespace=argo workflow=2-build-wf-djfht7
time="2020-10-22T08:40:28Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=11826795 workflow=2-build-wf-djfht7
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
Fixes #4246
Fixes #4344 
Fixes #4246 
Fixes #4267

### CODE REVIEW

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 1]
```diff
@@ -137,12 +137,8 @@ func (w Workflows) Filter(predicate WorkflowPredicate) Workflows {
 
 // GetTTLStrategy return TTLStrategy based on Order of precedence:
 //1. Workflow, 2. WorkflowTemplate, 3. Workflowdefault
-func (w *Workflow) GetTTLStrategy(defaultTTLStrategy *TTLStrategy) *TTLStrategy {
+func (w *Workflow) GetTTLStrategy() *TTLStrategy {
```
Comment (sarabala1979) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:140]: As a new approach, `StoredWorkflowSpec` will hold the merged workflowSpec which will have WFSpec, WFTSpec, and WFDefaultSpec. Reverting the previous fix

File: workflow/controller/controller.go [hunk 2]
```diff
@@ -510,24 +508,6 @@ func (wfc *WorkflowController) processNextItem() bool {
 		wfc.throttler.Remove(key)
 		return true
 	}
-
```
Comment (sarabala1979) [inline workflow/controller/controller.go:513]: Moving inside `operate()` to support the `synchronization` from WfDefault and WFTSpec

File: workflow/controller/operator.go [hunk 3]
```diff
@@ -191,14 +191,30 @@ func (woc *wfOperationCtx) operate() {
 
 	woc.log.Infof("Processing workflow")
 
-	// Load the WorkflowSpec for execution
-	execTmplRef, execArgs, err := woc.loadExecutionSpec()
+	// Loading the Execute workflow spec for execution
+	// ExecWF is a runtime execution spec which merged from Wf, WFT and Wfdefault
+	err := woc.loadExecWFFromWfDefaultOrWFTRef()
```
Comment (sarabala1979) [inline workflow/controller/operator.go:196]: This new function will load the ExecWF in Context. This function will make sure `storedworkflowSpec` set for `workflowtemplateRef` scenario and WorkflowDefault merged for normal workflow scenario

File: workflow/controller/operator.go [hunk 4]
```diff
@@ -3074,76 +3090,99 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
+				return err
+			}
+		}
+		if woc.wf.Status.StoredWorkflowSpec == nil {
 
-	//In WorkflowTemplateRef scenario, we need to merge the  Workflow spec, :StoredWorkflowspec and Workflow Default for execWf.
-	// Overlay
-	targetWf := wfv1.Workflow{Spec: *woc.wf.Spec.DeepCopy()}
+			// Merge wfT Metadata to Wf
+			wfutil.MergeMetaDataTo(wftHolder.GetWorkflowMetadata(), &woc.wf.ObjectMeta)
```
Comment (sarabala1979) [inline workflow/controller/operator.go:3138]: Merge the WFT Metadata into Workflow Metadata

File: workflow/controller/operator.go [hunk 5]
```diff
@@ -3074,76 +3090,99 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
-	err := wfutil.MergeTo(&wfv1.Workflow{Spec: *woc.wf.Status.StoredWorkflowSpec}, &targetWf)
-	if err != nil {
-		return nil, executionParameters, err
-	}
+			wfDefault := woc.controller.Config.WorkflowDefaults
+			if wfDefault == nil {
+				wfDefault = &wfv1.Workflow{}
+			}
+			// Merge wfDefault Metadata to Wf
+			wfutil.MergeMetaDataTo(&wfDefault.ObjectMeta, &woc.wf.ObjectMeta)
```
Comment (sarabala1979) [inline workflow/controller/operator.go:3145]: Merge the WFDefault Metadata into Workflow Metadata

File: workflow/controller/operator.go [hunk 6]
```diff
@@ -3074,76 +3090,99 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
-	woc.execWf = &targetWf
+			// Merge WF spec WFT spec and WorkflowDefault spec
 
-	woc.volumes = woc.execWf.Spec.DeepCopy().Volumes
-	tmplRef := &wfv1.WorkflowStep{TemplateRef: woc.wf.Spec.WorkflowTemplateRef.ToTemplateRef(woc.execWf.Spec.Entrypoint)}
-	if len(woc.execWf.Spec.Arguments.Parameters) > 0 {
-		executionParameters.Parameters = util.MergeParameters(executionParameters.Parameters, woc.execWf.Spec.Arguments.Parameters)
-	}
-	executionParameters.Artifacts = util.MergeArtifacts(executionParameters.Artifacts, woc.execWf.Spec.Arguments.Artifacts)
+			mergedWf, err := wfutil.MergeWfSpecs(&woc.wf.Spec, wftHolder.GetWorkflowSpec(), &wfDefault.Spec)
```
Comment (sarabala1979) [inline workflow/controller/operator.go:3149]: Merge WfSpec, WFTSpec, and WFDefaultSpec for `StoredWorkflowSpec`
order of precedence is WfSpec, WFTSpec and WFDefaultSpec

File: workflow/controller/operator.go [hunk 7]
```diff
@@ -191,14 +191,30 @@ func (woc *wfOperationCtx) operate() {
...
 	if err != nil {
-		woc.log.WithError(err).Errorf("Unable to get Workflow Template Reference for workflow")
+		woc.log.Errorf("loading WorkflowDefault or WorkflowTemplateRef failed: %v", err)
 		woc.markWorkflowError(err, true)
 		return
 	}
 
+	// Workflow Level Synchronization lock
+	if woc.execWf.Spec.Synchronization != nil {
+		acquired, wfUpdate, _, err := woc.controller.syncManager.TryAcquire(woc.wf, "", woc.execWf.Spec.Synchronization)
```
Comment (simster7) [inline workflow/controller/operator.go:205]: Why are we suddenly ignoring `msg` here?

File: workflow/controller/operator.go [hunk 8]
```diff
@@ -3074,76 +3090,99 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
+func (woc *wfOperationCtx) retryStrategy(tmpl *wfv1.Template) *wfv1.RetryStrategy {
+	if tmpl != nil && tmpl.RetryStrategy != nil {
+		return tmpl.RetryStrategy
 	}
+	return woc.execWf.Spec.RetryStrategy
+}
 
-	if woc.wf.Status.StoredWorkflowSpec == nil {
-		wftSpec, err := woc.fetchWorkflowSpec()
+func (woc *wfOperationCtx) loadExecWFFromWfDefaultOrWFTRef() error {
```
Comment (simster7) [inline workflow/controller/operator.go:3103]: This function name is almost impossible to parse. Please make it concise and clear about what it does.

File: workflow/controller/operator.go [hunk 9]
```diff
@@ -3074,76 +3090,99 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
 		if err != nil {
-			return nil, executionParameters, err
+			return err
 		}
-		woc.wf.Status.StoredWorkflowSpec = wftSpec
-		woc.updated = true
-	} else if woc.controller.Config.WorkflowRestrictions.MustNotChangeSpec() {
-		// If the controller is in reference mode, ensure that the stored spec is identical to the reference spec at every operation
-		wftSpec, err := woc.fetchWorkflowSpec()
+		err = woc.setExecWorkflow()
```
Comment (simster7) [inline workflow/controller/operator.go:3109]: This should be in-lined. `setExecWorkflow` is not used anywhere else and has redundant code (such as `if woc.wf.Spec.WorkflowTemplateRef != nil`)

File: workflow/controller/operator.go [hunk 10]
```diff
@@ -3074,76 +3090,99 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
+		err := woc.controller.setWorkflowDefaults(woc.wf)
+		if err != nil {
+			return err
 		}
+		woc.volumes = woc.wf.Spec.DeepCopy().Volumes
 	}
+	return nil
+}
+
+func (woc *wfOperationCtx) setStoredWFSpec() error {
```
Comment (simster7) [inline workflow/controller/operator.go:3125]: This function is very messy and disorganized: it's impossible to parse and its convoluted structure is likely to introduce bugs. Can you please spend some time tidying it up? It's a crucial piece of code, so it's worth investing time making sure it's readable and well-structured.

File: workflow/util/merge.go [hunk 11]
```diff
@@ -37,3 +39,52 @@ func MergeTo(patch, target *wfv1.Workflow) error {
 	}
 	return nil
 }
+
+// MergeMap will merge all element from right map to left map if it is not present in left.
+func MergeMap(left, right map[string]string) {
+	for key, val := range right {
+		if _, ok := left[key]; !ok {
+			fmt.Println(key, val)
```
Comment (simster7) [inline workflow/util/merge.go:47]: Remove?

File: workflow/util/merge.go [hunk 12]
```diff
@@ -37,3 +39,52 @@ func MergeTo(patch, target *wfv1.Workflow) error {
 	}
 	return nil
 }
+
+// MergeMap will merge all element from right map to left map if it is not present in left.
```
Comment (simster7) [inline workflow/util/merge.go:43]:
```suggestion
// MergeMap will add all elements from the right map that are not present in the left map into the left map.
```

File: workflow/util/merge.go [hunk 13]
```diff
@@ -37,3 +39,52 @@ func MergeTo(patch, target *wfv1.Workflow) error {
...
+		if _, ok := left[key]; !ok {
+			fmt.Println(key, val)
+			left[key] = val
+		}
+	}
+}
+
+// MergeWfSpece will merge the workflow space with order of precedence.
+// 1. Workflow Spec, 2 WorkflowTemplate Spec (WorkflowTemplateRef), 3. WorkflowDefault Spec.
+func MergeWfSpecs(wfSpec, wftSpec, wfDefaultSpec *wfv1.WorkflowSpec) (*wfv1.Workflow, error) {
```
Comment (simster7) [inline workflow/util/merge.go:55]:
```suggestion
func JoinWorkflowSpec(wfSpec, wfTmplSpec, wfDefaultSpec *wfv1.WorkflowSpec) (*wfv1.Workflow, error) {
```

File: workflow/util/merge.go [hunk 14]
```diff
@@ -37,3 +39,52 @@ func MergeTo(patch, target *wfv1.Workflow) error {
...
+func MergeMap(left, right map[string]string) {
+	for key, val := range right {
+		if _, ok := left[key]; !ok {
+			fmt.Println(key, val)
+			left[key] = val
+		}
+	}
+}
+
+// MergeWfSpece will merge the workflow space with order of precedence.
```
Comment (simster7) [inline workflow/util/merge.go:53]:
```suggestion
// JoinWorkflowSpec will join the workflow specs with the following order of preference
```

File: workflow/util/merge.go [hunk 15]
```diff
@@ -37,3 +39,52 @@ func MergeTo(patch, target *wfv1.Workflow) error {
...
+// 1. Workflow Spec, 2 WorkflowTemplate Spec (WorkflowTemplateRef), 3. WorkflowDefault Spec.
+func MergeWfSpecs(wfSpec, wftSpec, wfDefaultSpec *wfv1.WorkflowSpec) (*wfv1.Workflow, error) {
+	if wfSpec == nil {
+		return nil, fmt.Errorf("invalid Workflow spec")
+	}
```
Comment (simster7) [inline workflow/util/merge.go:58]: If `wfSpec` is `nil`, then we should just return `nil` instead of an error and let the caller handle it.

File: workflow/util/merge.go [hunk 16]
```diff
@@ -37,3 +39,52 @@ func MergeTo(patch, target *wfv1.Workflow) error {
 	}
 	return nil
 }
+
+// MergeMap will merge all element from right map to left map if it is not present in left.
+func MergeMap(left, right map[string]string) {
```
Comment (simster7) [inline workflow/util/merge.go:44]: Why is this exported if it's only used in this file?

File: workflow/util/merge.go [hunk 17]
```diff
@@ -37,3 +39,52 @@ func MergeTo(patch, target *wfv1.Workflow) error {
...
+		if err != nil {
+			return nil, err
+		}
+	}
+	return &targetWf, nil
+}
+
+// MergeMetaData will merge the patch metadata into target metadata.
+// This func will merge only labels and annotations.
+func MergeMetaDataTo(patch, targetMetaData *metav1.ObjectMeta) {
```
Comment (simster7) [inline workflow/util/merge.go:77]: This function merges from left argument to right argument, while other functions in this file do the opposite. Can you please make sure the ordering is consistent?

Comment (simster7) [reply workflow/util/merge.go:77]:
```suggestion
func MergeMetadata(from, to *metav1.ObjectMeta) {
```

File: workflow/util/merge.go [hunk 18]
```diff
@@ -37,3 +39,52 @@ func MergeTo(patch, target *wfv1.Workflow) error {
...
+		err := MergeTo(&wfv1.Workflow{Spec: *wfDefaultSpec.DeepCopy()}, &targetWf)
+		if err != nil {
+			return nil, err
+		}
+	}
+	return &targetWf, nil
+}
+
+// MergeMetaData will merge the patch metadata into target metadata.
+// This func will merge only labels and annotations.
```
Comment (simster7) [inline workflow/util/merge.go:76]:
```suggestion
// MergeMetadata will merge the labels and annotations into the target metadata.
```

File: workflow/util/merge.go [hunk 19]
```diff
@@ -37,3 +39,52 @@ func MergeTo(patch, target *wfv1.Workflow) error {
...
+func MergeMetaDataTo(patch, targetMetaData *metav1.ObjectMeta) {
+	if patch != nil && patch.Labels != nil {
```
Comment (simster7) [inline workflow/util/merge.go:78]: Perhaps we should just have a single

```go
if patch == nil {
  return
}
```

instead of checking this consistently

**Review by simster7 — CHANGES_REQUESTED** [review]
I was only able to review the code syntax itself, not the actual functional code, because it's difficult to parse. Can you tidy it up and request another review once you do so?

File: workflow/controller/operator.go (hunk 7 above)
Comment (sarabala1979) [reply workflow/controller/operator.go]: Good catch, Previous this code was in controller.go that's why message was ignored. But here we can update the wf object.

File: workflow/controller/operator.go [hunk 20]
```diff
@@ -3074,76 +3091,70 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
 	if woc.wf.Status.StoredWorkflowSpec == nil {
-		wftSpec, err := woc.fetchWorkflowSpec()
+		wfDefault := woc.controller.Config.WorkflowDefaults
+		wftHolder, err := woc.fetchWorkflowSpec()
 		if err != nil {
-			return nil, executionParameters, err
+			return err
 		}
-		woc.wf.Status.StoredWorkflowSpec = wftSpec
+		// Join WFT and WfDefault metadata to Workflow metadata.
```
Comment (simster7) [inline workflow/controller/operator.go:3131]:
```suggestion
		// Join workflow template and workflow default metadata to workflow metadata.
```

File: workflow/controller/operator.go [hunk 21]
```diff
@@ -3074,76 +3091,70 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
+		wfutil.JoinWorkflowMetaData(&woc.wf.ObjectMeta, wftHolder.GetWorkflowMetadata(), &wfDefault.ObjectMeta)
+
+		// Join WF spec WFT spec and WorkflowDefault spec
```
Comment (simster7) [inline workflow/controller/operator.go:3134]:
```suggestion
		// Join workflow template and workflow default metadata to workflow spec.
```

File: workflow/controller/operator.go [hunk 22]
```diff
@@ -3074,76 +3091,70 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
+		mergedWf, err := wfutil.JoinWorkflowSpec(&woc.wf.Spec, wftHolder.GetWorkflowSpec(), &wfDefault.Spec)
```
Comment (simster7) [inline workflow/controller/operator.go:3135]: Is there a reason as to why we need to do `Spec` and `ObjectMeta` separately? Why can't it all be done in one funciton?

File: workflow/controller/operator.go [hunk 23]
```diff
@@ -3074,76 +3091,70 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
+		if err != nil {
+			return err
+		}
+		// Clear the WorkflowTemplateRef from merged Workflow
+		mergedWf.Spec.WorkflowTemplateRef = nil
```
Comment (simster7) [inline workflow/controller/operator.go:3140]: This seems like a code smell... we shouldn't modify the original workflow spec at all. Why is this necessary?

File: workflow/controller/operator.go [hunk 24]
```diff
@@ -3074,76 +3091,70 @@ func (woc *wfOperationCtx) fetchWorkflowSpec() (*wfv1.WorkflowSpec, error) {
...
-		wftSpec, err := woc.fetchWorkflowSpec()
+		wftHolder, err := woc.fetchWorkflowSpec()
 		if err != nil {
-			return nil, executionParameters, err
+			return err
 		}
-		if woc.wf.Status.StoredWorkflowSpec.String() != wftSpec.String() {
-			return nil, executionParameters, fmt.Errorf("workflowTemplateRef reference may not change during execution when the controller is in reference mode")
+		wfDefault := woc.controller.Config.WorkflowDefaults
+		mergedWf, err := wfutil.JoinWorkflowSpec(&woc.wf.Spec, wftHolder.GetWorkflowSpec(), &wfDefault.Spec)
```
Comment (simster7) [inline workflow/controller/operator.go:3150]: What if workflow defaults change during execution? That would trigger this failure. Is that something we want? Unsure because the cluster admin has access to workflow defaults, so we might not want to consider that a breaking change to the execution.

File: workflow/controller/operator.go (hunk 10 above)
Comment (simster7) [reply workflow/controller/operator.go:3124]: By the way: the function is now much easier to read. Thanks.

**Review by simster7 — COMMENTED** [review]
Some comments

File: workflow/controller/operator.go (hunk 22 above)
Comment (sarabala1979) [reply workflow/controller/operator.go:3132]: WorkflowTemplate's and Workflow Default's Metadata needs to merge to the original workflow's metadata for searchable/filtering (labels/annotations).

File: workflow/controller/operator.go (hunk 23 above)
Comment (sarabala1979) [reply workflow/controller/operator.go:3137]: This mainly avoids `WorkflowTemplateRef`  in `storedWorkflowSpec`.  It is kind of confusing. I will remove this.

File: workflow/controller/operator.go (hunk 24 above)
Comment (sarabala1979) [reply workflow/controller/operator.go:3147]: Yes, We (Jesse & Alex) discussed this behavior. We need to fail it

**Review by simster7 — APPROVED** [review]
