### PR TITLE
fix(server): Only try to use auth-mode if enabled. Fixes #4400

### LINKED ISSUE #4400: auth-mode server fails when Authorization header is passed.
## Summary 

We have argo server behind a reverse proxy that does github SSO.. Upgrading from argo 2.8 to 2.11, using `--auth-mode server` broke the UI. /api/v1/version was returned
```json
{"code":16,"message":"no valid authentication methods found for mode client"}
```
## Diagnostics
The error is caused because our reverse proxy adds an authorization header.

To recreate:
- run argo server with auth-mode server
- port-forward to argo-ui
- This works `curl http://localhost:2746/api/v1/version`
- This fails `curl -H "Authorization: Bearer 1234"  http://localhost:2746/api/v1/version`

This was tracked down to:
https://github.com/argoproj/argo/blob/f9b65c52321d6e49d7fbc78f69d18e7d1ee442ad/server/auth/gatekeeper.go#L117-L118

when only auth-mode server is active, authorization and cookie headers should be ignored.

What Kubernetes provider are you using? 
GKE

What version of Argo Workflows are you running? 

2.11.8

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Signed-off-by: Alex Collins <alex_collins@intuit.com>
Fixes #4400

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

**Comment by alexec** [comment]
Engineering build created.

File: server/auth/mode.go [hunk 1]
```diff
@@ -30,15 +30,15 @@ func (m Modes) Add(value string) error {
...
-	if strings.HasPrefix(authorisation, sso.Prefix) {
+func (m Modes) GetMode(authorisation string) (Mode, error) {
+	if strings.HasPrefix(authorisation, sso.Prefix) && m[SSO] {
 		return SSO, nil
 	}
-	if strings.HasPrefix(authorisation, "Bearer ") || strings.HasPrefix(authorisation, "Basic ") {
+	if (strings.HasPrefix(authorisation, "Bearer ") || strings.HasPrefix(authorisation, "Basic ")) && m[Client] {
 		return Client, nil
 	}
+	if m[Server] {
```
Comment (sarabala1979) [inline server/auth/mode.go:40]: minor
can you move to first so other checks can be avoided?

**Review by sarabala1979 — APPROVED** [review]
