### PR TITLE
fix: Redirect to correct page when using managed namespace. Fixes #2015

### LINKED ISSUE #2015: UI gives 403 Forbidden rather than correctly using managed namespace
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

I open the UI and it redirected to http://localhost:2746/workflows/?namespace=argo, but I get "forbidden" error.

**What you expected to happen**:

It should actually redirect to managed namespace.

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

**Environment**:
- Argo version:
```
$ argo version
```
- Kubernetes version :
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the README.
* [x] I've signed the CLA and required builds are green. 

FIxes #2015

### CODE REVIEW

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx [hunk 1]
```diff
@@ -71,7 +77,7 @@ export class ArchivedWorkflowList extends BasePage<RouteComponentProps<any>, Sta
                     ]
                 }}>
                 <div className='row'>
-                    <div className='columns small-12 xxlarge-2'>{this.renderWorkflows()}</div>
```
Comment (alexec) [inline ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx]: this fixes an unrelated problem we had

Comment (simster7) [reply ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx]: I had seen this before
