### PR TITLE
fix(ui): Fix multiple UI issues

### LINKED ISSUE #3570: Issues with Workflow details UI toolbar
Some items no enabled when they should be, redirection broken. Working on it now.

### PR DESCRIPTION
**Pull request by simster7**
Fixes #3570 

This PR fixes:

* Issue with buttons being improperly hidden in "Workflow DAG" view (e.g. "Stop" is hidden when Workflow is running)
* Issue with actions not correctly redirecting after they are performed
* Issue with toolbar buttons being improperly hidden
* Issue when performing a batch action Workflows remain selected

### CODE REVIEW

File: ui/src/app/shared/workflow-operations-map.ts [hunk 1]
```diff
@@ -9,56 +9,62 @@ export type OperationDisabled = {
...
-    title: string;
-    action: () => Promise<any>;
+    title: WorkflowOperationName;
+    action: WorkflowOperationAction;
     iconClassName: string;
     disabled: (wf: Workflow) => boolean;
 }
 
-export const WorkflowOperations = {
+export type WorkflowOperationAction = (wf: Workflow) => Promise<any>;
```
Comment (alexec) [inline ui/src/app/shared/workflow-operations-map.ts:18]: I think you could use just `Operation` or `Action` as they are synonyms
