### PR TITLE
fix(controller): Revert parameter value to `*string`. Fixes #3960

### LINKED ISSUE #3960: Argo CLI (v2.10.0+) doesn't handle int64 values
## Summary 

Argo CLI v2.10.0 and above doesn't handle integer value that is greater than 32 bit. It is working fine with v2.9.0 & earlier.

## Diagnostics

**Version: 2.10.0**

**Cmd:**
```yaml
argo submit sample.yaml -p aws-account=81861780812
```

**Error:**
```
E0907 12:48:23.984423    6264 intstr.go:61] value: 881217801864 overflows int32
goroutine 1 [running]:
runtime/debug.Stack(0x20, 0x2b37200, 0xc000202600)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/debug/stack.go:24 +0x9d
k8s.io/apimachinery/pkg/util/intstr.FromInt(0xcd2cac8e88, 0xc, 0xcd2cac8e88, 0x0, 0x0)
	/Users/acollins8/go/pkg/mod/k8s.io/apimachinery@v0.17.5/pkg/util/intstr/intstr.go:61 +0x3a
k8s.io/apimachinery/pkg/util/intstr.Parse(0x7ffeefbffa34, 0xc, 0x2c8ae01, 0x1, 0x0, 0x1)
	/Users/acollins8/go/pkg/mod/k8s.io/apimachinery@v0.17.5/pkg/util/intstr/intstr.go:78 +0x7e
github.com/argoproj/argo/workflow/util.ApplySubmitOpts(0xc0000a5000, 0xc00068a090, 0x1, 0xc00068a090)
	/Users/acollins8/go/src/github.com/argoproj/argo/workflow/util/util.go:229 +0xde3
github.com/argoproj/argo/cmd/argo/commands.submitWorkflows(0x38788e0, 0xc0000cbbc0, 0x38afb40, 0xc0003a5480, 0xc0002c8de0, 0x15, 0xc0004ab800, 0x1, 0x1, 0xc00068a090, ...)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/submit.go:211 +0x1ad
github.com/argoproj/argo/cmd/argo/commands.submitWorkflowsFromFile(0x38788e0, 0xc0000cbbc0, 0x38afb40, 0xc0003a5480, 0xc0002c8de0, 0x15, 0xc0008fa5a0, 0x1, 0x3, 0xc00068a090, ...)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/submit.go:123 +0x2a7
github.com/argoproj/argo/cmd/argo/commands.NewSubmitCommand.func1(0xc0003a9680, 0xc0008fa5a0, 0x1, 0x3)
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/commands/submit.go:83 +0x29a
github.com/spf13/cobra.(*Command).execute(0xc0003a9680, 0xc0008fa510, 0x3, 0x3, 0xc0003a9680, 0xc0008fa510)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007b3680, 0xc00008c750, 0xc0008cbf50, 0x100545f)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/acollins8/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/Users/acollins8/go/src/github.com/argoproj/argo/cmd/argo/main.go:17 +0x2b

2020/09/07 12:48:23 Failed to submit workflow: spec.arguments.external-ip.value is required
```

## Findings
[util.go](https://github.com/argoproj/argo/blob/release-2.10/workflow/util/util.go#L229)

```go
intOrString := intstr.Parse(parts[1])
```
Here the `intstr.Parse` is the culprit and it's a K8s API machinery package. This restricts integer to be 32 bit. 

[intstr.go](https://github.com/kubernetes/apimachinery/blob/v0.19.0/pkg/util/intstr/intstr.go#L60)

```go
func FromInt(val int) IntOrString {
	if val > math.MaxInt32 || val < math.MinInt32 {
		klog.Errorf("value: %d overflows int32\n%s\n", val, debug.Stack())
	}
	return IntOrString{Type: Int, IntVal: int32(val)}
}
```

I think we need to either remove using this K8s parsing if not required or we can go for custom implementation. 
[v2.11-intstr/parse.go](https://github.com/argoproj/argo/blob/release-2.11/util/intstr/parse.go)

Please expedite, this is holding us from upgrading to the latest.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] ~~I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.~~
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #3960

`IntStr` is a misnomer. It cannot handle integer values (specifically int64). This PR reverts to v2.9

### CODE REVIEW

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 1]
```diff
@@ -610,11 +610,11 @@ type Parameter struct {
 	Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
 
 	// Default is the default value to use for an input parameter if a value was not supplied
-	Default *intstr.IntOrString `json:"default,omitempty" protobuf:"bytes,2,opt,name=default"`
+	Default *string `json:"default,omitempty" protobuf:"bytes,2,opt,name=default"`
```
Comment (simster7) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:613]: I think this value is wholly unused. Can we remove it?

Comment (alexec) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:613]: I thought that, but I actually think it's used in some weird and non-obvious dynamic way .

**Comment by alexec** [comment]
@jessesuen can you please approve this PR? It is a revert to v2.9 code and needs to be back-ported to v2.10 and v2.11.

**Review by jessesuen — APPROVED** [review]
