### PR TITLE
fix: Improve cookie security. Fixes #2759

### LINKED ISSUE #2759: Improve cookie security
After investigating SSO, I think we need to improve this:

* Remove display the cookie from the login page. 
* Set-up flags, `[]string{"path=/", "SameSite=lax", "httpOnly"}` but not `Secure`.

@alexmt why does Argo CD use "lax" not "strict"?

OSWAP

This is probably the most secure configuration we have for
now:
`Set-Cookie: __Host-SessionID=3h93...;Path=/;Secure;HttpOnly;SameSite=Strict`

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to USERS.md.

### CODE REVIEW

File: ui/src/app/login/components/login.tsx [hunk 1]
```diff
@@ -15,24 +15,24 @@ const getToken = () => {
...
     document.location.href = uiUrl('');
 };
 export const Login = () => (
     <Page title='Login' toolbar={{breadcrumbs: [{title: 'Login'}]}}>
         <div className='argo-container'>
             <p>
-                <i className='fa fa-info-circle' /> You appear to be logged {maybeLoggedIn() ? 'in' : 'out'}. It may not be necessary to login to use Argo, it depends on how it is
-                configured.
+                <i className='fa fa-info-circle' /> You appear to be <b>logged {maybeLoggedIn() ? 'in' : 'out'}</b>. It may not be necessary to login to use Argo, it depends on how
+                it is configured.
```
Comment (simster7) [inline ui/src/app/login/components/login.tsx:30]: A link to https://github.com/argoproj/argo/blob/master/docs/argo-server.md would be useful here

Comment (alexec) [reply ui/src/app/login/components/login.tsx:30]: yes - but not today :(

**Comment by simster7** [comment]
Back-ported to 2.7
