### PR TITLE
fix: Don't save label filter in local storage. Fixes #3966

### LINKED ISSUE #3966: workflows label field bricks argo using localstorage
## Summary 

I decided to try the "LABELS" field in the workflow list view of the web UI. I thought it might take a wildcard so I tried searching with an * . This bricked the argo workflow list page -- I would get Bad Request, and no amount of refreshing helped. I tried clearing the cache and everything before thinking of going into my localstorage in dev tools and deleting the offending info there.

image

image

I suggest one a solution might be that the error page, instead of just having "refresh," has a button that clears local storage. Or maybe the refresh link just clears any dangerous localstorage.

## Diagnostics

2.10.1

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by simster7**
Fixes https://github.com/argoproj/argo/issues/3966

### CODE REVIEW

File: ui/src/app/workflows/components/workflows-list/workflows-list.tsx [hunk 1]
```diff
@@ -89,7 +87,7 @@ export class WorkflowsList extends BasePage<RouteComponentProps<any>, State> {
             },
             namespace: this.props.match.params.namespace || '',
             selectedPhases: this.queryParams('phase').length > 0 ? this.queryParams('phase') : savedOptions.selectedPhases,
```
Comment (alexec) [inline ui/src/app/workflows/components/workflows-list/workflows-list.tsx:89]: do we need to the same for phases?

**Review by alexec — APPROVED** [review]

File: ui/src/app/workflows/components/workflows-list/workflows-list.tsx (hunk 1 above)
Comment (simster7) [reply ui/src/app/workflows/components/workflows-list/workflows-list.tsx:89]: I think phases makes more sense to store for two reasons: (1) it's a close-ended input (we provide all available options), and (2) I think the use case makes more sense
