### PR TITLE
fix(persistence): set postgres ssl config to string Fixes #1866

### LINKED ISSUE #1866: Argo Database Persistence SSL does not work
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [ ] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
Setting up SSL on postgres database to persist workflow objects fails because config is incorrect.

**What you expected to happen**:
I expected SSL to work :smile: 

**How to reproduce it (as minimally and precisely as possible)**:
Deploy argo with Helm chart v0.6.4 and set values as follows:

```yaml
argo:
  controller:
    persistence:
      connectionPool:
        maxIdleConns: 100
        maxOpenConns: 0
      # save the entire workflow into etcd and DB
      nodeStatusOffLoad: false
      postgresql:
        host: database.data.com
        port: 25060
        database: test
        tableName: argo_workflows
        userNameSecret:
          name: argo-postgres-secret
          key: POSTGRES_USER
        passwordSecret:
          name: argo-postgres-secret
          key: POSTGRES_PASSWORD
        ssl: true
```

**Anything else we need to know?**:

This relates to the following issue (#1712) and PR (#1756)

**Environment**:
- Argo version: 2.4.3
```
$ argo version
```
- Kubernetes version : 1.15.5
```
$ kubectl version -o yaml
```

**Other debugging information (if applicable)**:
- workflow-controller logs:
```
time="2019-12-17T04:12:15Z" level=info msg="workflow controller configuration from argo-workflow-controller-configmap:\ncontainerRuntimeExecutor: docker\nartifactRepository:\n  archiveLogs: true\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: argo-artifact-creds\n    secretKeySecret:\n      key: secretkey\n      name: argo-artifact-creds\n    bucket: pollination-bucket\n    endpoint: argo-minio:9000\n    insecure: false\n    keyPrefix: simulation-logs\npersistence:\n  connectionPool:\n    maxIdleConns: 100\n    maxOpenConns: 0\n  nodeStatusOffLoad: false\n  postgresql:\n    database: simulations\n    host: data-hive-do-user-2842631-0.db.ondigitalocean.com\n    passwordSecret:\n      key: POSTGRES_PASSWORD\n      name: argo-postgres-secret\n    port: 25060\n    ssl: true\n    tableName: argo_workflows\n    userNameSecret:\n      key: POSTGRES_USER\n      name: argo-postgres-secret\n  \n"
time="2019-12-17T04:12:15Z" level=info msg="Persistence configuration enabled"
time="2019-12-17T04:12:15Z" level=error msg="Error in createPersistenceContext. pq: unsupported sslmode \"true\"; only \"require\" (default), \"verify-full\", \"verify-ca\", and \"disable\" supported"
time="2019-12-17T04:12:15Z" level=error msg="Error Creating Persistence context. pq: unsupported sslmode \"true\"; only \"require\" (default), \"verify-full\", \"verify-ca\", and \"disable\" supported"
time="2019-12-17T04:12:15Z" level=info msg="Workflow Controller (version: v2.4.3) starting"
time="2019-12-17T04:12:15Z" level=info msg="Workers: workflow: 8, pod: 8"
time="2019-12-17T04:12:15Z" level=info msg="Watch Workflow controller config map updates"
time="2019-12-17T04:12:15Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2019-12-17T04:12:15Z" level=info msg="Detected ConfigMap update. Updating the controller config."
time="2019-12-17T04:12:15Z" level=info msg="workflow controller configuration from argo-workflow-controller-configmap:\ncontainerRuntimeExecutor: docker\nartifactRepository:\n  archiveLogs: true\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: argo-artifact-creds\n    secretKeySecret:\n      key: secretkey\n      name: argo-artifact-creds\n    bucket: bucket\n    endpoint: argo-minio:9000\n    insecure: false\n    keyPrefix: simulation-logs\npersistence:\n  connectionPool:\n    maxIdleConns: 100\n    maxOpenConns: 0\n  nodeStatusOffLoad: false\n  postgresql:\n    database: test\n    host: database.my-data.com\n    passwordSecret:\n      key: POSTGRES_PASSWORD\n      name: argo-postgres-secret\n    port: 25060\n    ssl: true\n    tableName: argo_workflows\n    userNameSecret:\n      key: POSTGRES_USER\n      name: argo-postgres-secret\n  \n"
time="2019-12-17T04:12:15Z" level=info msg="Persistence configuration enabled"
time="2019-12-17T04:12:15Z" level=error msg="Error in createPersistenceContext. pq: unsupported sslmode \"true\"; only \"require\" (default), \"verify-full\", \"verify-ca\", and \"disable\" supported"
time="2019-12-17T04:12:15Z" level=error msg="Error Creating Persistence context. pq: unsupported sslmode \"true\"; only \"require\" (default), \"verify-full\", \"verify-ca\", and \"disable\" supported"
time="2019-12-17T04:12:16Z" level=info msg="Started workflow TTL worker"

```

### PR DESCRIPTION
**Pull request by AntoineDao**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`. Why? for the release notes. 
* [ ] I've signed the CLA and required builds are green. 

Fixes #1866

### CODE REVIEW

File: workflow/util/util_test.go [hunk 1]
```diff
@@ -168,3 +169,29 @@ func unmarshalWF(yamlStr string) *wfv1.Workflow {
...
+	  limits:
+		cpu: 1000m
+`
+
+func TestPodSpecPatchMerge(t *testing.T) {
+	tmpl := wfv1.Template{PodSpecPatch: "{\"containers\":[{\"name\":\"main\", \"resources\":{\"limits\":{\"cpu\": \"1000m\"}}}]}"}
+	wf := wfv1.Workflow{Spec: wfv1.WorkflowSpec{PodSpecPatch: "{\"containers\":[{\"name\":\"main\", \"resources\":{\"limits\":{\"memory\": \"100Mi\"}}}]}"}}
+	merged, _ := PodSpecPatchMerge(&wf, &tmpl)
+	var spec v1.PodSpec
+	json.Unmarshal([]byte(merged), &spec)
```
Comment (golangcibot) [inline workflow/util/util_test.go]: Error return value of `json.Unmarshal` is not checked (from `errcheck`)

File: workflow/util/util_test.go [hunk 2]
```diff
@@ -168,3 +169,29 @@ func unmarshalWF(yamlStr string) *wfv1.Workflow {
...
+	assert.Equal(t, "1.000", spec.Containers[0].Resources.Limits.Cpu().AsDec().String())
+	assert.Equal(t, "104857600", spec.Containers[0].Resources.Limits.Memory().AsDec().String())
+
+	tmpl = wfv1.Template{PodSpecPatch: yamlStr}
+	wf = wfv1.Workflow{Spec: wfv1.WorkflowSpec{PodSpecPatch: "{\"containers\":[{\"name\":\"main\", \"resources\":{\"limits\":{\"memory\": \"100Mi\"}}}]}"}}
+	merged, _ = PodSpecPatchMerge(&wf, &tmpl)
+	json.Unmarshal([]byte(merged), &spec)
```
Comment (golangcibot) [inline workflow/util/util_test.go]: Error return value of `json.Unmarshal` is not checked (from `errcheck`)

**Comment by simster7** [comment]
It seems like you used an old branch to make these changes, causing a lot of conflicts and old commits to be included. Can you redo your changes on a new branch that is checked out from a fresh pull of master?

**Comment by AntoineDao** [comment]
I tested this on our cluster using `sslMode: require` and it worked as expected. Sorry for the initially faulty PR that made it into release v2.4.3... Should've read the `pq` docs a bit more before making changes :nerd_face:

File: workflow/config/config.go [hunk 3]
```diff
@@ -108,7 +108,7 @@ type PostgreSQLConfig struct {
 	TableName      string                  `json:"tableName"`
 	UsernameSecret apiv1.SecretKeySelector `json:"userNameSecret"`
 	PasswordSecret apiv1.SecretKeySelector `json:"passwordSecret"`
-	SSL            bool                    `json:"ssl,omitempty"`
+	SSLMode        string                  `json:"sslMode,omitempty"`
```
Comment (simster7) [inline workflow/config/config.go]: We are technically changing an API here, but since it has been a short time and a niche feature I think it might be fine.

This is in @sarabala1979's domain so I will let him make the final review.

Comment (AntoineDao) [reply workflow/config/config.go]: Ah yeah didn't think of that. Happy to change it if folk are already using it. Is there some documentation/guidance on managing API changes for the Argo project somewhere I can refer to in order to get it right next time?

Comment (alexec) [reply workflow/config/config.go]: Can we please have two flags? You can mark `SSL` as deprecated.

Comment (AntoineDao) [reply workflow/config/config.go]: Yep will do. Do you guys manage deprecation through a comment in the code or is there a way to surface it back to the OpenAPI spec?

Comment (alexec) [reply workflow/config/config.go]: I think you make them with the commend `//DEPRECATED`, but how about using `SSL` to turn it on and `SSLMode` to choose the mode?

Comment (AntoineDao) [reply workflow/config/config.go]: I'm not fussed either way. Which are you most comfortable with?

Comment (alexec) [reply workflow/config/config.go]: lets have both fields

Comment (AntoineDao) [reply workflow/config/config.go]: On it. Will send a patch in the next few hours.

Comment (AntoineDao) [reply workflow/config/config.go]: Edit: I patched it in a few months...

**Comment by AntoineDao** [comment]
As discussed the following changes enable the following behavior:

- Enable the use of SSL between database and argo controller through `ssl` boolean toggle
- Specify the the SSL connection behavior through the `sslMode` string

Here are some example values if you were using an Argo helm chart
```yaml
argo:
  controller:
    persistence:
        ssl: true
        sslMode: require
```

According to the pq code docs I could find the following values are supported for `sslMode`:
* `disable` - No SSL
* `require` - Always SSL (skip verification)
* `verify-ca` - Always SSL (verify that the certificate presented by the server was signed by a trusted CA)
* `verify-full` - Always SSL (verify that the certification presented by the server was signed by a trusted CA and the server host name matches the one in the certificate)

**Comment by AntoineDao** [comment]
Server suite tests are failing. Something about a `PodLogsNotFound` test which is supposed to return 404 but returns 200. Not sure how the changes I've made could have impacted that...

```log
--- FAIL: TestArgoServerSuite (15.60s)
    --- PASS: TestArgoServerSuite/TestArchivedWorkflowService (7.88s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListDoesNotExist (0.02s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListEquals (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListDoubleEquals (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListIn (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListNotEquals (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListNotIn (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListExists (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListGreaterThan0 (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListGreaterThan1 (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListLessThan1 (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListLessThan2 (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/ListWithLimitAndOffset (0.01s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/Get (0.02s)
        --- PASS: TestArgoServerSuite/TestArchivedWorkflowService/Delete (0.02s)
    --- PASS: TestArgoServerSuite/TestArtifactServer (0.06s)
    --- PASS: TestArgoServerSuite/TestCookieAuth (0.03s)
    --- PASS: TestArgoServerSuite/TestCreateWorkflowDryRun (0.04s)
    --- PASS: TestArgoServerSuite/TestCronWorkflowService (0.69s)
    --- PASS: TestArgoServerSuite/TestInfo (0.39s)
    --- PASS: TestArgoServerSuite/TestLintWorkflow (0.40s)
    --- PASS: TestArgoServerSuite/TestPermission (0.40s)
    --- PASS: TestArgoServerSuite/TestUnauthorized (0.40s)
    --- PASS: TestArgoServerSuite/TestWorkflowService (0.40s)
    --- FAIL: TestArgoServerSuite/TestWorkflowServiceStream (4.77s)
        --- PASS: TestArgoServerSuite/TestWorkflowServiceStream/Watch (4.00s)
        --- PASS: TestArgoServerSuite/TestWorkflowServiceStream/PodLogs (0.07s)
        --- FAIL: TestArgoServerSuite/TestWorkflowServiceStream/PodLogsNotFound (0.02s)
            argo_server_test.go:811: 
                	Error Trace:	argo_server_test.go:811
                	            				suite.go:76
                	Error:      	Not equal: 
                	            	expected: 404
                	            	actual  : 200
                	Test:       	TestArgoServerSuite/TestWorkflowServiceStream/PodLogsNotFound
    --- PASS: TestArgoServerSuite/TestWorkflowTemplateService (0.09s)
```

**Comment by alexec** [comment]
@AntoineDao lets try updating your branch...

**Comment by alexec** [comment]
:shipit:
