### PR TITLE
fix(executor): Fix the artifacts option in k8sapi and PNS executor Fixes#4244

### LINKED ISSUE #4244: With workflow executor set to k8sapi, artifact optional feature does not work when tgz archive is disabled
## Summary 

For security concern, We are trying to switch workflow executor from default docker to k8sapi.
When testing in Dev environment, we noticed that artifact `optional` feature does not work when `archive` is disabled. when output file does not exist(optional set to true), instead of ignore, the workflow failed locating the file and timeout. 
(It worked when we used  docker executor)

## Diagnostics

env: EKS cluster, k8s 1.14

Argo version: 2.9.5

workflow executor: k8sapi

below is the yaml which can reproduce the issue. 
with `archive:     none: {}`, the workflow fails, if remove `archive:     none: {}`, It works

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: output-artifact-optional-
spec:
  arguments:
    parameters:
    - name: seq-id
      value: |
        [1,2]

  entrypoint: artifact-example

  volumes:
    - name: shared
      emptyDir: {}

  templates:
    - name: artifact-example
      parallelism: 2
      inputs:
        parameters:
        - name: seq-id
      steps:
        - - name: generate-artifact
            template: whalesay
            arguments:
              parameters:
              - name: seq-id
                value: "{{item}}"
            withParam: "{{inputs.parameters.seq-id}}"

    - name: whalesay
      inputs:
        parameters:
        - name: seq-id
      container:
        image: argoproj/argosay:v1
        command: [sh, -c]
        args: ["sleep 1; cowsay hello world | tee /tmp/hello-world-1.txt"]
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"
          requests:
            memory: "100Mi"
            cpu: "100m"
        volumeMounts:
          - mountPath: /tmp
            name: shared

      outputs:
        artifacts:
          - name: hello-art
            path: "/tmp/hello-world-{{inputs.parameters.seq-id}}.txt"
            archive:
              none: {}
            optional: true
```

log from failed job:
```
time="2020-10-08T17:55:51.863Z" level=info msg="S3 Save path: /mainctrfs/tmp/hello-world-2.txt, key: sib/artifacts/2020/10/08/output-artifact-optional-f7klk/output-artifact-optional-f7klk-3139361642/hello-world-2.txt"
time="2020-10-08T17:55:51.863Z" level=info msg="Creating minio client using GetAWSCredentials credentials"
time="2020-10-08T17:55:51.876Z" level=warning msg="Failed to test if /mainctrfs/tmp/hello-world-2.txt is a directory: open /mainctrfs/tmp/hello-world-2.txt: no such file or directory"
time="2020-10-08T17:55:51.876Z" level=error msg="executor error: timed out waiting for the condition"
time="2020-10-08T17:55:51.876Z" level=info msg="Killing sidecars"
time="2020-10-08T17:55:51.881Z" level=info msg="Alloc=9010 TotalAlloc=24497 Sys=71360 NumGC=7 Goroutines=9"
time="2020-10-08T17:55:51.890Z" level=fatal msg="timed out waiting for the condition"
```

Could you please help check? Thanks.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
Fixes #4244

### CODE REVIEW

File: workflow/executor/executor.go [hunk 1]
```diff
@@ -374,6 +374,9 @@ func (we *WorkflowExecutor) stageArchiveFile(mainCtrID string, art *wfv1.Artifac
 		if strategy.None != nil {
 			fileName := filepath.Base(art.Path)
 			log.Infof("No compression strategy needed. Staging skipped")
+			if !argofile.Exists(mountedArtPath) {
+				return "", "", os.ErrNotExist
```
Comment (alexec) [inline workflow/executor/executor.go:378]: why not return errors.CodeNotFound?

File: workflow/executor/executor.go [hunk 2]
```diff
@@ -374,6 +374,9 @@ func (we *WorkflowExecutor) stageArchiveFile(mainCtrID string, art *wfv1.Artifac
 		if strategy.None != nil {
 			fileName := filepath.Base(art.Path)
 			log.Infof("No compression strategy needed. Staging skipped")
+			if !argofile.Exists(mountedArtPath) {
```
Comment (alexec) [inline workflow/executor/executor.go:377]: test?

**Review by alexec — CHANGES_REQUESTED** [review]
needs tests

**Review by alexec — APPROVED** [review]
