### PR TITLE
fix(controller): prepend script path to the script template args. Resolves #4481

### LINKED ISSUE #4481: Weird argument arrangement when using script template
# Summary

I wanted to add a template that is activated on a workflow exit (the `onExit` field) with a purpose of notifying the user about the workflow status. I decided to use a template of type `script`, like this:

```YAML
name: "workflow-status-test"
script: 
 image: "python:3.6-alpine"
 command:
  - python3
 args:
  - "{{workflow.status}}"
 source: "import sys; import my_notify_func; my_notify_func(sys.argv[1])"
```

This failed. After inspecting the pod, I saw that Argo passed the arguments to the python container in the following way `Succeeded /argo/staging/script`, I would expect it to do it like this `/argo/staging/script Succeeded`.

Later I noticed in one of your examples in git repo that I could embed a template directly in the `source` field. But this wasn't documented anywhere (at least I didnt see it). So, this solves my issue:

```YAML
name: "workflow-status-test"
script: 
 image: "python:3.6-alpine"
 command:
  - python3
 source: "import my_notify_func; my_notify_func('{{workflow.status}}')"
```

The order in which the arguments are passed is unintuitive and I don't see a case where this particular order would be useful. My suggestion is to change the order (so first goes the script path, and then the user args) or put a notice/disclaimer in the docs. Also, you could provide an example for using templates [here](https://argoproj.github.io/argo/examples/), or document it.

# Use Cases

When would you use this?

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by ivancili**
Signed-off-by: ivancili <ivandotilic@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Resolves #4481

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -2285,7 +2285,10 @@ func (woc *wfOperationCtx) executeScript(nodeName string, templateScope string,
 	}
 
 	mainCtr := tmpl.Script.Container
-	mainCtr.Args = append(mainCtr.Args, common.ExecutorScriptSourcePath)
+	// if script source is specified then pass all container args to the script
+	if tmpl.Script.Source != "" {
```
Comment (alexec) [inline workflow/controller/operator.go:2289]: Test?

Comment (ivancili) [reply workflow/controller/operator.go:2289]: @alexec I didnt have time to test it properly yet, thats why I created a draft PR. But I will try to finish this today.

**Review by ivancili — COMMENTED** [review]
@alexec The function `extractMainCtrFromScriptTemplate` that I wrote could also be used by the test `TestScriptTemplateWithoutVolumeOptionalArtifact`, which was previously written inside `workflowpod_test.go`. Let me know if you want me to update the PR with those changes.

File: workflow/controller/workflowpod_test.go [hunk 2]
```diff
@@ -69,6 +69,87 @@ func TestScriptTemplateWithVolume(t *testing.T) {
 	assert.NoError(t, err)
 }
 
+var scriptTemplateWithArgsAndWithSource = `
```
Comment (alexec) [inline workflow/controller/workflowpod_test.go:72]: I thought I'd never say this, but there is a first time for everything.

I think you've written TOO many tests. 

I think you only need to test `extractMainCtrFromScriptTemplate.

Comment (ivancili) [reply workflow/controller/workflowpod_test.go:72]: Haha no problem, I'll delete those that don't test `extractMainCtrFromScriptTemplate` explicitly. What I was trying to do is really test that exit code of a container in all these cases is zero, instead of just testing correct args order before execution.

**Comment by ivancili** [comment]
So I deleted those unnecessary tests that you pointed out, and now some existing tests that were passing before are failing. And everything is passing locally.

File: workflow/controller/workflowpod_test.go (hunk 2 above)
Comment (alexec) [reply workflow/controller/workflowpod_test.go:72]: cool - I'll mark this as "Draft" while you do that

Comment (ivancili) [reply workflow/controller/workflowpod_test.go:72]: Here you go, I left only 2 tests which cover `extractMainCtrFromScriptTemplate`. One for when script source is specified, and the other one when the source is empty.

**Review by alexec — APPROVED** [review]
LGTM
