### PR TITLE
fix(controller): Apply Workflow default on normal workflow scenario Fixes #4208

### LINKED ISSUE #4208: v2.11: workflow-controller-configmap serviceAccountName not being honored
## Summary 

`serviceAccountName` in `workflowDefaults` takes no effect.

## Diagnostics

> What version of Argo Workflows are you running?

v2.11.1

I created the following `workflow-controller-configmap` with a default `serviceAccountName`.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    workflowDefaults:
      spec:
        serviceAccountName: argo-workflow
```

I submitted a workflow omitting `serviceAccountName`.
So, I expected for Argo to use `argo-workflow` ServiceAccount specified in `workflowDefaults.spec`.
However, Argo used `default` ServiceAccount.

```
$ argo submit --log tutorial-01.yml
Name:                tutorial-01-xsn58
Namespace:           argo-tutorial
ServiceAccount:      default
Status:              Pending
Created:             Sun Oct 04 16:02:47 +0900 (now)
```

Actually, the pod ran as `default`.

```
$ kubectl get pod tutorial-01-xsn58-1084908792 -o yaml
apiVersion: v1
kind: Pod
spec:
  serviceAccount: default
  serviceAccountName: default
```

It's noted that the workflow resource has the expected `ServiceAccountName`.

```
$ kubectl get wf tutorial-01-xsn58 -o yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
spec:
  serviceAccountName: argo-workflow
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
Fixes #4208

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -133,10 +133,11 @@ func newWorkflowOperationCtx(wf *wfv1.Workflow, wfc *WorkflowController) *wfOper
 	// NEVER modify objects from the store. It's a read-only, local cache.
 	// You can use DeepCopy() to make a deep copy of original object and modify this copy
 	// Or create a copy manually for better performance
+	wfCopy := wf.DeepCopyObject().(*wfv1.Workflow)
 	woc := wfOperationCtx{
-		wf:      wf.DeepCopyObject().(*wfv1.Workflow),
+		wf:      wfCopy,
```
Comment (sarabala1979) [inline workflow/controller/operator.go:138]: wf and execWf should have the same pointer for downstream execution.

**Review by alexec — APPROVED** [review]
