### PR TITLE
fix(controller): Get correct Step or DAG name. Fixes #2244

### LINKED ISSUE #2244: parameter-aggregation.yaml in examples failing without errors
argo: v2.4.3
  BuildDate: 2019-12-06T03:36:01Z
  GitCommit: cfe5f377bc3552fba90afe6db7a76edd92c753cd
  GitTreeState: clean
  GitTag: v2.4.3
  GoVersion: go1.11.5
  Compiler: gc
  Platform: linux/amd64

When I try the [parameter-aggregation.yaml template](https://github.com/argoproj/argo/blob/master/examples/parameter-aggregation.yaml) from examples:
It says success and I get the following:
```
Name:                parameter-aggregation-r876w
Namespace:           default
ServiceAccount:      default
Status:              Succeeded
Created:             Sat Feb 15 16:12:05 +0530 (43 seconds ago)
Started:             Sat Feb 15 16:12:05 +0530 (43 seconds ago)
Finished:            Sat Feb 15 16:12:48 +0530 (now)
Duration:            43 seconds

STEP                                                     PODNAME                                 DURATION  MESSAGE
 ✔ parameter-aggregation-r876w (parameter-aggregation)                                                     
 ├-·-✔ odd-or-even(0:1) (odd-or-even)                    parameter-aggregation-r876w-3463065390  7s        
 | ├-✔ odd-or-even(1:2) (odd-or-even)                    parameter-aggregation-r876w-2735603540  7s        
 | ├-✔ odd-or-even(2:3) (odd-or-even)                    parameter-aggregation-r876w-2177316838  6s        
 | ├-✔ odd-or-even(3:4) (odd-or-even)                    parameter-aggregation-r876w-2272973104  8s        
 | ├-✔ odd-or-even(4:5) (odd-or-even)                    parameter-aggregation-r876w-259735830   6s        
 | └-✔ odd-or-even(5:6) (odd-or-even)                    parameter-aggregation-r876w-1753430276  7s        
 ├-·-○ divide-by-2(0:evenness:odd,num:1) (divide-by-2)                                                     when 'odd == even' evaluated false
 | ├-✔ divide-by-2(1:evenness:even,num:2) (divide-by-2)  parameter-aggregation-r876w-3705536022  30s       
 | ├-○ divide-by-2(2:evenness:odd,num:3) (divide-by-2)                                                     when 'odd == even' evaluated false
 | ├-✔ divide-by-2(3:evenness:even,num:4) (divide-by-2)  parameter-aggregation-r876w-3942260798  30s       
 | ├-○ divide-by-2(4:evenness:odd,num:5) (divide-by-2)                                                     when 'odd == even' evaluated false
 | └-✔ divide-by-2(5:evenness:even,num:6) (divide-by-2)  parameter-aggregation-r876w-3436829278  30s
```

**But the last step `print` with template `whalesay` doesn't run. It doesn't give any errors either.**

**Environment**:
Kubernetes version:
```
clientVersion:
  buildDate: "2020-01-18T23:30:10Z"
  compiler: gc
  gitCommit: 59603c6e503c87169aea6106f57b9f242f64df89
  gitTreeState: clean
  gitVersion: v1.17.2
  goVersion: go1.13.5
  major: "1"
  minor: "17"
  platform: linux/amd64
serverVersion:
  buildDate: "2019-12-22T23:14:11Z"
  compiler: gc
  gitCommit: c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2
  gitTreeState: clean
  gitVersion: v1.14.9-eks-c0eccc
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Logs** 
`kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)`
```
time="2020-02-15T10:42:05Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Updated phase  -> Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Steps node parameter-aggregation-r876w (parameter-aggregation-r876w) initialized Pending" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="node parameter-aggregation-r876w (parameter-aggregation-r876w) phase Pending -> Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="StepGroup node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) initialized Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Pod node parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390) initialized Pending" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Created pod: parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Pod node parameter-aggregation-r876w[0].odd-or-even(1:2) (parameter-aggregation-r876w-2735603540) initialized Pending" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Created pod: parameter-aggregation-r876w[0].odd-or-even(1:2) (parameter-aggregation-r876w-2735603540)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Pod node parameter-aggregation-r876w[0].odd-or-even(2:3) (parameter-aggregation-r876w-2177316838) initialized Pending" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Created pod: parameter-aggregation-r876w[0].odd-or-even(2:3) (parameter-aggregation-r876w-2177316838)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Pod node parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) initialized Pending" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Created pod: parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Pod node parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) initialized Pending" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Created pod: parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Pod node parameter-aggregation-r876w[0].odd-or-even(5:6) (parameter-aggregation-r876w-1753430276) initialized Pending" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Created pod: parameter-aggregation-r876w[0].odd-or-even(5:6) (parameter-aggregation-r876w-1753430276)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Workflow step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:05Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:06Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:06Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390) message: ContainerCreating"
time="2020-02-15T10:42:06Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) message: ContainerCreating"
time="2020-02-15T10:42:06Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(5:6) (parameter-aggregation-r876w-1753430276) message: ContainerCreating"
time="2020-02-15T10:42:06Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(2:3) (parameter-aggregation-r876w-2177316838) message: ContainerCreating"
time="2020-02-15T10:42:06Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) message: ContainerCreating"
time="2020-02-15T10:42:06Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(1:2) (parameter-aggregation-r876w-2735603540) message: ContainerCreating"
time="2020-02-15T10:42:06Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:07Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(1:2) (parameter-aggregation-r876w-2735603540) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:07Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(2:3) (parameter-aggregation-r876w-2177316838) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:07Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:07Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:07Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(5:6) (parameter-aggregation-r876w-1753430276) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:07Z" level=info msg="Workflow step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:07Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:08Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:08Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:08Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(1:2) (parameter-aggregation-r876w-2735603540) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:08Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(2:3) (parameter-aggregation-r876w-2177316838) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:08Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:08Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:08Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(5:6) (parameter-aggregation-r876w-1753430276) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:08Z" level=info msg="Workflow step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:10Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:10Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390) status Pending -> Running"
time="2020-02-15T10:42:10Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:10Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(1:2) (parameter-aggregation-r876w-2735603540) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:10Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(2:3) (parameter-aggregation-r876w-2177316838) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:10Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:10Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:10Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(5:6) (parameter-aggregation-r876w-1753430276) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:10Z" level=info msg="Workflow step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:10Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:11Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:11Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(5:6) (parameter-aggregation-r876w-1753430276) status Pending -> Running"
time="2020-02-15T10:42:11Z" level=info msg="Setting node parameter-aggregation-r876w[0].odd-or-even(2:3) (parameter-aggregation-r876w-2177316838) outputs"
time="2020-02-15T10:42:11Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(2:3) (parameter-aggregation-r876w-2177316838) status Pending -> Running"
time="2020-02-15T10:42:11Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) status Pending -> Running"
time="2020-02-15T10:42:11Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(1:2) (parameter-aggregation-r876w-2735603540) status Pending -> Running"
time="2020-02-15T10:42:11Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:11Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(1:2) (parameter-aggregation-r876w-2735603540) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:11Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(2:3) (parameter-aggregation-r876w-2177316838) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:11Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:11Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:11Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(5:6) (parameter-aggregation-r876w-1753430276) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:11Z" level=info msg="Workflow step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:11Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:12Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:12Z" level=info msg="Setting node parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390) outputs"
time="2020-02-15T10:42:12Z" level=info msg="Setting node parameter-aggregation-r876w[0].odd-or-even(5:6) (parameter-aggregation-r876w-1753430276) outputs"
time="2020-02-15T10:42:12Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(5:6) (parameter-aggregation-r876w-1753430276) status Running -> Succeeded"
time="2020-02-15T10:42:12Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(2:3) (parameter-aggregation-r876w-2177316838) status Running -> Succeeded"
time="2020-02-15T10:42:12Z" level=info msg="Setting node parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) outputs"
time="2020-02-15T10:42:12Z" level=info msg="Setting node parameter-aggregation-r876w[0].odd-or-even(1:2) (parameter-aggregation-r876w-2735603540) outputs"
time="2020-02-15T10:42:12Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(1:2) (parameter-aggregation-r876w-2735603540) status Running -> Succeeded"
time="2020-02-15T10:42:12Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:12Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:12Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:12Z" level=info msg="Workflow step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:12Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:13Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:13Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-1753430276 completed"
time="2020-02-15T10:42:13Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(0:1) (parameter-aggregation-r876w-3463065390) status Running -> Succeeded"
time="2020-02-15T10:42:13Z" level=info msg="Setting node parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) outputs"
time="2020-02-15T10:42:13Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) status Pending -> Running"
time="2020-02-15T10:42:13Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-2177316838 completed"
time="2020-02-15T10:42:13Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-2735603540 completed"
time="2020-02-15T10:42:13Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:13Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:13Z" level=info msg="Workflow step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:13Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:14Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:15Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-3463065390 completed"
time="2020-02-15T10:42:15Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-1753430276 completed"
time="2020-02-15T10:42:15Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(4:5) (parameter-aggregation-r876w-259735830) status Running -> Succeeded"
time="2020-02-15T10:42:15Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-2177316838 completed"
time="2020-02-15T10:42:15Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-2735603540 completed"
time="2020-02-15T10:42:15Z" level=info msg="Skipped pod parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:15Z" level=info msg="Workflow step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:15Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-3463065390 completed"
time="2020-02-15T10:42:16Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-259735830 completed"
time="2020-02-15T10:42:16Z" level=info msg="Updating node parameter-aggregation-r876w[0].odd-or-even(3:4) (parameter-aggregation-r876w-2272973104) status Running -> Succeeded"
time="2020-02-15T10:42:16Z" level=info msg="Step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) finished: 2020-02-15 10:42:16.630918224 +0000 UTC" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="StepGroup node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) initialized Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3463065390 are [parameter-aggregation-r876w-3463065390]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2735603540 are [parameter-aggregation-r876w-2735603540]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2177316838 are [parameter-aggregation-r876w-2177316838]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2272973104 are [parameter-aggregation-r876w-2272973104]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-259735830 are [parameter-aggregation-r876w-259735830]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-1753430276 are [parameter-aggregation-r876w-1753430276]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Skipping parameter-aggregation-r876w[1].divide-by-2(0:evenness:odd,num:1): when 'odd == even' evaluated false" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Skipped node parameter-aggregation-r876w[1].divide-by-2(0:evenness:odd,num:1) (parameter-aggregation-r876w-795838447) initialized Skipped (message: when 'odd == even' evaluated false)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Pod node parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022) initialized Pending" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Created pod: parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Skipping parameter-aggregation-r876w[1].divide-by-2(2:evenness:odd,num:3): when 'odd == even' evaluated false" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Skipped node parameter-aggregation-r876w[1].divide-by-2(2:evenness:odd,num:3) (parameter-aggregation-r876w-1608921575) initialized Skipped (message: when 'odd == even' evaluated false)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Pod node parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798) initialized Pending" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Created pod: parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Skipping parameter-aggregation-r876w[1].divide-by-2(4:evenness:odd,num:5): when 'odd == even' evaluated false" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Skipped node parameter-aggregation-r876w[1].divide-by-2(4:evenness:odd,num:5) (parameter-aggregation-r876w-2801704975) initialized Skipped (message: when 'odd == even' evaluated false)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Pod node parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278) initialized Pending" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Created pod: parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278)" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Workflow step group node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:16Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-2272973104 completed"
time="2020-02-15T10:42:17Z" level=info msg="Updating node parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798) message: PodInitializing"
time="2020-02-15T10:42:17Z" level=info msg="Updating node parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278) message: PodInitializing"
time="2020-02-15T10:42:17Z" level=info msg="Updating node parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022) message: PodInitializing"
time="2020-02-15T10:42:17Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Succeeded -> Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="Step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3463065390 are [parameter-aggregation-r876w-3463065390]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2735603540 are [parameter-aggregation-r876w-2735603540]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2177316838 are [parameter-aggregation-r876w-2177316838]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2272973104 are [parameter-aggregation-r876w-2272973104]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-259735830 are [parameter-aggregation-r876w-259735830]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-1753430276 are [parameter-aggregation-r876w-1753430276]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-259735830 completed"
time="2020-02-15T10:42:17Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="Workflow step group node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:17Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-2272973104 completed"
time="2020-02-15T10:42:18Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Succeeded -> Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="Step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3463065390 are [parameter-aggregation-r876w-3463065390]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2735603540 are [parameter-aggregation-r876w-2735603540]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2177316838 are [parameter-aggregation-r876w-2177316838]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2272973104 are [parameter-aggregation-r876w-2272973104]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-259735830 are [parameter-aggregation-r876w-259735830]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-1753430276 are [parameter-aggregation-r876w-1753430276]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="Workflow step group node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:18Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Succeeded -> Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="Step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3463065390 are [parameter-aggregation-r876w-3463065390]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2735603540 are [parameter-aggregation-r876w-2735603540]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2177316838 are [parameter-aggregation-r876w-2177316838]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2272973104 are [parameter-aggregation-r876w-2272973104]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-259735830 are [parameter-aggregation-r876w-259735830]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-1753430276 are [parameter-aggregation-r876w-1753430276]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="Workflow step group node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:43Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Succeeded -> Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="Step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3463065390 are [parameter-aggregation-r876w-3463065390]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2735603540 are [parameter-aggregation-r876w-2735603540]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2177316838 are [parameter-aggregation-r876w-2177316838]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2272973104 are [parameter-aggregation-r876w-2272973104]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-259735830 are [parameter-aggregation-r876w-259735830]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-1753430276 are [parameter-aggregation-r876w-1753430276]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="Workflow step group node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:44Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="Updating node parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278) status Pending -> Running"
time="2020-02-15T10:42:46Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Succeeded -> Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="Step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3463065390 are [parameter-aggregation-r876w-3463065390]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2735603540 are [parameter-aggregation-r876w-2735603540]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2177316838 are [parameter-aggregation-r876w-2177316838]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2272973104 are [parameter-aggregation-r876w-2272973104]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-259735830 are [parameter-aggregation-r876w-259735830]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-1753430276 are [parameter-aggregation-r876w-1753430276]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="Workflow step group node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:46Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="Updating node parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798) status Pending -> Running"
time="2020-02-15T10:42:47Z" level=info msg="Updating node parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022) status Pending -> Running"
time="2020-02-15T10:42:47Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Succeeded -> Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="Step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3463065390 are [parameter-aggregation-r876w-3463065390]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2735603540 are [parameter-aggregation-r876w-2735603540]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2177316838 are [parameter-aggregation-r876w-2177316838]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2272973104 are [parameter-aggregation-r876w-2272973104]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-259735830 are [parameter-aggregation-r876w-259735830]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-1753430276 are [parameter-aggregation-r876w-1753430276]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="Skipped pod parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278) creation: already exists" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="Workflow step group node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) not yet completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:47Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Processing workflow" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Updating node parameter-aggregation-r876w[1].divide-by-2(3:evenness:even,num:4) (parameter-aggregation-r876w-3942260798) status Running -> Succeeded"
time="2020-02-15T10:42:48Z" level=info msg="Updating node parameter-aggregation-r876w[1].divide-by-2(5:evenness:even,num:6) (parameter-aggregation-r876w-3436829278) status Running -> Succeeded"
time="2020-02-15T10:42:48Z" level=info msg="Updating node parameter-aggregation-r876w[1].divide-by-2(1:evenness:even,num:2) (parameter-aggregation-r876w-3705536022) status Running -> Succeeded"
time="2020-02-15T10:42:48Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Succeeded -> Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Step group node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="node parameter-aggregation-r876w[0] (parameter-aggregation-r876w-628139180) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3463065390 are [parameter-aggregation-r876w-3463065390]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2735603540 are [parameter-aggregation-r876w-2735603540]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2177316838 are [parameter-aggregation-r876w-2177316838]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2272973104 are [parameter-aggregation-r876w-2272973104]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-259735830 are [parameter-aggregation-r876w-259735830]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-1753430276 are [parameter-aggregation-r876w-1753430276]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Step group node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="node parameter-aggregation-r876w[1] (parameter-aggregation-r876w-695102561) finished: 2020-02-15 10:42:48.334515484 +0000 UTC" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="StepGroup node parameter-aggregation-r876w[2] (parameter-aggregation-r876w-3916155146) initialized Running" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-795838447 are [parameter-aggregation-r876w-795838447]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3705536022 are [parameter-aggregation-r876w-3705536022]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-1608921575 are [parameter-aggregation-r876w-1608921575]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3942260798 are [parameter-aggregation-r876w-3942260798]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-2801704975 are [parameter-aggregation-r876w-2801704975]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="SG Outbound nodes of parameter-aggregation-r876w-3436829278 are [parameter-aggregation-r876w-3436829278]" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Step group node parameter-aggregation-r876w[2] (parameter-aggregation-r876w-3916155146) successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="node parameter-aggregation-r876w[2] (parameter-aggregation-r876w-3916155146) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="node parameter-aggregation-r876w[2] (parameter-aggregation-r876w-3916155146) finished: 2020-02-15 10:42:48.334825977 +0000 UTC" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Step '<nil>' has no expanded child nodes" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Outbound nodes of parameter-aggregation-r876w is []" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="node parameter-aggregation-r876w (parameter-aggregation-r876w) phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="node parameter-aggregation-r876w (parameter-aggregation-r876w) finished: 2020-02-15 10:42:48.334903763 +0000 UTC" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Checking daemoned children of parameter-aggregation-r876w" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Updated phase Running -> Succeeded" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Marking workflow completed" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Checking daemoned children of " namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:48Z" level=info msg="Workflow update successful" namespace=default workflow=parameter-aggregation-r876w
time="2020-02-15T10:42:49Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-3942260798 completed"
time="2020-02-15T10:42:49Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-3436829278 completed"
time="2020-02-15T10:42:49Z" level=info msg="Labeled pod default/parameter-aggregation-r876w-3705536022 completed"
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by whynowy**
Fixes #2244

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [ ] Optional. I've added My organization is added to the README.
* [x] I've signed the CLA and required builds are green.

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -1704,14 +1704,12 @@ func hasOutputResultRef(name string, parentTmpl *wfv1.Template) bool {
 }
 
 // getStepOrDAGTaskName will extract the node from NodeStatus Name
-func getStepOrDAGTaskName(nodeName string, hasRetryStrategy bool) string {
+func getStepOrDAGTaskName(nodeName string) string {
 	if strings.Contains(nodeName, ".") {
 		name := nodeName[strings.LastIndex(nodeName, ".")+1:]
-		// Check retry scenario
```
Comment (whynowy) [inline workflow/controller/operator.go]: Not only `retry` scenario has `(`, but also `withItems` and `withParam`. Simply removed the `retry` condition check, and do it for all - This is based on the fact that neither template name nor step/DAG name is allowed to contain `(`.

**Comment by whynowy** [comment]
> Conditional approval: can you add new tests for this behavior? Perhaps from the reference issue?

Thanks! will add a functional test for that example.
