### PR TITLE
fix(test): fix TestWFDefaultWithWFTAndWf flakiness

### LINKED ISSUE #4501: "TestWFDefaultWithWFTAndWf" is flakey
Failed runs:

https://github.com/argoproj/argo/runs/1379089047

https://github.com/argoproj/argo/runs/1380263090

https://github.com/argoproj/argo/runs/1376428332

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #4501

### CODE REVIEW

File: workflow/controller/operator_wfdefault_test.go [hunk 1]
```diff
@@ -222,12 +222,11 @@ func TestWFDefaultWithWFTAndWf(t *testing.T) {
 	var resultSpec wfv1.WorkflowSpec
 	err := json.Unmarshal([]byte(storedSpecResult), &resultSpec)
 	assert.NoError(err)
-	cancel, controller := newControllerWithDefaults()
-	defer cancel()
-	controller.Config.WorkflowDefaults = wfDefault
-	_, err = controller.wfclientset.ArgoprojV1alpha1().WorkflowTemplates("default").Create(wft)
-	assert.NoError(err)
 	t.Run("SubmitSimpleWorkflowRef", func(t *testing.T) {
+		cancel, controller := newController(wft)
```
Comment (sarabala1979) [inline workflow/controller/operator_wfdefault_test.go:226]: The test was randomly failed with "workflow-template-submittable" not found.
Moved controller to local and pass WFT to the controller instead of making create api call

**Review by alexec — APPROVED** [review]
