### PR TITLE
fix(controller): Fix template resolution for step groups. Fixes #1868 

### LINKED ISSUE #1868: WorkflowTemplate withParam causes "template not found"
**What happened**:

A Workflow relying on a WorkflowTemplate using `withParam` fails with `template [template-name] not found`. The individual steps based on `[template-name]` succeed, but the Workflow as a whole fails.

**What you expected to happen**:

I expected the Workflow to finish successfully.

**How to reproduce it (as minimally and precisely as possible)**:

WorkflowTemplate:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test-template
spec:
  templates:
    - name: main
      steps:
        - - name: print-string
            template: print-string
            arguments:
              parameters:
               - name: letter
                 value: '{{item}}'
            withParam: '["x", "y", "z"]'
    - name: print-string
      inputs:
        parameters:
         - name: letter
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo {{inputs.parameters.letter}}"]
```

Workflow:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: test-
spec:
  entrypoint: main
  templates:
    - name: main
      templateRef:
        name: test-template
        template: main
```

**Anything else we need to know?**:

This appears to be a regression in 2.4.3. I can't reproduce the issue in 2.4.2.

**Environment**:
- Argo version: 2.4.3
- Kubernetes version: 1.16.4

**Other debugging information (if applicable)**:
- workflow result:
```
Name:                test-c6rc9
Namespace:           default
ServiceAccount:      default
Status:              Error
Message:             template print-string not found
Created:             Tue Dec 17 11:08:35 -0500 (1 minute ago)
Started:             Tue Dec 17 11:08:35 -0500 (1 minute ago)
Finished:            Tue Dec 17 11:08:40 -0500 (1 minute ago)
Duration:            5 seconds

STEP                                     PODNAME                DURATION  MESSAGE
 ⚠ test-c6rc9 (main)                                                      template print-string not found
 └-·-✔ print-string(0:x) (print-string)  test-c6rc9-49408079    2s
   ├-✔ print-string(1:y) (print-string)  test-c6rc9-2133394499  2s
   └-✔ print-string(2:z) (print-string)  test-c6rc9-166185159   2s
```
- executor logs:
N/A - no pods failed
- workflow-controller logs:
```
time="2019-12-17T16:08:26Z" level=warning msg="ConfigMap 'workflow-controller-configmap' does not have key 'config'"
time="2019-12-17T16:08:26Z" level=info msg="Workflow Controller (version: v2.4.3) starting"
time="2019-12-17T16:08:26Z" level=info msg="Workers: workflow: 8, pod: 8"
time="2019-12-17T16:08:26Z" level=info msg="Watch Workflow controller config map updates"
time="2019-12-17T16:08:26Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2019-12-17T16:08:26Z" level=info msg="Detected ConfigMap update. Updating the controller config."
time="2019-12-17T16:08:26Z" level=warning msg="ConfigMap 'workflow-controller-configmap' does not have key 'config'"
time="2019-12-17T16:08:27Z" level=info msg="Started workflow TTL worker"
time="2019-12-17T16:08:35Z" level=info msg="Processing workflow" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="Updated phase  -> Running" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="Steps node test-c6rc9 (test-c6rc9) initialized Pending" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="node test-c6rc9 (test-c6rc9) phase Pending -> Running" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="StepGroup node test-c6rc9[0] (test-c6rc9-1012822101) initialized Running" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="Pod node test-c6rc9[0].print-string(0:x) (test-c6rc9-49408079) initialized Pending" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="Created pod: test-c6rc9[0].print-string(0:x) (test-c6rc9-49408079)" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="Pod node test-c6rc9[0].print-string(1:y) (test-c6rc9-2133394499) initialized Pending" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="Created pod: test-c6rc9[0].print-string(1:y) (test-c6rc9-2133394499)" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="Pod node test-c6rc9[0].print-string(2:z) (test-c6rc9-166185159) initialized Pending" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="Created pod: test-c6rc9[0].print-string(2:z) (test-c6rc9-166185159)" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="Workflow step group node test-c6rc9[0] (test-c6rc9-1012822101) not yet completed" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:35Z" level=info msg="Workflow update successful" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:36Z" level=info msg="Processing workflow" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:36Z" level=info msg="Updating node test-c6rc9[0].print-string(0:x) (test-c6rc9-49408079) message: ContainerCreating"
time="2019-12-17T16:08:36Z" level=info msg="Updating node test-c6rc9[0].print-string(2:z) (test-c6rc9-166185159) message: ContainerCreating"
time="2019-12-17T16:08:36Z" level=info msg="Updating node test-c6rc9[0].print-string(1:y) (test-c6rc9-2133394499) message: ContainerCreating"
time="2019-12-17T16:08:36Z" level=info msg="Skipped pod test-c6rc9[0].print-string(0:x) (test-c6rc9-49408079) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:36Z" level=info msg="Skipped pod test-c6rc9[0].print-string(1:y) (test-c6rc9-2133394499) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:36Z" level=info msg="Skipped pod test-c6rc9[0].print-string(2:z) (test-c6rc9-166185159) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:36Z" level=info msg="Workflow step group node test-c6rc9[0] (test-c6rc9-1012822101) not yet completed" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:36Z" level=info msg="Workflow update successful" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Processing workflow" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Skipped pod test-c6rc9[0].print-string(0:x) (test-c6rc9-49408079) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Skipped pod test-c6rc9[0].print-string(1:y) (test-c6rc9-2133394499) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Skipped pod test-c6rc9[0].print-string(2:z) (test-c6rc9-166185159) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Workflow step group node test-c6rc9[0] (test-c6rc9-1012822101) not yet completed" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Processing workflow" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Updating node test-c6rc9[0].print-string(1:y) (test-c6rc9-2133394499) status Pending -> Running"
time="2019-12-17T16:08:37Z" level=info msg="Skipped pod test-c6rc9[0].print-string(0:x) (test-c6rc9-49408079) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Skipped pod test-c6rc9[0].print-string(1:y) (test-c6rc9-2133394499) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Skipped pod test-c6rc9[0].print-string(2:z) (test-c6rc9-166185159) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Workflow step group node test-c6rc9[0] (test-c6rc9-1012822101) not yet completed" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:37Z" level=info msg="Workflow update successful" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:38Z" level=info msg="Processing workflow" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:38Z" level=info msg="Updating node test-c6rc9[0].print-string(0:x) (test-c6rc9-49408079) status Pending -> Running"
time="2019-12-17T16:08:38Z" level=info msg="Updating node test-c6rc9[0].print-string(2:z) (test-c6rc9-166185159) status Pending -> Running"
time="2019-12-17T16:08:38Z" level=info msg="Skipped pod test-c6rc9[0].print-string(0:x) (test-c6rc9-49408079) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:38Z" level=info msg="Skipped pod test-c6rc9[0].print-string(1:y) (test-c6rc9-2133394499) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:38Z" level=info msg="Skipped pod test-c6rc9[0].print-string(2:z) (test-c6rc9-166185159) creation: already exists" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:38Z" level=info msg="Workflow step group node test-c6rc9[0] (test-c6rc9-1012822101) not yet completed" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:38Z" level=info msg="Workflow update successful" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:39Z" level=info msg="Processing workflow" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:39Z" level=info msg="Updating node test-c6rc9[0].print-string(0:x) (test-c6rc9-49408079) status Running -> Succeeded"
time="2019-12-17T16:08:39Z" level=info msg="Updating node test-c6rc9[0].print-string(2:z) (test-c6rc9-166185159) status Running -> Succeeded"
time="2019-12-17T16:08:39Z" level=info msg="Updating node test-c6rc9[0].print-string(1:y) (test-c6rc9-2133394499) status Running -> Succeeded"
time="2019-12-17T16:08:39Z" level=info msg="Step group node test-c6rc9[0] (test-c6rc9-1012822101) successful" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:39Z" level=info msg="node test-c6rc9[0] (test-c6rc9-1012822101) phase Running -> Succeeded" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:39Z" level=info msg="node test-c6rc9[0] (test-c6rc9-1012822101) finished: 2019-12-17 16:08:39.961871107 +0000 UTC" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:39Z" level=error msg="Mark error node test-c6rc9: template print-string not found\ngithub.com/argoproj/argo/errors.New\n\t/go/src/github.com/argoproj/argo/errors/errors.go:49\ngithub.com/argoproj/argo/errors.Errorf\n\t/go/src/github.com/argoproj/argo/errors/errors.go:55\ngithub.com/argoproj/argo/workflow/templateresolution.(*Context).GetTemplateByName\n\t/go/src/github.com/argoproj/argo/workflow/templateresolution/context.go:76\ngithub.com/argoproj/argo/workflow/templateresolution.(*Context).GetTemplate\n\t/go/src/github.com/argoproj/argo/workflow/templateresolution/context.go:108\ngithub.com/argoproj/argo/workflow/templateresolution.(*Context).resolveTemplateImpl\n\t/go/src/github.com/argoproj/argo/workflow/templateresolution/context.go:157\ngithub.com/argoproj/argo/workflow/templateresolution.(*Context).ResolveTemplate\n\t/go/src/github.com/argoproj/argo/workflow/templateresolution/context.go:128\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:107\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1195\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:216\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:304\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:230\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker-fm\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:39Z" level=info msg="node test-c6rc9 (test-c6rc9) phase Running -> Error" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:39Z" level=info msg="node test-c6rc9 (test-c6rc9) message: template print-string not found" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:39Z" level=info msg="node test-c6rc9 (test-c6rc9) finished: 2019-12-17 16:08:39.96214338 +0000 UTC" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:39Z" level=error msg="test-c6rc9 error in entry template execution: template print-string not found\ngithub.com/argoproj/argo/errors.New\n\t/go/src/github.com/argoproj/argo/errors/errors.go:49\ngithub.com/argoproj/argo/errors.Errorf\n\t/go/src/github.com/argoproj/argo/errors/errors.go:55\ngithub.com/argoproj/argo/workflow/templateresolution.(*Context).GetTemplateByName\n\t/go/src/github.com/argoproj/argo/workflow/templateresolution/context.go:76\ngithub.com/argoproj/argo/workflow/templateresolution.(*Context).GetTemplate\n\t/go/src/github.com/argoproj/argo/workflow/templateresolution/context.go:108\ngithub.com/argoproj/argo/workflow/templateresolution.(*Context).resolveTemplateImpl\n\t/go/src/github.com/argoproj/argo/workflow/templateresolution/context.go:157\ngithub.com/argoproj/argo/workflow/templateresolution.(*Context).ResolveTemplate\n\t/go/src/github.com/argoproj/argo/workflow/templateresolution/context.go:128\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeSteps\n\t/go/src/github.com/argoproj/argo/workflow/controller/steps.go:107\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).executeTemplate\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:1195\ngithub.com/argoproj/argo/workflow/controller.(*wfOperationCtx).operate\n\t/go/src/github.com/argoproj/argo/workflow/controller/operator.go:216\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).processNextItem\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:304\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:230\ngithub.com/argoproj/argo/workflow/controller.(*WorkflowController).runWorker-fm\n\t/go/src/github.com/argoproj/argo/workflow/controller/controller.go:171\nk8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:152\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:153\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/k8s.io/apimachinery/pkg/util/wait/wait.go:88\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:39Z" level=info msg="Workflow update successful" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:40Z" level=info msg="Processing workflow" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:40Z" level=info msg="Updated phase Running -> Error" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:40Z" level=info msg="Updated message  -> template print-string not found" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:40Z" level=info msg="Marking workflow completed" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:40Z" level=info msg="Checking daemoned children of " namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:40Z" level=info msg="Labeled pod default/test-c6rc9-2133394499 completed"
time="2019-12-17T16:08:41Z" level=info msg="Workflow update successful" namespace=default workflow=test-c6rc9
time="2019-12-17T16:08:41Z" level=info msg="Labeled pod default/test-c6rc9-49408079 completed"
time="2019-12-17T16:08:41Z" level=info msg="Labeled pod default/test-c6rc9-166185159 completed"
time="2019-12-17T16:08:42Z" level=info msg="Labeled pod default/test-c6rc9-166185159 completed"
time="2019-12-17T16:08:42Z" level=info msg="Labeled pod default/test-c6rc9-2133394499 completed"
time="2019-12-17T16:08:42Z" level=info msg="Labeled pod default/test-c6rc9-49408079 completed"
```

### PR DESCRIPTION
**Pull request by dtaniwaki**
Fixes #1868 #1876 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`. Why? for the release notes. 
* [x] Optional. I've added My organization is added to the README.
* [x] I've signed the CLA and required builds are green. 

I have fixed the wrong use of template context for step groups and also set a template scope in every node just in case it might be useful in the future.

### CODE REVIEW

**Comment by dtaniwaki** [comment]
I also fixed an error of parallelism check caused by template scope which can be reproduced with the following manifests.

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: nested-steps-with-params
spec:
  templates:
    - name: main
      steps:
        - - name: main-sub
            template: sub
    - name: sub
      steps:
        - - name: sub-print-string
            template: print-string
            arguments:
              parameters:
               - name: letter
                 value: '{{item}}'
            withParam: '["x", "y", "z"]'
    - name: print-string
      inputs:
        parameters:
         - name: letter
      container:
        image: alpine:3.6
        command: [sh, -c]
        args: ["echo {{inputs.parameters.letter}}"]
---
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: nested-steps-with-params-
spec:
  entrypoint: main
  templates:
    - name: main
      templateRef:
        name: nested-steps-with-params
        template: main
```

**Comment by dtaniwaki** [comment]
@alexec Added.

**Comment by ddseapy** [comment]
@alexec can this get merged before the release candidate?  If so should be able to help test the rc.

File: workflow/controller/workflowpod_test.go [hunk 1]
```diff
@@ -5,6 +5,7 @@ import (
 	"fmt"
 	"testing"
 
+	"github.com/argoproj/argo/workflow/common"
```
Comment (golangcibot) [inline workflow/controller/workflowpod_test.go]: File is not `goimports`-ed with -local github.com/argoproj/argo (from `goimports`)
```suggestion

```

File: workflow/controller/dag.go [hunk 2]
```diff
@@ -204,7 +204,7 @@ func (d *dagContext) hasMoreRetries(node *wfv1.NodeStatus) bool {
 func (woc *wfOperationCtx) executeDAG(nodeName string, tmplCtx *templateresolution.Context, templateScope string, tmpl *wfv1.Template, orgTmpl wfv1.TemplateHolder, boundaryID string) (*wfv1.NodeStatus, error) {
 	node := woc.getNodeByName(nodeName)
 	if node == nil {
-		node = woc.initializeExecutableNode(nodeName, wfv1.NodeTypeSteps, templateScope, tmpl, orgTmpl, boundaryID, wfv1.NodeRunning)
+		node = woc.initializeExecutableNode(nodeName, wfv1.NodeTypeDAG, templateScope, tmpl, orgTmpl, boundaryID, wfv1.NodeRunning)
```
Comment (alexec) [inline workflow/controller/dag.go]: I think this might fix #2056
