### PR TITLE
fix(controller): Do not panic if `woc.orig` in not hydrated. Fixes #3118

### LINKED ISSUE #3118: Fix panics
```
 controller | time="2020-05-27T23:58:02Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"test-cron-wf-basic-mj5bn\": StorageError: invalid object, Code: 4, Key: /registry/argoproj.io/workflows/argo/test-cron-wf-basic-mj5bn, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 73299ac8-7de4-48b5-b25d-ef1941ad8d2e, UID in object meta:  Conflict" namespace=argo workflow=test-cron-wf-basic-mj5bn
 controller | time="2020-05-27T23:58:02Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=argo workflow=test-cron-wf-basic-mj5bn
 controller | E0527 23:58:02.422603   19236 runtime.go:76] Observed a panic: original workflow is not hydrated
 controller | goroutine 271 [running]:
 controller | k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1628e80, 0x1ac7d80)
```

https://app.circleci.com/pipelines/github/argoproj/argo/4080/workflows/575ce35b-ed70-4512-bc31-2670d3fc51fc/jobs/25086/steps

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #3118

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -543,16 +543,17 @@ func (woc *wfOperationCtx) persistWorkflowSizeLimitErr(wfClient v1alpha1.Workflo
 	woc.markWorkflowError(err, true)
 	_, err = wfClient.Update(woc.wf)
 	if err != nil {
-		woc.log.Warnf("Error updating workflow: %v", err)
+		woc.log.Warnf("Error updating workflow with size error: %v", err)
```
Comment (alexec) [inline workflow/controller/operator.go:546]: this message is indistinguishable from another error, so tweak the message

Comment (simster7) [reply workflow/controller/operator.go:546]: This is great, makes finding errors much easier.
