### PR TITLE
fix(controller): Tolerate malformed resources. Fixes #3677

### LINKED ISSUE #3677: Make the controller tolerant to malformed resources
Currently, if you `kubectl apply -f malformed-cronworkflow.yaml` (or workflow template or cluster workflow template) we cannot list those resources, see #3666.

The workaround is delete the malformed resource. However, in a multi-tenant environment, this means a single malformed resource could other user's workflows.

# Analysis

@jessesuen you asked about whether or not having malformed resources (i.e. kubectl applied) would impact the controller. I loaded the malformed resources (1x cron workflow, 1x template template, 1x cluster workflow template, 1x workflow) and I could still create workflows directly.

Problems:

* I created another valid cron workflow - this did not schedule. 
* I could not create a workflow from a valid workflow template
* I could not create a workflow from a valid cluster workflow template.

These resolved after deleting the resource - I did not need to restart the container.

# Diagnostics

```
 controller | E0805 11:42:30.478792   33530 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1alpha1.CronWorkflow: v1alpha1.CronWorkflowList.Items: []v1alpha1.CronWorkflow: v1alpha1.CronWorkflow.Spec: v1alpha1.CronWorkflowSpec.WorkflowSpec: v1alpha1.WorkflowSpec.Arguments: v1alpha1.Arguments.Parameters: []v1alpha1.Parameter: decode slice: expect [ or n, but found {, error found in #10 byte of ...|ameters":{"someParam|..., bigger context ...|spec":{"workflowSpec":{"arguments":{"parameters":{"someParam":"Hello, world!"}}}}}],"kind":"CronWork|...
 controller | E0805 11:42:30.505177   33530 reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.5/tools/cache/reflector.go:105: Failed to list *v1alpha1.WorkflowTemplate: v1alpha1.WorkflowTemplateList.Items: v1alpha1.WorkflowTemplates: v1alpha1.WorkflowTemplate.Spec: v1alpha1.WorkflowTemplateSpec.WorkflowSpec: Arguments: v1alpha1.Arguments.Parameters: []v1alpha1.Parameter: decode slice: expect [ or n, but found {, error found in #10 byte of ...|ameters":{"someParam|..., bigger context ...|e81e75032120"},"spec":{"arguments":{"parameters":{"someParam":"Hello, world!"}}}}],"kind":"WorkflowT|...
```

https://github.com/kubernetes/kubernetes/issues/57705
https://github.com/argoproj/argo/issues/632

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #3677

# Summary

This PR replaces the standard Kubernetes informer with a dynamic informer, where the code ignores malformed resources.

 # Changes

The approach differs slightly for workflow templates and cron workflows. Cron is simpler to directly replace the informer with our own informer, keeping the changes simpler. With workflow templates, the code wraps the informers in a "tolerant" translation layer that ignores malformed resources for list operations.

# Testing

This is tested using e2e tests.

### CODE REVIEW

File: test/e2e/fixtures/when.go [hunk 1]
```diff
@@ -108,10 +105,17 @@ func (w *When) WaitForWorkflowCondition(test func(wf *wfv1.Workflow) bool, condi
 }
 
 func (w *When) waitForWorkflow(workflowName string, test func(wf *wfv1.Workflow) bool, condition string, timeout time.Duration) *When {
+	w.t.Helper()
 	start := time.Now()
-	logCtx := log.WithFields(log.Fields{"workflow": workflowName, "condition": condition, "timeout": timeout})
+
+	fieldSelector := ""
```
Comment (alexec) [inline test/e2e/fixtures/when.go:111]: This changes the behaviour of this func to make it more useful, you no longer need to know the name of the workflow you want to wait for. We alternatively wait for any `argo-e2e` workflow.

File: test/e2e/malformed_resources_test.go [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+		Then().
+		ExpectWorkflow(func(t *testing.T, metadata *metav1.ObjectMeta, status *wfv1.WorkflowStatus) {
+			assert.Equal(t, "wellformed", metadata.Labels[common.LabelKeyCronWorkflow])
+			assert.Equal(t, wfv1.NodeSucceeded, status.Phase)
+		})
+}
+
+func (s *MalformedResourcesSuite) TestMalformedWorkflowTemplate() {
+	s.Given().
+		Exec("kubectl", []string{"apply", "-f", "testdata/malformed/malformed-workflowtemplate.yaml"}, fixtures.NoError).
```
Comment (alexec) [inline test/e2e/malformed_resources_test.go:60]: I need to add a workflow that uses a malformed workflow template here

File: workflow/cron/controller.go [hunk 3]
```diff
@@ -141,17 +140,23 @@ func (cc *Controller) processNextCronItem() bool {
...
 
-	cronWf, ok := obj.(*v1alpha1.CronWorkflow)
+	un, ok := obj.(*unstructured.Unstructured)
 	if !ok {
-		log.Warnf("Key '%s' in index is not a CronWorkflow", key)
+		log.WithField("key", key).Errorf("malformed cluster workflow template: expected *unstructured.Unstructured, got %s", reflect.TypeOf(obj).Name())
+		return true
+	}
+	cronWf := &v1alpha1.CronWorkflow{}
+	err = runtime.DefaultUnstructuredConverter.FromUnstructured(un.Object, cronWf)
```
Comment (alexec) [inline workflow/cron/controller.go:149]: @jessesuen you asked how I dealt with malformed resources, in the case of cron we log the error and reject - this is what we already do

File: workflow/controller/informer/tolerant_cluster_workflow_template_informer.go [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+	extwfv1 "github.com/argoproj/argo/pkg/client/informers/externalversions/workflow/v1alpha1"
+	"github.com/argoproj/argo/pkg/client/listers/workflow/v1alpha1"
+)
+
+type tolerantClusterWorkflowTemplateInformer struct {
+	delegate informers.GenericInformer
+}
+
+// a drop-in replacement for `extwfv1.ClusterWorkflowTemplateInformer` that ignores malformed resources
+func NewTolerantClusterWorkflowTemplateInformer(dynamicInterface dynamic.Interface, defaultResync time.Duration) extwfv1.ClusterWorkflowTemplateInformer {
```
Comment (simster7) [inline workflow/controller/informer/tolerant_cluster_workflow_template_informer.go:23]: Not sure what makes this "tolerant". Can you explain a bit?

File: workflow/controller/informer/tolerant_workflow_template_namespace_lister.co.go [hunk 5]
```diff
@@ -0,0 +1,28 @@
+package informer
```
Comment (simster7) [inline workflow/controller/informer/tolerant_workflow_template_namespace_lister.co.go:1]: This file name ends in `.co.go`. Typo?

File: workflow/cron/controller.go [hunk 6]
```diff
@@ -39,9 +44,10 @@ type Controller struct {
 	wfInformer         cache.SharedIndexInformer
 	wfLister           util.WorkflowLister
 	wfQueue            workqueue.RateLimitingInterface
-	cronWfInformer     extv1alpha1.CronWorkflowInformer
+	cronWfInformer     informers.GenericInformer
```
Comment (simster7) [inline workflow/cron/controller.go:47]: Why is this change necessary?

File: workflow/cron/controller.go [hunk 7]
```diff
@@ -51,21 +57,15 @@ const (
...
-) *Controller {
+func NewCronController(wfclientset versioned.Interface, restConfig *rest.Config, dynamicInterface dynamic.Interface, namespace string, managedNamespace string, instanceId string, metrics *metrics.Metrics) *Controller {
 	return &Controller{
 		wfClientset:        wfclientset,
 		namespace:          namespace,
 		managedNamespace:   managedNamespace,
 		instanceId:         instanceId,
 		cron:               cron.New(),
 		restConfig:         restConfig,
+		dynamicInterface:   dynamicInterface,
```
Comment (simster7) [inline workflow/cron/controller.go:68]: What is this used for?

File: workflow/cron/controller.go (hunk 6 above)
Comment (alexec) [reply workflow/cron/controller.go:47]: The generated informers we currently use get "stuck" if a **malformed resource** in created. By "malformed" I mean that while they are correctly formatted as JSON or YAML, they cannot be the resource kind, e.g. because they have an array where an object is expected. This stops the inform working: the informer sits there repeatedly printing an error.

By using a **dynamic informer** (which is effectively the same as as an unstructured informer) we remove this problem and we control the parsing into the required type.

File: workflow/cron/controller.go (hunk 7 above)
Comment (alexec) [reply workflow/cron/controller.go:68]: for creating a generic informer

File: test/e2e/malformed_resources_test.go [hunk 8]
```diff
@@ -0,0 +1,114 @@
...
+func (s *MalformedResourcesSuite) TestMalformedWorkflowTemplateRef() {
+	s.Given().
+		Exec("kubectl", []string{"apply", "-f", "testdata/malformed/malformed-workflowtemplate.yaml"}, fixtures.NoError).
+		Exec("kubectl", []string{"apply", "-f", "testdata/wellformed/wellformed-workflow-with-malformed-workflow-template-ref.yaml"}, fixtures.NoError).
+		When().
+		WaitForWorkflow(15 * time.Second).
+		Then().
+		ExpectWorkflow(func(t *testing.T, metadata *metav1.ObjectMeta, status *wfv1.WorkflowStatus) {
+			assert.Equal(t, "wellformed", metadata.Name)
+			assert.Equal(t, wfv1.NodeError, status.Phase)
```
Comment (alexec) [inline test/e2e/malformed_resources_test.go:81]: we should also check the message makes sense to the user

File: test/e2e/malformed_resources_test.go [hunk 9]
```diff
@@ -0,0 +1,114 @@
...
+func (s *MalformedResourcesSuite) TestMalformedClusterWorkflowTemplateRef() {
+	s.Given().
+		Exec("kubectl", []string{"apply", "-f", "testdata/malformed/malformed-clusterworkflowtemplate.yaml"}, fixtures.NoError).
+		Exec("kubectl", []string{"apply", "-f", "testdata/wellformed/wellformed-workflow-with-malformed-cluster-workflow-template-ref.yaml"}, fixtures.NoError).
+		When().
+		WaitForWorkflow(15 * time.Second).
+		Then().
+		ExpectWorkflow(func(t *testing.T, metadata *metav1.ObjectMeta, status *wfv1.WorkflowStatus) {
+			assert.Equal(t, "wellformed", metadata.Name)
+			assert.Equal(t, wfv1.NodeError, status.Phase)
```
Comment (alexec) [inline test/e2e/malformed_resources_test.go:108]: we should also check the message makes sense to the user
