### PR TITLE
fix: Custom metrics are not recorded for DAG tasks Fixes #3872

### LINKED ISSUE #3872: Custom metrics are not recorded for DAG tasks.
## Summary 

**What happened?**
After slightly altering the [custom metrics example](https://github.com/argoproj/argo/blob/master/examples/custom-metrics.yaml) to use a DAG instead of steps, the custom metrics were no longer picked up by prometheus, specifically the `result_counter` metric. I used the following dag:

```yaml
# ...
dag:
  tasks:
    - name: random-int
      template: random-int
    - name: flakey
      template: flakey
      dependencies:
        - random-int
# ...
```

**What I expected to happen:**

The same behaviour as with a steps-based workflow: all recorded custom metrics should be visible in prometheus.

## Diagnostics

Running argo version 2.9.1

**Workflow:**
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-08-26T12:33:06Z"
  generateName: hello-world-
  generation: 10
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Succeeded
  name: hello-world-mgglj
  namespace: default
  resourceVersion: "41716344"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/default/workflows/hello-world-mgglj
  uid: 6403cb37-bb56-4bf7-9878-a9b3b5fa3792
spec:
  arguments: {}
  entrypoint: steps
  metrics:
    prometheus:
    - counter: null
      gauge:
        realtime: true
        value: '{{workflow.duration}}'
      help: Duration gauge by name
      histogram: null
      labels:
      - key: name
        value: workflow
      name: duration_gauge
      when: ""
  templates:
  - arguments: {}
    dag:
      tasks:
      - arguments: {}
        name: random-int
        template: random-int
      - arguments: {}
        dependencies:
        - random-int
        name: flakey
        template: flakey
    inputs: {}
    metadata: {}
    metrics:
      prometheus:
      - counter: null
        gauge:
          realtime: true
          value: '{{duration}}'
        help: Duration gauge by name
        histogram: null
        labels:
        - key: name
          value: steps
        name: duration_gauge
        when: ""
    name: steps
    outputs: {}
  - arguments: {}
    container:
      args:
      - RAND_INT=$((1 + RANDOM % 10)); echo $RAND_INT; echo $RAND_INT > /tmp/rand_int.txt
      command:
      - sh
      - -c
      image: alpine:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    metrics:
      prometheus:
      - counter: null
        gauge: null
        help: Value of the int emitted by random-int at step level
        histogram:
          buckets:
          - 2.01
          - 4.01
          - 6.01
          - 8.01
          - 10.01
          value: '{{outputs.parameters.rand-int-value}}'
        labels: null
        name: random_int_step_histogram
        when: '{{status}} == Succeeded'
      - counter: null
        gauge:
          realtime: true
          value: '{{duration}}'
        help: Duration gauge by name
        histogram: null
        labels:
        - key: name
          value: random-int
        name: duration_gauge
        when: ""
    name: random-int
    outputs:
      parameters:
      - globalName: rand-int-value
        name: rand-int-value
        valueFrom:
          path: /tmp/rand_int.txt
  - arguments: {}
    container:
      args:
      - import random; import sys; exit_code = random.choice([0, 1, 1]); sys.exit(exit_code)
      command:
      - python
      - -c
      image: python:alpine3.6
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    metrics:
      prometheus:
      - counter:
          value: "1"
        gauge: null
        help: Count of step execution by result status
        histogram: null
        labels:
        - key: name
          value: flakey
        - key: status
          value: '{{status}}'
        name: result_counter
        when: ""
    name: flakey
    outputs: {}
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-08-26T12:33:13Z"
  nodes:
    hello-world-mgglj:
      children:
      - hello-world-mgglj-870276649
      displayName: hello-world-mgglj
      finishedAt: "2020-08-26T12:33:13Z"
      id: hello-world-mgglj
      name: hello-world-mgglj
      outboundNodes:
      - hello-world-mgglj-1469680114
      phase: Succeeded
      startedAt: "2020-08-26T12:33:06Z"
      templateName: steps
      templateScope: local/hello-world-mgglj
      type: DAG
    hello-world-mgglj-870276649:
      boundaryID: hello-world-mgglj
      children:
      - hello-world-mgglj-1469680114
      displayName: random-int
      finishedAt: "2020-08-26T12:33:08Z"
      hostNodeName: gke-smec-adengine360-dev-long-running-417d9a7b-wvc6
      id: hello-world-mgglj-870276649
      name: hello-world-mgglj.random-int
      outputs:
        exitCode: "0"
        parameters:
        - globalName: rand-int-value
          name: rand-int-value
          value: "10"
          valueFrom:
            path: /tmp/rand_int.txt
      phase: Succeeded
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-08-26T12:33:06Z"
      templateName: random-int
      templateScope: local/hello-world-mgglj
      type: Pod
    hello-world-mgglj-1469680114:
      boundaryID: hello-world-mgglj
      displayName: flakey
      finishedAt: "2020-08-26T12:33:12Z"
      hostNodeName: gke-smec-adengine360-dev-long-running-417d9a7b-wvc6
      id: hello-world-mgglj-1469680114
      name: hello-world-mgglj.flakey
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 1
        memory: 1
      startedAt: "2020-08-26T12:33:10Z"
      templateName: flakey
      templateScope: local/hello-world-mgglj
      type: Pod
  outputs:
    parameters:
    - name: rand-int-value
      value: "10"
  phase: Succeeded
  resourcesDuration:
    cpu: 2
    memory: 2
  startedAt: "2020-08-26T12:33:06Z"
```

**Workflow controller logs:**
```
time="2020-08-26T12:33:06Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:06Z" level=info msg="Updated phase  -> Running" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:06Z" level=info msg="DAG node hello-world-mgglj initialized Running" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:06Z" level=info msg="All of node hello-world-mgglj.random-int dependencies [] completed" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:06Z" level=info msg="Pod node hello-world-mgglj-870276649 initialized Pending" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:06Z" level=info msg="Created pod: hello-world-mgglj.random-int (hello-world-mgglj-870276649)" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:06Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=41716229 workflow=hello-world-mgglj
time="2020-08-26T12:33:06Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:06Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=41716231 workflow=hello-world-mgglj
time="2020-08-26T12:33:06Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:07Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:07Z" level=info msg="Updating node hello-world-mgglj-870276649 message: ContainerCreating"
time="2020-08-26T12:33:07Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=41716240 workflow=hello-world-mgglj
time="2020-08-26T12:33:07Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:09Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:09Z" level=info msg="Setting node hello-world-mgglj-870276649 outputs"
time="2020-08-26T12:33:09Z" level=info msg="Updating node hello-world-mgglj-870276649 status Pending -> Running"
time="2020-08-26T12:33:09Z" level=info msg="setting workflow.outputs.parameters.rand-int-value: '10'" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:09Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=41716269 workflow=hello-world-mgglj
time="2020-08-26T12:33:09Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:10Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:10Z" level=info msg="Updating node hello-world-mgglj-870276649 status Running -> Succeeded"
time="2020-08-26T12:33:10Z" level=info msg="All of node hello-world-mgglj.flakey dependencies [random-int] completed" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:10Z" level=info msg="Pod node hello-world-mgglj-1469680114 initialized Pending" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:10Z" level=info msg="Created pod: hello-world-mgglj.flakey (hello-world-mgglj-1469680114)" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:10Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=41716298 workflow=hello-world-mgglj
time="2020-08-26T12:33:10Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:10Z" level=info msg="Labeled pod default/hello-world-mgglj-870276649 completed"
time="2020-08-26T12:33:10Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=41716300 workflow=hello-world-mgglj
time="2020-08-26T12:33:10Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:10Z" level=info msg="Updating node hello-world-mgglj-1469680114 message: ContainerCreating"
time="2020-08-26T12:33:10Z" level=info msg="Labeled pod default/hello-world-mgglj-870276649 completed"
time="2020-08-26T12:33:10Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=41716302 workflow=hello-world-mgglj
time="2020-08-26T12:33:10Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:11Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:11Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="Setting node hello-world-mgglj-1469680114 outputs"
time="2020-08-26T12:33:13Z" level=info msg="Updating node hello-world-mgglj-1469680114 status Pending -> Running"
time="2020-08-26T12:33:13Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=41716340 workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="Processing workflow" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="Updating node hello-world-mgglj-1469680114 status Running -> Succeeded"
time="2020-08-26T12:33:13Z" level=info msg="Outbound nodes of hello-world-mgglj set to [hello-world-mgglj-1469680114]" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="node hello-world-mgglj phase Running -> Succeeded" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="node hello-world-mgglj finished: 2020-08-26 12:33:13.339413822 +0000 UTC" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="Checking daemoned children of hello-world-mgglj" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="Updated phase Running -> Succeeded" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="Marking workflow completed" namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="Checking daemoned children of " namespace=default workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="Workflow update successful" namespace=default phase=Succeeded resourceVersion=41716344 workflow=hello-world-mgglj
time="2020-08-26T12:33:13Z" level=info msg="Labeled pod default/hello-world-mgglj-1469680114 completed"

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  Fixes #3872 
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

File: workflow/controller/dag.go [hunk 1]
```diff
@@ -314,6 +314,14 @@ func (woc *wfOperationCtx) executeDAGTask(dagCtx *dagContext, taskName string) {
...
 	task := dagCtx.GetTask(taskName)
 	if node != nil && node.Fulfilled() {
+		// Collect the completed task metrics
+		tmpl := woc.wf.GetTemplateByName(task.Template)
+		if tmpl != nil && tmpl.Metrics != nil {
+			if prevNodeStatus, ok := woc.preExecutionNodePhases[node.ID]; ok && !prevNodeStatus.Fulfilled() {
+				localScope, realTimeScope := woc.prepareMetricScope(node)
+				woc.computeMetrics(tmpl.Metrics.Prometheus, localScope, realTimeScope, false)
+			}
+		}
```
Comment (simster7) [inline workflow/controller/dag.go:324]: Not too sure this is the correct approach here. All metrics should be emitted within `executeTemplate`. If you notice for DAG or Steps, metrics are never emitted outside of it. Can you investigate why the current metric emission code in `executeTemplate` is not getting called in this case?

Comment (sarabala1979) [reply workflow/controller/dag.go:324]: In DAG flow, the Code is checking the `node.Fulfilled()` in  early-stage  (executeDAGTask) which prevents to execute the `executeTemplate` for completed the tasks.  
https://github.com/argoproj/argo/blob/5b5d2359ef9f573121fe6429e386f03dd8652ece/workflow/controller/dag.go#L316-L326

Options:
1.  We can remove the `return` statement on the above code. So, Completed node will travel to `executetemplate` But I am not sure whether it will break ay DAG flow
2. Above fix, Add metrics emission code in `node.Fulfilled()` check

File: workflow/controller/dag.go [hunk 2]
```diff
@@ -314,6 +314,14 @@ func (woc *wfOperationCtx) executeDAGTask(dagCtx *dagContext, taskName string) {
 	node := dagCtx.getTaskNode(taskName)
 	task := dagCtx.GetTask(taskName)
 	if node != nil && node.Fulfilled() {
+		// Collect the completed task metrics
+		tmpl := woc.wf.GetTemplateByName(task.Template)
```
Comment (simster7) [inline workflow/controller/dag.go:318]: Are we sure `task.Template` will always resolve? Even if it's a `templateRef`?

File: workflow/controller/dag.go [hunk 3]
```diff
@@ -314,6 +314,14 @@ func (woc *wfOperationCtx) executeDAGTask(dagCtx *dagContext, taskName string) {
...
+		if tmpl != nil && tmpl.Metrics != nil {
```
Comment (simster7) [inline workflow/controller/dag.go:319]: Shouldn't this be under the `if node.Completed() {` statement below?

File: workflow/controller/dag.go (hunk 1 above)
Comment (simster7) [reply workflow/controller/dag.go:324]: On second thought, I think we can keep this current fix for this issue.

File: workflow/controller/dag.go (hunk 2 above)
Comment (simster7) [reply workflow/controller/dag.go:318]: What if `task` is  actually an expanded task with a `withItems`?

Comment (sarabala1979) [reply workflow/controller/dag.go:318]: Good catch, we need to cover those usecases

File: workflow/controller/dag.go (hunk 3 above)
Comment (sarabala1979) [reply workflow/controller/dag.go:319]: it should cover the `Skipped` and `Omitted` status too.

**Review by simster7 — APPROVED** [review]

**Comment by YourPsychiatrist** [comment]
Thank you for taking care of the issue that fast! Highly appreciated

**Comment by YourPsychiatrist** [comment]
@simster7 or @alexec or someone else: Is this fix already scheduled for a specific release?

**Comment by simster7** [comment]
Backported to 2.10 and 2.11
