### PR TITLE
test: Maybe fix TestPendingRetryWorkflowWithRetryStrategy. Fixes #2446

### LINKED ISSUE #2446: Fix flakey test: `TestPendingRetryWorkflowWithRetryStrategy`
This test is failing master builds. It looks like the test is flakey rather than incorrect.

This test was introduced in #2385.

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the USERS.md.
* [ ] I've signed the CLA and required builds are green.

### CODE REVIEW

File: workflow/common/common.go [hunk 1]
```diff
@@ -62,7 +62,6 @@ const (
 	// LabelKeyWorkflowTemplate is a label applied to Workflows that are submitted from Workflowtemplate
 	LabelKeyWorkflowTemplate = workflow.WorkflowFullName + "/workflow-template"
 
-
```
Comment (alexec) [inline workflow/common/common.go]: `make lint`

File: test/e2e/functional_test.go [hunk 2]
```diff
@@ -227,12 +227,10 @@ spec:
 			b := wf.Status.Nodes.FindByDisplayName("b")
 			return wfv1.NodeSucceeded == a.Phase && wfv1.NodeSucceeded == b.Phase
 		}, "pods succeeded", 20*time.Second)
-	s.TearDownSuite()
```
Comment (alexec) [inline test/e2e/functional_test.go]: I think this is the problem

**Comment by alexec** [comment]
PLEASE DON'T WAIT FOR ME TO MERGE THIS ONE!
