### PR TITLE
fix(controller): Support exit handler on workflow templates.  Fixes #3737

### LINKED ISSUE #3737: `argo submit` from a WorkflowTemplate with default exit handler produces "invalid field in spec" error
### Use Case
I would like to use the `argo submit --from workflowtemplate/[template_name]` command to run ad hoc `Workflows` from an existing `WorkflowTemplate`.  This works fine.  I would also like to have a default exit handler defined in the workflow controller configmap so that all of my workflows have the same exit behavior, but then when I run `argo submit`, the resulting workflow fails immediately with:

```
Status:              Failed
Message:             invalid spec: OnExit is invalid field in spec if workflow referred WorkflowTemplate reference
```

### Steps to reproduce:
1. Install Argo Workflows 2.9.3
2. Edit the workflow controller configmap to add a default exit handler for all workflows:

```yaml
data:
  workflowDefaults: |
    spec:
      onExit: whalesay-exit
      templates:
        - name: whalesay-exit
          container:
          image: docker/whalesay
          command: [cowsay]
          args: ["hello from the default exit handler"]
```

3. Create `whalesay-template.yaml` using the sample `WorkflowTemplate` from [the Argo docs](https://argoproj.github.io/argo/workflow-templates/#workflowtemplate-spec):

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  entrypoint: whalesay-template     # Fields other than "arguments" and "templates" not supported in v2.4 - v2.6
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```

4. Submit the `WorkflowTemplate` to your Argo cluster:

```
$ argo template create whalesay-template.yaml
```

5. Use the `argo` CLI to create and watch a `Workflow` from the `WorkflowTemplate`:

```
$ argo submit --from workflowtemplate/workflow-template-submittable --watch
```

Expected behavior: The `Workflow` is successfully started.  (Note that it subsequently fails because the `default` service account has insufficient permissions, but that behavior is known and unrelated to this issue.)

Actual behavior: The `Workflow` fails immediately with the failure message shown above.  In version 2.9.5, this issue reproduces with a slightly different failure message:

```
Status:              Failed
Message:             invalid spec: Templates is invalid field in spec if workflow referred WorkflowTemplate reference
```

This behavior does not reproduce in version 2.8.2.

## Diagnostics

What version of Argo Workflows are you running?

2.9.3

Here's the resulting `Workflow` YAML:

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-08-11T17:39:31Z"
  generateName: workflow-template-submittable-
  generation: 2
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Failed
  name: workflow-template-submittable-5shzj
  namespace: default
  resourceVersion: "31356"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/default/workflows/workflow-template-submittable-5shzj
  uid: 9e84c2db-6b92-4824-bd7c-347b401cba0b
spec:
  arguments: {}
  onExit: whalesay-exit
  templates: null
  workflowTemplateRef:
    name: workflow-template-submittable
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-08-11T17:39:31Z"
  message: 'invalid spec: OnExit is invalid field in spec if workflow referred WorkflowTemplate
    reference'
  phase: Failed
  startedAt: "2020-08-11T17:39:31Z"
  storedTemplates:
    namespaced/workflow-template-submittable/whalesay-template:
      arguments: {}
      container:
        args:
        - '{{inputs.parameters.message}}'
        command:
        - cowsay
        image: docker/whalesay
        name: ""
        resources: {}
      inputs:
        parameters:
        - name: message
      metadata: {}
      name: whalesay-template
      outputs: {}
  storedWorkflowTemplateSpec:
    arguments:
      parameters:
      - name: message
        value: hello world
    entrypoint: whalesay-template
    templates:
    - arguments: {}
      container:
        args:
        - '{{inputs.parameters.message}}'
        command:
        - cowsay
        image: docker/whalesay
        name: ""
        resources: {}
      inputs:
        parameters:
        - name: message
      metadata: {}
      name: whalesay-template
      outputs: {}
```

Logs from the workflow controller:

```
time="2020-08-11T17:39:31Z" level=info msg="Processing workflow" namespace=default workflow=workflow-template-submittable-5shzj
time="2020-08-11T17:39:31Z" level=info msg="Updated phase  -> Running" namespace=default workflow=workflow-template-submittable-5shzj
time="2020-08-11T17:39:31Z" level=info msg="Updated phase Running -> Failed" namespace=default workflow=workflow-template-submittable-5shzj
time="2020-08-11T17:39:31Z" level=info msg="Updated message  -> invalid spec: OnExit is invalid field in spec if workflow referred WorkflowTemplate reference" namespace=default workflow=workflow-template-submittable-5shzj
time="2020-08-11T17:39:31Z" level=info msg="Marking workflow completed" namespace=default workflow=workflow-template-submittable-5shzj
time="2020-08-11T17:39:31Z" level=info msg="Checking daemoned children of " namespace=default workflow=workflow-template-submittable-5shzj
time="2020-08-11T17:39:31Z" level=info msg="Workflow update successful" namespace=default phase=Failed resourceVersion=31356 workflow=workflow-template-submittable-5shzj
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  Fixes #3737
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

File: workflow/controller/controller.go [hunk 1]
```diff
@@ -465,16 +465,6 @@ func (wfc *WorkflowController) processNextItem() bool {
 		return true
 	}
 
-	err = wfc.setWorkflowDefaults(wf)
```
Comment (sarabala1979) [inline workflow/controller/controller.go:468]: Moved LoadexecutionSpec

File: workflow/controller/operator.go [hunk 2]
```diff
@@ -89,11 +89,14 @@ type wfOperationCtx struct {
...
-	// This should usually be used instead `wf.Spec`, with two exceptions for user editable fields:
+
+	// execWf holds the Workflow for use in execution.
+	// In Normal workflow scenario: It holds copy of workflow object
+	// In Submit From WorkflowTemplate: It holds merged workflow with WorkflowDefault, Workflow and WorkflowTemplate
+	// 'execWf.Spec' should usually be used instead `wf.Spec`, with two exceptions for user editable fields:
 	// 1. `wf.Spec.Suspend`
 	// 2. `wf.Spec.Shutdown`
-	wfSpec *wfv1.WorkflowSpec
+	execWf *wfv1.Workflow
```
Comment (sarabala1979) [inline workflow/controller/operator.go:99]: Replaced to `Workflow` object for support `workflowdefault` templates

File: workflow/controller/operator.go [hunk 3]
```diff
@@ -2651,7 +2655,7 @@ func (woc *wfOperationCtx) createTemplateContext(scope wfv1.ResourceScope, resou
 	} else {
 		clusterWorkflowTemplateGetter = &templateresolution.NullClusterWorkflowTemplateGetter{}
 	}
-	ctx := templateresolution.NewContext(woc.controller.wftmplInformer.Lister().WorkflowTemplates(woc.wf.Namespace), clusterWorkflowTemplateGetter, woc.wf, woc.wf)
+	ctx := templateresolution.NewContext(woc.controller.wftmplInformer.Lister().WorkflowTemplates(woc.wf.Namespace), clusterWorkflowTemplateGetter, woc.execWf, woc.wf)
```
Comment (sarabala1979) [inline workflow/controller/operator.go:2658]: This context is resolving the templates for execution. If `WorkflowDefault` templates need to resolve for execution, we need to pass the merged workflow (execwf)  which has all execution templates.

File: workflow/controller/operator.go [hunk 4]
```diff
@@ -2936,6 +2940,11 @@ func (woc *wfOperationCtx) loadExecutionSpec() (wfv1.TemplateReferenceHolder, wf
 		if woc.controller.Config.WorkflowRestrictions.MustUseReference() {
 			return nil, executionParameters, fmt.Errorf("workflows must use workflowTemplateRef to be executed when the controller is in reference mode")
 		}
+		// Set the WorkflowDefaults from Configmap
+		err := woc.controller.setWorkflowDefaults(woc.wf)
```
Comment (sarabala1979) [inline workflow/controller/operator.go:2944]: moved SetWorkflowDefault here to handle all execution-related operations in one place and avoid the validation failure in 'WorkflowTemplateRef` scenario.

File: test/e2e/cli_test.go [hunk 5]
```diff
@@ -963,9 +963,6 @@ func (s *CLISuite) TestWorkflowLevelSemaphore() {
 			}
 		}).
 		SubmitWorkflow().
-		RunCli([]string{"get", "semaphore-wf-level-1"}, func(t *testing.T, output string, err error) {
```
Comment (sarabala1979) [inline test/e2e/cli_test.go:966]: This is another flaky condition.  I will work on enhance e2e to support waitcondition for `runcli`

Comment (sarabala1979) [reply test/e2e/cli_test.go:966]: In this test case, we need to submit two workflows and monitor the status of both
