### PR TITLE
fix: Corrects CRD and Swagger types. Fixes #3578

### LINKED ISSUE #3578: withItems incorrect type in full CRD
Is

```yaml
                            withItems:
                              items:
                                properties:
                                  value:
                                    format: byte
                                    type: string
                                required:
                                - value
                                type: object
                              type: array
```

Should be:

```yaml
                            withItems:
                              items:
                                type: object
                              type: array
```

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #3578

### CODE REVIEW

File: pkg/apis/workflow/v1alpha1/item.go [hunk 1]
```diff
@@ -20,11 +20,10 @@ const (
 // Item expands a single workflow step into multiple parallel steps
 // The value of Item can be a map, string, bool, or number
 //
-// +protobuf=true
 // +protobuf.options.(gogoproto.goproto_stringer)=false
-// +k8s:openapi-gen=true
+// +kubebuilder:validation:Type=object
```
Comment (alexec) [inline pkg/apis/workflow/v1alpha1/item.go:24]: this is actually not fixable, because `Item` can be anything, but `code-generator` mandates a single type only, we must choose the best/least worst type.

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 2]
```diff
@@ -338,8 +338,9 @@ func (s ShutdownStrategy) ShouldExecute(isOnExitPod bool) bool {
 	}
 }
 
+// +kubebuilder:validation:Type=array
```
Comment (alexec) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:341]: kubebuilder is too limited to correctly describe this type. We must choose a best option.

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 3]
```diff
@@ -379,7 +380,7 @@ func (p *ParallelSteps) UnmarshalJSON(value []byte) error {
 	return nil
 }
 
-func (p *ParallelSteps) MarshalJSON() ([]byte, error) {
+func (p ParallelSteps) MarshalJSON() ([]byte, error) {
```
Comment (alexec) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:383]: `MarshallJSON` MUST not be a pointer receiver.

**Comment by alexec** [comment]
Need @jessesuen to approve proto changes.

**Comment by alexec** [comment]
@jessesuen tried out v0.4.0 and got it working, but looks like IntellI does not support `Any` :(
