### PR TITLE
fix(security): Fixes an issue that allowed you to list archived workf…

### LINKED ISSUE #2049: Lack of permission check when listing archived workflows
There's no permission check when listing archived workflows, as a result, listing archived workflows with an unauthorized token also returns items.

### PR DESCRIPTION
**Pull request by alexec**
…lows you were not allowed to. Fixes #2049

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the README.
* [x] I've signed the CLA and required builds are green.

### CODE REVIEW

File: test/e2e/argo_server_test.go [hunk 1]
```diff
@@ -265,14 +265,32 @@ func (s *ArgoServerSuite) TestPermission() {
 			Status(403)
 	})
 
-	if s.Persistence.IsEnabled() {
+	// Simply wait 10 seconds for the wf to be completed
```
Comment (whynowy) [inline test/e2e/argo_server_test.go]: 30

File: test/e2e/argo_server_test.go [hunk 2]
```diff
@@ -286,61 +304,50 @@ func (s *ArgoServerSuite) TestPermission() {
...
-		s.Run("ListArchivedWFsBadToken", func(t *testing.T) {
-			s.e(t).GET("/api/v1/archived-workflows/"+uid).
-				WithQuery("listOptions.labelSelector", "argo-e2e").
+		s.Run("GetArchivedWFsBadToken", func(t *testing.T) {
+			s.e(t).GET("/api/v1/archived-workflows/" + uid).
 				Expect().
 				Status(403)
 		})
 
+		// Test get delete archived wf with bad token
```
Comment (whynowy) [inline test/e2e/argo_server_test.go]: Test delete xxxx

File: test/e2e/argo_server_test.go [hunk 3]
```diff
@@ -286,61 +304,50 @@ func (s *ArgoServerSuite) TestPermission() {
...
+		s.bearerToken = badToken
+		s.Run("DeleteArchivedWFsBadToken", func(t *testing.T) {
+			s.e(t).DELETE("/api/v1/archived-workflows/" + uid).
+				Expect().
+				Status(403)
+		})
+		// Test get delete archived wf with bad token
```
Comment (whynowy) [inline test/e2e/argo_server_test.go]: Test delete xxxx with good token
