### PR TITLE
fix(offload): Fix bug which deleted completed workflows. Fixes #2233

### LINKED ISSUE #2233: Offload GC deleting completed wf data

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the README.
* [ ] I've signed the CLA and required builds are green. 

Fixes #2233

### CODE REVIEW

File: workflow/controller/config_controller.go [hunk 1]
```diff
@@ -71,7 +71,15 @@ func (wfc *WorkflowController) updateConfig(cm *apiv1.ConfigMap) error {
 		}
 
 		wfc.session = session
-		wfc.offloadNodeStatusRepo = sqldb.NewOffloadNodeStatusRepo(session, persistence.GetClusterName(), tableName)
+		if persistence.NodeStatusOffload {
```
Comment (alexec) [inline workflow/controller/config_controller.go]: this condition was missing
