### PR TITLE
fix(controller): Prevent tasks with names staring with a digit to use `depends` . Fixes #4199

### LINKED ISSUE #4199: Workflow controller fails when dependencies are UUIDs
## Summary 

I set argo workflow dependencies to a UUID, which messes up the expr.eval https://github.com/antonmedv/expr package because it tries to parse the UUID as a number. 

## Diagnostics

What Kubernetes provider are you using? Local

What version of Argo Workflows are you running? 2.11.1
```
Name:         bje-5f7768fb5da4261220ffa1cc
Namespace:    bje-ns-5f7768fb5da4261220ffa1cc
Labels:       workflows.argoproj.io/completed=true
              workflows.argoproj.io/phase=Error
Annotations:  <none>
API Version:  argoproj.io/v1alpha1
Kind:         Workflow
Metadata:
  Creation Timestamp:  2020-10-02T17:52:59Z
  Generation:          6
  Resource Version:    174067
  Self Link:           /apis/argoproj.io/v1alpha1/namespaces/bje-ns-5f7768fb5da4261220ffa1cc/workflows/bje-5f7768fb5da4261220ffa1cc
  UID:                 71bf07f3-7937-489b-9f20-31951d965489
Spec:
  Arguments:
  Entrypoint:  bje-5f7768fb5da4261220ffa1cc-dag
  Image Pull Secrets:
    Name:                regcred-5f7768fb5da4261220ffa1cc
  Service Account Name:  argo-workflow
  Templates:
    Arguments:
    Container:
      Command:
        /opt/code/runme.sh
      Env:
        Name:   xxx
        Value:  http://192.168.0.6
      Image:    localhost:5000/managed-image:5f7768f75da4261220ffa1c5
      Name:     5f7768fb5da4261220ffa1c9
      Resources:
        Limits:
          Cpu:     1
          Memory:  104857600
        Requests:
          Cpu:     1
          Memory:  104857600
      Volume Mounts:
        Mount Path:  /mnt/output
        Name:        5f7768fb5da4261220ffa1c9-pvc
    Inputs:
    Metadata:
    Name:  5f7768fb5da4261220ffa1c9-container
    Outputs:
    Arguments:
    Container:
      Command:
        /opt/code/runme.sh
      Env:
        Name:   xxx
        Value:  http://192.168.0.6
      Image:    localhost:5000/managed-image:5f7768f75da4261220ffa1c5
      Name:     5f7768fb5da4261220ffa1cb
      Resources:
        Limits:
          Cpu:     1
          Memory:  104857600
        Requests:
          Cpu:     1
          Memory:  104857600
      Volume Mounts:
        Mount Path:  /mnt/output
        Name:        5f7768fb5da4261220ffa1cb-pvc
        Mount Path:  /mnt/input
        Name:        5f7768fb5da4261220ffa1c9-pvc
    Inputs:
    Metadata:
    Name:  5f7768fb5da4261220ffa1cb-container
    Outputs:
    Arguments:
    Dag:
      Tasks:
        Arguments:
        Name:      5f7768fb5da4261220ffa1c9
        Template:  5f7768fb5da4261220ffa1c9-container
        Arguments:
        Dependencies:
          5f7768fb5da4261220ffa1c9
        Name:      5f7768fb5da4261220ffa1cb
        Template:  5f7768fb5da4261220ffa1cb-container
    Inputs:
    Metadata:
    Name:  bje-5f7768fb5da4261220ffa1cc-dag
    Outputs:
  Volume Claim Templates:
    Metadata:
      Creation Timestamp:  <nil>
      Name:                5f7768fb5da4261220ffa1c9-pvc
    Spec:
      Access Modes:
        ReadWriteOnce
      Resources:
        Limits:
          Storage:  0
        Requests:
          Storage:  1073741824
    Status:
    Metadata:
      Creation Timestamp:  <nil>
      Name:                5f7768fb5da4261220ffa1cb-pvc
    Spec:
      Access Modes:
        ReadWriteOnce
      Resources:
        Limits:
          Storage:  0
        Requests:
          Storage:  1073741824
    Status:
Status:
  Conditions:
    Status:     True
    Type:       Completed
  Finished At:  2020-10-02T17:53:05Z
  Nodes:
    bje-5f7768fb5da4261220ffa1cc:
      Children:
        bje-5f7768fb5da4261220ffa1cc-1751792309
      Display Name:  bje-5f7768fb5da4261220ffa1cc
      Finished At:   2020-10-02T17:53:05Z
      Id:            bje-5f7768fb5da4261220ffa1cc
      Name:          bje-5f7768fb5da4261220ffa1cc
      Outbound Nodes:
        bje-5f7768fb5da4261220ffa1cc-2641006116
      Phase:           Error
      Started At:      2020-10-02T17:52:59Z
      Template Name:   bje-5f7768fb5da4261220ffa1cc-dag
      Template Scope:  local/bje-5f7768fb5da4261220ffa1cc
      Type:            DAG
    bje-5f7768fb5da4261220ffa1cc-1751792309:
      Boundary ID:  bje-5f7768fb5da4261220ffa1cc
      Children:
        bje-5f7768fb5da4261220ffa1cc-2641006116
      Display Name:    5f7768fb5da4261220ffa1c9
      Finished At:     2020-10-02T17:53:03Z
      Host Node Name:  node.localdev
      Id:              bje-5f7768fb5da4261220ffa1cc-1751792309
      Name:            bje-5f7768fb5da4261220ffa1cc.5f7768fb5da4261220ffa1c9
      Outputs:
        Exit Code:  0
      Phase:        Succeeded
      Resources Duration:
        Cpu:           3
        Memory:        3
      Started At:      2020-10-02T17:52:59Z
      Template Name:   5f7768fb5da4261220ffa1c9-container
      Template Scope:  local/bje-5f7768fb5da4261220ffa1cc
      Type:            Pod
    bje-5f7768fb5da4261220ffa1cc-2641006116:
      Boundary ID:   bje-5f7768fb5da4261220ffa1cc
      Display Name:  5f7768fb5da4261220ffa1cb
      Finished At:   2020-10-02T17:53:05Z
      Id:            bje-5f7768fb5da4261220ffa1cc-2641006116
      Message:       unable to evaluate expression '(5f7768fb5da4261220ffa1c9.Succeeded || 5f7768fb5da4261220ffa1c9.Skipped || 5f7768fb5da4261220ffa1c9.Daemoned)': bad number syntax: "5f" (1:4)
 | (5f7768fb5da4261220ffa1c9.Succeeded || 5f7768fb5da4261220ffa1c9.Skipped || 5f7768fb5da4261220ffa1c9.Daemoned)
 | ...^
      Name:            bje-5f7768fb5da4261220ffa1cc.5f7768fb5da4261220ffa1cb
      Phase:           Error
      Started At:      2020-10-02T17:53:05Z
      Template Name:   5f7768fb5da4261220ffa1cb-container
      Template Scope:  local/bje-5f7768fb5da4261220ffa1cc
      Type:            Skipped
  Phase:               Error
  Resources Duration:
    Cpu:       3
    Memory:    3
  Started At:  2020-10-02T17:52:59Z
Events:        <none>

```

```
time="2020-10-02T17:38:27Z" level=info msg="Skipped pod bje-5f7765735da42616dd60bae9.5f7765735da42616dd60bae3 (bje-5f7765735da42616dd60bae9-127836785) creation: already exists" namespace=bje-ns-5f7765735da42616dd60bae9 podPhase=Pending wor
kflow=bje-5f7765735da42616dd60bae9
time="2020-10-02T17:38:34Z" level=info msg="Processing workflow" namespace=bje-ns-5f7765735da42616dd60bae9 workflow=bje-5f7765735da42616dd60bae9
time="2020-10-02T17:38:34Z" level=info msg="Setting node bje-5f7765735da42616dd60bae9-127836785 outputs"
time="2020-10-02T17:38:34Z" level=info msg="Updating node bje-5f7765735da42616dd60bae9-127836785 status Pending -> Running"
time="2020-10-02T17:38:34Z" level=info msg="Workflow update successful" namespace=bje-ns-5f7765735da42616dd60bae9 phase=Running resourceVersion=172157 workflow=bje-5f7765735da42616dd60bae9
time="2020-10-02T17:38:35Z" level=info msg="Processing workflow" namespace=bje-ns-5f7765735da42616dd60bae9 workflow=bje-5f7765735da42616dd60bae9
time="2020-10-02T17:38:35Z" level=info msg="Updating node bje-5f7765735da42616dd60bae9-127836785 status Running -> Succeeded"
time="2020-10-02T17:38:35Z" level=info msg="Skipped node bje-5f7765735da42616dd60bae9-178169642 initialized Error (message: unable to evaluate expression '(5f7765735da42616dd60bae3.Succeeded || 5f7765735da42616dd60bae3.Skipped || 5f7765735da42616dd60bae3.Daemoned)': bad number syntax: \"5f\" (1:4)\n | (5f7765735da42616dd60bae3.Succeeded || 5f7765735da42616dd60bae3.Skipped || 5f7765735da42616dd60bae3.Daemoned)\n | ...^)" namespace=bje-ns-5f7765735da42616dd60bae9 workflow=bje-5f7765735da42616dd60bae9
time="2020-10-02T17:38:35Z" level=info msg="Skipped node bje-5f7765735da42616dd60bae9-194947261 initialized Error (message: unable to evaluate expression '(5f7765735da42616dd60bae6.Succeeded || 5f7765735da42616dd60bae6.Skipped || 5f7765735da42616dd60bae6.Daemoned)': bad number syntax: \"5f\" (1:4)\n | (5f7765735da42616dd60bae6.Succeeded || 5f7765735da42616dd60bae6.Skipped || 5f7765735da42616dd60bae6.Daemoned)\n | ...^)" namespace=bje-ns-5f7765735da42616dd60bae9 workflow=bje-5f7765735da42616dd60bae9

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by simster7**
Fixes: https://github.com/argoproj/argo/issues/4199

Trivial fix, seems the safest as the workaround (prepend tasks names with any non-digit character) seems trivial.

### CODE REVIEW

File: workflow/validate/validate_dag_test.go [hunk 1]
```diff
@@ -689,3 +689,57 @@ func TestDependsAndContinueOn(t *testing.T) {
...
+        image: alpine:3.7
+        command:
+          - sh
+          - -c
+          - exit 1
+`
+
+func TestDAGDependsDigit(t *testing.T) {
+	_, err := validate(dagDependsDigit)
+	if assert.NotNil(t, err) {
```
Comment (alexec) [inline workflow/validate/validate_dag_test.go:742]: minor: assert.NoError

nice guard condition

**Review by alexec — APPROVED** [review]
