### PR TITLE
fix: Remove active wf from Cron when deleted

### LINKED ISSUE #2297: CronWorkflow status active when no workflows are running
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
CronWorkflow has active pods on its status after deleting a running pod in the UI. This conflicts with `concurrencyPolicy: "Forbid"` and prevents further Workflows to run.

**What you expected to happen**:
Expected that CronWorkflow didn't have a status active.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a CronWorkflow:
```
metadata:
  name: lovely-rhino
  namespace: default
spec:
  schedule: '30 11 * * *'
  concurrencyPolicy: "Forbid"
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        retryStrategy:
          limit: 3
        container:
          name: main
          image: 'docker/whalesay:latest'
          command:
            - cowsay
          args:
            - hello world
```
2. Wait for the Workflow to start
3. Delete the running Workflow on the UI
4. CronWorkflow has an active Workflow (which was deleted) and prevents further Workflows to be scheduled due to the `concurrencyPolicy: "Forbid"`:
```
metadata:
  name: lovely-rhino
  namespace: default
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/default/cronworkflows/lovely-rhino
  uid: e41232e1-56f9-11ea-beaa-067fd2a748c8
  resourceVersion: '8350290'
  generation: 3
  creationTimestamp: '2020-02-24T11:36:26Z'
spec:
  workflowSpec:
    templates:
      - name: whalesay
        inputs: {}
        outputs: {}
        metadata: {}
        container:
          name: main
          image: 'docker/whalesay:latest'
          command:
            - cowsay
          args:
            - hello world
          resources: {}
        retryStrategy:
          limit: 3
    entrypoint: whalesay
    arguments: {}
  schedule: 38 11 * * *
  concurrencyPolicy: Forbid
status:
  active:
    - kind: Workflow
      namespace: default
      name: lovely-rhino-qtpcf
      uid: 1c0370a7-56fa-11ea-b6f9-0282aa35f482
      resourceVersion: '8350258'
  lastScheduledTime: '2020-02-24T11:38:00Z'
```

**Anything else we need to know?**:
N/A

**Environment**:
- Argo version:
```
$ argo version
2.6.0-rc2
```
- Kubernetes version :
```
$ kubectl version -o yaml
clientVersion:
  buildDate: "2019-06-19T16:40:16Z"
  compiler: gc
  gitCommit: e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529
  gitTreeState: clean
  gitVersion: v1.15.0
  goVersion: go1.12.5
  major: "1"
  minor: "15"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-12-22T23:14:11Z"
  compiler: gc
  gitCommit: c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2
  gitTreeState: clean
  gitVersion: v1.14.9-eks-c0eccc
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by simster7**
Fixes #2297

### CODE REVIEW

File: workflow/cron/controller.go [hunk 1]
```diff
@@ -187,6 +189,17 @@ func (cc *Controller) processNextWorkflowItem() bool {
 		return true
 	}
 
+	// If the workflow was deleted, recover the workflow object from the cache
+	if !wfExists {
+		if cachedObj, ok := cc.deletedObjectCache[key.(string)]; ok {
```
Comment (alexec) [inline workflow/cron/controller.go]: Can this solution cannot survive controller restart?

**Comment by simster7** [comment]
@alexec After much thought, I reworked the logic so that deleted workflows are reconciled at run time. This solution is no longer memory-dependent.

Ready for another review

File: workflow/cron/operator.go [hunk 2]
```diff
@@ -159,19 +169,45 @@ func (woc *cronWfOperationCtx) runOutstandingWorkflows() error {
...
-			}
+	woc.removeFromActiveList(wf.ObjectMeta.UID)
+	err := woc.persistUpdate()
+	if err != nil {
+		log.Errorf("Unable to update CronWorkflow '%s': %s", woc.cronWf.Name, err)
+	}
+}
+
+func (woc *cronWfOperationCtx) removeFromActiveList(uid types.UID) {
+	var newActive []v12.ObjectReference
```
Comment (alexec) [inline workflow/cron/operator.go]: `v12`?

Comment (alexec) [reply workflow/cron/operator.go]: can we fix this to `corev1`?

File: workflow/cron/controller.go [hunk 3]
```diff
@@ -84,6 +85,8 @@ func (cc *Controller) Run(ctx context.Context) {
 	})
 	cc.addWorkflowInformerHandler()
 
+	cc.wfLister = util.NewWorkflowLister(cc.wfInformer)
```
Comment (alexec) [inline workflow/cron/controller.go]: check to see if this informer contains both completed and in-complete workflows -  I seem to recall it contained only in-complete versions

File: workflow/cron/operator.go [hunk 4]
```diff
@@ -159,19 +169,45 @@ func (woc *cronWfOperationCtx) runOutstandingWorkflows() error {
...
-		if objectRef.UID == wf.ObjectMeta.UID {
-			woc.cronWf.Status.Active = append(woc.cronWf.Status.Active[:i], woc.cronWf.Status.Active[i+1:]...)
-			err := woc.persistUpdate()
-			if err != nil {
-				log.Errorf("Unable to update CronWorkflow '%s': %s", woc.cronWf.Name, err)
-			}
+	woc.removeFromActiveList(wf.ObjectMeta.UID)
+	err := woc.persistUpdate()
+	if err != nil {
+		log.Errorf("Unable to update CronWorkflow '%s': %s", woc.cronWf.Name, err)
```
Comment (alexec) [inline workflow/cron/operator.go]: minor - should be structured logging

File: workflow/cron/operator.go (hunk 2 above)
Comment (simster7) [reply workflow/cron/operator.go]: Done

File: workflow/cron/controller.go (hunk 3 above)
Comment (simster7) [reply workflow/cron/controller.go]: The informer options are defined right above and contains all workflows with `LabelKeyCronWorkflow`

File: workflow/cron/operator.go (hunk 4 above)
Comment (simster7) [reply workflow/cron/operator.go]: Perhaps do this in a separate PR? A significant amount of logging statements would have to change, and I think it would be better to do them all at once
