### PR TITLE
fix(offloading): Correctly deleted offloaded data. Fixes #2206

### LINKED ISSUE #2206: Offload GC is not deleted old data
We should not be doing `select *`:
```
workflow-controller-6dbf4dcf4d-fktqs workflow-controller 	Query:          SELECT * FROM "argo_workflows" WHERE ("clustername" = $1 AND "namespace" = $2 AND updatedat < current_timestamp - interval '5' minute)
workflow-controller-6dbf4dcf4d-fktqs workflow-controller 	Arguments:      []interface {}{"default", "argo"}
```
Deleting uid=""????

```
workflow-controller-6dbf4dcf4d-fktqs workflow-controller time="2020-02-11T00:51:20Z" level=info msg="Deleting old UIDs that are not live" len_old_records=60 len_wfs=0
workflow-controller-6dbf4dcf4d-fktqs workflow-controller time="2020-02-11T00:51:20Z" level=debug msg="Deleting offloaded nodes" uid= version=
workflow-controller-6dbf4dcf4d-fktqs workflow-controller 2020/02/11 00:51:20 
workflow-controller-6dbf4dcf4d-fktqs workflow-controller 	Session ID:     00049
workflow-controller-6dbf4dcf4d-fktqs workflow-controller 	Query:          DELETE FROM "argo_workflows" WHERE ("clustername" = $1 AND "uid" = $2 AND "version" = $3)
workflow-controller-6dbf4dcf4d-fktqs workflow-controller 	Arguments:      []interface {}{"default", "", ""}
workflow-controller-6dbf4dcf4d-fktqs workflow-controller 	Rows affected:  0
workflow-controller-6dbf4dcf4d-fktqs workflow-controller 	Time taken:     0.00219s
workflow-controller-6dbf4dcf4d-fktqs workflow-controller 	Context:        context.Background
workflow-controller-6dbf4dcf4d-fktqs workflow-controller 
```

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [x] Optional. I've added My organization is added to the README.
* [x] I've signed the CLA and required builds are green. 

 Fixes #2206

### CODE REVIEW

File: persist/sqldb/offload_node_status_repo.go [hunk 1]
```diff
@@ -182,6 +186,12 @@ func (wdc *nodeOffloadRepo) ListOldOffloads(namespace string) ([]UUIDVersion, er
 }
 
 func (wdc *nodeOffloadRepo) Delete(uid, version string) error {
+	if uid == "" {
```
Comment (alexec) [inline persist/sqldb/offload_node_status_repo.go]: checks to make sure that can't happen again

File: persist/sqldb/offload_node_status_repo.go [hunk 2]
```diff
@@ -145,7 +147,8 @@ func (wdc *nodeOffloadRepo) List(namespace string) (map[UUIDVersion]wfv1.Nodes,
 	log.WithFields(log.Fields{"namespace": namespace}).Debug("Listing offloaded nodes")
 	var records []nodesRecord
 	err := wdc.session.
-		SelectFrom(wdc.tableName).
```
Comment (alexec) [inline persist/sqldb/offload_node_status_repo.go]: we should never use `SelectFrom` it always does `SELECT *`

File: workflow/controller/controller.go [hunk 3]
```diff
@@ -268,6 +268,7 @@ func (wfc *WorkflowController) periodicWorkflowGarbageCollector(stopCh <-chan st
 				oldRecords, err := wfc.offloadNodeStatusRepo.ListOldOffloads(wfc.GetManagedNamespace())
 				if err != nil {
 					log.WithField("err", err).Error("Failed to list old offloaded nodes")
+					return
```
Comment (alexec) [inline workflow/controller/controller.go]: bonus fix

File: persist/sqldb/offload_node_status_repo.go [hunk 4]
```diff
@@ -14,7 +14,8 @@ import (
 )
 
 type UUIDVersion struct {
-	UID, Version string
+	UID     string `db:"uid"`
```
Comment (alexec) [inline persist/sqldb/offload_node_status_repo.go]: these were all empty strings

File: workflow/controller/controller.go (hunk 3 above)
Comment (sarabala1979) [inline workflow/controller/controller.go]: This will exit the loop. if there is any intermediate network issue or DB issue, `return` will exit the loop with an error message and stop the node status GC.
 Do you think the following behavior will fit for this scenario? 
 1. Implement ExponentialBackoff for the Query inside the loop instead of return
2. Restart the controller so it will check the DB connectivity while start.

Comment (alexec) [reply workflow/controller/controller.go]: This fix is incorrect - should be continue - good spot. I'm not sure about back off etc. Adds a massive level of testing complexity for little benefit.

Comment (sarabala1979) [reply workflow/controller/controller.go]: how will the application behave if `wfc.offloadNodeStatusRepo.ListOldOffloads`  return the err?

Comment (alexec) [reply workflow/controller/controller.go]: if will exit, I think this is incorrect, should continue (same applies for other lines) - I will fix
