### PR TITLE
fix(ui): Show "waiting for data" while waiting for pod logs. Fixes #3916

### LINKED ISSUE #3916: Pod did not output any logs
## Summary 

UI always flashes "Pod did not output any logs." before showing logs.

This should actually say something like "Attempting to load logs." unless there is a way to determine definitively that there are actually no logs.

## Diagnostics

2.10.0

### PR DESCRIPTION
**Pull request by dcherman**
Fixes #3916

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

**Comment by dcherman** [comment]
It doesn't look like the UI has any form of testing set up.  Would you be interested in having Jest set up as part of this?  Could add a snapshot test for this particular bug pretty easily.

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 1]
```diff
@@ -99,21 +100,30 @@ export class WorkflowLogsViewer extends React.Component<WorkflowLogsViewerProps,
...
+                });
             },
             error => {
-                this.setState({error});
+                this.setState({error, loaded: true});
             }
         );
     }
 
+    private podHasNoLogs() {
```
Comment (dcherman) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:119]: I'm using type inference here rather than explicitly specifying that the return type is `boolean` since typescript can infer that; is this acceptable here?

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 2]
```diff
@@ -99,21 +100,30 @@ export class WorkflowLogsViewer extends React.Component<WorkflowLogsViewerProps,
...
-                        log.split('\n').forEach(line => {
-                            state.lines.push(line);
-                        });
-                        return state;
-                    });
-                }
+                this.setState(state => {
+                    const newState = {...state, loaded: true};
+
+                    if (log) {
```
Comment (dcherman) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:106]: Noting that I did not have this `if` statement in a previous version, and I had this fail with `undefined has no method split`.  That means the typings for this callback fn are wrong since it should likely be `string | undefined` rather than `string` so typescript can catch those types of errors.  Either that or the code emitting values to this stream should be emitting `""` rather than `undefined`.

Comment (alexec) [reply ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:106]: I did not know this.

**Comment by alexec** [comment]
LGTM

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
An aside note, there is a bug in this control if the step fails and does not upload logs. 

See #4117
