### PR TITLE
Do not resolve remote templates in lint

### LINKED ISSUE #1662: argo lint requires kubeconfig
**BUG REPORT**:

**What happened**:
argo lint failed in my CI environment

**What you expected to happen**:
argo lint to succeed

**How to reproduce it (as minimally and precisely as possible)**:
Fails:
```
curl --silent https://raw.githubusercontent.com/argoproj/argo/master/examples/coinflip.yaml > wf.yaml ; argo lint wf.yaml ; rm wf.yaml
```

Succeeds:
```
curl --silent https://raw.githubusercontent.com/argoproj/argo/master/examples/coinflip.yaml > wf.yaml ; argo --kubeconfig=config lint wf.yaml ; rm wf.yaml
```

**Environment**:
- Argo version:
2.4.1
- Kubernetes version :
```
clientVersion:
  buildDate: "1970-01-01T00:00:01Z"
  compiler: gc
  gitCommit: 5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0
  gitTreeState: archive
  gitVersion: v1.14.3
  goVersion: go1.12.7
  major: "1"
  minor: "14"
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-08-21T22:32:40Z"
  compiler: gc
  gitCommit: 5047edce664593832e9b889e447ac75ab104f527
  gitTreeState: clean
  gitVersion: v1.14.6-eks-5047ed
  goVersion: go1.12.9
  major: "1"
  minor: 14+
  platform: linux/amd64
```

**Context**:
I understand the difficulty in linting Workflows which have been decomposed into WorkflowTemplates, but I'm not sure a `lint` should attempt to resolve Kubernetes resources. 

Perhaps an additional command that does a full `validate` or an option to `lint` to prevent it from connecting to a cluster would be more appropriate.

A `lint` in my opinion should purely validate the structure or schema of the individual files, not the entire graph if it happens to contain remote resources in a cluster.

### PR DESCRIPTION
**Pull request by dtaniwaki**
Fixes #1662

I created a concept of `local template resolution context` so lint validation rejects remote template resolutions unless passed a flag.

Here's the lint test result with this fix.

```
$ argo lint examples/workflow-template/steps.yaml
FATA[0000] examples/workflow-template/steps.yaml: templates.hello-hello-hello.steps[0].hello1 failed to get a remote template in local context

$ argo lint --resolve-remote-templates examples/workflow-template/steps.yaml
Workflow manifests validated

$ argo lint --kubeconfig=config examples/workflow-template/steps.yaml
FATA[0000] examples/workflow-template/steps.yaml: templates.hello-hello-hello.steps[0].hello1 failed to get a remote template in local context

$ argo lint --kubeconfig=config --resolve-remote-templates examples/workflowtemplate/steps.yaml
FATA[0000] invalid configuration: no configuration has been provided

$ argo template lint examples/workflow-template/tem
plates.yaml
FATA[0000] examples/workflow-template/templates.yaml: templates.whalesay-inner-template failed to get a remote template in local context

$ argo template lint --resolve-remote-templates exa
mples/workflow-template/templates.yaml
WorkflowTemplate manifests validated

$ argo template lint --kubeconfig=config examples/workflow-template/templates.yaml
FATA[0000] examples/workflow-template/templates.yaml: templates.whalesay-inner-template failed to get a remote template in local context

$ argo template lint --kubeconfig=config --resolve-remote-templates examples/workflow-template/templates.yaml
FATA[0000] invalid configuration: no configuration has been provided
```

### CODE REVIEW

File: cmd/argo/commands/template/lint.go [hunk 1]
```diff
@@ -57,9 +63,10 @@ func NewLintCommand() *cobra.Command {
 			if err != nil {
 				log.Fatal(err)
 			}
-			fmt.Printf("Workflow manifests validated\n")
+			fmt.Printf("WorkflowTemplate manifests validated\n")
 		},
 	}
-	command.Flags().BoolVar(&strict, "strict", true, "perform strict workflow validatation")
+	command.Flags().BoolVar(&strict, "strict", true, "perform strict workflow template validatation")
+	command.Flags().BoolVar(&resolveRemoteTemplates, "resolve-remote-templates", false, "resolve remote templates during workflow template validatation")
```
Comment (dtaniwaki) [inline cmd/argo/commands/template/lint.go]: Is there any better flag name?

**Comment by dtaniwaki** [comment]
Honestly speaking, a simpler solution is just check `Lint` flag at https://github.com/argoproj/argo/blob/3bead0db3d2777638992ba5e11a2de1c65be162c/workflow/validate/validate.go#L272.

Please tell me your thought.

File: cmd/argo/commands/template/lint.go (hunk 1 above)
Comment (simster7) [reply cmd/argo/commands/template/lint.go]: My vote would say that `--resolve-remote-templates` is good

**Comment by simster7** [comment]
`Honestly speaking, a simpler solution is passing nil getter and just checking Lint flag at `

What do you think of using the `nil` getter as the default behavior and only doing template resolution when passed in a flag. We can maybe add a warning when trying to lint remote templates locally saying that runtime resolution is not validated unless the flag is provided.

File: cmd/argo/commands/template/lint.go (hunk 1 above)
Comment (dtaniwaki) [reply cmd/argo/commands/template/lint.go]: Thank you for your ideas.

In the current implementation of this PR, the difference between using this flag is whether it tries to solve `TemplateRef` which means remote and it raises an error if a given linting workflow reaches any `TemplateRef`. I think we should discuss the expected behavior.

Comment (sarabala1979) [reply cmd/argo/commands/template/lint.go]: Got it. I misunderstood the issue. you are referring `@dtaniwaki is it possible to make client-side linting not require a kubeconfig in the case where templates are not used?` @jessesuen comments.

Expected Behaviors:
1. Kubeconfig should not be loaded for normal workflow (without `TemplateRef`) 
2.  Kubeconfig should be loaded for the workflow with `TemplateRef`(no flag). 

Argo Cli should automatically detect the WF with `TemplateRef` and without `TemplateRef`and execute the above behavior.  `lint` should resolve the `TemplateRef`.
ArgoCli should provide firstclass support for this instead of passing flag.

**Comment by dtaniwaki** [comment]
I have updated the code based on https://github.com/argoproj/argo/pull/1787#discussion_r353333836 and tested basic cases below.

```
$ argo lint examples/hello-world.yaml
Workflow manifests validated

$ argo lint examples/workflow-template/hello-world.yaml
Workflow manifests validated

$ argo lint --kubeconfig=config examples/hello-world.yaml
Workflow manifests validated

$ argo lint --kubeconfig=config examples/workflow-template/hello-world.yaml
2019/12/04 20:55:09 invalid configuration: no configuration has been provided
```

**Comment by sarabala1979** [comment]
@dtaniwaki Please resolve the conflict.

**Comment by dtaniwaki** [comment]
Passed functional tests except `examples/dag-daemon-task.yaml` which looks no relation with this PR.

Here's the pod log

```
$ argo get dag-daemon-task-d9769
Name:                dag-daemon-task-d9769
Namespace:           default
ServiceAccount:      default
Status:              Failed
Created:             Thu Dec 05 11:03:42 +0900 (3 hours ago)
Started:             Thu Dec 05 11:03:44 +0900 (3 hours ago)
Finished:            Thu Dec 05 14:16:48 +0900 (3 minutes ago)
Duration:            3 hours 13 minutes

STEP                                       PODNAME                           DURATION  MESSAGE
 ✖ dag-daemon-task-d9769 (daemon-example)
 ├-✔ influx (influxdb)                     dag-daemon-task-d9769-2721168474  3h
 └-✖ init-database (influxdb-client)       dag-daemon-task-d9769-3806812314  7s        failed with exit code 3

$ argo logs dag-daemon-task-d9769 -w
WARN[0000] pods "dag-daemon-task-d9769-2721168474" not found
init-database:  curl: (3) [globbing] nested brace in column 9
```

**Comment by dtaniwaki** [comment]
I will try it in the mastbr branch.

**Comment by dtaniwaki** [comment]
It succeeded now. Maybe, it's a race conditional failure of another thing.
