### PR TITLE
fix: Always validate templates with different input parameters. Fixes #2313

### LINKED ISSUE #2313: Argo lint does not check the parameters/inputs validity of tasks in a dag
**Note:** [This was working in `2.2.1`](https://github.com/argoproj/argo/issues/2313#issuecomment-591259701)

----

Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [ ] I've included the logs.
 
**What happened**:

We had a Argo workflow spec that passed `lint`ing even though it had a step that did not specify a parameter required by the template it was referring to. On submission, the workflow failed with an error like: 

```
Name:                demonstrate-lint-bug-pmf45
Namespace:           argo
ServiceAccount:      default
Status:              Failed
Message:             invalid spec: templates.abc.tasks.a inputs.parameters.message was not supplied
Created:             Wed Feb 26 17:11:54 +1100 (now)
Started:             Wed Feb 26 17:11:54 +1100 (now)
Finished:            Wed Feb 26 17:11:54 +1100 (now)
Duration:            0 seconds
```

**What you expected to happen**:

`argo lint` should have failed with a message like: `FATA[0000] args-params.yaml: templates.whalesay inputs.parameters.message was not supplied`

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-
spec:
  entrypoint: abc
  # Parameters can be passed/overridden via the argo CLI.
  # To override the printed message, run `argo submit` with the -p option:
  # $ argo submit examples/arguments-parameters.yaml -p message="goodbye world"
  arguments:
    parameters: []
  templates:
  - dag:
      tasks:
        - name: a
          template: whalesay
          arguments:
             parameters:
        - name: b
          template: whalesay
          arguments:
             parameters:
               - name: message
                 value: "banana"
        - name: c
          template: whalesay
          arguments:
             parameters:
               - name: message
                 value: "apple"
    name: abc
  - name: whalesay
    inputs:
      parameters:
      - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

**Anything else we need to know?**:

**Environment**:
- Argo version: We use Nix. Our Nix'd `argo` version is [2.4.3](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/cluster/argo/default.nix#L5)
- Kubernetes version : 
```
clientVersion:
  buildDate: "1970-01-01T00:00:01Z"
  compiler: gc
  gitCommit: e7f962ba86f4ce7033828210ca3556393c377bcc
  gitTreeState: archive
  gitVersion: v1.16.6-beta.0
  goVersion: go1.13.6
  major: "1"
  minor: 16+
  platform: darwin/amd64
serverVersion:
  buildDate: "2019-12-22T23:14:11Z"
  compiler: gc
  gitCommit: c0eccca51d7500bb03b2f163dd8d534ffeb2f7a2
  gitTreeState: clean
  gitVersion: v1.14.9-eks-c0eccc
  goVersion: go1.12.12
  major: "1"
  minor: 14+
  platform: linux/amd64
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by whynowy**
Fixes #2313

The issue was introduced in #1744, where `ResolveTemplate()` in `context.go` does not call `ProcessArgs()` any more.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [ ] Optional. I've added My organization is added to the README.
* [ ] I've signed the CLA and required builds are green.

### CODE REVIEW

File: workflow/validate/validate.go [hunk 1]
```diff
@@ -243,6 +235,15 @@ func (ctx *templateValidationCtx) validateTemplate(tmpl *wfv1.Template, tmplCtx
 	if err != nil {
 		return errors.Errorf(errors.CodeBadRequest, "templates.%s %s", tmpl.Name, err)
 	}
+
```
Comment (whynowy) [inline workflow/validate/validate.go]: Move this part here from the beginning to make it runs `common.ProcessArgs` every time.

This is because `ProcessArgs` is not invoked any more in `ResolveTemplate` (function in `context.go`, called by `validateTemplateHolder`) with the change #1744.

File: server/workflow/workflow_server.go [hunk 2]
```diff
@@ -286,7 +286,7 @@ func (s *workflowServer) LintWorkflow(ctx context.Context, req *workflowpkg.Work
 
 	wftmplGetter := templateresolution.WrapWorkflowTemplateInterface(wfClient.ArgoprojV1alpha1().WorkflowTemplates(req.Namespace))
 
-	err := validate.ValidateWorkflow(wftmplGetter, req.Workflow, validate.ValidateOpts{})
+	err := validate.ValidateWorkflow(wftmplGetter, req.Workflow, validate.ValidateOpts{Lint: true})
```
Comment (whynowy) [inline server/workflow/workflow_server.go]: I believe this was missing during migration.

This is used here:
https://github.com/argoproj/argo/blob/master/workflow/validate/validate.go#L98

**Comment by whynowy** [comment]
> LGTM. Please allow some time for @dtaniwaki to take a look at this, if possible

Thanks @simster7 !

@dtaniwaki

**Comment by whynowy** [comment]
> Thank you for fixing the issue!

Thanks for looking at it!
