### PR TITLE
fix(ui): correct log viewer only showing first log line

### LINKED ISSUE #4388: v2.12: log viewer only showing first log line
## Summary 

Should see all lines of logs, but only see first line.

## Diagnostics

Network shows all lines:

image

UI states correct number of lines, but only first appears:

image

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by dcherman**
Fixes #4388

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [x] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My builds are green. Try syncing with master if they are not.

### CODE REVIEW

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 1]
```diff
@@ -18,7 +18,8 @@ interface WorkflowLogsViewerProps {
 interface WorkflowLogsViewerState {
     error?: Error;
     loaded: boolean;
-    lines: string[];
+    lineCount: number;
+    logsObservable?: Observable<string>;
```
Comment (alexec) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:22]: should this be part of the state? or just a field?

**Review by alexec — CHANGES_REQUESTED** [review]
can I ask for a screenshot please?

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx (hunk 1 above)
Comment (dcherman) [reply ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:22]: So this is where my knowledge of React falls flat a bit (historically most of my development is in Vue/Angular).  I put this object into the `state` only because it's referenced from within JSX.  I'm not entirely sure whether that's the right thing to do or not.  I can try using this as a simple field and see if that works as well.  I *think* it will since it doesn't directly participate in data flow (it's returned via a function).

Comment (alexec) [reply ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:22]: but it works?

Comment (dcherman) [reply ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:22]: Seems to, just tried it.  I'll make that change in a couple minutes.

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 2]
```diff
@@ -60,19 +61,19 @@ export class WorkflowLogsViewer extends React.Component<WorkflowLogsViewerProps,
...
                     )}
                     {!this.state.error && this.podHasNoLogs() && <p>Pod did not output any logs.</p>}
-                    {this.state.lines.length > 0 && (
+                    {this.state.lineCount > 0 && (
                         <div className='log-box'>
                             <FullHeightLogsViewer
                                 source={{
                                     key: `${this.props.workflow.metadata.name}-${this.props.container}`,
-                                    loadLogs: () => Observable.from(this.state.lines),
+                                    loadLogs: () => this.state.logsObservable,
```
Comment (dcherman) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:69]: Just noting that this component is actually relatively confusing.  For example, you can change the `loadLogs` function completely, however the new observable will only be subscribed to in the event that the `key` property changes

https://github.com/argoproj/argo-ui/blob/master/src/components/logs-viewer/logs-viewer.tsx#L28-L30

I think this would be a good candidate for refactoring; why doesn't it simply accept an `observable` via props and manage the subscription based on when that changes?

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 3]
```diff
@@ -18,16 +18,21 @@ interface WorkflowLogsViewerProps {
 interface WorkflowLogsViewerState {
     error?: Error;
     loaded: boolean;
-    lines: string[];
+    lineCount: number;
+}
+
+function identity<T>(value: T) {
```
Comment (dcherman) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:24]: Do you have a preferred place to put helper function like this?  I see there's a `utils` file that exports a giant object of helpers, however I wanted to keep this as a separate function for minification/tree shaking purposes and wasn't sure that was the right location.

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx [hunk 4]
```diff
@@ -60,19 +65,19 @@ export class WorkflowLogsViewer extends React.Component<WorkflowLogsViewerProps,
...
                     )}
                     {!this.state.error && this.podHasNoLogs() && <p>Pod did not output any logs.</p>}
-                    {this.state.lines.length > 0 && (
+                    {this.state.lineCount > 0 && this.logsObservable && (
                         <div className='log-box'>
                             <FullHeightLogsViewer
                                 source={{
                                     key: `${this.props.workflow.metadata.name}-${this.props.container}`,
-                                    loadLogs: () => Observable.from(this.state.lines),
+                                    loadLogs: identity(this.logsObservable),
```
Comment (dcherman) [inline ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:73]: This change was introduced so that when strict types are added, we don't have to go back and fix this.  Inside the function (with strict typings enabled), the type of `logsObservable` would be `Observable<string> | undefined`.  By adding the conditional above and using the `identity` function, we can avoid that and resolve the type to `Observable<string>` like the API requires.

File: ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx (hunk 3 above)
Comment (alexec) [reply ui/src/app/workflows/components/workflow-logs-viewer/workflow-logs-viewer.tsx:24]: I don't feel strongly about this.

**Comment by dcherman** [comment]
GIF Showing the fix working w/ multiline output

Screen Recording 2020-10-27 at 1 03 07 PM

**Review by alexec — APPROVED** [review]

**Comment by alexec** [comment]
LGTM
