### PR TITLE
fix: Support workflowDefaults on TTLController for WorkflowTemplateRef Fixes #4188

### LINKED ISSUE #4188: EKS workflowDefaults inconsistencies - kubelet executor
## Summary 

What happened/what you expected to happen?
I expected workflowDefaults to be honored the same with with the following commands:
```
argo submit steps.yaml -n test
argo submit --from workflowtemplate/dag-diamond-xyyxx -n test
```
When I run the the submission directly serviceaccount is not honored
When I run the submission from workflowtemplate ttl strategy is not honored

Running a fresh install of argo on a fresh EKS cluster:
```
kubectl create namespace argo
kubectl apply -n argo -f https://raw.githubusercontent.com/argoproj/argo/v2.11.1/manifests/install.yaml
kubectl create ns test
kubectl create sa -n test argo-test
kubectl create clusterrolebinding delete-me --clusterrole=cluster-admin --serviceaccount=test:argo-test
```

```
 k get cm -n argo workflow-controller-configmap -oyaml


apiVersion: v1
data:
  config: |
    containerRuntimeExecutor: kubelet
    workflowDefaults:
      spec:
        serviceAccountName: argo-test
        ttlStrategy:
          secondsAfterCompletion: 3600
          secondsAfterFailure: 3600
          secondsAfterSuccess: 3600
kind: ConfigMap
```

## Diagnostics

What Kubernetes provider are you using? 
EKS 
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-26T06:16:15Z", GoVersion:"go1.14", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-eks-4c6976", GitCommit:"4c6976793196d70bc5cd29d56ce5440c9473648e", GitTreeState:"clean", BuildDate:"2020-07-17T18:46:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

What version of Argo Workflows are you running? 
Argo client and server 2.11.1

Bug where ttl is honored but not serviceAccount:
(workflow fails and wait logs complain about the default not having enough permissions)
argo submit steps.yaml -n test
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-10-02T02:12:37Z"
  generateName: dag-diamond-
  generation: 5
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Error
  name: dag-diamond-fz54p
  namespace: test
  resourceVersion: "10049"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/test/workflows/dag-diamond-fz54p
  uid: 8c5b2fe8-149d-4b23-9e71-16eda92ae401
spec:
  arguments: {}
  entrypoint: diamond
  serviceAccountName: argo-test
  templates:
  - arguments: {}
    container:
      command:
      - echo
      - '{{inputs.parameters.message}}'
      image: alpine:3.7
      name: ""
      resources: {}
    inputs:
      parameters:
      - name: message
    metadata: {}
    name: echo
    outputs: {}
  - arguments: {}
    dag:
      tasks:
      - arguments:
          parameters:
          - name: message
            value: A
        name: A
        template: echo
      - arguments:
          parameters:
          - name: message
            value: B
        dependencies:
        - A
        name: B
        template: echo
      - arguments:
          parameters:
          - name: message
            value: C
        dependencies:
        - A
        name: C
        template: echo
      - arguments:
          parameters:
          - name: message
            value: D
        dependencies:
        - B
        - C
        name: D
        template: echo
    inputs: {}
    metadata: {}
    name: diamond
    outputs: {}
  ttlStrategy:
    secondsAfterCompletion: 3600
    secondsAfterFailure: 3600
    secondsAfterSuccess: 3600
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-10-02T02:12:47Z"
  nodes:
    dag-diamond-fz54p:
      children:
      - dag-diamond-fz54p-4207938145
      displayName: dag-diamond-fz54p
      finishedAt: "2020-10-02T02:12:47Z"
      id: dag-diamond-fz54p
      name: dag-diamond-fz54p
      outboundNodes:
      - dag-diamond-fz54p-4258271002
      phase: Error
      startedAt: "2020-10-02T02:12:37Z"
      templateName: diamond
      templateScope: local/dag-diamond-fz54p
      type: DAG
    dag-diamond-fz54p-4157605288:
      boundaryID: dag-diamond-fz54p
      children:
      - dag-diamond-fz54p-4258271002
      displayName: B
      finishedAt: "2020-10-02T02:12:47Z"
      id: dag-diamond-fz54p-4157605288
      message: 'omitted: depends condition not met'
      name: dag-diamond-fz54p.B
      phase: Omitted
      startedAt: "2020-10-02T02:12:47Z"
      templateName: echo
      templateScope: local/dag-diamond-fz54p
      type: Skipped
    dag-diamond-fz54p-4174382907:
      boundaryID: dag-diamond-fz54p
      children:
      - dag-diamond-fz54p-4258271002
      displayName: C
      finishedAt: "2020-10-02T02:12:47Z"
      id: dag-diamond-fz54p-4174382907
      message: 'omitted: depends condition not met'
      name: dag-diamond-fz54p.C
      phase: Omitted
      startedAt: "2020-10-02T02:12:47Z"
      templateName: echo
      templateScope: local/dag-diamond-fz54p
      type: Skipped
    dag-diamond-fz54p-4207938145:
      boundaryID: dag-diamond-fz54p
      children:
      - dag-diamond-fz54p-4157605288
      - dag-diamond-fz54p-4174382907
      displayName: A
      finishedAt: "2020-10-02T02:12:46Z"
      hostNodeName: ip-10-0-2-189.us-west-2.compute.internal
      id: dag-diamond-fz54p-4207938145
      inputs:
        parameters:
        - name: message
          value: A
      message: 'failed to save outputs: Failed to establish pod watch: timed out waiting
        for the condition'
      name: dag-diamond-fz54p.A
      phase: Error
      resourcesDuration:
        cpu: 8
        memory: 8
      startedAt: "2020-10-02T02:12:37Z"
      templateName: echo
      templateScope: local/dag-diamond-fz54p
      type: Pod
    dag-diamond-fz54p-4258271002:
      boundaryID: dag-diamond-fz54p
      displayName: D
      finishedAt: "2020-10-02T02:12:47Z"
      id: dag-diamond-fz54p-4258271002
      message: 'omitted: depends condition not met'
      name: dag-diamond-fz54p.D
      phase: Omitted
      startedAt: "2020-10-02T02:12:47Z"
      templateName: echo
      templateScope: local/dag-diamond-fz54p
      type: Skipped
  phase: Error
  resourcesDuration:
    cpu: 8
    memory: 8
  startedAt: "2020-10-02T02:12:37Z"
```

Bug where service account is honored and not ttl:
argo submit --from workflowtemplate/dag-diamond-sf8vp -n test
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-10-02T02:14:26Z"
  generateName: dag-diamond-sf8vp-
  generation: 13
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Succeeded
    workflows.argoproj.io/workflow-template: dag-diamond-sf8vp
  name: dag-diamond-sf8vp-dxnjn
  namespace: test
  resourceVersion: "10464"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/test/workflows/dag-diamond-sf8vp-dxnjn
  uid: 319ff382-0ce6-4f10-acdc-abffedabb0e3
spec:
  arguments: {}
  workflowTemplateRef:
    name: dag-diamond-sf8vp
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-10-02T02:14:40Z"
  nodes:
    dag-diamond-sf8vp-dxnjn:
      children:
      - dag-diamond-sf8vp-dxnjn-126754612
      displayName: dag-diamond-sf8vp-dxnjn
      finishedAt: "2020-10-02T02:14:40Z"
      id: dag-diamond-sf8vp-dxnjn
      name: dag-diamond-sf8vp-dxnjn
      outboundNodes:
      - dag-diamond-sf8vp-dxnjn-76421755
      phase: Succeeded
      startedAt: "2020-10-02T02:14:26Z"
      templateRef:
        name: dag-diamond-sf8vp
        template: diamond
      templateScope: local/
      type: DAG
    dag-diamond-sf8vp-dxnjn-76421755:
      boundaryID: dag-diamond-sf8vp-dxnjn
      displayName: D
      finishedAt: "2020-10-02T02:14:40Z"
      hostNodeName: ip-10-0-2-189.us-west-2.compute.internal
      id: dag-diamond-sf8vp-dxnjn-76421755
      inputs:
        parameters:
        - name: message
          value: D
      name: dag-diamond-sf8vp-dxnjn.D
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 3
        memory: 3
      startedAt: "2020-10-02T02:14:36Z"
      templateName: echo
      templateScope: namespaced/dag-diamond-sf8vp
      type: Pod
    dag-diamond-sf8vp-dxnjn-126754612:
      boundaryID: dag-diamond-sf8vp-dxnjn
      children:
      - dag-diamond-sf8vp-dxnjn-177087469
      - dag-diamond-sf8vp-dxnjn-160309850
      displayName: A
      finishedAt: "2020-10-02T02:14:29Z"
      hostNodeName: ip-10-0-2-189.us-west-2.compute.internal
      id: dag-diamond-sf8vp-dxnjn-126754612
      inputs:
        parameters:
        - name: message
          value: A
      name: dag-diamond-sf8vp-dxnjn.A
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 2
        memory: 2
      startedAt: "2020-10-02T02:14:26Z"
      templateName: echo
      templateScope: namespaced/dag-diamond-sf8vp
      type: Pod
    dag-diamond-sf8vp-dxnjn-160309850:
      boundaryID: dag-diamond-sf8vp-dxnjn
      children:
      - dag-diamond-sf8vp-dxnjn-76421755
      displayName: C
      finishedAt: "2020-10-02T02:14:34Z"
      hostNodeName: ip-10-0-2-189.us-west-2.compute.internal
      id: dag-diamond-sf8vp-dxnjn-160309850
      inputs:
        parameters:
        - name: message
          value: C
      name: dag-diamond-sf8vp-dxnjn.C
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 2
        memory: 2
      startedAt: "2020-10-02T02:14:31Z"
      templateName: echo
      templateScope: namespaced/dag-diamond-sf8vp
      type: Pod
    dag-diamond-sf8vp-dxnjn-177087469:
      boundaryID: dag-diamond-sf8vp-dxnjn
      children:
      - dag-diamond-sf8vp-dxnjn-76421755
      displayName: B
      finishedAt: "2020-10-02T02:14:34Z"
      hostNodeName: ip-10-0-2-189.us-west-2.compute.internal
      id: dag-diamond-sf8vp-dxnjn-177087469
      inputs:
        parameters:
        - name: message
          value: B
      name: dag-diamond-sf8vp-dxnjn.B
      outputs:
        exitCode: "0"
      phase: Succeeded
      resourcesDuration:
        cpu: 2
        memory: 2
      startedAt: "2020-10-02T02:14:31Z"
      templateName: echo
      templateScope: namespaced/dag-diamond-sf8vp
      type: Pod
  phase: Succeeded
  resourcesDuration:
    cpu: 9
    memory: 9
  startedAt: "2020-10-02T02:14:26Z"
  storedTemplates:
    namespaced/dag-diamond-sf8vp/diamond:
      arguments: {}
      dag:
        tasks:
        - arguments:
            parameters:
            - name: message
              value: A
          name: A
          template: echo
        - arguments:
            parameters:
            - name: message
              value: B
          dependencies:
          - A
          name: B
          template: echo
        - arguments:
            parameters:
            - name: message
              value: C
          dependencies:
          - A
          name: C
          template: echo
        - arguments:
            parameters:
            - name: message
              value: D
          dependencies:
          - B
          - C
          name: D
          template: echo
      inputs: {}
      metadata: {}
      name: diamond
      outputs: {}
    namespaced/dag-diamond-sf8vp/echo:
      arguments: {}
      container:
        command:
        - echo
        - '{{inputs.parameters.message}}'
        image: alpine:3.7
        name: ""
        resources: {}
      inputs:
        parameters:
        - name: message
      metadata: {}
      name: echo
      outputs: {}
  storedWorkflowTemplateSpec:
    arguments: {}
    entrypoint: diamond
    templates:
    - arguments: {}
      container:
        command:
        - echo
        - '{{inputs.parameters.message}}'
        image: alpine:3.7
        name: ""
        resources: {}
      inputs:
        parameters:
        - name: message
      metadata: {}
      name: echo
      outputs: {}
    - arguments: {}
      dag:
        tasks:
        - arguments:
            parameters:
            - name: message
              value: A
          name: A
          template: echo
        - arguments:
            parameters:
            - name: message
              value: B
          dependencies:
          - A
          name: B
          template: echo
        - arguments:
            parameters:
            - name: message
              value: C
          dependencies:
          - A
          name: C
          template: echo
        - arguments:
            parameters:
            - name: message
              value: D
          dependencies:
          - B
          - C
          name: D
          template: echo
      inputs: {}
      metadata: {}
      name: diamond
      outputs: {}
```

ttl honored but not serviceAccount:
```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

time="2020-10-02T02:12:37Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="Updated phase  -> Running" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="DAG node dag-diamond-fz54p initialized Running" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="All of node dag-diamond-fz54p.A dependencies [] completed" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="Pod node dag-diamond-fz54p-4207938145 initialized Pending" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="Created pod: dag-diamond-fz54p.A (dag-diamond-fz54p-4207938145)" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10005 workflow=dag-diamond-fz54p
time="2020-10-02T02:12:38Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:38Z" level=info msg="Updating node dag-diamond-fz54p-4207938145 message: ContainerCreating"
time="2020-10-02T02:12:38Z" level=info msg="Skipped pod dag-diamond-fz54p.A (dag-diamond-fz54p-4207938145) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-fz54p
time="2020-10-02T02:12:38Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10013 workflow=dag-diamond-fz54p
time="2020-10-02T02:12:39Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:39Z" level=info msg="Skipped pod dag-diamond-fz54p.A (dag-diamond-fz54p-4207938145) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-fz54p
time="2020-10-02T02:12:40Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:40Z" level=info msg="Updating node dag-diamond-fz54p-4207938145 status Pending -> Running"
time="2020-10-02T02:12:40Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10026 workflow=dag-diamond-fz54p
time="2020-10-02T02:12:41Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Updating node dag-diamond-fz54p-4207938145 status Running -> Error"
time="2020-10-02T02:12:47Z" level=info msg="Updating node dag-diamond-fz54p-4207938145 message: failed to save outputs: Failed to establish pod watch: timed out waiting for the condition"
time="2020-10-02T02:12:47Z" level=info msg="Skipped node dag-diamond-fz54p-4157605288 initialized Omitted (message: omitted: depends condition not met)" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Skipped node dag-diamond-fz54p-4174382907 initialized Omitted (message: omitted: depends condition not met)" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Skipped node dag-diamond-fz54p-4258271002 initialized Omitted (message: omitted: depends condition not met)" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Outbound nodes of dag-diamond-fz54p set to [dag-diamond-fz54p-4258271002]" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="node dag-diamond-fz54p phase Running -> Error" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="node dag-diamond-fz54p finished: 2020-10-02 02:12:47.879673481 +0000 UTC" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Checking daemoned children of dag-diamond-fz54p" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Updated phase Running -> Error" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Marking workflow completed" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Checking daemoned children of " namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Workflow update successful" namespace=test phase=Error resourceVersion=10049 workflow=dag-diamond-fz54p
time="2020-10-02T02:12:48Z" level=info msg="Labeled pod completed" namespace=test pod=dag-diamond-fz54p-4207938145
```
serviceAccount honored but not ttl:
```
time="2020-10-02T02:12:37Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="Updated phase  -> Running" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="DAG node dag-diamond-fz54p initialized Running" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="All of node dag-diamond-fz54p.A dependencies [] completed" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="Pod node dag-diamond-fz54p-4207938145 initialized Pending" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="Created pod: dag-diamond-fz54p.A (dag-diamond-fz54p-4207938145)" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:37Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10005 workflow=dag-diamond-fz54p
time="2020-10-02T02:12:38Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:38Z" level=info msg="Updating node dag-diamond-fz54p-4207938145 message: ContainerCreating"
time="2020-10-02T02:12:38Z" level=info msg="Skipped pod dag-diamond-fz54p.A (dag-diamond-fz54p-4207938145) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-fz54p
time="2020-10-02T02:12:38Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10013 workflow=dag-diamond-fz54p
time="2020-10-02T02:12:39Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:39Z" level=info msg="Skipped pod dag-diamond-fz54p.A (dag-diamond-fz54p-4207938145) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-fz54p
time="2020-10-02T02:12:40Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:40Z" level=info msg="Updating node dag-diamond-fz54p-4207938145 status Pending -> Running"
time="2020-10-02T02:12:40Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10026 workflow=dag-diamond-fz54p
time="2020-10-02T02:12:41Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Updating node dag-diamond-fz54p-4207938145 status Running -> Error"
time="2020-10-02T02:12:47Z" level=info msg="Updating node dag-diamond-fz54p-4207938145 message: failed to save outputs: Failed to establish pod watch: timed out waiting for the condition"
time="2020-10-02T02:12:47Z" level=info msg="Skipped node dag-diamond-fz54p-4157605288 initialized Omitted (message: omitted: depends condition not met)" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Skipped node dag-diamond-fz54p-4174382907 initialized Omitted (message: omitted: depends condition not met)" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Skipped node dag-diamond-fz54p-4258271002 initialized Omitted (message: omitted: depends condition not met)" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Outbound nodes of dag-diamond-fz54p set to [dag-diamond-fz54p-4258271002]" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="node dag-diamond-fz54p phase Running -> Error" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="node dag-diamond-fz54p finished: 2020-10-02 02:12:47.879673481 +0000 UTC" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Checking daemoned children of dag-diamond-fz54p" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Updated phase Running -> Error" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Marking workflow completed" namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Checking daemoned children of " namespace=test workflow=dag-diamond-fz54p
time="2020-10-02T02:12:47Z" level=info msg="Workflow update successful" namespace=test phase=Error resourceVersion=10049 workflow=dag-diamond-fz54p
time="2020-10-02T02:12:48Z" level=info msg="Labeled pod completed" namespace=test pod=dag-diamond-fz54p-4207938145
    ~  kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep dag-diamond-sf8vp-dxnjn                      ✔  py3   example ⎈  20:16:28 
time="2020-10-02T02:14:26Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:26Z" level=info msg="Updated phase  -> Running" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:26Z" level=info msg="DAG node dag-diamond-sf8vp-dxnjn initialized Running" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:26Z" level=info msg="All of node dag-diamond-sf8vp-dxnjn.A dependencies [] completed" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:26Z" level=info msg="Pod node dag-diamond-sf8vp-dxnjn-126754612 initialized Pending" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:26Z" level=info msg="Created pod: dag-diamond-sf8vp-dxnjn.A (dag-diamond-sf8vp-dxnjn-126754612)" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:26Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10351 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:27Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:27Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-126754612 message: ContainerCreating"
time="2020-10-02T02:14:27Z" level=info msg="Skipped pod dag-diamond-sf8vp-dxnjn.A (dag-diamond-sf8vp-dxnjn-126754612) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:27Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10357 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:28Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:28Z" level=info msg="Skipped pod dag-diamond-sf8vp-dxnjn.A (dag-diamond-sf8vp-dxnjn-126754612) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:29Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:29Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-126754612 status Pending -> Running"
time="2020-10-02T02:14:29Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10373 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:30Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:30Z" level=info msg="Setting node dag-diamond-sf8vp-dxnjn-126754612 outputs"
time="2020-10-02T02:14:30Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10378 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:31Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:31Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-126754612 status Running -> Succeeded"
time="2020-10-02T02:14:31Z" level=info msg="All of node dag-diamond-sf8vp-dxnjn.B dependencies [A] completed" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:31Z" level=info msg="Pod node dag-diamond-sf8vp-dxnjn-177087469 initialized Pending" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:31Z" level=info msg="Created pod: dag-diamond-sf8vp-dxnjn.B (dag-diamond-sf8vp-dxnjn-177087469)" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:31Z" level=info msg="All of node dag-diamond-sf8vp-dxnjn.C dependencies [A] completed" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:31Z" level=info msg="Pod node dag-diamond-sf8vp-dxnjn-160309850 initialized Pending" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:31Z" level=info msg="Created pod: dag-diamond-sf8vp-dxnjn.C (dag-diamond-sf8vp-dxnjn-160309850)" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:31Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10389 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:32Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:32Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-160309850 message: ContainerCreating"
time="2020-10-02T02:14:32Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-177087469 message: ContainerCreating"
time="2020-10-02T02:14:32Z" level=info msg="Labeled pod completed" namespace=test pod=dag-diamond-sf8vp-dxnjn-126754612
time="2020-10-02T02:14:32Z" level=info msg="Skipped pod dag-diamond-sf8vp-dxnjn.B (dag-diamond-sf8vp-dxnjn-177087469) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:32Z" level=info msg="Skipped pod dag-diamond-sf8vp-dxnjn.C (dag-diamond-sf8vp-dxnjn-160309850) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:32Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10398 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:33Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:33Z" level=info msg="Labeled pod completed" namespace=test pod=dag-diamond-sf8vp-dxnjn-126754612
time="2020-10-02T02:14:33Z" level=info msg="Skipped pod dag-diamond-sf8vp-dxnjn.B (dag-diamond-sf8vp-dxnjn-177087469) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:33Z" level=info msg="Skipped pod dag-diamond-sf8vp-dxnjn.C (dag-diamond-sf8vp-dxnjn-160309850) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:34Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:34Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-177087469 status Pending -> Running"
time="2020-10-02T02:14:34Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-160309850 status Pending -> Running"
time="2020-10-02T02:14:34Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10416 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:35Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:35Z" level=info msg="Setting node dag-diamond-sf8vp-dxnjn-177087469 outputs"
time="2020-10-02T02:14:35Z" level=info msg="Setting node dag-diamond-sf8vp-dxnjn-160309850 outputs"
time="2020-10-02T02:14:35Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10426 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:36Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:36Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-177087469 status Running -> Succeeded"
time="2020-10-02T02:14:36Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-160309850 status Running -> Succeeded"
time="2020-10-02T02:14:36Z" level=info msg="All of node dag-diamond-sf8vp-dxnjn.D dependencies [B C] completed" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:36Z" level=info msg="Pod node dag-diamond-sf8vp-dxnjn-76421755 initialized Pending" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:36Z" level=info msg="Created pod: dag-diamond-sf8vp-dxnjn.D (dag-diamond-sf8vp-dxnjn-76421755)" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:36Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10433 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:37Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:37Z" level=info msg="Labeled pod completed" namespace=test pod=dag-diamond-sf8vp-dxnjn-177087469
time="2020-10-02T02:14:37Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-76421755 message: ContainerCreating"
time="2020-10-02T02:14:37Z" level=info msg="Skipped pod dag-diamond-sf8vp-dxnjn.D (dag-diamond-sf8vp-dxnjn-76421755) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:37Z" level=info msg="Labeled pod completed" namespace=test pod=dag-diamond-sf8vp-dxnjn-160309850
time="2020-10-02T02:14:37Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10444 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:38Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:38Z" level=info msg="Skipped pod dag-diamond-sf8vp-dxnjn.D (dag-diamond-sf8vp-dxnjn-76421755) creation: already exists" namespace=test podPhase=Pending workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:38Z" level=info msg="Labeled pod completed" namespace=test pod=dag-diamond-sf8vp-dxnjn-160309850
time="2020-10-02T02:14:38Z" level=info msg="Labeled pod completed" namespace=test pod=dag-diamond-sf8vp-dxnjn-177087469
time="2020-10-02T02:14:39Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:39Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-76421755 status Pending -> Running"
time="2020-10-02T02:14:39Z" level=info msg="Workflow update successful" namespace=test phase=Running resourceVersion=10456 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:40Z" level=info msg="Processing workflow" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:40Z" level=info msg="Setting node dag-diamond-sf8vp-dxnjn-76421755 outputs"
time="2020-10-02T02:14:40Z" level=info msg="Updating node dag-diamond-sf8vp-dxnjn-76421755 status Running -> Succeeded"
time="2020-10-02T02:14:40Z" level=info msg="Outbound nodes of dag-diamond-sf8vp-dxnjn set to [dag-diamond-sf8vp-dxnjn-76421755]" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:40Z" level=info msg="node dag-diamond-sf8vp-dxnjn phase Running -> Succeeded" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:40Z" level=info msg="node dag-diamond-sf8vp-dxnjn finished: 2020-10-02 02:14:40.982669012 +0000 UTC" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:40Z" level=info msg="Checking daemoned children of dag-diamond-sf8vp-dxnjn" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:40Z" level=info msg="Updated phase Running -> Succeeded" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:40Z" level=info msg="Marking workflow completed" namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:40Z" level=info msg="Checking daemoned children of " namespace=test workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:40Z" level=info msg="Workflow update successful" namespace=test phase=Succeeded resourceVersion=10464 workflow=dag-diamond-sf8vp-dxnjn
time="2020-10-02T02:14:42Z" level=info msg="Labeled pod completed" namespace=test pod=dag-diamond-sf8vp-dxnjn-76421755
```

The example I used for this is and also turned it into a workflowTemplate
```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: echo
    inputs:
      parameters:
      - name: message
    container:
      image: alpine:3.7
      command: [echo, "{{inputs.parameters.message}}"]
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: message, value: A}]
      - name: B
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: B}]
      - name: C
        dependencies: [A]
        template: echo
        arguments:
          parameters: [{name: message, value: C}]
      - name: D
        dependencies: [B, C]
        template: echo
        arguments:
          parameters: [{name: message, value: D}]
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 

Fixes #4188

### CODE REVIEW

File: workflow/util/util.go [hunk 1]
```diff
@@ -120,15 +120,22 @@ func NewWorkflowLister(informer cache.SharedIndexInformer) WorkflowLister {
...
-			wf.Spec.TTLStrategy = &ttlstrategy
-		} else if wf.Spec.TTLStrategy.SecondsAfterCompletion == nil {
-			wf.Spec.TTLStrategy.SecondsAfterCompletion = wf.Spec.TTLSecondsAfterFinished
+	ConstructTTLStrategy(&wf.Spec)
+	return &wf, err
+}
+
+// This function can be remove once `TTLSecondsAfterFinished` completely removed.
+func ConstructTTLStrategy(spec *wfv1.WorkflowSpec) {
+	if spec != nil {
```
Comment (alexec) [inline workflow/util/util.go:129]: could this instead be `func (s *WorkflowSpec) GetTTLStrategy() {...}`

File: workflow/controller/controller.go [hunk 2]
```diff
@@ -148,7 +148,7 @@ func NewWorkflowController(restConfig *rest.Config, kubeclientset kubernetes.Int
 
 // RunTTLController runs the workflow TTL controller
 func (wfc *WorkflowController) runTTLController(ctx context.Context) {
-	ttlCtrl := ttlcontroller.NewController(wfc.wfclientset, wfc.wfInformer)
+	ttlCtrl := ttlcontroller.NewController(wfc.wfclientset, wfc.wfInformer, wfc.Config.WorkflowDefaults.Spec.GetTTLStrategy())
```
Comment (sarabala1979) [inline workflow/controller/controller.go:151]: Passing default TTLStrategy to TTL Controller

File: workflow/ttlcontroller/ttlcontroller.go [hunk 3]
```diff
@@ -236,11 +239,19 @@ func timeLeft(wf *wfv1.Workflow, since *time.Time) (*time.Duration, *time.Time)
 	}
 }
 
-func getTTLStrategy(wf *wfv1.Workflow) *wfv1.TTLStrategy {
-	ttlStrategy := wf.Spec.TTLStrategy
-
-	if ttlStrategy == nil && wf.Status.StoredWorkflowSpec != nil && wf.Status.StoredWorkflowSpec.TTLStrategy != nil {
-		return wf.Status.StoredWorkflowSpec.TTLStrategy
+func getTTLStrategy(wf *wfv1.Workflow, defaultTTLStrategy *wfv1.TTLStrategy) *wfv1.TTLStrategy {
```
Comment (sarabala1979) [inline workflow/ttlcontroller/ttlcontroller.go:242]: Apply the TTLStrategy in order

File: workflow/util/util.go [hunk 4]
```diff
@@ -120,14 +120,6 @@ func NewWorkflowLister(informer cache.SharedIndexInformer) WorkflowLister {
 func FromUnstructured(un *unstructured.Unstructured) (*wfv1.Workflow, error) {
 	var wf wfv1.Workflow
 	err := runtime.DefaultUnstructuredConverter.FromUnstructured(un.Object, &wf)
-	if wf.Spec.TTLSecondsAfterFinished != nil {
```
Comment (alexec) [inline workflow/util/util.go:123]: nice

File: workflow/ttlcontroller/ttlcontroller.go [hunk 5]
```diff
@@ -236,11 +239,19 @@ func timeLeft(wf *wfv1.Workflow, since *time.Time) (*time.Duration, *time.Time)
...
+	var ttlStrategy *wfv1.TTLStrategy
+	// TTLStrategy from Workflow default from Config
+	if defaultTTLStrategy != nil {
+		ttlStrategy = defaultTTLStrategy
+	}
+	// TTLStrategy from WorkflowTemplate
+	if wf.Status.StoredWorkflowSpec != nil && wf.Status.StoredWorkflowSpec.GetTTLStrategy() != nil {
```
Comment (alexec) [inline workflow/ttlcontroller/ttlcontroller.go:249]: is this correct - that the store spec is low precedence than the original?

File: pkg/apis/workflow/v1alpha1/workflow_types.go [hunk 6]
```diff
@@ -356,6 +356,18 @@ func (wfs WorkflowSpec) GetVolumeClaimGC() *VolumeClaimGC {
 	return wfs.VolumeClaimGC
 }
 
+func (wfs WorkflowSpec) GetTTLStrategy() *TTLStrategy {
+	if wfs.TTLSecondsAfterFinished != nil {
```
Comment (alexec) [inline pkg/apis/workflow/v1alpha1/workflow_types.go:360]: please add a test

**Review by alexec — CHANGES_REQUESTED** [review]
tests requested

File: workflow/ttlcontroller/ttlcontroller.go (hunk 5 above)
Comment (sarabala1979) [reply workflow/ttlcontroller/ttlcontroller.go:249]: Order of precedence:
1. Workflow
2. WorkflowTemplate
3. Workflowdefault

File: pkg/apis/workflow/v1alpha1/workflow_types.go (hunk 6 above)
Comment (sarabala1979) [reply pkg/apis/workflow/v1alpha1/workflow_types.go:360]: @alexec  added test

File: pkg/apis/workflow/v1alpha1/workflow_types_test.go [hunk 7]
```diff
@@ -222,3 +222,20 @@ func TestWorkflowSpec_GetVolumeGC(t *testing.T) {
 	assert.NotNil(t, spec.GetVolumeClaimGC())
 	assert.Equal(t, &VolumeClaimGC{Strategy: VolumeClaimGCOnSuccess}, spec.GetVolumeClaimGC())
 }
+
+func TestGetTTLStrategy(t *testing.T) {
+	var ten int32 = 10
+	var twenty int32 = 20
```
Comment (alexec) [inline pkg/apis/workflow/v1alpha1/workflow_types_test.go:228]: minor: prefer `pointer.Int32(20)`

File: workflow/controller/controller.go (hunk 2 above)
Comment (alexec) [reply workflow/controller/controller.go:151]: this will not change if the config is edited - instead you should just do 👍 
`wfc.Config.WorkflowDefaults.Spec.GetTTLStrategy)`

Can `wfc.Config.WorkflowDefaults` be `nil`

Comment (alexec) [reply workflow/controller/controller.go:151]: This is a not trivial fix, and I think you need to make it support reconfiguration at runtime of the to controller.

I suggest you have `configSupplied: func() Config`

File: workflow/ttlcontroller/ttlcontroller.go (hunk 5 above)
Comment (alexec) [inline workflow/ttlcontroller/ttlcontroller.go:249]: I think you can create
```golang
func (w *Workflow) GetTTLStrategy(defaultTTLStrategy *wfv1.TTLStrategy) {
  if w == nil {return defaultTTLStrategy}
  if wf.Status.StoredWorkflowSpec != nil && wf.Status.StoredWorkflowSpec.GetTTLStrategy() != nil {
    return wf.Status.StoredWorkflowSpec.GetTTLStrategy()
  }
  if wf.Spec.GetTTLStrategy()!=nil {
    return  wf.Spec.GetTTLStrategy()
  }
  return defaultTTLStrategy
}
```

Comment (sarabala1979) [reply workflow/ttlcontroller/ttlcontroller.go:259]: This is `GetTTLStrategy` is only accessed in the TTL controller. I didn't see the benefit to move to the Workflow object level.

Comment (alexec) [reply workflow/ttlcontroller/ttlcontroller.go:259]: can you test it easily here? would be easier to test as a object func, I tend to find that be the case

File: workflow/ttlcontroller/ttlcontroller_test.go [hunk 8]
```diff
@@ -349,6 +352,9 @@ func newTTLController() *Controller {
 		resyncPeriod: workflowTTLResyncPeriod,
 		clock:        clock,
 		workqueue:    workqueue.NewDelayingQueue(),
+		configSuppliger: func() *config.Config {
```
Comment (alexec) [inline workflow/ttlcontroller/ttlcontroller_test.go:355]: spelling

**Review by alexec — APPROVED** [review]
