### PR TITLE
fix: Avoid overriding the Workflow parameter when it is merging with WorkflowTemplate parameter

### LINKED ISSUE #3630: v2.9.4: Parameter file with WorkflowTemplate items unset
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:
Using a WorkflowTemplate with parameters file and default argument values results in inconsistent setting of the parameters in the workflow (i.e. some are set from the file and some are not). Seems like it might be related to random map iteration and some combination of parameter parsing issues.

This is a new issue for me in v2.9.4 and was not a problem in earlier versions (tested in v2.9.3 locally and it works).

**What you expected to happen**:
Submitting from a `WorkflowTemplate` with a parameters file and a number of varied parameters should override the relevant parameters defined in the workflow template.

**How to reproduce it (as minimally and precisely as possible)**:

Here's a workflow template I managed to reproduce it with, which is boiled down from a far more complex real world system (similar types of parameters, with a loop etc.):

```
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: params-test
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: a-a
        value: "10"
      - name: b
        value: ""
      - name: c-c
        value: "0"
      - name: d
        value: ""
      - name: e-e
        value: "10"
      - name: f
        value: ""
      - name: g-g
        value: "1"
      - name: h
        value: ""
      - name: i-i
        value: "{}"
      - name: things
        value: "[]"

  templates:
  - name: main
    steps:
    - - name: say1
        template: whalesay
        arguments:
          parameters:
            - name: message
              value: "{{workflow.parameters.a-a}}"
    - - name: say2
        template: whalesay
        arguments:
          parameters:
            - name: message
              value: "{{workflow.parameters.b}}"
    - - name: say3
        template: whalesay
        arguments:
          parameters:
            - name: message
              value: "{{workflow.parameters.c-c}}"
    - - name: say4
        template: whalesay
        arguments:
          parameters:
            - name: message
              value: "{{workflow.parameters.d}}"
    - - name: say5
        template: whalesay
        arguments:
          parameters:
            - name: message
              value: "{{workflow.parameters.e-e}}"
    - - name: say6
        template: whalesay
        arguments:
          parameters:
            - name: message
              value: "{{workflow.parameters.f}}"
    - - name: say7
        template: whalesay
        arguments:
          parameters:
            - name: message
              value: "{{workflow.parameters.i-i}}"
    - - name: loopsay
        template: whalesay
        arguments:
          parameters:
            - name: message
              value: "{{item}}"
        withParam: "{{workflow.parameters.things}}"
        
  - name: whalesay
    inputs:
      parameters:
        - name: message
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.message}}"]
```

Using a file `parameters.yaml` file like so:

```
a-a: "5"
b: b
d: d
f: f
g-g: "2"
h: h
i-i: "{}"
things:
- a: "1"
  nested:
    B: "3"
- a: "2"
```
With the command:

```
argo submit --from wftmpl/params-test -f parameters.yaml --watch
```

Apologies for the strange naming, I had originally thought it was something to do with `-` dashes in the names but I don't think that's the case now. I will try and reduce the example to get the same behaviour if I can.

**Anything else we need to know?**:

Running in a local kind cluster, Argo is deployed via helm, like so:

```
helm install argo argo/argo --set "controller.containerRuntimeExecutor=k8sapi" --set "images.tag=v2.9.4" --set "minio.install=true"
```

Using k8sapi executor here as the docker one is incompatible with kind. I don't think this is related, as I've been running local multi-node testing like this since 2.8.x.

- Argo version:
```
argo: v2.9.4
  BuildDate: 2020-07-24T21:18:51Z
  GitCommit: 20d2ace3d5344db68ce1bc2a250bbb1ba9862613
  GitTreeState: clean
  GitTag: v2.9.4
  GoVersion: go1.13
  Compiler: gc
  Platform: linux/amd64
```
- Kubernetes version :
```
clientVersion:
  buildDate: "2020-07-16T14:19:25Z"
  compiler: gc
  gitCommit: dff82dc0de47299ab66c83c626e08b245ab19037
  gitTreeState: clean
  gitVersion: v1.18.6
  goVersion: go1.13.13
  major: "1"
  minor: "18"
  platform: linux/amd64
serverVersion:
  buildDate: "2020-04-16T11:48:36Z"
  compiler: gc
  gitCommit: 52c56ce7a8272c798dbc29846288d7cd9fbae032
  gitTreeState: clean
  gitVersion: v1.18.2
  goVersion: go1.13.9
  major: "1"
  minor: "18"
  platform: linux/amd64
```

**Other debugging information (if applicable)**:

I noticed while running the below `Parameters` output would change on update, sometimes dropping parameters from the list, sometimes changing order or both. I assume this must be related.

- workflow result:

```
DEBU[0000] CLI version                                   version="{v2.9.4 2020-07-24T21:18:51Z 20d2ace3d5344db68ce1bc2a250bbb1ba9862613 v2.9.4 clean go1.13 gc linux/amd64}"
DEBU[0000] Client options                                opts="{{ false false}  0x16764f0 0xc0000f3590}"
Name:                params-test-fvxqz
Namespace:           default
ServiceAccount:      default
Status:              Succeeded
Conditions:          
 Completed           True
Created:             Wed Jul 29 17:39:12 +0100 (9 minutes ago)
Started:             Wed Jul 29 17:39:12 +0100 (9 minutes ago)
Finished:            Wed Jul 29 17:39:54 +0100 (8 minutes ago)
Duration:            42 seconds
ResourcesDuration:   24s*(1 cpu),24s*(100Mi memory)
Parameters:          
  a-a:               10
  b:                 
  c-c:               0
  d:                 
  e-e:               10
  f:                 
  g-g:               1
  h:                 h

STEP                  TEMPLATE          PODNAME                       DURATION  MESSAGE
 ✔ params-test-fvxqz  params-test/main                                                                 
 ├---✔ say1           whalesay          params-test-fvxqz-1230247442  4s                               
 ├---✔ say2           whalesay          params-test-fvxqz-2490518236  4s                               
 ├---✔ say3           whalesay          params-test-fvxqz-731919486   4s                               
 ├---✔ say4           whalesay          params-test-fvxqz-639778484   4s                               
 ├---✔ say5           whalesay          params-test-fvxqz-3567350474  4s                               
 ├---✔ say6           whalesay          params-test-fvxqz-3203226692  4s                               
 ├---✔ say7           whalesay          params-test-fvxqz-1022026638  4s                               
 └---○ loopsay        whalesay                                                  Skipped, empty params
```

In another run, here's the output after running a few seconds (same inputs/wftmpl):

```
ame:                params-test-qc5wc
Namespace:           default
ServiceAccount:      default
Status:              Running
Created:             Wed Jul 29 17:54:34 +0100 (3 seconds ago)
Started:             Wed Jul 29 17:54:34 +0100 (3 seconds ago)
Duration:            3 seconds
Parameters:          
  b:                 
  c-c:               0
  d:                 
  e-e:               10
  f:                 
  g-g:               1
  h:                 h
  i-i:               {}
```

You can see that the `a-a` parameter is missing, the `h` parameter is set correctly, and everything else is set to default where various parameters should have been set.

- executor logs:

```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```

- workflow-controller logs:

```
time="2020-07-29T16:01:47Z" level=info msg="config map" name=argo-workflow-controller-configmap
time="2020-07-29T16:01:47Z" level=info msg="Configuration:\nartifactRepository:\n  s3:\n    accessKeySecret:\n      key: accesskey\n      name: argo-minio\n    bucket: argo-artifacts\n    endpoint: argo-minio:9000\n    insecure: true\n    secretKeySecret:\n      key: secretkey\n      name: argo-minio\ncontainerRuntimeExecutor: k8sapi\nmetricsConfig: {}\nnodeEvents: {}\npodSpecLogStrategy: {}\nsso:\n  clientId:\n    key: \"\"\n  clientSecret:\n    key: \"\"\n  issuer: \"\"\n  redirectUrl: \"\"\ntelemetryConfig: {}\n"
time="2020-07-29T16:01:47Z" level=info msg="Persistence configuration disabled"
time="2020-07-29T16:01:47Z" level=info msg="Starting Workflow Controller" version=v2.9.4
time="2020-07-29T16:01:47Z" level=info msg="Workers: workflow: 32, pod: 32"
time="2020-07-29T16:01:47Z" level=info msg="Performing periodic GC every 5m0s"
time="2020-07-29T16:01:47Z" level=info msg="Starting CronWorkflow controller"
time="2020-07-29T16:01:47Z" level=info msg="Starting workflow TTL controller (resync 20m0s)"
time="2020-07-29T16:01:47Z" level=info msg="Persistence disabled - so archived workflow GC disabled - you must restart the controller if you enable this"
time="2020-07-29T16:01:48Z" level=info msg="Starting prometheus metrics server at localhost:9090/metrics"
time="2020-07-29T16:01:48Z" level=info msg="Started workflow TTL worker"
time="2020-07-29T16:06:47Z" level=info msg="Alloc=5968 TotalAlloc=33664 Sys=71616 NumGC=11 Goroutines=159"
time="2020-07-29T16:11:47Z" level=info msg="Alloc=6139 TotalAlloc=33954 Sys=71616 NumGC=13 Goroutines=159"
time="2020-07-29T16:16:47Z" level=info msg="Alloc=5994 TotalAlloc=34033 Sys=71616 NumGC=16 Goroutines=159"
time="2020-07-29T16:21:47Z" level=info msg="Alloc=6112 TotalAlloc=34268 Sys=71616 NumGC=18 Goroutines=159"
time="2020-07-29T16:26:47Z" level=info msg="Alloc=6071 TotalAlloc=36682 Sys=71616 NumGC=21 Goroutines=159"
time="2020-07-29T16:31:47Z" level=info msg="Alloc=6119 TotalAlloc=36841 Sys=71616 NumGC=23 Goroutines=159"
time="2020-07-29T16:36:47Z" level=info msg="Alloc=6066 TotalAlloc=36984 Sys=71616 NumGC=26 Goroutines=159"
time="2020-07-29T16:39:12Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Updated phase  -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Steps node params-test-fvxqz initialized Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="StepGroup node params-test-fvxqz-2947035866 initialized Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Pod node params-test-fvxqz-1230247442 initialized Pending" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Created pod: params-test-fvxqz[0].say1 (params-test-fvxqz-1230247442)" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Workflow step group node params-test-fvxqz-2947035866 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234524 workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Skipped pod params-test-fvxqz[0].say1 (params-test-fvxqz-1230247442) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Workflow step group node params-test-fvxqz-2947035866 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234527 workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Updating node params-test-fvxqz-1230247442 message: ContainerCreating"
time="2020-07-29T16:39:12Z" level=info msg="Skipped pod params-test-fvxqz[0].say1 (params-test-fvxqz-1230247442) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Workflow step group node params-test-fvxqz-2947035866 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234528 workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Skipped pod params-test-fvxqz[0].say1 (params-test-fvxqz-1230247442) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:12Z" level=info msg="Workflow step group node params-test-fvxqz-2947035866 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:13Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:13Z" level=info msg="Skipped pod params-test-fvxqz[0].say1 (params-test-fvxqz-1230247442) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:13Z" level=info msg="Workflow step group node params-test-fvxqz-2947035866 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:16Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:16Z" level=info msg="Updating node params-test-fvxqz-1230247442 status Pending -> Running"
time="2020-07-29T16:39:16Z" level=info msg="Workflow step group node params-test-fvxqz-2947035866 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:16Z" level=info msg="insignificant pod change" key=default/params-test-fvxqz-1230247442
time="2020-07-29T16:39:16Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234551 workflow=params-test-fvxqz
time="2020-07-29T16:39:16Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:16Z" level=info msg="Setting node params-test-fvxqz-1230247442 outputs"
time="2020-07-29T16:39:16Z" level=info msg="Workflow step group node params-test-fvxqz-2947035866 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:16Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234552 workflow=params-test-fvxqz
time="2020-07-29T16:39:16Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:16Z" level=info msg="Workflow step group node params-test-fvxqz-2947035866 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Updating node params-test-fvxqz-1230247442 status Running -> Succeeded"
time="2020-07-29T16:39:18Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="node params-test-fvxqz-2947035866 finished: 2020-07-29 16:39:18.411623998 +0000 UTC" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="StepGroup node params-test-fvxqz-1806010679 initialized Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Pod node params-test-fvxqz-2490518236 initialized Pending" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Created pod: params-test-fvxqz[1].say2 (params-test-fvxqz-2490518236)" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Workflow step group node params-test-fvxqz-1806010679 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234565 workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Labeled pod default/params-test-fvxqz-1230247442 completed"
time="2020-07-29T16:39:18Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Skipped pod params-test-fvxqz[1].say2 (params-test-fvxqz-2490518236) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Workflow step group node params-test-fvxqz-1806010679 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234568 workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Labeled pod default/params-test-fvxqz-1230247442 completed"
time="2020-07-29T16:39:18Z" level=info msg="Updating node params-test-fvxqz-2490518236 message: ContainerCreating"
time="2020-07-29T16:39:18Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Skipped pod params-test-fvxqz[1].say2 (params-test-fvxqz-2490518236) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Workflow step group node params-test-fvxqz-1806010679 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234569 workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Skipped pod params-test-fvxqz[1].say2 (params-test-fvxqz-2490518236) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Workflow step group node params-test-fvxqz-1806010679 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:18Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234569 workflow=params-test-fvxqz
time="2020-07-29T16:39:19Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:19Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:19Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:19Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:19Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:19Z" level=info msg="Skipped pod params-test-fvxqz[1].say2 (params-test-fvxqz-2490518236) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:19Z" level=info msg="Workflow step group node params-test-fvxqz-1806010679 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:19Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234569 workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Updating node params-test-fvxqz-2490518236 status Pending -> Running"
time="2020-07-29T16:39:22Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Workflow step group node params-test-fvxqz-1806010679 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="insignificant pod change" key=default/params-test-fvxqz-2490518236
time="2020-07-29T16:39:22Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234589 workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Setting node params-test-fvxqz-2490518236 outputs"
time="2020-07-29T16:39:22Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Workflow step group node params-test-fvxqz-1806010679 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234590 workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Workflow step group node params-test-fvxqz-1806010679 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:22Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234590 workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Updating node params-test-fvxqz-2490518236 status Running -> Succeeded"
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-1806010679 finished: 2020-07-29 16:39:24.429046008 +0000 UTC" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="StepGroup node params-test-fvxqz-1806451964 initialized Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Pod node params-test-fvxqz-731919486 initialized Pending" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Created pod: params-test-fvxqz[2].say3 (params-test-fvxqz-731919486)" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Workflow step group node params-test-fvxqz-1806451964 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234601 workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Updating node params-test-fvxqz-731919486 message: ContainerCreating"
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Labeled pod default/params-test-fvxqz-2490518236 completed"
time="2020-07-29T16:39:24Z" level=info msg="Skipped pod params-test-fvxqz[2].say3 (params-test-fvxqz-731919486) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Workflow step group node params-test-fvxqz-1806451964 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234605 workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Labeled pod default/params-test-fvxqz-2490518236 completed"
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Skipped pod params-test-fvxqz[2].say3 (params-test-fvxqz-731919486) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Workflow step group node params-test-fvxqz-1806451964 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:24Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234605 workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="Skipped pod params-test-fvxqz[2].say3 (params-test-fvxqz-731919486) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="Workflow step group node params-test-fvxqz-1806451964 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:25Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234605 workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Updating node params-test-fvxqz-731919486 status Pending -> Running"
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Workflow step group node params-test-fvxqz-1806451964 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="insignificant pod change" key=default/params-test-fvxqz-731919486
time="2020-07-29T16:39:28Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234629 workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Setting node params-test-fvxqz-731919486 outputs"
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Workflow step group node params-test-fvxqz-1806451964 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234630 workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Workflow step group node params-test-fvxqz-1806451964 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:28Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234630 workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Updating node params-test-fvxqz-731919486 status Running -> Succeeded"
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806451964 finished: 2020-07-29 16:39:30.439229282 +0000 UTC" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="StepGroup node params-test-fvxqz-2947182961 initialized Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Pod node params-test-fvxqz-639778484 initialized Pending" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Created pod: params-test-fvxqz[3].say4 (params-test-fvxqz-639778484)" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Workflow step group node params-test-fvxqz-2947182961 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234642 workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Labeled pod default/params-test-fvxqz-731919486 completed"
time="2020-07-29T16:39:30Z" level=info msg="Updating node params-test-fvxqz-639778484 message: ContainerCreating"
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Skipped pod params-test-fvxqz[3].say4 (params-test-fvxqz-639778484) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Workflow step group node params-test-fvxqz-2947182961 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234645 workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Skipped pod params-test-fvxqz[3].say4 (params-test-fvxqz-639778484) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Workflow step group node params-test-fvxqz-2947182961 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:30Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234645 workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="Skipped pod params-test-fvxqz[3].say4 (params-test-fvxqz-639778484) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="Workflow step group node params-test-fvxqz-2947182961 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:31Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234645 workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Updating node params-test-fvxqz-639778484 status Pending -> Running"
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Workflow step group node params-test-fvxqz-2947182961 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="insignificant pod change" key=default/params-test-fvxqz-639778484
time="2020-07-29T16:39:34Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234665 workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Setting node params-test-fvxqz-639778484 outputs"
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Workflow step group node params-test-fvxqz-2947182961 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234666 workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Workflow step group node params-test-fvxqz-2947182961 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:34Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234666 workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Updating node params-test-fvxqz-639778484 status Running -> Succeeded"
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947182961 finished: 2020-07-29 16:39:36.45624768 +0000 UTC" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="StepGroup node params-test-fvxqz-2947624246 initialized Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Pod node params-test-fvxqz-3567350474 initialized Pending" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Created pod: params-test-fvxqz[4].say5 (params-test-fvxqz-3567350474)" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Workflow step group node params-test-fvxqz-2947624246 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234681 workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Labeled pod default/params-test-fvxqz-639778484 completed"
time="2020-07-29T16:39:36Z" level=info msg="Updating node params-test-fvxqz-3567350474 message: ContainerCreating"
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Skipped pod params-test-fvxqz[4].say5 (params-test-fvxqz-3567350474) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Workflow step group node params-test-fvxqz-2947624246 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234684 workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Skipped pod params-test-fvxqz[4].say5 (params-test-fvxqz-3567350474) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Workflow step group node params-test-fvxqz-2947624246 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:36Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234684 workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="Skipped pod params-test-fvxqz[4].say5 (params-test-fvxqz-3567350474) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="Workflow step group node params-test-fvxqz-2947624246 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:37Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234684 workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Updating node params-test-fvxqz-3567350474 status Pending -> Running"
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Workflow step group node params-test-fvxqz-2947624246 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="insignificant pod change" key=default/params-test-fvxqz-3567350474
time="2020-07-29T16:39:40Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234705 workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Setting node params-test-fvxqz-3567350474 outputs"
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Workflow step group node params-test-fvxqz-2947624246 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234706 workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Workflow step group node params-test-fvxqz-2947624246 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:40Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234706 workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Updating node params-test-fvxqz-3567350474 status Running -> Succeeded"
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947624246 finished: 2020-07-29 16:39:42.480809213 +0000 UTC" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="StepGroup node params-test-fvxqz-1806599059 initialized Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Pod node params-test-fvxqz-3203226692 initialized Pending" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Created pod: params-test-fvxqz[5].say6 (params-test-fvxqz-3203226692)" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Workflow step group node params-test-fvxqz-1806599059 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234718 workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Labeled pod default/params-test-fvxqz-3567350474 completed"
time="2020-07-29T16:39:42Z" level=info msg="Updating node params-test-fvxqz-3203226692 message: ContainerCreating"
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Skipped pod params-test-fvxqz[5].say6 (params-test-fvxqz-3203226692) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Workflow step group node params-test-fvxqz-1806599059 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234721 workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Skipped pod params-test-fvxqz[5].say6 (params-test-fvxqz-3203226692) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Workflow step group node params-test-fvxqz-1806599059 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:42Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234721 workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="Skipped pod params-test-fvxqz[5].say6 (params-test-fvxqz-3203226692) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="Workflow step group node params-test-fvxqz-1806599059 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:43Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234721 workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Updating node params-test-fvxqz-3203226692 status Pending -> Running"
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Workflow step group node params-test-fvxqz-1806599059 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="insignificant pod change" key=default/params-test-fvxqz-3203226692
time="2020-07-29T16:39:46Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234744 workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Setting node params-test-fvxqz-3203226692 outputs"
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Workflow step group node params-test-fvxqz-1806599059 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234745 workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Workflow step group node params-test-fvxqz-1806599059 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:46Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234745 workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Updating node params-test-fvxqz-3203226692 status Running -> Succeeded"
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
E0729 16:39:48.501584       1 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"params-test-fvxqz.162646a2aee5b937", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Workflow", Namespace:"default", Name:"params-test-fvxqz", UID:"22553fa5-73a6-4b9c-afef-191ae9e33281", APIVersion:"argoproj.io/v1alpha1", ResourceVersion:"234745", FieldPath:""}, Reason:"WorkflowNodeSucceeded", Message:"(combined from similar events): Succeeded node params-test-fvxqz[5].say6", Source:v1.EventSource{Component:"workflow-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbfc087739cc02d37, ext:2274514398061, loc:(*time.Location)(0x2892740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfc087751dcd0ea8, ext:2280532019453, loc:(*time.Location)(0x2892740)}}, Count:2, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "params-test-fvxqz.162646a2aee5b937" is forbidden: User "system:serviceaccount:default:argo" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806599059,Name:params-test-fvxqz[5],DisplayName:[5],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:42 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3203226692],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806599059 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806599059 finished: 2020-07-29 16:39:48.502228594 +0000 UTC" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="StepGroup node params-test-fvxqz-1807143512 initialized Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3203226692 are [params-test-fvxqz-3203226692]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Pod node params-test-fvxqz-1022026638 initialized Pending" namespace=default workflow=params-test-fvxqz
E0729 16:39:48.503765       1 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"params-test-fvxqz.162646a2aee5b937", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Workflow", Namespace:"default", Name:"params-test-fvxqz", UID:"22553fa5-73a6-4b9c-afef-191ae9e33281", APIVersion:"argoproj.io/v1alpha1", ResourceVersion:"234745", FieldPath:""}, Reason:"WorkflowNodeSucceeded", Message:"(combined from similar events): Succeeded node params-test-fvxqz[5]", Source:v1.EventSource{Component:"workflow-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbfc087739cc02d37, ext:2274514398061, loc:(*time.Location)(0x2892740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfc087751df17103, ext:2280534403925, loc:(*time.Location)(0x2892740)}}, Count:3, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "params-test-fvxqz.162646a2aee5b937" is forbidden: User "system:serviceaccount:default:argo" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
time="2020-07-29T16:39:48Z" level=info msg="Created pod: params-test-fvxqz[6].say7 (params-test-fvxqz-1022026638)" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Workflow step group node params-test-fvxqz-1807143512 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234756 workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Labeled pod default/params-test-fvxqz-3203226692 completed"
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806599059 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806599059,Name:params-test-fvxqz[5],DisplayName:[5],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:42 +0000 UTC,FinishedAt:2020-07-29 16:39:48 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3203226692],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806599059 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3203226692 are [params-test-fvxqz-3203226692]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Skipped pod params-test-fvxqz[6].say7 (params-test-fvxqz-1022026638) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Workflow step group node params-test-fvxqz-1807143512 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234759 workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Updating node params-test-fvxqz-1022026638 message: ContainerCreating"
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806599059 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806599059,Name:params-test-fvxqz[5],DisplayName:[5],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:42 +0000 UTC,FinishedAt:2020-07-29 16:39:48 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3203226692],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806599059 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3203226692 are [params-test-fvxqz-3203226692]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Skipped pod params-test-fvxqz[6].say7 (params-test-fvxqz-1022026638) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Workflow step group node params-test-fvxqz-1807143512 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234760 workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806599059 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806599059,Name:params-test-fvxqz[5],DisplayName:[5],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:42 +0000 UTC,FinishedAt:2020-07-29 16:39:48 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3203226692],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="node params-test-fvxqz-1806599059 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3203226692 are [params-test-fvxqz-3203226692]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Skipped pod params-test-fvxqz[6].say7 (params-test-fvxqz-1022026638) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Workflow step group node params-test-fvxqz-1807143512 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:48Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234760 workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-1806599059 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806599059,Name:params-test-fvxqz[5],DisplayName:[5],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:42 +0000 UTC,FinishedAt:2020-07-29 16:39:48 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3203226692],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="node params-test-fvxqz-1806599059 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3203226692 are [params-test-fvxqz-3203226692]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="Skipped pod params-test-fvxqz[6].say7 (params-test-fvxqz-1022026638) creation: already exists" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="Workflow step group node params-test-fvxqz-1807143512 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:49Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234760 workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Updating node params-test-fvxqz-1022026638 status Pending -> Running"
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806599059 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806599059,Name:params-test-fvxqz[5],DisplayName:[5],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:42 +0000 UTC,FinishedAt:2020-07-29 16:39:48 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3203226692],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806599059 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3203226692 are [params-test-fvxqz-3203226692]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Workflow step group node params-test-fvxqz-1807143512 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="insignificant pod change" key=default/params-test-fvxqz-1022026638
time="2020-07-29T16:39:52Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234780 workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Setting node params-test-fvxqz-1022026638 outputs"
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806599059 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806599059,Name:params-test-fvxqz[5],DisplayName:[5],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:42 +0000 UTC,FinishedAt:2020-07-29 16:39:48 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3203226692],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806599059 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3203226692 are [params-test-fvxqz-3203226692]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Workflow step group node params-test-fvxqz-1807143512 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234781 workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806599059 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806599059,Name:params-test-fvxqz[5],DisplayName:[5],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:42 +0000 UTC,FinishedAt:2020-07-29 16:39:48 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3203226692],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="node params-test-fvxqz-1806599059 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3203226692 are [params-test-fvxqz-3203226692]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Workflow step group node params-test-fvxqz-1807143512 not yet completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:52Z" level=info msg="Workflow update successful" namespace=default phase=Running resourceVersion=234781 workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Processing workflow" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Updating node params-test-fvxqz-1022026638 status Running -> Succeeded"
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-2947035866 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
E0729 16:39:54.521946       1 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"params-test-fvxqz.162646a2aee5b937", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Workflow", Namespace:"default", Name:"params-test-fvxqz", UID:"22553fa5-73a6-4b9c-afef-191ae9e33281", APIVersion:"argoproj.io/v1alpha1", ResourceVersion:"234781", FieldPath:""}, Reason:"WorkflowNodeSucceeded", Message:"(combined from similar events): Succeeded node params-test-fvxqz[6].say7", Source:v1.EventSource{Component:"workflow-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbfc087739cc02d37, ext:2274514398061, loc:(*time.Location)(0x2892740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfc087769f065792, ext:2286552550892, loc:(*time.Location)(0x2892740)}}, Count:4, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "params-test-fvxqz.162646a2aee5b937" is forbidden: User "system:serviceaccount:default:argo" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
time="2020-07-29T16:39:54Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947035866,Name:params-test-fvxqz[0],DisplayName:[0],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:12 +0000 UTC,FinishedAt:2020-07-29 16:39:18 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1230247442],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-2947035866 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-1806010679 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1230247442 are [params-test-fvxqz-1230247442]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806010679,Name:params-test-fvxqz[1],DisplayName:[1],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:18 +0000 UTC,FinishedAt:2020-07-29 16:39:24 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-2490518236],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-1806010679 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-1806451964 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="SG Outbound nodes of params-test-fvxqz-2490518236 are [params-test-fvxqz-2490518236]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806451964,Name:params-test-fvxqz[2],DisplayName:[2],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:24 +0000 UTC,FinishedAt:2020-07-29 16:39:30 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-731919486],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-1806451964 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-2947182961 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="SG Outbound nodes of params-test-fvxqz-731919486 are [params-test-fvxqz-731919486]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947182961,Name:params-test-fvxqz[3],DisplayName:[3],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:30 +0000 UTC,FinishedAt:2020-07-29 16:39:36 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-639778484],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-2947182961 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-2947624246 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="SG Outbound nodes of params-test-fvxqz-639778484 are [params-test-fvxqz-639778484]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-2947624246,Name:params-test-fvxqz[4],DisplayName:[4],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:36 +0000 UTC,FinishedAt:2020-07-29 16:39:42 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3567350474],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-2947624246 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-1806599059 phase Succeeded -> Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3567350474 are [params-test-fvxqz-3567350474]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1806599059,Name:params-test-fvxqz[5],DisplayName:[5],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:42 +0000 UTC,FinishedAt:2020-07-29 16:39:48 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-3203226692],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-1806599059 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="SG Outbound nodes of params-test-fvxqz-3203226692 are [params-test-fvxqz-3203226692]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1807143512,Name:params-test-fvxqz[6],DisplayName:[6],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:48 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1022026638],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-1807143512 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-1807143512 finished: 2020-07-29 16:39:54.523420441 +0000 UTC" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="StepGroup node params-test-fvxqz-1874106893 initialized Running" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="SG Outbound nodes of params-test-fvxqz-1022026638 are [params-test-fvxqz-1022026638]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Skipping params-test-fvxqz[7].loopsay: Skipped, empty params" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Skipped node params-test-fvxqz-1354351594 initialized Skipped (message: Skipped, empty params)" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Step group node &NodeStatus{ID:params-test-fvxqz-1874106893,Name:params-test-fvxqz[7],DisplayName:[7],Type:StepGroup,TemplateName:main,TemplateRef:nil,Phase:Running,BoundaryID:params-test-fvxqz,Message:,StartedAt:2020-07-29 16:39:54.523484657 +0000 UTC,FinishedAt:0001-01-01 00:00:00 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[params-test-fvxqz-1354351594],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:namespaced/params-test,ResourcesDuration:ResourcesDuration{},HostNodeName:,} successful" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-1874106893 phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz-1874106893 finished: 2020-07-29 16:39:54.52378466 +0000 UTC" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Outbound nodes of params-test-fvxqz-1354351594 is [params-test-fvxqz-1354351594]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Outbound nodes of params-test-fvxqz is [params-test-fvxqz-1354351594]" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="node params-test-fvxqz finished: 2020-07-29 16:39:54.523865738 +0000 UTC" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Checking daemoned children of params-test-fvxqz" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Updated phase Running -> Succeeded" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Marking workflow completed" namespace=default workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Checking daemoned children of " namespace=default workflow=params-test-fvxqz
E0729 16:39:54.525013       1 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"params-test-fvxqz.162646a2aee5b937", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Workflow", Namespace:"default", Name:"params-test-fvxqz", UID:"22553fa5-73a6-4b9c-afef-191ae9e33281", APIVersion:"argoproj.io/v1alpha1", ResourceVersion:"234781", FieldPath:""}, Reason:"WorkflowNodeSucceeded", Message:"(combined from similar events): Succeeded node params-test-fvxqz[6]", Source:v1.EventSource{Component:"workflow-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbfc087739cc02d37, ext:2274514398061, loc:(*time.Location)(0x2892740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfc087769f35143f, ext:2286555613827, loc:(*time.Location)(0x2892740)}}, Count:5, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "params-test-fvxqz.162646a2aee5b937" is forbidden: User "system:serviceaccount:default:argo" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
E0729 16:39:54.526434       1 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"params-test-fvxqz.162646a2aee5b937", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Workflow", Namespace:"default", Name:"params-test-fvxqz", UID:"22553fa5-73a6-4b9c-afef-191ae9e33281", APIVersion:"argoproj.io/v1alpha1", ResourceVersion:"234781", FieldPath:""}, Reason:"WorkflowNodeSucceeded", Message:"(combined from similar events): Succeeded node params-test-fvxqz[7]", Source:v1.EventSource{Component:"workflow-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbfc087739cc02d37, ext:2274514398061, loc:(*time.Location)(0x2892740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfc087769f4c27d2, ext:2286557126152, loc:(*time.Location)(0x2892740)}}, Count:6, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "params-test-fvxqz.162646a2aee5b937" is forbidden: User "system:serviceaccount:default:argo" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
E0729 16:39:54.527557       1 event.go:240] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"params-test-fvxqz.162646a2aee5b937", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Workflow", Namespace:"default", Name:"params-test-fvxqz", UID:"22553fa5-73a6-4b9c-afef-191ae9e33281", APIVersion:"argoproj.io/v1alpha1", ResourceVersion:"234781", FieldPath:""}, Reason:"WorkflowNodeSucceeded", Message:"(combined from similar events): Succeeded node params-test-fvxqz", Source:v1.EventSource{Component:"workflow-controller", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbfc087739cc02d37, ext:2274514398061, loc:(*time.Location)(0x2892740)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfc087769f61dd8e, ext:2286558548927, loc:(*time.Location)(0x2892740)}}, Count:7, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "params-test-fvxqz.162646a2aee5b937" is forbidden: User "system:serviceaccount:default:argo" cannot patch resource "events" in API group "" in the namespace "default"' (will not retry!)
time="2020-07-29T16:39:54Z" level=info msg="Workflow update successful" namespace=default phase=Succeeded resourceVersion=234789 workflow=params-test-fvxqz
time="2020-07-29T16:39:54Z" level=info msg="Labeled pod default/params-test-fvxqz-1022026638 completed"
time="2020-07-29T16:41:47Z" level=info msg="Alloc=12660 TotalAlloc=115265 Sys=71616 NumGC=39 Goroutines=162"
time="2020-07-29T16:46:47Z" level=info msg="Alloc=7225 TotalAlloc=117876 Sys=71616 NumGC=42 Goroutines=162"
time="2020-07-29T16:51:47Z" level=info msg="Alloc=7245 TotalAlloc=118036 Sys=71616 NumGC=44 Goroutines=162"

```

---
<!-- Issue Author: Don't delete this message to encourage other users to support your issue! -->
**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by sarabala1979**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [ ] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  Fixes #3630 
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

### CODE REVIEW

File: workflow/controller/operator.go [hunk 1]
```diff
@@ -2925,7 +2925,7 @@ func (woc *wfOperationCtx) loadExecutionSpec() (wfv1.TemplateReferenceHolder, wf
 	}
 
 	// Merge the workflow spec and storedWorkflowspec.
-	targetWf := wfv1.Workflow{Spec: woc.wf.Spec}
+	targetWf := wfv1.Workflow{Spec: *woc.wf.Spec.DeepCopy()}
```
Comment (alexec) [inline workflow/controller/operator.go:2928]: ek!

**Comment by sarabala1979** [comment]
backported to 2.9 and 2.10

**Comment by alexec** [comment]
Fixed and available in v2.10.0-rc5.

**Comment by alexec** [comment]
Available in [v2.9.5](https://github.com/argoproj/argo/releases/tag/v2.9.5)
