### PR TITLE
fix(controller): Make the delay before the first workflow reconciliation configurable. Fixes #4107

### LINKED ISSUE #4107: v2.11: Steps (not DAG) always fails (with conflict error) and no helpful diagnostics (AWS only?)
## Summary 

Trying Example https://argoproj.github.io/argo/examples/#output-parameters

## Diagnostics
Argo version 2.11.0

2nd step(consume-parameter) failed because it was unable to get logs, while step 1(generate-parameter) was successful in pulling logs

Below are 2 API to made to get logs

> http://internal-23e.us-east-1.elb.amazonaws.com:2746/artifacts/argo/output-parameters-wt294/output-parameters-wt294-3630452401/main-logs  
(step : consume-parameter) Unsuccessful 
**Response: Artifact no found**

> http://internal-23e.us-east-1.elb.amazonaws.com:2746/artifacts/argo/output-parameters-wt294/output-parameters-wt294-2743065841/main-logs  
(step : generate-parameter) Successful
> 

```yaml
Paste the workflow here, including status:
kubectl get wf -o yaml ${workflow} 

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: "2020-09-22T22:29:47Z"
  generateName: output-parameters-dummy-
  generation: 13
  labels:
    workflows.argoproj.io/completed: "true"
    workflows.argoproj.io/phase: Failed
  name: output-parameters-dummy-k28ls
  namespace: argo
  resourceVersion: "46048090"
  selfLink: /apis/argoproj.io/v1alpha1/namespaces/argo/workflows/output-parameters-dummy-k28ls
  uid: 590d6b5c-b75b-4d4f-a98d-8f88c7b1130f
spec:
  arguments: {}
  entrypoint: output-parameters
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: output-parameters
    outputs: {}
    steps:
    - - arguments: {}
        name: generate-parameter
        template: whalesay
    - - arguments:
          parameters:
          - name: message
            value: '{{steps.generate-parameter.outputs.parameters.hello-param}}'
        name: consume-parameter
        template: print-message
    - - arguments: {}
        name: dummy
        template: dummy
  - arguments: {}
    container:
      args:
      - echo -n hello world > /tmp/hello_world.txt
      command:
      - sh
      - -c
      image: docker/whalesay:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: whalesay
    outputs:
      parameters:
      - name: hello-param
        valueFrom:
          path: /tmp/hello_world.txt
  - arguments: {}
    container:
      args:
      - '{{inputs.parameters.message}}'
      command:
      - cowsay
      image: docker/whalesay:latest
      name: ""
      resources: {}
    inputs:
      parameters:
      - name: message
    metadata: {}
    name: print-message
    outputs: {}
  - arguments: {}
    container:
      args:
      - test
      command:
      - echo
      image: selumalai/basicubuntu:latest
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: dummy
    outputs: {}
status:
  conditions:
  - status: "True"
    type: Completed
  finishedAt: "2020-09-22T22:31:00Z"
  message: child 'output-parameters-dummy-k28ls[1].consume-parameter' errored
  nodes:
    output-parameters-dummy-k28ls:
      children:
      - output-parameters-dummy-k28ls-898385737
      displayName: output-parameters-dummy-k28ls
      finishedAt: "2020-09-22T22:31:00Z"
      id: output-parameters-dummy-k28ls
      message: child 'output-parameters-dummy-k28ls[1].consume-parameter' errored
      name: output-parameters-dummy-k28ls
      phase: Failed
      startedAt: "2020-09-22T22:29:47Z"
      templateName: output-parameters
      templateScope: local/output-parameters-dummy-k28ls
      type: Steps
    output-parameters-dummy-k28ls-537766264:
      boundaryID: output-parameters-dummy-k28ls
      children:
      - output-parameters-dummy-k28ls-4052725204
      displayName: generate-parameter
      finishedAt: "2020-09-22T22:29:50Z"
      id: output-parameters-dummy-k28ls-537766264
      name: output-parameters-dummy-k28ls[0].generate-parameter
      outputs:
        artifacts:
        - archiveLogs: true
          name: main-logs
          s3:
            accessKeySecret:
              key: accesskey
              name: my-minio-cred
            bucket: my-bucket
            endpoint: minio:9000
            insecure: true
            key: output-parameters-dummy-k28ls/output-parameters-dummy-k28ls-537766264/main.log
            secretKeySecret:
              key: secretkey
              name: my-minio-cred
        parameters:
        - name: hello-param
          value: hello world
          valueFrom:
            path: /tmp/hello_world.txt
      phase: Succeeded
      startedAt: "2020-09-22T22:29:47Z"
      templateName: whalesay
      templateScope: local/output-parameters-dummy-k28ls
      type: Pod
    output-parameters-dummy-k28ls-898385737:
      boundaryID: output-parameters-dummy-k28ls
      children:
      - output-parameters-dummy-k28ls-537766264
      displayName: '[0]'
      finishedAt: "2020-09-22T22:29:51Z"
      id: output-parameters-dummy-k28ls-898385737
      name: output-parameters-dummy-k28ls[0]
      phase: Succeeded
      startedAt: "2020-09-22T22:29:47Z"
      templateName: output-parameters
      templateScope: local/output-parameters-dummy-k28ls
      type: StepGroup
    output-parameters-dummy-k28ls-4052725204:
      boundaryID: output-parameters-dummy-k28ls
      children:
      - output-parameters-dummy-k28ls-4217895726
      displayName: '[1]'
      finishedAt: "2020-09-22T22:31:00Z"
      id: output-parameters-dummy-k28ls-4052725204
      message: child 'output-parameters-dummy-k28ls[1].consume-parameter' errored
      name: output-parameters-dummy-k28ls[1]
      phase: Error
      startedAt: "2020-09-22T22:29:51Z"
      templateName: output-parameters
      type: StepGroup
    output-parameters-dummy-k28ls-4217895726:
      boundaryID: output-parameters-dummy-k28ls
      displayName: consume-parameter
      finishedAt: null
      id: output-parameters-dummy-k28ls-4217895726
      inputs:
        parameters:
        - name: message
          value: hello world
      name: output-parameters-dummy-k28ls[1].consume-parameter
      phase: Pending
      startedAt: "2020-09-22T22:31:00Z"
      templateName: print-message
      templateScope: local/output-parameters-dummy-k28ls
      type: Pod
  phase: Failed
  startedAt: "2020-09-22T22:29:47Z"


```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}

 k kubectl logs -n argo $(k kubectl get pods -l app=workflow-controller -n argo -o name) | grep output-parameters-dummy-k28ls

 time="2020-09-22T22:29:47Z" level=info msg="Processing workflow" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:47Z" level=info msg="Updated phase  -> Running" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:47Z" level=info msg="Steps node output-parameters-dummy-k28ls initialized Running" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:47Z" level=info msg="StepGroup node output-parameters-dummy-k28ls-898385737 initialized Running" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:47Z" level=info msg="Pod node output-parameters-dummy-k28ls-537766264 initialized Pending" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:47Z" level=info msg="Created pod: output-parameters-dummy-k28ls[0].generate-parameter (output-parameters-dummy-k28ls-537766264)" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:47Z" level=info msg="Workflow step group node output-parameters-dummy-k28ls-898385737 not yet completed" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:47Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=46047464 workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:48Z" level=info msg="Processing workflow" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:48Z" level=info msg="Updating node output-parameters-dummy-k28ls-537766264 message: ContainerCreating"
time="2020-09-22T22:29:48Z" level=info msg="Skipped pod output-parameters-dummy-k28ls[0].generate-parameter (output-parameters-dummy-k28ls-537766264) creation: already exists" namespace=argo podPhase=Pending workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:48Z" level=info msg="Workflow step group node output-parameters-dummy-k28ls-898385737 not yet completed" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:48Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=46047471 workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:49Z" level=info msg="Processing workflow" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:49Z" level=info msg="Skipped pod output-parameters-dummy-k28ls[0].generate-parameter (output-parameters-dummy-k28ls-537766264) creation: already exists" namespace=argo podPhase=Pending workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:49Z" level=info msg="Workflow step group node output-parameters-dummy-k28ls-898385737 not yet completed" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:49Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=46047490 workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:50Z" level=info msg="Processing workflow" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:50Z" level=info msg="Workflow step group node output-parameters-dummy-k28ls-898385737 not yet completed" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:50Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=46047498 workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:50Z" level=info msg="insignificant pod change" key=argo/output-parameters-dummy-k28ls-537766264
time="2020-09-22T22:29:51Z" level=info msg="Processing workflow" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:51Z" level=info msg="Workflow step group node output-parameters-dummy-k28ls-898385737 not yet completed" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:29:51Z" level=info msg="Workflow update successful" namespace=argo phase=Running resourceVersion=46047512 workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="Processing workflow" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="node output-parameters-dummy-k28ls-898385737 phase Succeeded -> Running" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="Step group node &NodeStatus{ID:output-parameters-dummy-k28ls-898385737,Name:output-parameters-dummy-k28l[0],DisplayName:[0],Type:StepGroup,TemplateName:output-parameters,TemplateRef:nil,Phase:Running,BoundaryID:output-parameters-dummy-k28ls,Message:,StartedAt:2020-09-22 22:29:47 +0000 UTC,FinishedAt:2020-09-22 22:29:51 +0000 UTC,PodIP:,Daemoned:nil,Inputs:nil,Outputs:nil,Children:[output-parameters-dummy-k28ls-537766264],OutboundNodes:[],StoredTemplateID:,WorkflowTemplateName:,TemplateScope:local/output-parameters-dummy-k28ls,ResourcesDuration:ResourcesDuration{},HostNodeName:,MemoizationStatus:nil,} successful" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="node output-parameters-dummy-k28ls-898385737 phase Running -> Succeeded" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="SG Outbound nodes of output-parameters-dummy-k28ls-537766264 are [output-parameters-dummy-k28ls-537766264]" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="Pod node output-parameters-dummy-k28ls-4217895726 initialized Pending" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="Created pod: output-parameters-dummy-k28ls[1].consume-parameter (output-parameters-dummy-k28ls-4217895726)" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="Workflow step group node output-parameters-dummy-k28ls-4052725204 not yet completed" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=warning msg="Error updating workflow: Operation cannot be fulfilled on workflows.argoproj.io \"output-parameters-dummy-k28ls\": the object has been modified; please apply your changes to the latest version and try again Conflict" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="Re-applying updates on latest version and retrying update" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="Update retry attempt 1 successful" namespace=argo workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:00Z" level=info msg="Workflow update successful" namespace=argo phase=Failed resourceVersion=46048090 workflow=output-parameters-dummy-k28ls
time="2020-09-22T22:31:03Z" level=info msg="insignificant pod change" key=argo/output-parameters-dummy-k28ls-4217895726

```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by saranyaeu2987**
Checklist:

* [x]  this is a bug fix
* [x] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).
* [ ] I've signed the CLA.
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My builds are green. Try syncing with master if they are not. 

Fixes #4107

### CODE REVIEW

File: config/config.go [hunk 1]
```diff
@@ -4,6 +4,7 @@ import (
 	apiv1 "k8s.io/api/core/v1"
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"k8s.io/apimachinery/pkg/labels"
+	"time"
```
Comment (alexec) [inline config/config.go:7]: you need to run `goimports` on this file to correct the formatting

File: config/config.go [hunk 2]
```diff
@@ -90,6 +91,9 @@ type Config struct {
 
 	// WorkflowRestrictions restricts the controller to executing Workflows that meet certain restrictions
 	WorkflowRestrictions *WorkflowRestrictions `json:"workflowRestrictions,omitempty"`
+
+	//configurable initial delay https://github.com/argoproj/argo/issues/4107
```
Comment (alexec) [inline config/config.go:95]: Might be good to say why you'd want to change this.

File: workflow/controller/controller.go [hunk 3]
```diff
@@ -662,7 +662,7 @@ func (wfc *WorkflowController) addWorkflowInformerHandlers() {
 				AddFunc: func(obj interface{}) {
 					key, err := cache.MetaNamespaceKeyFunc(obj)
 					if err == nil {
-						wfc.wfQueue.Add(key)
+						wfc.wfQueue.AddAfter(key, wfc.Config.InitialDelay)
```
Comment (alexec) [inline workflow/controller/controller.go:665]: perfect

File: config/config.go (hunk 1 above)
Comment (saranyaeu2987) [reply config/config.go]: ran goimports and it reformatted the file

File: config/config.go (hunk 2 above)
Comment (saranyaeu2987) [reply config/config.go]: edited

**Comment by alexec** [comment]
Can you please sign the CLA?

**Comment by saranyaeu2987** [comment]
I did sign CLA and made a dummy commit to kick start cla check, but still shows unsigned. I attached screenshot for your reference
image

File: config/config.go [hunk 4]
```diff
@@ -90,6 +92,9 @@ type Config struct {
 
 	// WorkflowRestrictions restricts the controller to executing Workflows that meet certain restrictions
 	WorkflowRestrictions *WorkflowRestrictions `json:"workflowRestrictions,omitempty"`
+
+	//Adding configurable initial delay (for K8S clusters with mutating webhooks) to prevent workflow getting modified by MWC.
+	InitialDelay time.Duration `json:"initialDelay,omitempty"`
```
Comment (alexec) [inline config/config.go:97]: Can we use `metav1.Duration` which parses durations like `10s`

**Review by alexec — CHANGES_REQUESTED** [review]
Can I request one change?

File: config/config.go (hunk 4 above)
Comment (saranyaeu2987) [reply config/config.go]: @alexec 
Test failed since AddAfter method is expecting only time.Duration

Comment (alexec) [reply config/config.go]:
```
Config. InitialDelay.Duration
```
???

Comment (saranyaeu2987) [reply config/config.go]: Is this acceptable (to cast to time.Duration)

`wfc.wfQueue.AddAfter(key, time.Duration(wfc.Config.InitialDelay.Seconds()))`

Comment (alexec) [reply config/config.go]: `time.Duration` is nano-seconds, so this would be the wrong amount.  I think you can do:

```
wfc.wfQueue.AddAfter(key, wfc.Config.InitialDelay.Duration)
```

**Comment by alexec** [comment]
Code changes look fine. Do you think you'll be able to build and test it yourself - or do you need help?

**Comment by saranyaeu2987** [comment]
> Code changes look fine. Do you think you'll be able to build and test it yourself - or do you need help?

Need help Alex.

**Comment by alexec** [comment]
Try `argoproj/workflow-controller:saranyaeu2987`

**Comment by saranyaeu2987** [comment]
> argoproj/workflow-controller:saranyaeu2987

Working as expected. Can this be resolved?

**Review by alexec — APPROVED** [review]
