### PR TITLE
fix(controller): Increase default EventSpamBurst in Event-recorder

### LINKED ISSUE #4671: WorkflowSucceeded event is missing on big workflows
## Summary 

What happened/what you expected to happen?

## Diagnostics

What Kubernetes provider are you using? 

What version of Argo Workflows are you running? 

```yaml
Paste a workflow that reproduces the bug, including status:
kubectl get wf -o yaml ${workflow} 
```

```
Paste the logs from the workflow controller:
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name) | grep ${workflow}
```

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We prioritise the issues with the most 👍.

### PR DESCRIPTION
**Pull request by sarabala1979**
Signed-off-by: Saravanan Balasubramanian <sarabala1979@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo/blob/master/USERS.md).

Fixes #4671

### CODE REVIEW

File: workflow/events/event_recorder_manager.go [hunk 1]
```diff
@@ -11,6 +11,9 @@ import (
 	"k8s.io/client-go/tools/record"
 )
 
+// by default, allow a source to send 10000 events about an object
+const defaultSpamBurst = 10000
```
Comment (sarabala1979) [inline workflow/events/event_recorder_manager.go:15]: This will support to trigger WorkflowSucceeded event if the workflow has 10000 steps. This change won't the default EventAggregator config.

**Review by alexec — APPROVED** [review]
