### PR TITLE
fix(sequence): broken in 2.5. Fixes #2248

### LINKED ISSUE #2248: Sequence broken in 2.5-rc10
Checklist:

 * [x] I've included the version.
 * [x] I've included reproduction steps.
 * [x] I've included the workflow YAML.
 * [x] I've included the logs.
 
**What happened**:

Running the standard loop-sequence example: https://github.com/argoproj/argo/blob/master/examples/loops-sequence.yaml leads to only 0s being printed.

```
argo logs -w -f loops-sequence-whtdr
sequence-start-end(4:0):	0
sequence-count(1:0):	0
sequence-count(3:0):	0
sequence-count(0:0):	0
sequence-start-end(3:0):	0
sequence-negative(2:0):	0
sequence-count(2:0):	0
sequence-start-end(2:0):	0
sequence-start-end(1:0):	0
sequence-param(1:0):	0
sequence-start-end(0:0):	0
sequence-negative(0:0):	0
sequence-count(4:0):	0
sequence-negative(1:0):	0
sequence-negative(3:0):	0
sequence-format(3:0):	0
sequence-negative(5:0):	0
sequence-param(2:0):	0
sequence-param(0:0):	0
sequence-format(4:0):	0
sequence-negative(4:0):	0
sequence-start-end(5:0):	0
sequence-format(1:0):	0
sequence-format(0:0):	0
sequence-format(2:0):	0
```

**What you expected to happen**:

A sequence of numbers should be printed. None of them should be 0.

**How to reproduce it (as minimally and precisely as possible)**:

```
wget https://github.com/argoproj/argo/blob/7864ad36788dc78d035d59ddb27ecd979f7216f4/examples/loops-sequence.yaml
argo submit loops-sequence.yaml
```

**Anything else we need to know?**:
One of the commits touching `item` is: https://github.com/CodecLondon/argo/commit/14c004f074f6542a6db5397b27ecb00e8704b0e8. Could possibly be a culprit?

It is weird that no tests have caught this. Perhaps no test actually covers the full path to what is rendered as `item`.

**Environment**:
Argo version: 2.5.0-rc10

- Kubernetes version :
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T23:49:20Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Other debugging information (if applicable)**:
- workflow result:
```
argo get <workflowname>
```
- executor logs:
```
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
```
- workflow-controller logs:
```
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

**Logs**

```
argo get <workflowname>
kubectl logs <failedpodname> -c init
kubectl logs <failedpodname> -c wait
kubectl logs -n argo $(kubectl get pods -l app=workflow-controller -n argo -o name)
```

---

**Message from the maintainers**:

If you are impacted by this bug please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by mark9white**
Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this is a chore.
* [X] The title of the PR is (a) [conventional](https://www.conventionalcommits.org/en/v1.0.0/), (b) states what changed, and (c) suffixes the related issues number. E.g. `"fix(controller): Updates such and such. Fixes #1234"`.  
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlike to be merged.
* [X] Optional. I've added My organization is added to the README.
* [X] I've signed the CLA and required builds are green. 

Fixes #2248

### CODE REVIEW

File: workflow/controller/operator_test.go [hunk 1]
```diff
@@ -773,6 +773,62 @@ func TestSuspendWithDeadline(t *testing.T) {
...
+		} else if node.DisplayName == "step1(1:101)" {
+			assert.Equal(t, "101", *node.Inputs.Parameters[0].Value)
+			found101 = true
+		}
+	}
+	assert.Equal(t, true, found100)
+	assert.Equal(t, true, found101)
+}
+
+
```
Comment (golangcibot) [inline workflow/controller/operator_test.go]: File is not `goimports`-ed with -local github.com/argoproj/argo (from `goimports`)
```suggestion

```

**Comment by alexec** [comment]
This is currently targeted for v2.7 (end of March) do you NEED it sooner?

**Comment by salanki** [comment]
Thank you for this fix and adding the test. From my end (the reporter) waiting until 2.6 is no problem.
