### PR TITLE
 fix: Namespace redirects no longer error and are snappier

### LINKED ISSUE #2102: When changing panes in the UI, an error is briefly shown
See: https://cl.ly/11b6ed542c4a

### PR DESCRIPTION
**Pull request by simster7**
Fixes #2102 

Demo (notice `managedNamespace` redirection still happens): https://cl.ly/4f3a073db983

### CODE REVIEW

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx [hunk 1]
```diff
@@ -29,16 +31,17 @@ export class ArchivedWorkflowList extends BasePage<RouteComponentProps<any>, Sta
     }
 
     private get namespace() {
-        return this.props.match.params.namespace || '';
+        return this.state.namespace;
```
Comment (simster7) [inline ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx]: Source of truth for namespace is now react state

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx [hunk 2]
```diff
@@ -29,16 +31,17 @@ export class ArchivedWorkflowList extends BasePage<RouteComponentProps<any>, Sta
...
     }
 
     private set namespace(namespace: string) {
-        document.location.href = uiUrl('archived-workflows/' + namespace);
+        this.setState({namespace});
+        history.pushState(null, '', uiUrl('cron-workflows/' + namespace));
```
Comment (simster7) [inline ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx]: This edits the URL without forcing a reload. This is cosmetic only, as the source of truth for the namespace is now on react state

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx [hunk 3]
```diff
@@ -29,16 +31,17 @@ export class ArchivedWorkflowList extends BasePage<RouteComponentProps<any>, Sta
...
     }
 
     constructor(props: RouteComponentProps<any>, context: any) {
         super(props, context);
-        this.state = {continue: ''};
+        this.state = {continue: '', loading: true, namespace: this.props.match.params.namespace || ''};
```
Comment (simster7) [inline ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx]: Desired namespace is loaded from URL only once

File: ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx [hunk 4]
```diff
@@ -51,16 +54,18 @@ export class ArchivedWorkflowList extends BasePage<RouteComponentProps<any>, Sta
...
-                this.setState({workflows: list.items || [], continue: list.metadata.continue || ''});
+                this.setState({workflows: list.items || [], continue: list.metadata.continue || '', loading: false});
             })
-            .catch(error => this.setState({error}));
+            .catch(error => this.setState({error, loading: false}));
     }
 
     public render() {
+        if (this.state.loading) {
+            return <Loading />;
```
Comment (simster7) [inline ui/src/app/archived-workflows/components/archived-workflow-list/archived-workflow-list.tsx]: Show a nice loading screen while API calls are being made
